Repository pluralsh/console, pull requests merged in 2022-08, with the labels that each got.

#76 Auto populate empty configuration in recipe install
  assets/src/components/repos/Configuration.js
Labels: bug-fix

#65 ENG-328: Release process part 1
  .dockerignore
  .github/workflows/assets.yaml
  .github/workflows/publish-cypress.yaml
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  Dockerfile
  Makefile
  VERSION
  assets/cypress/e2e/stories/bounce.cy.ts
  assets/e2e/.dockerignore
  assets/e2e/.gitignore
  assets/e2e/cypress.Dockerfile
  assets/e2e/cypress.config.ts
  assets/e2e/cypress/config/config.ts
  assets/e2e/cypress/e2e/stories/bounce.cy.ts
  assets/e2e/cypress/e2e/stories/deploy.cy.ts
  assets/e2e/cypress/pages/base.ts
  assets/e2e/cypress/pages/builds.ts
  assets/e2e/cypress/pages/login.ts
  assets/e2e/cypress/plugins/cy-ts-preprocessor.ts
  assets/e2e/cypress/plugins/index.ts
  assets/e2e/cypress/support/commands.ts
  assets/e2e/cypress/support/index.ts
  assets/e2e/cypress/utils/graphql-test-utils.ts
  assets/e2e/package.json
  assets/e2e/tsconfig.json
  assets/e2e/yarn.lock
  assets/package.json
  assets/src/components/graphql/users.js
  assets/yarn.lock
  mix.exs
Labels: enhancement

#79 Release process part 2
  .github/workflows/assets.yaml
  assets/.eslintrc.yml
  assets/e2e/.eslintrc.yaml
  assets/e2e/.gitignore
  assets/e2e/.yarn/releases/yarn-3.2.2.cjs
  assets/e2e/.yarnrc.yml
  assets/e2e/Makefile
  assets/e2e/cypress.Dockerfile
  assets/e2e/cypress.config.ts
  assets/e2e/cypress/config/config.ts
  assets/e2e/cypress/e2e/stories/bounce.cy.ts
  assets/e2e/cypress/e2e/stories/deploy.cy.ts
  assets/e2e/cypress/intercept/factory.ts
  assets/e2e/cypress/intercept/graphql.ts
  assets/e2e/cypress/intercept/query/build.ts
  assets/e2e/cypress/pages/base.ts
  assets/e2e/cypress/pages/builds.ts
  assets/e2e/cypress/pages/login.ts
  assets/e2e/cypress/pages/root.ts
  assets/e2e/cypress/plugins/cy-ts-preprocessor.ts
  assets/e2e/cypress/plugins/index.ts
  assets/e2e/cypress/support/index.ts
  assets/e2e/cypress/types/condition.ts
  assets/e2e/cypress/types/dispatch.ts
  assets/e2e/cypress/types/graphql.ts
  assets/e2e/cypress/types/mutations.ts
  assets/e2e/cypress/types/queries.ts
  assets/e2e/cypress/types/time.ts
  assets/e2e/cypress/utils/graphql-test-utils.ts
  assets/e2e/package.json
  assets/e2e/tsconfig.json
  assets/e2e/webpack.config.ts
  assets/e2e/yarn.lock
  plural/helm/console/Chart.lock
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/test-base-0.1.5.tgz
  plural/helm/console/templates/secrets.yaml
  plural/helm/console/values.yaml
  plural/helm/console/values.yaml.tpl
Labels: enhancement

#89 update to latest CLI
  Dockerfile
Labels: enhancement, dependencies

#90 add action to generate github release
  .github/release.yml
  .github/workflows/publish.yaml
Labels: enhancement

#96 fix dockerfile for renovate
  Dockerfile
Labels: dependencies

#109 add workflow for required labels
  .github/workflows/pr-labels.yaml
Labels: enhancement
