Repository pluralsh/console, pull requests merged in 2022-11, with the labels that each got.

#115 Bump logs fetch limit to help loki
  assets/src/components/Logs.js
  assets/src/components/graphql/dashboards.js
Labels: enhancement, frontend

#114 Autodeploy after config update
  lib/console/deployer.ex
Labels: enhancement

#116 Implement --from flag for installer
  Dockerfile
  lib/console/commands/plural.ex
  lib/console/deployer.ex
Labels: enhancement

#117 Add firebase
  .firebaserc
  .github/workflows/firebase-hosting-pull-request.yml
  firebase.json
Labels: enhancement, frontend

#118 Add CodeQL action
  .github/workflows/codeql.yml
Labels: enhancement

#152 Fix in-console oidc provider updates
  Dockerfile
  assets/src/components/oidc/queries.js
Labels: bug-fix, frontend

#151 Add notification status
  README.md
  lib/console/graphql/users.ex
  lib/console/schema/notification.ex
  lib/console/services/alertmanager.ex
  priv/repo/migrations/20221118165510_add_notification_status.exs
  test/console/services/alertmanager_test.exs
Labels: enhancement, backend

#153 Console leader election
  lib/console/deployer.ex
  lib/console/plural/context.ex
  lib/console/schema/leader.ex
  lib/console/services/leader_election.ex
  lib/console/services/plural.ex
  lib/console/storage.ex
  lib/console/storage/git.ex
  priv/repo/migrations/20221128153822_add_leaders.exs
  test/console/plural/context_test.exs
  test/console/services/leader_election_test.exs
  test/support/factory.ex
Labels: enhancement, backend

#150 Add better templating for repo encryption key
  plural/helm/console/Chart.yaml
  plural/helm/console/values.yaml
  plural/helm/console/values.yaml.tpl
Labels: bug-fix
