Repository pluralsh/console, pull requests merged in 2023-05, with the labels that each got.

#349 Remove unnecessary deps from docker image
  Dockerfile
Labels: enhancement, backend

#351 Release v0.4.13
  plural/helm/console/Chart.yaml
  plural/helm/console/values.yaml
Labels: release

#354 Support regex and repo list policies
  assets/src/components/builds/UpgradePolicyCreate.tsx
  lib/console/graphql/policies.ex
  lib/console/schema/upgrade_policy.ex
  lib/console/services/policies.ex
  priv/repo/migrations/20230516163204_add_upgrade_policy_repos.exs
  test/console/services/policies_test.exs
Labels: enhancement, backend

#357 feat(capi): add recipes and modify tf to make compatible with CAPI testing
  plural/plural/recipe/console-aws-cluster-api.yaml
  plural/plural/recipe/console-azure-cluster-api.yaml
  plural/plural/recipe/console-gcp-cluster-api.yaml
  plural/terraform/aws/deps.yaml
  plural/terraform/azure/deps.yaml
  plural/terraform/gcp/deps.yaml
Labels: enhancement

#359 feat: Hide installer steps for already installed apps
  assets/src/components/repos/installer/Installer.tsx
  assets/src/components/repos/installer/helpers.tsx
  assets/src/generated/graphql.ts
  schema/schema.graphql
Labels: enhancement, frontend
