Repository pluralsh/console, pull requests merged in 2023-03, with the labels that each got.

#306 fix: Fix VPN table scrolling
  assets/src/components/account/vpn/VPN.tsx
  assets/src/components/profile/VPN.tsx
  assets/src/components/vpn/VPNClientList.tsx
  assets/src/components/vpn/columns/Actions.tsx
Labels: bug-fix

#310 feat: Nested tab navigation for app docs
  assets/package.json
  assets/src/components/apps/app/App.tsx
  assets/src/components/apps/app/AppSelector.tsx
  assets/src/components/apps/app/docs/AppDocs.tsx
  assets/src/components/apps/app/docs/AppDocsContext.tsx
  assets/src/components/apps/app/docs/MarkdocContent.tsx
  assets/src/components/contexts/NavigationContext.tsx
  assets/src/components/contexts/contextReactRouter.tsx
  assets/src/components/hooks/useUnmount.tsx
  assets/src/components/layout/Console.tsx
  assets/src/components/layout/NotificationsPanelOverlay.tsx
  assets/src/components/layout/Overlay.tsx
  assets/src/components/utils/layout/ScrollablePage.tsx
  assets/src/markdoc/MarkdocContext.tsx
  assets/src/markdoc/components/Button.tsx
  assets/src/markdoc/components/Callout.tsx
  assets/src/markdoc/components/Heading.tsx
  assets/src/markdoc/components/Link.tsx
  assets/src/markdoc/components/Paragraph.tsx
  assets/src/markdoc/utils/collectHeadings.ts
  assets/src/markdoc/utils/contextReactRouter.tsx
  assets/src/markdoc/utils/getMdContent.tsx
  assets/src/markdoc/utils/useNormalizeHref.tsx
  assets/src/routes/appsRoutes.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#311 fix: App nav is displayed under overlay
  assets/src/components/layout/AppNav.tsx
Labels: bug-fix, frontend

#313 fix: Link in header is not helpful
  assets/src/components/layout/Header.tsx
Labels: bug-fix, frontend

#315 expose user management feature
  lib/console/graphql/configuration.ex
  lib/console/plural/queries.ex
Labels: enhancement

#314 docs: Update logo in readme
  README.md
  assets/public/PluralConsole-background.png
Labels: documentation, enhancement

#316 fix schema generation and update schema
  assets/codegen.yml
  assets/src/generated/graphql.ts
  schema/schema.graphql
Labels: bug-fix, frontend

#318 Release v0.4.7
  .github/workflows/pr-labels.yaml
  plural/helm/console/Chart.yaml
  plural/helm/console/values.yaml
Labels: backend, release

#320 feat: Convert Groups queries to generated TS queries
  assets/src/components/account/groups/Group.tsx
  assets/src/components/account/groups/GroupCreate.tsx
  assets/src/components/account/groups/GroupMember.tsx
  assets/src/components/account/groups/GroupsList.tsx
  assets/src/components/account/groups/queries.ts
  assets/src/components/utils/BindingInput.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/base.graphql
  assets/src/graph/groups.graphql
Labels: enhancement

#312 feat: Pricing
  assets/public/placeholder-groups.png
  assets/public/placeholder-roles.png
  assets/public/placeholder-vpn.png
  assets/src/components/account/Account.tsx
  assets/src/components/account/groups/Groups.tsx
  assets/src/components/account/roles/Roles.tsx
  assets/src/components/account/settings/AccountSettings.tsx
  assets/src/components/account/vpn/VPN.tsx
  assets/src/components/billing/BillingError.tsx
  assets/src/components/billing/BillingFeatureBlockBanner.tsx
  assets/src/components/billing/BillingLegacyUserBanner.tsx
  assets/src/components/billing/BillingLegacyUserMessage.tsx
  assets/src/components/billing/BillingLoading.tsx
  assets/src/components/billing/BillingPlatformPlansProvider.tsx
  assets/src/components/billing/BillingSubscriptionChip.tsx
  assets/src/components/billing/BillingSubscriptionProvider.tsx
  assets/src/components/billing/queries.ts
  assets/src/components/contexts/PlatformPlansContext.ts
  assets/src/components/contexts/SubscriptionContext.ts
  assets/src/components/layout/Console.tsx
  assets/src/components/layout/Header.tsx
  assets/src/components/login/OauthCallback.tsx
  assets/src/routes/consoleRoutes.tsx
Labels: enhancement

#327 Release v0.4.8
  plural/helm/console/Chart.yaml
  plural/helm/console/values.yaml
Labels: release

#328 Add query to fetch account
  assets/src/generated/graphql.ts
  lib/console/features.ex
  lib/console/graphql/configuration.ex
  lib/console/graphql/plural.ex
  lib/console/graphql/resolvers/plural.ex
  lib/console/graphql/schema/base.ex
  lib/console/plural/models.ex
  lib/console/plural/queries.ex
  schema/schema.graphql
  test/console/graphql/queries/plural_queries_test.exs
Labels: enhancement

#329 fix: Restore pricing functionality
  assets/package.json
  assets/src/components/account/groups/GroupCreate.tsx
  assets/src/components/account/groups/Groups.tsx
  assets/src/components/account/roles/RoleCreate.tsx
  assets/src/components/account/roles/Roles.tsx
  assets/src/components/account/vpn/VPNHeaderActions.tsx
  assets/src/components/billing/BillingFeatureBlockBanner.tsx
  assets/src/components/billing/BillingPlatformPlansProvider.tsx
  assets/src/components/billing/BillingSubscriptionProvider.tsx
  assets/src/components/billing/queries.ts
  assets/src/components/contexts/SubscriptionContext.ts
  assets/src/components/layout/Console.tsx
  assets/src/components/layout/Header.tsx
Labels: bug-fix, frontend

#331 release v0.4.9
  plural/helm/console/Chart.yaml
  plural/helm/console/values.yaml
Labels: release

#319 feat: add posthog to console
  assets/package.json
  assets/src/App.jsx
  assets/src/components/account/Account.tsx
  assets/src/components/account/settings/CookieSettings.tsx
  assets/src/components/account/users/User.tsx
  assets/src/components/contexts.ts
  assets/src/components/contexts.tsx
  assets/src/components/graphql/users.js
  assets/src/components/layout/Console.tsx
  assets/src/components/layout/DemoBanner.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/layout/WithApplicationUpdate.tsx
  assets/src/components/login/Login.tsx
  assets/src/components/login/LoginFooter.tsx
  assets/src/components/tracking/CookieSettings.tsx
  assets/src/components/utils/Posthog.ts
  assets/src/generated/graphql.ts
  assets/src/graph/groups.graphql
  assets/src/graph/users.graphql
  assets/src/index.tsx
  assets/src/routes/appsRoutes.tsx
  assets/src/routes/consoleRoutes.tsx
  assets/src/routes/rootRoutes.tsx
  assets/src/utils/cookiePrefs.tsx
  assets/yarn.lock
  lib/console/graphql/resolvers/user.ex
  lib/console/graphql/users.ex
  lib/console/schema/user.ex
  priv/repo/migrations/20230308163640_add_user_plural_id.exs
  schema/schema.graphql
  test/console/services/users_test.exs
Labels: enhancement, frontend, backend

#332 console release v0.4.10
  plural/helm/console/Chart.yaml
  plural/helm/console/values.yaml
Labels: release

#333 Add primary recipes
  .github/workflows/push-to-plural.yaml
  plural/plural/recipe/console-aws.yaml
  plural/plural/recipe/console-azure.yaml
  plural/plural/recipe/console-equinix.yaml
  plural/plural/recipe/console-gcp.yaml
  plural/plural/recipe/console-kind.yaml
Labels: documentation, enhancement

#335 Fix redirect urls for builds and configuration
  assets/src/components/apps/app/config/ConfigurationSettings.tsx
  assets/src/components/apps/app/runbooks/runbook/display/DisplayButton.tsx
  assets/src/helpers/url.js
Labels: enhancement

#337 feat: Make legacy user callouts dismissible
  assets/package.json
  assets/src/components/billing/BillingLegacyUserBanner.tsx
  assets/src/components/billing/BillingLegacyUserMessage.tsx
  assets/src/components/billing/BillingSubscriptionProvider.tsx
  assets/src/components/contexts/SubscriptionContext.ts
  assets/src/components/hooks/usePersistedState.tsx
  assets/yarn.lock
Labels: enhancement
