Repository pluralsh/console, pull requests merged in 2023-07, with the labels that each got.

#377 feat: Console OIDC in Users tab
  assets/src/components/account/users/OIDCInvite.tsx
  assets/src/components/account/users/Users.tsx
  assets/src/components/apps/app/oidc/UserManagement.tsx
Labels: enhancement, frontend

#378 Release v0.4.18
  plural/helm/console/Chart.yaml
  plural/helm/console/templates/deployment.yaml
  plural/helm/console/values.yaml
Labels: release

#381 fix: set missing image tag for migration
  plural/helm/console/Chart.yaml
  plural/helm/console/templates/deployment.yaml
  plural/helm/console/templates/migration.yaml
  plural/helm/console/values.yaml
Labels: bug-fix

#380 Allow tenant headers to be injected into grafana stack clients
  lib/console/services/plural.ex
  lib/loki/client.ex
  lib/prometheus/client.ex
  plural/helm/console/Chart.yaml
  plural/helm/console/values.yaml.tpl
  rel/config/config.exs
  test/console/graphql/queries/observability_queries_test.exs
  test/console_web/controllers/log_controller_test.exs
Labels: enhancement, backend

#382 Add auto-bump to console release process too
  .github/workflows/publish.yaml
Labels: enhancement

#383 fix: Width of container select dropdown too large
  assets/src/components/cluster/containers/Container.tsx
Labels: bug-fix

#384 Bump console cli to 0.6.26
  Dockerfile
  lib/console/commands/plural.ex
Labels: enhancement

#385 Rename user management, add delete mutation
  assets/package.json
  assets/src/components/apps/app/App.tsx
  assets/src/components/apps/app/oidc/UserManagement.tsx
  assets/src/generated/graphql.ts
  assets/yarn.lock
  lib/console/graphql/audit.ex
  lib/console/graphql/build.ex
  lib/console/graphql/configuration.ex
  lib/console/graphql/kubernetes.ex
  lib/console/graphql/kubernetes/application.ex
  lib/console/graphql/kubernetes/certificate.ex
  lib/console/graphql/kubernetes/ingress.ex
  lib/console/graphql/observability.ex
  lib/console/graphql/plural.ex
  lib/console/graphql/policies.ex
  lib/console/graphql/resolvers/kubernetes.ex
  lib/console/graphql/resolvers/user.ex
  lib/console/graphql/runbooks.ex
  lib/console/graphql/schema/base.ex
  lib/console/graphql/users.ex
  lib/console/graphql/webhooks.ex
  lib/console/services/users.ex
  lib/kube/client.ex
  schema/schema.graphql
  test/console/graphql/mutations/kubernetes_mutations_test.exs
  test/console/graphql/mutations/user_mutations_test.exs
  test/support/factory.ex
Labels: enhancement
