Repository pluralsh/console, pull requests merged in 2023-12, with the labels that each got.

#523 feat: Multi-source Helm FE changes
  assets/package.json
  assets/src/components/cd/cluster/ClusterServices.tsx
  assets/src/components/cd/pipelines/Pipelines.tsx
  assets/src/components/cd/repos/GitRepositories.tsx
  assets/src/components/cd/repos/GitRepositoriesColumns.tsx
  assets/src/components/cd/repos/GitRepositoriesTable.tsx
  assets/src/components/cd/repos/HelmHealthChip.tsx
  assets/src/components/cd/repos/HelmRepositoriesColumns.tsx
  assets/src/components/cd/repos/Repositories.tsx
  assets/src/components/cd/repos/RepositoriesFilters.tsx
  assets/src/components/cd/services/Services.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/services/ServicesFilters.tsx
  assets/src/components/cd/services/ServicesRollbackDeployment.tsx
  assets/src/components/cd/services/deployModal/DeployService.tsx
  assets/src/components/cd/services/deployModal/DeployServiceSettingsGit.tsx
  assets/src/components/cd/services/deployModal/DeployServiceSettingsHelm.tsx
  assets/src/components/cd/services/deployModal/DeployServiceSettingsHelmValues.tsx
  assets/src/components/cd/utils/RepoKindSelector.tsx
  assets/src/routes/cdRoutes.tsx
  assets/src/utils/graphql.ts
  assets/yarn.lock
  test-apps/helm-values/values-podinfo.yaml
Labels: enhancement, frontend

#525 fix small revision history bug
  lib/console.ex
  lib/console/deployments/services.ex
  lib/console/schema/revision.ex
  lib/console/schema/service.ex
  priv/repo/migrations/20231201032016_add_kustomize_revisions.exs
  test/console/deployments/services_test.exs
Labels: enhancement

#527 Change map type to json to make client development easier
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/schema/custom_types.ex
  schema/schema.graphql
  test-apps/helm-repositories/externaldns.yaml
Labels: enhancement

#528 better complete status for pipeline stages
  assets/src/components/cd/pipelines/nodes/StageNode.tsx
Labels: enhancement, frontend

#530 Add status query for services
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/schema/service.ex
  schema/schema.graphql
Labels: enhancement

#532 Add global prometheus + loki setup
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments.ex
  lib/console/graphql/middleware/observability_client.ex
  lib/console/graphql/observability.ex
  lib/console/schema/agent_migration.ex
  lib/console/schema/deployment_settings.ex
  lib/console/services/observability.ex
  lib/loki/client.ex
  lib/prometheus/client.ex
  priv/repo/migrations/20231204165634_add_prometheus_configs.exs
  schema/schema.graphql
Labels: enhancement

#535 Don't autoreconcile eks semvers
  lib/console/schema/cluster.ex
  test/console/deployments/clusters_test.exs
  test/console/graphql/mutations/deployment_mutations_test.exs
Labels: enhancement

#536 feat: Display values.yaml file and allow new file on upgrade
  assets/src/components/cd/services/ServiceSettings.tsx
  assets/src/components/cd/services/ServiceUpdateHelmValues.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/services/deployModal/DeployService.tsx
  assets/src/components/cd/services/deployModal/DeployServiceSettingsHelmValues.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceHelm.tsx
  assets/src/components/cd/services/service/ServiceSettings.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdServices.graphql
  assets/src/routes/cdRoutes.tsx
Labels: enhancement, frontend

#539 fix: Fix upgrade check
  assets/src/components/cd/clusters/ClusterUpgrade.tsx
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/utils/semver.ts
Labels: bug-fix

#542 feat: Add CD sections/clusters to Command Palette
  assets/package.json
  assets/src/components/CommandPalette.tsx
  assets/src/components/cd/ContinuousDeployment.tsx
  assets/src/components/cd/addOns/AddOns.tsx
  assets/src/components/cd/addOns/InstallAddOn.tsx
  assets/src/components/cd/cluster/ClusterServices.tsx
  assets/src/components/cd/providers/CreateProvider.tsx
  assets/src/components/cd/repos/GitRepositoriesImportGit.tsx
  assets/src/components/cd/repos/Repositories.tsx
  assets/src/components/cd/services/Services.tsx
  assets/src/components/cd/services/ServicesTable.tsx
  assets/src/components/cd/services/deployModal/DeployService.tsx
  assets/src/components/utils/KBarUpdateActions.tsx
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
  assets/yarn.lock
Labels: enhancement

#543 Allow configuring observability settings
  assets/src/components/cd/ContinuousDeployment.tsx
  assets/src/components/cd/cluster/ClusterNodes.tsx
  assets/src/components/cd/globalSettings/GlobalSettings.tsx
  assets/src/components/cd/globalSettings/GlobalSettingsObservability.tsx
  assets/src/components/cd/services/CreateGlobalServiceModal.tsx
  assets/src/components/cd/services/component/ServiceComponent.tsx
  assets/src/components/cluster/constants.ts
  assets/src/components/cluster/nodes/ClusterGauges.tsx
  assets/src/components/cluster/nodes/ClusterMetrics.tsx
  assets/src/components/cluster/nodes/SaturationGraphs.tsx
  assets/src/components/cluster/queries.js
  assets/src/components/component/ComponentDetails.tsx
  assets/src/components/component/ComponentMetrics.tsx
  assets/src/components/component/directory.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdComponent.graphql
  assets/src/graph/cdGlobalSettings.graphql
  assets/src/routes/cdRoutes.tsx
  lib/console/deployments/clusters.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/events.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/deployments/pubsub/recurse.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/observability.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/schema/agent_migration.ex
  lib/loki/client.ex
  lib/prometheus/client.ex
  priv/repo/migrations/20231210023110_add_agent_migration_name.exs
  schema/schema.graphql
  test/console/deployments/clusters_test.exs
  test/console/graphql/mutations/deployment_mutations_test.exs
  test/support/factory.ex
Labels: enhancement

#544 feat: Clusters page improvements
  assets/src/components/CommandPalette.tsx
  assets/src/components/cd/addOns/AddOns.tsx
  assets/src/components/cd/cluster/Cluster.tsx
  assets/src/components/cd/cluster/ClusterNodes.tsx
  assets/src/components/cd/cluster/ClusterPermissions.tsx
  assets/src/components/cd/cluster/ClusterSettings.tsx
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/cd/clusters/ClustersColumns.tsx
  assets/src/components/cd/clusters/DynamicClusterIcon.tsx
  assets/src/components/cd/clusters/deprecationsColumns.tsx
  assets/src/components/cd/globalSettings/GlobalSettingsObservability.tsx
  assets/src/components/cd/providers/DeleteCluster.tsx
  assets/src/components/cd/services/ServiceRevisionColumns.tsx
  assets/src/components/cd/services/component/ServiceComponent.tsx
  assets/src/components/cluster/nodes/SaturationGraphs.tsx
  assets/src/components/component/ComponentDetails.tsx
  assets/src/components/hooks/useNewKeyIf.tsx
  assets/src/components/utils/KBarUpdateActions.tsx
  assets/src/components/utils/table/StackedText.tsx
  assets/src/components/utils/tableFetchHelpers.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
Labels: enhancement

#546 fix: Error deploying a new service due to missing `refetch()` function
  assets/src/components/cd/services/ServicesTable.tsx
Labels: bug-fix

#545 Add additional cluster filters and grouping queries
  assets/src/generated/graphql.ts
  lib/console/cached/cluster_nodes.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/schema/cluster.ex
  lib/console/schema/tag.ex
  schema/schema.graphql
  test/console/graphql/queries/deployment_queries_test.exs
  test/support/factory.ex
Labels: enhancement

#548 feat: Improved UX for Deploy Service repository selection screen
  assets/src/components/cd/services/deployModal/DeployService.tsx
  assets/src/components/cd/services/deployModal/DeployServiceSettingsGit.tsx
  assets/src/components/cd/services/deployModal/DeployServiceSettingsHelm.tsx
  assets/src/components/cd/utils/RepoKindSelector.tsx
  assets/src/components/hooks/useOnUnMount.tsx
Labels: enhancement, frontend

#547 feat: figure out update component write frequency
  lib/console/deployments/services.ex
Labels: enhancement

#549 feat: Server side queries for Cluster selection and Service status filtering
  assets/package.json
  assets/src/components/cd/cluster/Cluster.tsx
  assets/src/components/cd/clusters/runtime/columns.tsx
  assets/src/components/cd/services/ServicesFilters.tsx
  assets/src/components/cd/services/ServicesTable.tsx
  assets/src/components/cd/services/deployModal/DeployService.tsx
  assets/src/components/cd/services/deployModal/DeployServiceSettingsBasic.tsx
  assets/src/components/cd/utils/ClusterSelector.tsx
  assets/src/components/hooks/useThrottle.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/graph/cdServices.graphql
  assets/yarn.lock
Labels: enhancement, frontend

#550 feat: Autogen operator secret in console
  assets/src/components/cd/clusters/create/ImportClusterContent.tsx
  config/prod.exs
  lib/console/application.ex
  lib/console/deployments/init.ex
  lib/kube/utils.ex
  test/console/deployments/init_test.exs
Labels: enhancement

#551 Begin working on flagger integration
  assets/src/components/cd/pipelines/nodes/StageNode.tsx
  assets/src/components/cd/services/ServiceStatusChip.tsx
  assets/src/components/cd/services/ServicesFilters.tsx
  assets/src/generated/graphql.ts
  crds/flagger-canary.yaml
  lib/console/deployments/services.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/kubernetes.ex
  lib/console/graphql/kubernetes/base.ex
  lib/console/graphql/kubernetes/canary.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/kubernetes.ex
  lib/console/schema/service.ex
  lib/console_web/controllers/git_controller.ex
  lib/console_web/router.ex
  lib/kube/client.ex
  lib/kube/models.ex
  priv/repo/migrations/20231215015805_add_service_proceed.exs
  schema/schema.graphql
  test-apps/canary/canary.yaml
  test-apps/canary/configmap.yaml
  test-apps/canary/deployment.yaml
  test-apps/canary/ingress.yaml
  test-apps/helm-values/values-flagger.yaml
  test/console/deployments/services_test.exs
  test/console/graphql/mutations/deployment_mutations_test.exs
  test/console_web/controllers/git_controller_test.exs
Labels: enhancement

#552 Add component paused
  assets/src/components/apps/app/components/misc.tsx
  assets/src/generated/graphql.ts
  lib/console/schema/service_component.ex
  schema/schema.graphql
Labels: enhancement

#553 Add promotion confirmation
  assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
  assets/src/components/cd/services/service/ServicePromote.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdServices.graphql
  lib/console/deployments/git/cache.ex
  lib/console/deployments/services.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/kubernetes.ex
  lib/console/graphql/kubernetes/daemon_set.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/kubernetes.ex
  lib/console/schema/service.ex
  lib/console_web/controllers/git_controller.ex
  lib/console_web/router.ex
  priv/repo/migrations/20231215223929_add_promotion_info.exs
  schema/schema.graphql
  test-apps/canary/canary.yaml
  test-apps/canary/deployment.yaml
  test-apps/psps/crd.yaml
  test/console/deployments/services_test.exs
  test/console/graphql/mutations/deployment_mutations_test.exs
  test/console_web/controllers/git_controller_test.exs
Labels: enhancement

#555 Support cluster tag updates
  assets/src/generated/graphql.ts
  lib/console/deployments/clusters.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/schema/cluster.ex
  schema/schema.graphql
Labels: enhancement

#556 feat: Allow editing cluster tags in cluster settings modal
  assets/src/components/cd/cluster/ClusterSettings.tsx
  assets/src/components/cd/clusters/ClustersColumns.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
Labels: enhancement, frontend

#557 Test out k3s upgrades via CRD
  charts/system-upgrade-controller/.helmignore
  charts/system-upgrade-controller/Chart.yaml
  charts/system-upgrade-controller/crds/plan.yaml
  charts/system-upgrade-controller/templates/_helpers.tpl
  charts/system-upgrade-controller/templates/clusterrolebinding.yaml
  charts/system-upgrade-controller/templates/configmap.yaml
  charts/system-upgrade-controller/templates/deployment.yaml
  charts/system-upgrade-controller/templates/serviceaccount.yaml
  charts/system-upgrade-controller/values.yaml
  test-apps/k3s/agent.yaml
  test-apps/k3s/server.yaml
Labels: enhancement

#559 Remove service vsn from sidecar
  assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
  charts/system-upgrade-controller/Chart.yaml
  charts/system-upgrade-controller/crds/plan.yaml
  test-apps/pipelines/k3s.yaml
Labels: enhancement

#561 feat: Update design system
  assets/package.json
  assets/src/components/account/webhooks/Webhook.tsx
  assets/src/components/apps/Apps.tsx
  assets/src/components/apps/app/components/misc.tsx
  assets/src/components/apps/app/dashboards/Dashboards.tsx
  assets/src/components/apps/app/logs/LogsDownloader.tsx
  assets/src/components/apps/app/logs/LogsFullScreen.tsx
  assets/src/components/apps/app/misc.tsx
  assets/src/components/apps/app/runbooks/Runbooks.tsx
  assets/src/components/apps/app/runbooks/runbook/RunbookAlerts.tsx
  assets/src/components/builds/UpgradePolicies.tsx
  assets/src/components/cd/addOns/AddOns.tsx
  assets/src/components/cd/cluster/ClusterMetadata.tsx
  assets/src/components/cd/clusters/ClusterConditions.tsx
  assets/src/components/cd/clusters/ClusterHealthChip.tsx
  assets/src/components/cd/services/CreateGlobalService.tsx
  assets/src/components/cd/services/deployModal/DeployServiceSettingsHelmValues.tsx
  assets/src/components/cd/services/deployModal/DeployServiceSettingsSecrets.tsx
  assets/src/components/db-management/DatabasesList.tsx
  assets/src/components/help/ChatbotMarkdown.tsx
  assets/src/components/layout/NotificationSeverity.tsx
  assets/src/components/utils/BindingInput.tsx
  assets/src/types/styled.d.ts
  assets/src/utils/color.ts
  assets/tsconfig.eslint.json
  assets/tsconfig.json
  assets/tsconfig.node.json
  assets/vite.config.ts
  assets/vitest.config.ts
  assets/yarn.lock
Labels: enhancement

#564 feat: Pipeline routing + layout fix
  assets/src/components/cd/pipelines/Pipeline.tsx
  assets/src/components/cd/pipelines/Pipelines.tsx
  assets/src/components/cd/pipelines/utils/nodeLayouter.tsx
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
Labels: enhancement, frontend

#565 fix: Infinite redirect on `/cd/pipelines` route
  assets/src/components/cd/pipelines/Pipelines.tsx
Labels: bug-fix, frontend

#560 Allow querying branches/tags for repos
  Makefile
  assets/src/components/cd/services/ServiceSettings.tsx
  assets/src/components/cd/services/deployModal/DeployServiceSettingsGit.tsx
  assets/src/components/cd/services/service/ServiceSettings.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdGitRepos.graphql
  lib/console/deployments/git/agent.ex
  lib/console/deployments/git/discovery.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/resolvers/deployments.ex
  schema/schema.graphql
  test-apps/pipelines/k3s.yaml
  test/console/deployments/helm/repository_test.exs
Labels: enhancement

#566 Add ability to create service accounts, token scopes, add tests for all
  assets/src/components/cd/services/deployModal/DeployServiceSettingsGit.tsx
  assets/src/generated/graphql.ts
  lib/console/deployments/clusters.ex
  lib/console/deployments/git/discovery.ex
  lib/console/deployments/global.ex
  lib/console/deployments/policies/policies.ex
  lib/console/deployments/services.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/middleware/feature.ex
  lib/console/graphql/middleware/scope.ex
  lib/console/graphql/resolvers/user.ex
  lib/console/graphql/schema/base.ex
  lib/console/graphql/users.ex
  lib/console/schema/access_token.ex
  lib/console/schema/cluster.ex
  lib/console/schema/global_service.ex
  lib/console/schema/tag.ex
  lib/console/schema/user.ex
  lib/console/services/users.ex
  lib/console/services/users/access_tokens.ex
  priv/repo/migrations/20231221213852_add_service_account_policies.exs
  priv/repo/migrations/20231223172158_add_cluster_metadata_distro.exs
  priv/repo/migrations/20231223194523_add_distro_global.exs
  schema/schema.graphql
  test/console/deployments/clusters_test.exs
  test/console/deployments/global_test.exs
  test/console/graphql/mutations/deployment_mutations_test.exs
  test/console/graphql/mutations/user_mutations_test.exs
  test/console/graphql/queries/deployment_queries_test.exs
  test/console/services/users/access_tokens_test.exs
  test/console/services/users_test.exs
  test/support/factory.ex
Labels: enhancement

#568 Add rate limiting configuration
  config/config.exs
  lib/console.ex
  lib/console_web/endpoint.ex
  mix.exs
  mix.lock
  rel/config/config.exs
Labels: enhancement, backend

#569 Delete pod in CD
  assets/src/components/cluster/pods/PodsList.tsx
  assets/src/components/cluster/queries.js
  assets/src/components/component/info/Pods.tsx
  charts/console/Chart.yaml
  charts/console/templates/migration.yaml
Labels: enhancement, frontend
