Repository pluralsh/console, pull requests merged in 2023-01, with the labels that each got.

#179 App components redesign
  assets/src/components/Breadcrumbs.tsx
  assets/src/components/apps/app/components/component/Component.tsx
  assets/src/components/apps/app/components/component/ComponentEvents.tsx
  assets/src/components/apps/app/components/component/ComponentInfo.tsx
  assets/src/components/apps/app/components/component/info/Certificate.tsx
  assets/src/components/apps/app/components/component/info/CronJob.tsx
  assets/src/components/apps/app/components/component/info/Deployment.jsx
  assets/src/components/apps/app/components/component/info/Ingress.jsx
  assets/src/components/apps/app/components/component/info/Job.tsx
  assets/src/components/apps/app/components/component/info/Metadata.tsx
  assets/src/components/apps/app/components/component/info/Pods.tsx
  assets/src/components/apps/app/components/component/info/Service.jsx
  assets/src/components/apps/app/components/component/info/StatefulSet.jsx
  assets/src/components/apps/app/cost/CostAnalysis.tsx
  assets/src/components/cluster/Certificate.jsx
  assets/src/components/cluster/Job.jsx
  assets/src/components/cluster/nodes/TableElements.tsx
  assets/src/components/cluster/pods/Pod.tsx
  assets/src/components/cluster/pods/PodList.tsx
  assets/src/components/repos/installer/ConfigurationItem.tsx
  assets/src/components/utils/Alert.tsx
  assets/src/components/utils/Confirm.tsx
  assets/src/components/utils/PropWide.tsx
  assets/src/utils/status.ts
Labels: enhancement

#182 Better oauth error handling
  assets/src/components/OauthCallback.js
Labels: bug-fix, frontend

#171 Add buckets/domains to stack install apis and pluralContext gql query
  lib/console/deployer.ex
  lib/console/graphql/plural.ex
  lib/console/graphql/resolvers/plural.ex
  lib/console/plural/context.ex
  lib/console/services/plural.ex
  test/console/graphql/mutations/plural_mutations_test.exs
  test/console/services/plural_test.exs
Labels: enhancement, backend

#177 Refactor deployer and runner
  lib/console/deployer.ex
  lib/console/deployer/operations.ex
  lib/console/graphql/resolvers/plural.ex
  lib/console/runbooks/action.ex
  lib/console/runner.ex
  lib/console/services/runbooks.ex
  test/console/deployer_test.exs
  test/console/runner_test.exs
  test/support/test_helpers.ex
Labels: enhancement, backend

#183 Use updated elixir k8s client
  lib/console/graphql/resolvers/kubernetes.ex
  mix.exs
  mix.lock
  test/support/kubernetes_scaffolds.ex
Labels: bug-fix, backend

#184 Cache command output locally
  lib/console/commands/command.ex
  lib/console/graphql/build.ex
  lib/console/schema/command.ex
  lib/console/services/builds.ex
  test/console/commands/command_test.exs
  test/console/commands/tee_test.exs
Labels: enhancement, backend

#197 push pr images to ghcr for testing
  .github/workflows/test.yaml
Labels: bug-fix

#192 bump helm chart version
  plural/helm/console/Chart.yaml
  plural/helm/console/values.yaml
Labels: dependencies

#198 Add pod watcher timeout
  lib/console/cached/kubernetes.ex
  lib/console/cached/namespace.ex
  lib/console/watchers/pod.ex
  mix.exs
  mix.lock
  test/console/cached/namespace_test.exs
Labels: bug-fix, backend

#209 Make upgrade queue setup more robust
  lib/console/watchers/upgrade.ex
Labels: enhancement, backend

#203 ENG-1117 Add dedicated node group for console nodes
  assets/src/components/types.js
  config/config.exs
  lib/console.ex
  lib/console/application.ex
  lib/console/clustering/bootstrapper.ex
  lib/console/clustering/connect.ex
  lib/console/commands/configuration.ex
  lib/console/commands/plural.ex
  lib/console/deployer.ex
  lib/console/deployer/dedicated.ex
  lib/console/deployer/operations.ex
  lib/console/runner/harakiri.ex
  lib/console/schema/build.ex
  lib/console/services/builds.ex
  lib/kube/builder.ex
  mix.lock
  plural/helm/console/templates/secrets.yaml
  plural/terraform/aws/deps.yaml
  plural/terraform/aws/node-group.tf
  plural/terraform/aws/variables.tf
  priv/repo/migrations/20230118012409_add_build_k8s_job.exs
  rel/config/console.exs
Labels: enhancement, backend

#216 feat: Expose optional field on the recipe configuration
  lib/console/graphql/plural.ex
  lib/console/plural/models.ex
  test/console/graphql/queries/plural_queries_test.exs
Labels: enhancement, backend

#220 Improve oidc resilience
  mix.exs
  mix.lock
Labels: enhancement, backend

#222 feat: Update recipe config query fragment to properly expose optional field
  lib/console/plural/queries.ex
Labels: bug-fix, backend

#221 Add build info query
  lib/console/graphql/build.ex
  lib/console/graphql/resolvers/build.ex
  lib/console/graphql/resolvers/user.ex
  lib/console/graphql/users.ex
  lib/console/schema/build.ex
  lib/console/schema/user.ex
  lib/console/services/users.ex
  priv/repo/migrations/20230125163535_add_build_timestamp.exs
  test/console/graphql/mutations/user_mutations_test.exs
  test/console/graphql/queries/build_queries_test.exs
Labels: enhancement, backend

#224 Make console node group optional
  plural/terraform/aws/deps.yaml
  plural/terraform/aws/node-group.tf
  plural/terraform/aws/variables.tf
Labels: enhancement, backend, hotfix

#219 Add protection support for destroy builds
  lib/console/plural/context.ex
  lib/console/services/builds.ex
  test/console/services/builds_test.exs
Labels: enhancement, backend

#223 Fix SMTP update
  lib/console/services/plural.ex
  test/console/services/plural_test.exs
Labels: bug-fix, backend

#225 fix: Update empty config message and add leading period to domain
  assets/package.json
  assets/src/components/cluster/containers/ContainersList.tsx
  assets/src/components/repos/installer/Application.tsx
  assets/src/components/repos/installer/Configuration.tsx
  assets/src/components/repos/installer/ConfigurationItem.tsx
  assets/yarn.lock
Labels: bug-fix

#227 Minor Console language fixes
  assets/src/components/apps/AppCard.tsx
  assets/src/components/apps/AppStatus.tsx
  assets/src/components/apps/app/App.tsx
  assets/src/components/apps/app/components/ComponentProgress.tsx
  assets/src/components/apps/app/config/ConfigurationEditor.tsx
  assets/src/components/builds/BuildStatus.tsx
  assets/src/components/cluster/nodes/NodesList.tsx
  assets/src/components/cluster/pods/PodInfo.tsx
Labels: bug-fix, frontend

#226 feat: Add dropdown Components filter
  assets/package.json
  assets/src/components/apps/app/components/Components.tsx
  assets/src/components/utils/layout/ResponsiveLayoutSidecarContainer.tsx
  assets/src/components/utils/layout/ResponsiveLayoutSidenavContainer.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#229 Add role search
  lib/console/graphql/resolvers/user.ex
  lib/console/graphql/users.ex
  lib/console/schema/role.ex
  test/console/graphql/queries/user_queries_test.exs
Labels: enhancement, backend

#230 Start of conversion to Full-screen views
  assets/src/components/apps/Apps.tsx
  assets/src/components/cluster/Cluster.tsx
  assets/src/components/cluster/TableElements.tsx
  assets/src/components/cluster/containers/ContainersList.tsx
  assets/src/components/cluster/nodes/ClusterGauges.tsx
  assets/src/components/cluster/nodes/ClusterMetrics.tsx
  assets/src/components/cluster/nodes/Node.tsx
  assets/src/components/cluster/nodes/NodeEvents.tsx
  assets/src/components/cluster/nodes/NodeGraphs.tsx
  assets/src/components/cluster/nodes/NodeInfo.tsx
  assets/src/components/cluster/nodes/NodeRaw.tsx
  assets/src/components/cluster/nodes/NodeSideNav.tsx
  assets/src/components/cluster/nodes/Nodes.tsx
  assets/src/components/cluster/nodes/SaturationGraphs.tsx
  assets/src/components/cluster/pods/Pods.tsx
  assets/src/components/cluster/pods/PodsList.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/utils/Tabs.tsx
  assets/src/components/utils/layout/ResponsiveLayoutPage.tsx
  assets/src/components/utils/layout/ResponsivePageFullWidth.tsx
  assets/src/components/utils/layout/ScrollablePage.tsx
  assets/src/routes/clusterRoutes.tsx
Labels: enhancement

#232 Fix nodes table display
  assets/src/components/cluster/nodes/NodesList.tsx
Labels: enhancement, frontend
