Repository pluralsh/console, pull requests merged in 2023-08, with the labels that each got.

#388 Add config map/secret queries
  assets/src/generated/graphql.ts
  lib/console/graphql/kubernetes.ex
  lib/console/graphql/kubernetes/base.ex
  lib/console/graphql/kubernetes/config.ex
  lib/console/graphql/resolvers/kubernetes.ex
  schema/schema.graphql
  test/console/graphql/queries/kubernetes_queries_test.exs
  test/support/kubernetes_scaffolds.ex
Labels: enhancement, backend

#391 Use new setup-plural action
  .github/workflows/publish.yaml
  .github/workflows/push-to-plural.yaml
Labels: enhancement

#392 Better version name inference
  assets/src/components/apps/AppCard.tsx
Labels: enhancement

#395 fix: Intercom chat not appearing for some users
  assets/src/components/login/Login.tsx
Labels: bug-fix, frontend

#396 Fix vpn download and remove plural account cta
  assets/src/components/layout/Header.tsx
  assets/src/components/vpn/actions/Download.tsx
  lib/console/services/vpn.ex
  test/support/kubernetes_scaffolds.ex
Labels: enhancement

#397 fix: Support chat on sandbox
  assets/package.json
  assets/src/components/login/CurrentUser.tsx
  assets/src/components/login/Login.tsx
  assets/yarn.lock
Labels: bug-fix, frontend

#398 Bump cli version in console
  Dockerfile
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  lib/console/graphql/database.ex
  lib/console/graphql/kubernetes.ex
  schema/schema.graphql
Labels: enhancement

#400 Allow postgres statuses to be nullable
  assets/src/generated/graphql.ts
  lib/console/graphql/database.ex
  schema/schema.graphql
Labels: enhancement

#401 feat: Database management
  assets/package.json
  assets/src/components/billing/queries.ts
  assets/src/components/db-management/DatabaseManagement.tsx
  assets/src/components/db-management/DatabasesList.tsx
  assets/src/components/db-management/RestoreDatabaseModal.tsx
  assets/src/components/db-management/TimezoneComboBox.tsx
  assets/src/components/db-management/constants.ts
  assets/src/components/db-management/demo-dbs.json
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/utils/Alert.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/databases.graphql
  assets/src/routes/clusterRoutes.tsx
  assets/src/utils/kubernetes.ts
  assets/src/utils/time.ts
  assets/yarn.lock
Labels: enhancement, frontend
