Repository pluralsh/console, pull requests merged in 2023-10, with the labels that each got.

#432 Add support for specifying cluster credentials
  lib/console/deployments/clusters.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/schema/cluster.ex
  priv/repo/migrations/20231006141431_add_cluster_creds.exs
  test/console/deployments/clusters_test.exs
Labels: enhancement

#430 Allow for secret mounts to be configured
  plural/helm/console/Chart.yaml
  plural/helm/console/templates/deployment.yaml
  plural/helm/console/templates/migration.yaml
  plural/helm/console/values.yaml
Labels: enhancement

#433 fix: Merge with origin/master
  assets/src/components/apps/app/App.tsx
  assets/src/components/apps/app/config/Configuration.tsx
  assets/src/components/apps/app/config/misc.ts
  assets/src/components/graphql/plural.js
  assets/src/components/utils/MarkdocContent.tsx
  assets/src/generated/graphql.ts
  lib/console/graphql/configuration.ex
  lib/console/graphql/resolvers/plural.ex
  lib/console/services/plural.ex
  lib/console/storage/git.ex
  lib/console/watchers/upgrade.ex
  plural/helm/console/Chart.yaml
  plural/helm/console/templates/deployment.yaml
  plural/helm/console/templates/migration.yaml
  plural/helm/console/templates/secrets.yaml
  plural/helm/console/values.yaml
  plural/helm/console/values.yaml.tpl
  schema/schema.graphql
Labels: bug-fix

#434 fix: Add configurable probes
  plural/helm/console/Chart.yaml
  plural/helm/console/templates/deployment.yaml
  plural/helm/console/values.yaml
Labels: enhancement

#431 Convert console dkr image to run as nonroot
  Dockerfile
  lib/console_web/console_web.ex
  rel/config/console.exs
Labels: enhancement

#438 feat: Service Secrets page
  assets/src/components/cd/services/ServiceSelector.tsx
  assets/src/components/cd/services/service/ServiceSecrets.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdServices.graphql
Labels: enhancement, frontend

#443 feat: Component details pages complete
  assets/src/components/apps/app/components/component/AppComponent.tsx
  assets/src/components/apps/app/components/component/info/Certificate.tsx
  assets/src/components/apps/app/components/component/info/Deployment.tsx
  assets/src/components/apps/app/components/component/info/Metadata.tsx
  assets/src/components/apps/app/components/component/info/Service.tsx
  assets/src/components/apps/app/components/component/info/StatefulSet.tsx
  assets/src/components/cd/services/component/ServiceComponent.tsx
  assets/src/components/cd/services/service/ServiceComponents.tsx
  assets/src/components/cluster/queries.js
  assets/src/components/component/ComponentEvents.tsx
  assets/src/components/component/ComponentInfo.tsx
  assets/src/components/component/ComponentMetrics.tsx
  assets/src/components/component/ComponentRaw.tsx
  assets/src/components/component/ViewLogsButton.tsx
  assets/src/components/component/directory.tsx
  assets/src/components/component/info/Certificate.tsx
  assets/src/components/component/info/CronJob.tsx
  assets/src/components/component/info/Deployment.tsx
  assets/src/components/component/info/Ingress.tsx
  assets/src/components/component/info/Job.tsx
  assets/src/components/component/info/Metadata.tsx
  assets/src/components/component/info/Pods.tsx
  assets/src/components/component/info/Service.tsx
  assets/src/components/component/info/StatefulSet.tsx
  assets/src/components/component/info/common.tsx
  assets/src/components/component/kindToQuery.tsx
  assets/src/components/graphql/kubernetes.js
  assets/src/generated/graphql.ts
  assets/src/graph/cdComponent.graphql
  assets/src/graph/databases.graphql
  assets/src/graph/kubernetes/certificate.graphql
  assets/src/graph/kubernetes/cronJob.graphql
  assets/src/graph/kubernetes/deployment.graphql
  assets/src/graph/kubernetes/ingress.graphql
  assets/src/graph/kubernetes/job.graphql
  assets/src/graph/kubernetes/kubernetes.graphql
  assets/src/graph/kubernetes/service.graphql
  assets/src/graph/kubernetes/statefulSet.graphql
  assets/src/graph/kubernetes/unstructuredResource.graphql
  assets/src/routes/appsRoutes.tsx
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
Labels: enhancement, frontend

#446 feat: Providers page
  assets/src/components/apps/app/components/ComponentCard.tsx
  assets/src/components/apps/app/components/ComponentList.tsx
  assets/src/components/apps/app/components/component/AppComponent.tsx
  assets/src/components/cd/cluster/ClusterPods.tsx
  assets/src/components/cd/clusters/ClusterUpgrade.tsx
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/cd/clusters/deprecationsColumns.tsx
  assets/src/components/cd/providers/CreateProvider.tsx
  assets/src/components/cd/providers/InputRevealer.tsx
  assets/src/components/cd/providers/Providers.tsx
  assets/src/components/cd/providers/ProvidersColumns.tsx
  assets/src/components/cd/services/ServiceSelector.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/services/ServicesFilters.tsx
  assets/src/components/cd/services/component/ServiceComponent.tsx
  assets/src/components/cd/services/service/ServiceComponents.tsx
  assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
  assets/src/components/cd/services/service/countDeprecations.tsx
  assets/src/components/cd/services/service/deprecationUtils.tsx
  assets/src/components/component/ComponentDetails.tsx
  assets/src/components/component/ComponentRaw.tsx
  assets/src/components/component/kindToQuery.tsx
  assets/src/components/utils/Provider.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdProviders.graphql
  assets/src/graph/cdServices.graphql
  assets/src/routes/appsRoutes.tsx
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
  assets/src/utils/hasDefined.ts
  assets/src/utils/isNonNullable.ts
Labels: enhancement, frontend

#451 feat: Component Details path change + Service deployment creation
  assets/src/components/cd/cluster/ClusterPods.tsx
  assets/src/components/cd/providers/CreateProvider.tsx
  assets/src/components/cd/providers/ProviderSettings.tsx
  assets/src/components/cd/providers/UpdateProvider.tsx
  assets/src/components/cd/services/DecoratedName.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/services/ServicesDeployService.tsx
  assets/src/components/cd/services/ServicesFilters.tsx
  assets/src/components/cd/services/component/ServiceComponent.tsx
  assets/src/components/cd/services/service/ServiceComponents.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceSecrets.tsx
  assets/src/components/component/ComponentDetails.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdGitRepos.graphql
  assets/src/graph/cdServices.graphql
  assets/src/routes/cdRoutesConsts.tsx
Labels: enhancement

#457 fix: Update packages to fix vulnerability
  assets/e2e/package.json
  assets/e2e/yarn.lock
  assets/package.json
  assets/src/components/account/Account.tsx
  assets/src/components/apps/app/App.tsx
  assets/src/components/billing/BillingSubscriptionProvider.tsx
  assets/src/components/builds/build/Build.tsx
  assets/src/components/builds/build/changelog/Changelog.tsx
  assets/src/components/cluster/containers/Container.tsx
  assets/src/components/cluster/containers/getPodContainersStats.tsx
  assets/src/components/cluster/pods/Pods.tsx
  assets/src/components/contexts/PluralContext.tsx
  assets/src/components/profile/MyProfile.tsx
  assets/src/components/repos/installer/helpers.tsx
  assets/src/components/utils/BindingInput.tsx
  assets/src/components/utils/PageTitleSelectButton.tsx
  assets/yarn.lock
Labels: dependencies

#460 Cluster view tweaks
  assets/src/components/cd/clusters/ClusterHealthChip.tsx
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/utils/table/ColWithIcon.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
Labels: enhancement, frontend

#462 feat: FileDrop, Spinner, Modal, Providers Table, Git Import improvements
  assets/.stylelintrc.yaml
  assets/package.json
  assets/src/App.tsx
  assets/src/components/builds/build/progress/CommandExitStatus.tsx
  assets/src/components/cd/ModalAlt.tsx
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/cd/providers/GcpCredentials.tsx
  assets/src/components/cd/providers/ProvidersColumns.tsx
  assets/src/components/cd/providers/fileInputTheme.ts
  assets/src/components/cd/repos/GitHealthChip.tsx
  assets/src/components/cd/repos/GitRepositoriesImportGit.tsx
  assets/src/components/layout/Console.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/utils/FileDrop.tsx
  assets/src/components/utils/typography/BasicLink.tsx
  assets/src/index.css
  assets/yarn.lock
Labels: enhancement, frontend

#465 feat: [VQA] Add chip for cluster conditions
  assets/src/components/cd/clusters/ClusterConditions.tsx
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/cd/clusters/GlobalSettings.tsx
  assets/src/components/cd/services/ServiceErrors.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/services/globalSettings/GlobalSettingsPermissions.tsx
  assets/src/components/cd/services/globalSettings/GlobalSettingsRepositories.tsx
  assets/src/components/cd/services/service/ServiceDeprecationsModal.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/layout/SideNavEntries.tsx
  assets/src/components/layout/Subheader.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
  assets/src/utils/sha.tsx
Labels: enhancement

#466 feat: Daily CD handoff
  assets/src/components/cd/ModalAlt.tsx
  assets/src/components/cd/cluster/ClusterPermissions.tsx
  assets/src/components/cd/clusters/GlobalSettings.tsx
  assets/src/components/cd/providers/ProviderSettings.tsx
  assets/src/components/cd/repos/GitHealthChip.tsx
  assets/src/components/cd/repos/GitRepositoriesImportGit.tsx
  assets/src/components/cd/repos/GitRepositoriesUpdateGit.tsx
  assets/src/components/cd/services/CreateGlobalService.tsx
  assets/src/components/cd/services/DeleteService.tsx
  assets/src/components/cd/services/ServicePermissions.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/utils/PermissionsModal.tsx
  assets/src/components/cd/utils/SshKeyUpload.tsx
  assets/src/components/utils/FileDrop.tsx
  assets/src/components/utils/MoreMenu.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/graph/cdGlobalServices.graphql
  assets/src/graph/cdServices.graphql
Labels: enhancement

#467 feat: update cluster/services routes and fix cluster pod detail view
  assets/src/components/cd/cluster/ClusterServices.tsx
  assets/src/components/cd/services/ServiceSelector.tsx
  assets/src/components/cd/services/Services.tsx
  assets/src/components/cd/services/ServicesFilters.tsx
  assets/src/components/cd/services/component/ServiceComponent.tsx
  assets/src/components/cd/services/service/ServiceComponents.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
  assets/src/components/cd/services/service/ServiceSecrets.tsx
  assets/src/components/component/ComponentDetails.tsx
  assets/src/components/component/info/CronJob.tsx
  assets/src/components/component/info/Pods.tsx
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
Labels: bug-fix
