Repository pluralsh/console, pull requests merged in 2023-06, with the labels that each got.

#353 Implement command palette
  assets/package.json
  assets/src/App.jsx
  assets/src/components/CommandPalette.jsx
  assets/src/components/layout/AppNav.tsx
  assets/src/components/layout/Console.tsx
  assets/src/generated/graphql.ts
  assets/yarn.lock
  lib/console/graphql/plural.ex
  lib/console/graphql/resolvers/plural.ex
  lib/console/plural/accounts.ex
  lib/console/plural/queries.ex
  lib/console/services/plural.ex
  schema/schema.graphql
  test/console/graphql/queries/plural_queries_test.exs
Labels: enhancement, frontend, backend

#360 Update plural cli in dockerfile
  Dockerfile
Labels: enhancement

#363 fix(frontend): bump react table to fix build
  assets/package.json
  assets/yarn.lock
Labels: bug-fix

#361 Application info query
  Dockerfile
  assets/src/components/apps/app/App.tsx
  assets/src/components/apps/app/credentials/Credentials.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/apps.graphql
  assets/src/routes/appsRoutes.tsx
  lib/console/commands/command.ex
  lib/console/commands/plural.ex
  lib/console/graphql/kubernetes/application.ex
  lib/console/graphql/resolvers/plural.ex
  lib/console/services/plural.ex
  schema/schema.graphql
  test/console/graphql/queries/plural_queries_test.exs
Labels: enhancement, backend

#364 Release v0.4.15
  plural/helm/console/Chart.yaml
Labels: release

#365 feat: Upgrade front-end dependencies
  assets/.yarn/releases/yarn-3.2.4.cjs
  assets/.yarn/releases/yarn-3.6.0.cjs
  assets/.yarnrc.yml
  assets/codegen.yml
  assets/e2e/.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  assets/e2e/.yarn/releases/yarn-3.2.4.cjs
  assets/e2e/.yarn/releases/yarn-3.6.0.cjs
  assets/e2e/.yarnrc.yml
  assets/e2e/package.json
  assets/e2e/yarn.lock
  assets/package.json
  assets/src/App.jsx
  assets/src/components/CommandPalette.jsx
  assets/src/components/apps/Apps.tsx
  assets/src/components/apps/app/runbooks/runbook/Runbook.tsx
  assets/src/components/apps/app/runbooks/runbook/RunbookAlerts.tsx
  assets/src/components/layout/NotificationSeverity.tsx
  assets/src/components/utils/PieChart.tsx
  assets/src/generated/graphql.ts
  assets/src/types/styled.d.ts
  assets/yarn.lock
Labels: dependencies, frontend

#370 feat: app uninstall dialog
  assets/src/components/apps/app/App.tsx
  assets/src/components/apps/app/uninstall/Uninstall.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/builds.graphql
  assets/src/routes/appsRoutes.tsx
  plural/helm/console/Chart.lock
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/test-base-0.1.10.tgz
  plural/helm/console/charts/test-base-0.1.5.tgz
  plural/helm/console/values.yaml
Labels: enhancement, frontend

#375 feat: Sync admin state in console logins
  lib/console/services/users.ex
  test/console/services/users_test.exs
Labels: enhancement

#376 release v0.4.17
  plural/helm/console/Chart.yaml
  plural/helm/console/values.yaml
Labels: release
