Repository pluralsh/console, pull requests merged in 2023-02, with the labels that each got.

#235 Console updates
  assets/package.json
  assets/src/components/apps/Apps.tsx
  assets/src/components/apps/app/runbooks/runbook/Runbook.tsx
  assets/src/components/apps/app/runbooks/runbook/RunbookExecutions.tsx
  assets/src/components/cluster/containers/ContainerShell.tsx
  assets/src/components/terminal/Terminal.tsx
  assets/yarn.lock
Labels: enhancement

#234 Create add-asana-comment.yml
  .github/workflows/add-asana-comment.yml
Labels: enhancement

#238 Fix readiness color scheme
  assets/src/components/apps/app/components/component/Component.tsx
  assets/src/utils/status.ts
  lib/console/application.ex
  lib/console/cached/pods.ex
  lib/console/graphql/kubernetes/application.ex
  test/console/cached/pod_test.exs
Labels: bug-fix, frontend

#236 Fix "Update" button interaction
  assets/package.json
  assets/public/service-worker.js
  assets/src/components/AutoRefresh.jsx
  assets/src/components/layout/Console.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/layout/WithApplicationUpdate.tsx
  assets/src/service-worker.ts
  assets/src/serviceWorker.ts
  assets/src/serviceWorkerRegistration.ts
  assets/vite.config.ts
  assets/yarn.lock
Labels: bug-fix

#242 Query for cached pods
  lib/console/graphql/kubernetes.ex
  lib/console/graphql/resolvers/kubernetes.ex
  test/test_helper.exs
Labels: enhancement, backend

#243 Speed up pods view
  assets/src/components/apps/app/components/component/info/Ingress.tsx
  assets/src/components/cluster/constants.ts
  assets/src/components/cluster/containers/ContainersList.tsx
  assets/src/components/cluster/pods/Pods.tsx
  assets/src/components/cluster/queries.js
  assets/src/components/graphql/kubernetes.js
  assets/src/generated/graphql.ts
  lib/console/plural/queries.ex
  lib/console/plural/repositories.ex
  test/console/graphql/queries/plural_queries_test.exs
Labels: enhancement, frontend

#246 Bump console to v0.3.25
  plural/helm/console/Chart.yaml
  plural/helm/console/values.yaml
Labels: enhancement, backend

#247 Register build pids in db
  lib/console/pubsub/protocols/recurse.ex
  lib/console/runner.ex
  lib/console/schema/build.ex
  lib/console/services/builds.ex
  priv/repo/migrations/20230203195928_add_build_pid.exs
  test/console/pubsub/recurse/builds_test.exs
  test/console/runner_test.exs
Labels: bug-fix, backend

#250 Small console tweaks
  assets/src/components/apps/AppCard.tsx
  assets/src/components/apps/app/logs/LogLine.tsx
  lib/console/schema/user.ex
Labels: enhancement

#252 feat: Split components into 2 across
  assets/src/components/apps/app/components/Component.tsx
  assets/src/components/apps/app/components/Components.tsx
Labels: enhancement

#257 Releasing console v0.4.0
  plural/helm/console/Chart.yaml
  plural/helm/console/values.yaml
Labels: enhancement

#260 feat: Update installer
  assets/src/components/repos/constants.ts
  assets/src/components/repos/installer/Configuration.tsx
  assets/src/components/repos/installer/ConfigurationItem.tsx
  assets/src/components/repos/installer/Installer.tsx
Labels: enhancement, frontend

#259 fix: Various improvements
  assets/src/components/apps/app/components/Components.tsx
  assets/src/components/apps/app/components/component/Component.tsx
  assets/src/components/utils/Graph.tsx
Labels: enhancement, frontend

#261 feat: Add hover to table rows and remove inline links
  assets/package.json
  assets/src/components/apps/app/components/component/info/CronJob.tsx
  assets/src/components/apps/app/components/component/info/Pods.tsx
  assets/src/components/cluster/containers/ContainersList.tsx
  assets/src/components/cluster/nodes/NodeInfo.tsx
  assets/src/components/cluster/nodes/NodesList.tsx
  assets/src/components/cluster/pods/Pods.tsx
  assets/src/components/cluster/pods/PodsList.tsx
  assets/yarn.lock
Labels: enhancement

#264 Get a full list of repos for the installer
  assets/src/components/repos/installer/Installer.tsx
  assets/src/components/repos/installer/query.ts
Labels: bug-fix, frontend

#265 feat: Global app navigation
  assets/src/components/cluster/ContainerStatuses.tsx
  assets/src/components/layout/AppNav.tsx
  assets/src/components/layout/Subheader.tsx
Labels: enhancement, frontend

#267 Release v0.4.1
  plural/helm/console/Chart.yaml
  plural/helm/console/values.yaml
Labels: enhancement

#269 feat: Update component detail views
  assets/src/components/apps/app/components/component/Component.tsx
  assets/src/components/apps/app/components/component/ComponentInfo.tsx
  assets/src/components/apps/app/components/component/ComponentMetrics.tsx
  assets/src/components/apps/app/components/component/info/Certificate.tsx
  assets/src/components/apps/app/components/component/info/CronJob.tsx
  assets/src/components/apps/app/components/component/info/Deployment.tsx
  assets/src/components/apps/app/components/component/info/Ingress.tsx
  assets/src/components/apps/app/components/component/info/Job.tsx
  assets/src/components/apps/app/components/component/info/Metadata.tsx
  assets/src/components/apps/app/components/component/info/Pods.tsx
  assets/src/components/apps/app/components/component/info/Service.tsx
  assets/src/components/apps/app/components/component/info/StatefulSet.tsx
  assets/src/routes/appsRoutes.tsx
Labels: enhancement

#270 Update dependencies
  assets/package.json
  assets/src/components/account/users/Users.tsx
  assets/src/components/apps/Apps.tsx
  assets/src/components/apps/app/components/component/Component.tsx
  assets/src/components/apps/app/config/Configuration.tsx
  assets/src/components/apps/app/runbooks/runbook/Runbook.tsx
  assets/src/components/audits/Audits.tsx
  assets/src/components/builds/build/changelog/Changelog.tsx
  assets/src/components/cluster/containers/Container.tsx
  assets/src/components/cluster/nodes/Node.tsx
  assets/src/components/utils/RangePicker.tsx
  assets/yarn.lock
Labels: dependencies

#268 feat: Finesse App switcher transitions
  assets/src/components/hooks/useOnClickOutside.tsx
  assets/src/components/layout/AppNav.tsx
Labels: enhancement, frontend

#262 Update auth/login pages on Console
  assets/public/login-sidebar.avif
  assets/public/login-sidebar.jpg
  assets/src/components/Invite.jsx
  assets/src/components/Login.jsx
  assets/src/components/layout/Console.tsx
  assets/src/components/login/CurrentUser.tsx
  assets/src/components/login/Invite.tsx
  assets/src/components/login/LinkLogin.tsx
  assets/src/components/login/Login.tsx
  assets/src/components/login/LoginFooter.tsx
  assets/src/components/login/LoginPortal.tsx
  assets/src/components/login/OauthCallback.tsx
  assets/src/components/login/PasswordValidation.tsx
  assets/src/components/login/constants.ts
  assets/src/components/utils/LabelledInput.jsx
  assets/src/components/utils/LabelledInput.tsx
  assets/src/components/utils/WelcomeHeader.tsx
  assets/src/components/utils/query.ts
  assets/src/routes/rootRoutes.tsx
  assets/src/utils/email.test.ts
  assets/src/utils/email.ts
Labels: enhancement, frontend

#266 feat: Truncate and reduce label sizes + Responsive enhancements
  assets/src/components/apps/Apps.tsx
  assets/src/components/apps/app/components/Component.tsx
  assets/src/components/cluster/LabelsAnnotations.tsx
  assets/src/components/cluster/containers/Container.tsx
  assets/src/components/cluster/nodes/Node.tsx
  assets/src/components/utils/Metadata.tsx
  assets/src/components/utils/layout/ResponsivePageFullWidth.tsx
  assets/src/components/utils/layout/ScrollablePage.tsx
  assets/src/utils/makeGrid.ts
Labels: enhancement, frontend

#272 Console release
  plural/helm/console/Chart.yaml
  plural/helm/console/values.yaml
Labels: enhancement, backend

#273 fix: OAuthCallback was hanging
  assets/src/components/login/OauthCallback.tsx
Labels: bug-fix

#275 Release console v0.4.3
  plural/helm/console/Chart.yaml
  plural/helm/console/values.yaml
Labels: enhancement, hotfix

#278 fix: Fix component detail page layout
  assets/src/components/apps/app/components/component/ComponentInfo.tsx
  assets/src/components/apps/app/components/component/info/Metadata.tsx
Labels: bug-fix

#277 fix target name
  plural/helm/console/Chart.yaml
  plural/helm/console/templates/proxies.yaml
Labels: bug-fix

#279 fix: Get rid of test message
  assets/src/components/layout/Console.tsx
Labels: bug-fix

#280 Don't open logs in new tab
  assets/src/components/apps/app/components/component/ViewLogsButton.tsx
Labels: enhancement, frontend

#282 feat: Add option to clear all selected component types
  assets/src/components/apps/app/components/Components.tsx
Labels: enhancement

#283 feat: Use combobox to filter apps and namespaces
  assets/src/components/apps/app/config/ConfigurationSettings.tsx
  assets/src/components/builds/CreateBuild.tsx
  assets/src/components/cluster/containers/getPodContainersStats.tsx
  assets/src/components/cluster/pods/Pods.tsx
  assets/src/components/login/Login.tsx
Labels: enhancement

#285 fix: List component improvements
  assets/src/components/account/groups/GroupMember.tsx
  assets/src/components/account/groups/GroupMembers.tsx
  assets/src/components/account/groups/GroupsList.tsx
  assets/src/components/account/roles/RolePermissionToggle.tsx
  assets/src/components/account/roles/RolesList.tsx
  assets/src/components/account/users/UserInvite.tsx
  assets/src/components/account/users/UsersList.tsx
  assets/src/components/apps/Apps.tsx
  assets/src/components/apps/app/components/component/info/CronJob.tsx
  assets/src/components/apps/app/components/component/info/Service.tsx
  assets/src/components/apps/app/dashboards/Dashboards.tsx
  assets/src/components/apps/app/dashboards/dashboard/Dashboard.tsx
  assets/src/components/apps/app/logs/LogsLabels.tsx
  assets/src/components/apps/app/misc.tsx
  assets/src/components/apps/app/runbooks/Runbooks.tsx
  assets/src/components/apps/app/runbooks/runbook/Runbook.tsx
  assets/src/components/apps/misc.tsx
  assets/src/components/audits/table/AuditAction.tsx
  assets/src/components/audits/table/AuditLocation.tsx
  assets/src/components/builds/build/Build.tsx
  assets/src/components/builds/build/BuildCancel.tsx
  assets/src/components/builds/build/BuildRestart.tsx
  assets/src/components/builds/build/BuildTimer.tsx
  assets/src/components/builds/build/progress/Command.tsx
  assets/src/components/cluster/ContainerStatuses.tsx
  assets/src/components/cluster/LabelsAnnotations.tsx
  assets/src/components/cluster/TableElements.tsx
  assets/src/components/cluster/nodes/NodesList.tsx
  assets/src/components/layout/Notification.tsx
  assets/src/components/profile/SecurityAccess.tsx
  assets/src/components/profile/SecurityPassword.tsx
  assets/src/components/repos/installer/Modal.tsx
  assets/src/components/utils/ChartTooltip.tsx
  assets/src/components/utils/Graph.tsx
  assets/src/components/utils/List.tsx
  assets/src/components/utils/PageTitleSelectButton.tsx
Labels: enhancement

#294 Implement vpn crud apis
  lib/console/application.ex
  lib/console/cached/kubernetes.ex
  lib/console/cached/vpn.ex
  lib/console/configuration.ex
  lib/console/features.ex
  lib/console/graphql.ex
  lib/console/graphql/configuration.ex
  lib/console/graphql/kubernetes.ex
  lib/console/graphql/kubernetes/vpn.ex
  lib/console/graphql/middleware/feature.ex
  lib/console/graphql/plural.ex
  lib/console/graphql/resolvers/plural.ex
  lib/console/graphql/resolvers/user_loader.ex
  lib/console/graphql/resolvers/vpn.ex
  lib/console/plural/accounts.ex
  lib/console/plural/models.ex
  lib/console/plural/queries.ex
  lib/console/plural/repositories.ex
  lib/console/schema/user.ex
  lib/console/services/vpn.ex
  lib/kube/client.ex
  lib/kube/wireguard.ex
  test/console/features_test.exs
  test/console/graphql/mutations/kubernetes_mutations_test.exs
  test/console/graphql/queries/kubernetes_queries_test.exs
  test/console/graphql/queries/plural_queries_test.exs
  test/support/kubernetes_scaffolds.ex
  test/test_helper.exs
Labels: enhancement, backend

#295 Release v0.4.4
  plural/helm/console/Chart.yaml
Labels: enhancement

#297 Use annotations instead of labels
  lib/console/graphql/kubernetes/vpn.ex
  lib/console/services/vpn.ex
  lib/kube/client.ex
  test/console/graphql/queries/kubernetes_queries_test.exs
  test/support/kubernetes_scaffolds.ex
Labels: bug-fix

#300 fix: Fix VPN api typo
  assets/.gitignore
  lib/kube/wireguard.ex
Labels: bug-fix, backend

#301 Use local GraphQL schema for TS generation
  .github/workflows/test.yaml
  Makefile
  assets/codegen.yml
  assets/package.json
  assets/src/generated/graphql.ts
  schema/schema.graphql
Labels: enhancement

#302 Fix vpn config fetch
  lib/console/graphql/kubernetes/vpn.ex
  lib/console/graphql/schema/base.ex
  lib/console/services/vpn.ex
  lib/kube/client.ex
  lib/kube/wireguard.ex
  test/support/kubernetes_scaffolds.ex
Labels: bug-fix, backend

#281 feat: Migrate animated notifications panel from App
  assets/src/App.jsx
  assets/src/components/hooks/useOnClickOutside.tsx
  assets/src/components/hooks/useUnmount.tsx
  assets/src/components/layout/AppNav.tsx
  assets/src/components/layout/Console.tsx
  assets/src/components/layout/NotificationsPanelOverlay.tsx
  assets/src/components/layout/Overlay.tsx
  assets/src/components/layout/Sidebar.tsx
Labels: enhancement

#298 feat: Add UI support for VPN list/create/delete
  assets/package.json
  assets/src/components/account/Account.tsx
  assets/src/components/account/vpn/VPN.tsx
  assets/src/components/account/vpn/VPNHeaderActions.tsx
  assets/src/components/cluster/pods/Pods.tsx
  assets/src/components/graphql/users.js
  assets/src/components/login/Login.tsx
  assets/src/components/profile/MyProfile.tsx
  assets/src/components/profile/VPN.tsx
  assets/src/components/utils/Avatar.jsx
  assets/src/components/utils/MoreMenu.tsx
  assets/src/components/vpn/VPNClientList.tsx
  assets/src/components/vpn/actions/Create.tsx
  assets/src/components/vpn/actions/Delete.tsx
  assets/src/components/vpn/actions/Download.tsx
  assets/src/components/vpn/columns/Actions.tsx
  assets/src/components/vpn/columns/Address.tsx
  assets/src/components/vpn/columns/Delete.tsx
  assets/src/components/vpn/columns/Download.tsx
  assets/src/components/vpn/columns/Name.tsx
  assets/src/components/vpn/columns/PublicKey.tsx
  assets/src/components/vpn/columns/Status.tsx
  assets/src/components/vpn/columns/User.tsx
  assets/src/components/vpn/columns/index.ts
  assets/src/components/vpn/columns/types.ts
  assets/src/components/vpn/graphql/fragments.ts
  assets/src/components/vpn/graphql/mutations.ts
  assets/src/components/vpn/graphql/queries.ts
  assets/src/generated/graphql.ts
  assets/src/routes/consoleRoutes.tsx
  assets/src/types/react-table.d.ts
  assets/src/utils/file.ts
  assets/yarn.lock
  schema/schema.graphql
Labels: enhancement, frontend

#304 Potentially fix deleting wireguard peer
  assets/src/components/account/vpn/VPN.tsx
  lib/kube/client.ex
  lib/kube/client/base.ex
Labels: bug-fix

#305 Publish v0.4.5
  plural/helm/console/Chart.yaml
  plural/helm/console/values.yaml
Labels: enhancement
