Repository pluralsh/console, pull requests merged in 2023-04, with the labels that each got.

#338 Bump cli version in dockerfile
  Dockerfile
Labels: enhancement

#339 Implement config builds
  assets/src/generated/graphql.ts
  lib/console/deployer/operations.ex
  lib/console/schema/build.ex
  lib/console/services/plural.ex
  lib/console/services/policies.ex
  lib/console/utils/path.ex
  lib/console/utils/yaml.ex
  lib/console/watchers/handlers/upgrade.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20230405231928_add_build_config.exs
  schema/schema.graphql
  test/console/services/plural_test.exs
  test/console/utils/path_test.exs
  test/console/watchers/handlers/upgrade_test.exs
Labels: enhancement

#340 Release v0.4.12
  plural/helm/console/Chart.yaml
  plural/helm/console/values.yaml
Labels: release

#341 feat: Use new collapsible `Breadcrumbs` in subheader
  assets/package.json
  assets/src/components/account/Account.tsx
  assets/src/components/apps/Apps.tsx
  assets/src/components/apps/app/components/Components.tsx
  assets/src/components/apps/app/components/component/Component.tsx
  assets/src/components/apps/app/config/Configuration.tsx
  assets/src/components/apps/app/cost/CostAnalysis.tsx
  assets/src/components/apps/app/dashboards/Dashboards.tsx
  assets/src/components/apps/app/dashboards/dashboard/Dashboard.tsx
  assets/src/components/apps/app/logs/Logs.tsx
  assets/src/components/apps/app/oidc/UserManagement.tsx
  assets/src/components/apps/app/runbooks/Runbooks.tsx
  assets/src/components/apps/app/runbooks/runbook/Runbook.tsx
  assets/src/components/audits/Audits.tsx
  assets/src/components/builds/Builds.tsx
  assets/src/components/builds/build/Build.tsx
  assets/src/components/cluster/containers/Container.tsx
  assets/src/components/cluster/nodes/Node.tsx
  assets/src/components/cluster/nodes/Nodes.tsx
  assets/src/components/cluster/pods/Pod.tsx
  assets/src/components/cluster/pods/Pods.tsx
  assets/src/components/contexts/BreadcrumbsProvider.tsx
  assets/src/components/incidents/Incident.jsx
  assets/src/components/incidents/Incidents.jsx
  assets/src/components/layout/Breadcrumbs.tsx
  assets/src/components/layout/Console.tsx
  assets/src/components/layout/Subheader.tsx
  assets/src/components/profile/MyProfile.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#342 fix: Data syncing issue with virtualized lists
  assets/src/components/account/groups/GroupsList.tsx
  assets/src/components/account/roles/RolesList.tsx
  assets/src/components/account/users/UsersList.tsx
  assets/src/components/account/webhooks/WebhooksList.tsx
  assets/src/components/apps/app/logs/LogContent.tsx
  assets/src/components/apps/app/logs/LogLine.tsx
  assets/src/components/incidents/Incident.jsx
Labels: bug-fix, frontend

#343 feat: Use markdoc components from design system
  assets/.eslintrc.js
  assets/package.json
  assets/src/components/apps/app/App.tsx
  assets/src/components/apps/app/docs/AppDocs.tsx
  assets/src/components/apps/app/docs/MarkdocContent.tsx
  assets/src/components/apps/app/logs/LogLine.tsx
  assets/src/components/apps/app/logs/LogsLegend.tsx
  assets/src/components/contexts/NavigationContext.tsx
  assets/src/components/contexts/contextReactRouter.tsx
  assets/src/components/layout/Console.tsx
  assets/src/markdoc/MarkdocContext.tsx
  assets/src/markdoc/components/Blockquote.tsx
  assets/src/markdoc/components/Button.tsx
  assets/src/markdoc/components/Callout.tsx
  assets/src/markdoc/components/Code.tsx
  assets/src/markdoc/components/CodeTabs.tsx
  assets/src/markdoc/components/Embed.tsx
  assets/src/markdoc/components/Fence.tsx
  assets/src/markdoc/components/Figure.tsx
  assets/src/markdoc/components/Heading.tsx
  assets/src/markdoc/components/HorizontalRule.tsx
  assets/src/markdoc/components/Image.tsx
  assets/src/markdoc/components/Link.tsx
  assets/src/markdoc/components/List.tsx
  assets/src/markdoc/components/MdBaseNodes.tsx
  assets/src/markdoc/components/MediaWrap.tsx
  assets/src/markdoc/components/Paragraph.tsx
  assets/src/markdoc/components/Tab.tsx
  assets/src/markdoc/components/Table.tsx
  assets/src/markdoc/components/Tabs.tsx
  assets/src/markdoc/config/index.ts
  assets/src/markdoc/functions.ts
  assets/src/markdoc/mdSchema.ts
  assets/src/markdoc/mdSchemaTransforms.js
  assets/src/markdoc/nodes/blockquote.markdoc.ts
  assets/src/markdoc/nodes/code.markdoc.ts
  assets/src/markdoc/nodes/fence.markdoc.ts
  assets/src/markdoc/nodes/heading.markdoc.ts
  assets/src/markdoc/nodes/hr.markdoc.ts
  assets/src/markdoc/nodes/image.markdoc.ts
  assets/src/markdoc/nodes/index.ts
  assets/src/markdoc/nodes/link.markdoc.ts
  assets/src/markdoc/nodes/list.markdoc.ts
  assets/src/markdoc/nodes/paragraph.markdoc.ts
  assets/src/markdoc/nodes/table.markdoc.ts
  assets/src/markdoc/tags/button.markdoc.ts
  assets/src/markdoc/tags/callout.markdoc.ts
  assets/src/markdoc/tags/codetabs.markdoc.ts
  assets/src/markdoc/tags/embed.markdoc.ts
  assets/src/markdoc/tags/figure.markdoc.ts
  assets/src/markdoc/tags/index.ts
  assets/src/markdoc/tags/tabs.markdoc.ts
  assets/src/markdoc/utils/collectHeadings.ts
  assets/src/markdoc/utils/getMdContent.tsx
  assets/src/markdoc/utils/text.ts
  assets/src/markdoc/utils/unwrapParagraphs.ts
  assets/src/markdoc/utils/useNormalizeHref.tsx
  assets/src/types/styled.d.ts
  assets/yarn.lock
Labels: enhancement, frontend

#346 make private recipes for cluster api
  plural/plural/recipe/console-aws-cluster-api.yaml
  plural/plural/recipe/console-gcp-cluster-api.yaml
Labels: bug-fix

#348 fix: Console Pod Logs broken if not in a plural application
  assets/src/components/apps/app/logs/LogContent.tsx
  assets/src/components/apps/app/logs/Logs.tsx
  assets/src/components/apps/app/logs/LogsCard.tsx
  assets/src/components/apps/app/logs/LogsFullScreen.tsx
  assets/src/components/cluster/pods/Pod.tsx
  assets/src/components/cluster/pods/PodInfo.tsx
  assets/src/components/cluster/pods/PodLogs.tsx
  assets/src/components/cluster/pods/PodSideNav.tsx
  assets/src/components/cluster/pods/PodsList.tsx
  assets/src/components/hooks/useNamespaceIsApp.tsx
  assets/src/components/layout/AppNav.tsx
  assets/src/routes/clusterRoutes.tsx
Labels: bug-fix, frontend
