Repository pluralsh/console, pull requests merged in 2023-11, with the labels that each got.

#477 feat: Cluster/Provider creation enhancements
  assets/src/components/cd/cluster/ClusterMetadata.tsx
  assets/src/components/cd/clusters/ClusterConditions.tsx
  assets/src/components/cd/clusters/ClusterUpgrade.tsx
  assets/src/components/cd/clusters/VersionSelect.tsx
  assets/src/components/cd/clusters/create/CreateCluster.tsx
  assets/src/components/cd/clusters/create/CreateClusterContent.tsx
  assets/src/components/cd/clusters/create/NameVersionHandle.tsx
  assets/src/components/cd/clusters/create/ProviderTabSelector.tsx
  assets/src/components/cd/clusters/create/helpers.ts
  assets/src/components/cd/clusters/create/provider/AWS.tsx
  assets/src/components/cd/clusters/create/provider/Azure.tsx
  assets/src/components/cd/clusters/create/provider/GCP.tsx
  assets/src/components/cd/clusters/create/provider/NodeGroup.tsx
  assets/src/components/cd/clusters/create/provider/NodeGroupContainer.tsx
  assets/src/components/cd/clusters/create/types.ts
  assets/src/components/cd/clusters/deprecationsColumns.tsx
  assets/src/components/cd/providers/CreateProvider.tsx
  assets/src/components/cd/providers/ProviderSettings.tsx
  assets/src/components/cd/providers/Providers.tsx
  assets/src/components/cd/utils/ProviderCredsSelect.tsx
  assets/src/components/cluster/pods/Pods.tsx
  assets/src/components/utils/typography/Text.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdProviders.graphql
Labels: enhancement

#479 feat: Enable Azure and AWS cluster creation
  assets/package.json
  assets/src/components/cd/ModalAlt.tsx
  assets/src/components/cd/clusters/create/CreateCluster.tsx
  assets/src/components/cd/clusters/create/CreateClusterContent.tsx
  assets/src/components/cd/clusters/create/ImportClusterContent.tsx
  assets/src/components/cd/clusters/create/NameVersionHandle.tsx
  assets/src/components/cd/clusters/create/provider/AWS.tsx
  assets/src/components/cd/clusters/create/provider/Azure.tsx
  assets/src/components/cd/clusters/create/provider/GCP.tsx
  assets/src/components/hooks/suspense/useOpenTransition.tsx
  assets/yarn.lock
Labels: enhancement

#481 feat: Cluster tags, Add-ons, small updates
  assets/src/components/apps/AppCard.tsx
  assets/src/components/apps/Apps.tsx
  assets/src/components/apps/app/App.tsx
  assets/src/components/apps/app/AppSelector.tsx
  assets/src/components/cd/ContinuousDeployment.tsx
  assets/src/components/cd/addOns/AddOnCard.tsx
  assets/src/components/cd/addOns/AddOns.tsx
  assets/src/components/cd/cluster/ClusterMetadata.tsx
  assets/src/components/cd/clusters/create/ClusterTagSelection.tsx
  assets/src/components/cd/clusters/create/CreateCluster.tsx
  assets/src/components/cd/clusters/create/CreateClusterContent.tsx
  assets/src/components/cd/clusters/create/ImportClusterContent.tsx
  assets/src/components/cd/clusters/create/provider/AWS.tsx
  assets/src/components/cd/clusters/create/provider/Azure.tsx
  assets/src/components/cd/clusters/create/provider/GCP.tsx
  assets/src/components/cd/services/CreateGlobalService.tsx
  assets/src/components/cd/services/ServicePermissions.tsx
  assets/src/components/cd/services/ServiceRevisionColumns.tsx
  assets/src/components/cd/services/ServiceSettings.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/services/ServicesUpdateService.tsx
  assets/src/components/cd/services/TagSelection.tsx
  assets/src/components/cd/services/deployModal/DeployServiceSettingsGit.tsx
  assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
  assets/src/components/cd/services/service/ServiceRevisions.tsx
  assets/src/components/help/HelpMenu.tsx
  assets/src/components/layout/Header.tsx
  assets/src/components/utils/SelectedIcon.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdAddons.graphql
  assets/src/graph/cdClusters.graphql
  assets/src/routes/appsRoutes.tsx
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
Labels: enhancement

#482 feat: add simplified logs viewer for cd cluster pods
  assets/src/components/apps/AppCard.tsx
  assets/src/components/apps/app/logs/LogContent.tsx
  assets/src/components/cd/cluster/pod/Pod.tsx
  assets/src/components/cd/cluster/pod/PodInfo.tsx
  assets/src/components/cd/cluster/pod/PodLogs.tsx
  assets/src/components/cd/cluster/pod/logs/ContainerLogs.tsx
  assets/src/components/cd/cluster/pod/logs/Logs.tsx
  assets/src/components/cluster/pods/Pod.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/kubernetes/pod.graphql
  assets/src/routes/cdRoutes.tsx
Labels: enhancement

#486 feat: Breadcrumbs and Routes fixes/cleanup, CD disabled state, remove suspense queries
  assets/package.json
  assets/src/App.tsx
  assets/src/components/billing/BillingFeatureBlockModal.tsx
  assets/src/components/cd/ContinuousDeployment.tsx
  assets/src/components/cd/PluralErrorBoundary.tsx
  assets/src/components/cd/addOns/AddOns.tsx
  assets/src/components/cd/cluster/Cluster.tsx
  assets/src/components/cd/cluster/ClusterPods.tsx
  assets/src/components/cd/cluster/node/Node.tsx
  assets/src/components/cd/cluster/pod/Pod.tsx
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/cd/clusters/create/CreateClusterContent.tsx
  assets/src/components/cd/globalSettings/GlobalSettings.tsx
  assets/src/components/cd/providers/Providers.tsx
  assets/src/components/cd/repos/GitRepositories.tsx
  assets/src/components/cd/services/ServiceSelector.tsx
  assets/src/components/cd/services/Services.tsx
  assets/src/components/cd/services/component/ServiceComponent.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
  assets/src/components/cd/services/service/ServiceDocs.tsx
  assets/src/components/cd/services/service/ServiceRevisions.tsx
  assets/src/components/cd/services/service/ServiceSecrets.tsx
  assets/src/components/cd/utils/useCDEnabled.tsx
  assets/src/components/cluster/pods/Pods.tsx
  assets/src/components/cluster/pods/PodsList.tsx
  assets/src/components/db-management/DatabaseManagement.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/users.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
  assets/yarn.lock
Labels: enhancement

#497 feat: add server-side validation for updating clusters
  lib/console/schema/cluster.ex
  test/console/deployments/clusters_test.exs
Labels: enhancement

#499 feat: Add Getting Started guide to Clusters page
  assets/src/components/apps/Apps.tsx
  assets/src/components/cd/PrepareGitStep.tsx
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/cd/clusters/ClustersDemoTable.tsx
  assets/src/components/cd/clusters/ClustersGettingStarted.tsx
  assets/src/components/cd/clusters/create/ImportClusterContent.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/utils/layout/EmbedAspectRatio.tsx
  assets/src/components/utils/typography/Text.tsx
  assets/src/routes/cdRoutesConsts.tsx
  assets/src/utils/constants.ts
Labels: enhancement, frontend

#500 fix: Broken discord link
  assets/src/utils/constants.ts
Labels: bug-fix

#502 add ability to bulk migrate agents to new versions
  config/prod.exs
  lib/console/deployments/cron.ex
  lib/console/schema/agent_migration.ex
  lib/console/schema/cluster.ex
  priv/repo/migrations/20231114173755_agent_migrations.exs
  priv/repo/seeds/05_agent.exs
Labels: enhancement

#503 bump console chart for v0.6.5
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/kas-0.0.2.tgz
  charts/console/charts/kas-0.0.3.tgz
  lib/console/application.ex
  plural/helm/console/Chart.yaml
Labels: enhancement, backend

#504 make features fetches more performant on app boot
  assets/src/generated/graphql.ts
  lib/console/application.ex
  lib/console/cached/cluster_nodes.ex
  lib/console/deployments/git.ex
  lib/console/features.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/resolvers/deployments.ex
  schema/schema.graphql
  test/console/graphql/queries/deployment_queries_test.exs
Labels: enhancement, backend

#508 fix: Inconsistent scrolling behavior on CD pages
  assets/src/components/cd/ContinuousDeployment.tsx
Labels: bug-fix

#505 Support external ingress configuration
  plural/helm/console/Chart.yaml
  plural/helm/console/templates/_helpers.tpl
  plural/helm/console/templates/ingress.yaml
  plural/helm/console/values.yaml
Labels: enhancement

#509 Basic Job Gate specification
  assets/src/generated/graphql.ts
  charts/console/Chart.yaml
  charts/console/templates/_helpers.tpl
  charts/console/templates/ingress.yaml
  charts/console/values.yaml
  lib/console/deployments/pipelines.ex
  lib/console/deployments/policies/policies.ex
  lib/console/external_graphql.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/pipeline.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/schema/gates/job_spec.ex
  lib/console/schema/pipeline_gate.ex
  priv/repo/migrations/20231116182334_add_job_status.exs
  schema/schema.graphql
  test/console/deployments/pipeline_test.exs
  test/console/graphql/mutations/deployment_mutations_test.exs
  test/console/graphql/queries/deployment_queries_test.exs
Labels: enhancement, backend

#510 Add-on compatibilities apis
  assets/public/addons/nginx.png
  assets/src/components/cd/clusters/ClusterUpgrade.tsx
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/cd/clusters/deprecationsColumns.tsx
  assets/src/components/cd/clusters/runtime/RuntimeServices.tsx
  assets/src/components/cd/clusters/runtime/columns.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/utils/semver.ts
  config/config.exs
  lib/console/application.ex
  lib/console/deployments/clusters.ex
  lib/console/deployments/compatibilities/schema.ex
  lib/console/deployments/compatibilities/table.ex
  lib/console/deployments/deprecations/table.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/schema/runtime_service.ex
  lib/console/watchers/supervisor.ex
  priv/repo/migrations/20231120165207_add_runtime_services.exs
  schema/schema.graphql
  static/compatibilities/ingress-nginx.yaml
  static/compatibilities/manifest.yaml
  test/console/deployments/clusters_test.exs
  test/console/graphql/mutations/deployment_mutations_test.exs
  test/console/graphql/queries/deployment_queries_test.exs
  test/support/factory.ex
Labels: enhancement

#512 More compatibilities
  lib/console/deployments/compatibilities/schema.ex
  lib/console/deployments/compatibilities/table.ex
  static/compatibilities/cert-manager.yaml
  static/compatibilities/external-dns.yaml
  static/compatibilities/manifest.yaml
  test/console/graphql/queries/deployment_queries_test.exs
Labels: enhancement

#507 feat: Pipelines
  assets/package.json
  assets/src/components/cd/ContinuousDeployment.tsx
  assets/src/components/cd/cluster/pod/Pod.tsx
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/cd/clusters/deprecationsColumns.tsx
  assets/src/components/cd/clusters/runtime/RuntimeServices.tsx
  assets/src/components/cd/clusters/runtime/columns.tsx
  assets/src/components/cd/pipelines/EdgeLine.tsx
  assets/src/components/cd/pipelines/Pipeline.tsx
  assets/src/components/cd/pipelines/Pipelines.tsx
  assets/src/components/cd/pipelines/PipelinesFilters.tsx
  assets/src/components/cd/pipelines/nodes/ApprovalNode.tsx
  assets/src/components/cd/pipelines/nodes/BaseNode.tsx
  assets/src/components/cd/pipelines/nodes/StageNode.tsx
  assets/src/components/cd/pipelines/nodes/TestsNode.tsx
  assets/src/components/cd/pipelines/utils/_demo_data.ts
  assets/src/components/cd/pipelines/utils/getNodesAndEdges.tsx
  assets/src/components/cd/pipelines/utils/hooks.tsx
  assets/src/components/cd/pipelines/utils/nodeLayouter.tsx
  assets/src/components/cd/pipelines/utils/reduceGateStatuses.tsx
  assets/src/components/cd/services/ServiceStatusChip.tsx
  assets/src/components/cd/utils/useCDEnabled.tsx
  assets/src/components/utils/Confirm.tsx
  assets/src/components/utils/VirtualList.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdPipelines.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
  assets/yarn.lock
  lib/console/deployments/pipelines.ex
  test/console/deployments/pipeline_test.exs
Labels: enhancement

#515 Add expander to display all versions for a discovered add-on
  assets/src/components/cd/clusters/runtime/ExpandedColumn.tsx
  assets/src/components/cd/clusters/runtime/RuntimeServices.tsx
  assets/src/components/cd/clusters/runtime/columns.tsx
Labels: enhancement

#519 fix: use semver sort for cluster version
  assets/src/components/cd/clusters/create/NameVersionHandle.tsx
  assets/src/components/cd/clusters/runtime/ExpandedColumn.tsx
  assets/src/components/cd/clusters/runtime/RuntimeServices.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/utils/semver.ts
Labels: enhancement

#518 Small pipelines tweaks
  assets/src/components/cd/ContinuousDeployment.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  charts/console/Chart.yaml
  charts/console/README.md
  charts/console/values.yaml.liquid
  config/prod.exs
  lib/console/deployments/cron.ex
  lib/console/deployments/git/agent.ex
  lib/console/deployments/pipelines.ex
  lib/console/deployments/pubsub/consumers/pipeline.ex
  lib/console/deployments/pubsub/protocols/pipelineable.ex
  lib/console/deployments/services.ex
  lib/console/schema/pipeline_stage.ex
  lib/console/schema/service.ex
  test/console/deployments/pipeline_test.exs
  test/console/deployments/pubsub/pipeline_test.exs
  test/test_helper.exs
Labels: enhancement

#521 Fix cloud settings schema
  assets/src/generated/graphql.ts
  lib/console/deployments/compatibilities/schema.ex
  lib/console/graphql/deployments/cluster.ex
  schema/schema.graphql
Labels: enhancement

#524 Improve update components performance
  lib/console/deployments/services.ex
  lib/console/schema/api_deprecation.ex
  priv/repo/migrations/20231130034012_add_deprecations_unique_constraint.exs
  test/console/deployments/services_test.exs
Labels: enhancement
