Repository pluralsh/console, pull requests merged in 2024-06, with the labels that each got.

#1007 fix: Few fixes for stack and stack run job views
  assets/src/components/stacks/StackJob.tsx
  assets/src/components/stacks/run/Header.tsx
  assets/src/components/stacks/run/job/RunJob.tsx
  assets/src/components/stacks/run/job/RunJobPods.tsx
  assets/src/components/stacks/run/job/RunJobSpecs.tsx
Labels: bug-fix

#1006 Ensure actor id is attached to stack run
  AGENT_VERSION
  assets/schema/kubernetes-schema.graphql
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/stacks/run/Route.tsx
  lib/console/deployments/addons.ex
  lib/console/deployments/stacks.ex
  lib/console/deployments/statistics.ex
  lib/console/graphql/deployments.ex
  lib/console/prom/metrics.ex
  lib/console/prom/scraper.ex
  lib/console/schema/cluster.ex
  lib/console/schema/deployment_settings.ex
  lib/console/schema/service.ex
  mix.exs
  mix.lock
  schema/schema.graphql
  test/console/deployments/stacks_test.exs
Labels: enhancement

#1012 feat: add propagation policy to k8s delete resource
  Makefile
  assets/schema/kubernetes-schema.graphql
  assets/src/components/kubernetes/common/DeleteResource.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/graph-kubernetes/common/resource.graphql
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.47.tgz
  charts/console/charts/kas-0.1.0.tgz
  charts/console/charts/kubernetes-dashboard-7.4.0.tgz
  charts/console/charts/kubernetes-dashboard-7.5.0.tgz
  plural/helm/console/Chart.lock
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/controller-0.0.47.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.4.0.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.5.0.tgz
Labels: enhancement

#1011 feat: Remove legacy image from login portal
  assets/public/login-sidebar.avif
  assets/public/login-sidebar.jpg
  assets/src/components/login/LoginPortal.tsx
  assets/src/components/login/constants.ts
Labels: enhancement

#1010 Fallback to global settings for stack job spec
  lib/console/cache.ex
  lib/console/deployments/settings.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  test/console/graphql/queries/deployments/stack_queries_test.exs
Labels: enhancement, hotfix

#1013 fix: handle delete resource error better
  assets/src/components/kubernetes/Cluster.tsx
  assets/src/components/kubernetes/common/DeleteResource.tsx
Labels: bug-fix

#1009 add temp-dir volumes and volume mounts using emptyDir to console pods /tmp
  charts/console/templates/deployment.yaml
  charts/console/templates/migration.yaml
Labels: enhancement

#1014 changed groups and users lists to use table instead of scroller
  assets/package.json
  assets/src/components/account/Account.tsx
  assets/src/components/account/groups/Group.tsx
  assets/src/components/account/groups/GroupEdit.tsx
  assets/src/components/account/groups/GroupMembers.tsx
  assets/src/components/account/groups/GroupView.tsx
  assets/src/components/account/groups/Groups.tsx
  assets/src/components/account/groups/GroupsColumns.tsx
  assets/src/components/account/groups/GroupsList.tsx
  assets/src/components/account/misc.tsx
  assets/src/components/account/users/Users.tsx
  assets/src/components/account/users/UsersColumns.tsx
  assets/src/components/account/users/UsersList.tsx
  assets/src/components/cd/utils/useFetchPaginatedData.tsx
  assets/src/components/utils/Info.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/groups.graphql
  assets/src/graph/users.graphql
  assets/yarn.lock
Labels: enhancement, frontend

#1016 Add ansible stack run commands
  assets/src/generated/graphql.ts
  lib/console/deployments/stacks.ex
  lib/console/deployments/stacks/commands.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  lib/console/schema/custom_stack_run.ex
  lib/console/schema/service_error.ex
  lib/console/schema/stack_run.ex
  schema/schema.graphql
  test/console/deployments/stacks_test.exs
  test/console/graphql/mutations/deployments/stack_mutations_test.exs
Labels: enhancement

#1019 Add get for custom stack runs
  assets/src/generated/graphql.ts
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  schema/schema.graphql
Labels: enhancement

#1023 fixed service breadcrumbs
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceHelm.tsx
  assets/src/components/cd/services/service/ServiceLogs.tsx
  assets/src/components/cd/services/service/ServiceSettings.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdServices.graphql
Labels: enhancement, frontend

#1022 bump design system version
  assets/package.json
  assets/src/components/CommandPalette.tsx
  assets/src/components/layout/Overlay.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#1008 add CustomStackRun CRD
  charts/controller/crds/deployments.plural.sh_customstackruns.yaml
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  charts/controller/templates/manager-rbac.yaml
  controller/PROJECT
  controller/api/v1alpha1/customstackrun_types.go
  controller/api/v1alpha1/prautomation_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_customstackruns.yaml
  controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  controller/config/rbac/customstackrun_editor_role.yaml
  controller/config/rbac/customstackrun_viewer_role.yaml
  controller/config/rbac/role.yaml
  controller/config/samples/deployments_v1alpha1_customstackrun.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/client/console.go
  controller/internal/client/stack.go
  controller/internal/controller/customstackrun_controller.go
  controller/internal/controller/customstackrun_scope.go
  controller/internal/controller/customstackrun_test.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_customstackruns.yaml
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
Labels: enhancement

#1029 fix group mutation false errors
  assets/src/components/account/groups/GroupCreate.tsx
  assets/src/components/account/groups/Groups.tsx
  assets/src/components/account/groups/GroupsColumns.tsx
  assets/src/components/account/groups/GroupsList.tsx
  assets/src/components/cd/utils/useFetchPaginatedData.tsx
Labels: bug-fix, frontend

#1021 Fix some global service edge cases
  assets/src/components/cd/services/DetachService.tsx
  assets/src/generated/graphql.ts
  controller/docs/api.md
  controller/internal/controller/globalservice_controller.go
  lib/console/deployments/global.ex
  lib/console/graphql/deployments/global.ex
  lib/console/graphql/resolvers/deployments/global.ex
  schema/schema.graphql
  test/console/deployments/global_test.exs
  test/console/graphql/mutations/deployments/global_mutations_test.exs
Labels: enhancement

#1030 add global service kick button
  assets/src/components/cd/globalServices/GlobalServiceDetailTable.tsx
  assets/src/components/cd/globalServices/GlobalServiceDetailView.tsx
  assets/src/components/cd/globalServices/GlobalServiceSidecar.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdGlobalServices.graphql
Labels: enhancement, frontend

#1025 feat: Move audits from sidebar to subview w/in the accounts page
  assets/src/components/account/Account.tsx
  assets/src/components/account/audits/Audits.tsx
  assets/src/components/account/audits/AuditsList.tsx
  assets/src/components/account/audits/AuditsMap.tsx
  assets/src/components/account/email/EmailSettings.tsx
  assets/src/components/account/groups/Groups.tsx
  assets/src/components/account/groups/GroupsSearchHeader.tsx
  assets/src/components/account/personas/Personas.tsx
  assets/src/components/account/personas/PersonasSearchHeader.tsx
  assets/src/components/account/roles/Roles.tsx
  assets/src/components/account/roles/RolesSearchHeader.tsx
  assets/src/components/account/settings/AccountSettings.tsx
  assets/src/components/account/users/Users.tsx
  assets/src/components/account/users/UsersList.tsx
  assets/src/components/account/vpn/VPN.tsx
  assets/src/components/account/webhooks/Webhooks.tsx
  assets/src/components/audits/Audits.tsx
  assets/src/components/audits/graph/AuditsGraph.tsx
  assets/src/components/audits/queries.ts
  assets/src/components/audits/table/AuditAction.tsx
  assets/src/components/audits/table/AuditLocation.tsx
  assets/src/components/graphql/audits.js
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/stacks/Stacks.tsx
  assets/src/components/utils/ListInput.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/audits.graphql
  assets/src/routes/consoleRoutes.tsx
  assets/yarn.lock
Labels: enhancement

#1026 add DeploymentSettings CRD
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  charts/controller/templates/manager-rbac.yaml
  controller/PROJECT
  controller/api/v1alpha1/deploymentsettings_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  controller/config/rbac/deploymentsettings_editor_role.yaml
  controller/config/rbac/deploymentsettings_viewer_role.yaml
  controller/config/rbac/role.yaml
  controller/config/samples/deployments_v1alpha1_deploymentsettings.yaml
  controller/internal/client/console.go
  controller/internal/client/settings.go
  controller/internal/controller/deploymentsettings_controller.go
  controller/internal/controller/deploymentsettings_scope.go
  controller/internal/controller/deploymentsettings_test.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
Labels: enhancement

#1031 Add stack tags
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/stack.ex
  lib/console/schema/stack.ex
  lib/console/schema/tag.ex
  priv/repo/migrations/20240606213310_add_tag_stacks.exs
  schema/schema.graphql
Labels: enhancement

#1027 feat: Point to resources in dashboard view from policy affected resources
  assets/src/components/kubernetes/customresources/CustomResourceDefinition.tsx
  assets/src/components/policies/Policies.tsx
  assets/src/components/policies/policy/Policy.tsx
  assets/src/components/policies/policy/affectedResources/PolicyAffectedResources.tsx
  assets/src/components/policies/policy/details/PolicyDetails.tsx
  assets/src/routes/kubernetesRoutesConsts.tsx
Labels: enhancement

#1033 add doctexts for create scm webhook
  assets/src/components/home/HomeCard.tsx
  assets/src/components/home/managerview/violations/ConstraintViolationsCard.tsx
  assets/src/components/policies/policy/affectedResources/PolicyAffectedResources.tsx
  assets/src/components/pr/scm/CreateScmWebhook.tsx
Labels: enhancement, frontend

#1032 Bump agent to v0.4.34
  AGENT_VERSION
Labels: enhancement, hotfix

#1035 Fix thrashing of templated global services
  lib/console/deployments/global.ex
  lib/console/schema/group.ex
  test/console/deployments/global_test.exs
  test/console/deployments/pubsub/recurse_test.exs
Labels: enhancement, hotfix

#1037 Add kubelet version to cluster schema
  .tool-versions
  assets/src/generated/graphql.ts
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/schema/cluster.ex
  lib/console/schema/stack.ex
  priv/repo/migrations/20240607224921_add_kubelet_vsn.exs
  priv/repo/migrations/20240608041954_add_stack_lock.exs
  schema/schema.graphql
Labels: enhancement, hotfix

#1044 add user/group cache
  controller/cmd/main.go
  controller/go.mod
  controller/go.sum
  controller/internal/cache/user_group.go
  controller/internal/controller/cluster_controller.go
  controller/internal/controller/common.go
  controller/internal/controller/infrastructurestack_controller.go
  controller/internal/controller/servicedeployment_controller.go
  controller/internal/types/reconciler.go
Labels: enhancement

#1040 fixed global service empty states
  assets/src/components/cd/globalServices/GlobalServiceDetailTable.tsx
  assets/src/components/cd/globalServices/GlobalServiceDetailView.tsx
  assets/src/components/cd/globalServices/GlobalServicesTable.tsx
Labels: enhancement, frontend

#1045 Add minor schema oversights
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/deployments/stack.ex
  schema/schema.graphql
Labels: bug-fix

#1043 fix: ensure that tokenSecretRef is set before getting secret
  controller/api/v1alpha1/common_types.go
  controller/internal/controller/scmconnection_controller.go
  controller/internal/controller/scmconnection_controller_test.go
  controller/internal/test/mocks/ConsoleClient_mock.go
Labels: bug-fix

#1047 feat: add scmConnectionRef to InfrastructureStack.Spec
  charts/controller/crds/deployments.plural.sh_infrastructurestacks.yaml
  controller/api/v1alpha1/infrastructurestack_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_infrastructurestacks.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/controller/infrastructurestack_controller.go
  plural/helm/console/crds/deployments.plural.sh_infrastructurestacks.yaml
Labels: enhancement

#1048 Add explicit destroy stage for stack runs
  assets/src/generated/graphql.ts
  lib/console/deployments/stacks/commands.ex
  lib/console/schema/run_step.ex
  schema/schema.graphql
Labels: enhancement

#1046 link pods tables to k8s dashboard
  assets/src/components/cd/ContinuousDeployment.tsx
  assets/src/components/cd/cluster/Cluster.tsx
  assets/src/components/cd/pipelines/job/PipelineJob.tsx
  assets/src/components/cd/pipelines/job/PipelineJobPods.tsx
  assets/src/components/cd/pipelines/job/PipelineJobSpecs.tsx
  assets/src/components/cluster/pods/PodsList.tsx
  assets/src/components/component/info/Pods.tsx
  assets/src/components/stacks/run/job/RunJob.tsx
  assets/src/components/stacks/run/job/RunJobPods.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdPipelines.graphql
Labels: enhancement, frontend

#1041 feat: Add project dropdown in UI
  assets/src/components/CommandPalette.tsx
  assets/src/components/cd/addOns/InstallAddOn.tsx
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/cd/pipelines/PipelineDetails.tsx
  assets/src/components/cd/pipelines/Pipelines.tsx
  assets/src/components/cd/services/ServicesTable.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/utils/ClusterSelector.tsx
  assets/src/components/contexts/ProjectsContext.tsx
  assets/src/components/home/clusteroverview/ClusterOverviewCard.tsx
  assets/src/components/home/deployments/DeploymentsCard.tsx
  assets/src/components/layout/Console.tsx
  assets/src/components/layout/Header.tsx
  assets/src/components/layout/ProjectSelect.tsx
  assets/src/components/layout/Subheader.tsx
  assets/src/components/policies/PoliciesFilter.tsx
  assets/src/components/stacks/Stacks.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/graph/cdPipelines.graphql
  assets/src/graph/cdServices.graphql
  assets/src/graph/projects.graphql
  assets/src/graph/stacks.graphql
Labels: enhancement

#1051 add three dot actions to pipelines table
  assets/src/components/cd/cluster/ClusterPermissions.tsx
  assets/src/components/cd/pipelines/DeletePipeline.tsx
  assets/src/components/cd/pipelines/PipelinePermissions.tsx
  assets/src/components/cd/pipelines/PipelinesColumns.tsx
  assets/src/components/cd/services/ServicePermissions.tsx
  assets/src/components/cd/utils/PermissionsModal.tsx
  assets/src/components/policies/policy/affectedResources/PolicyAffectedResources.tsx
  assets/src/components/utils/hooks.ts
  assets/src/generated/graphql.ts
  assets/src/graph/cdPipelines.graphql
  assets/src/graph/cdServices.graphql
Labels: enhancement, frontend

#1052 fix service component pod links
  assets/src/components/cd/pipelines/job/PipelineJobPods.tsx
  assets/src/components/cluster/pods/PodsList.tsx
  assets/src/components/component/info/Pods.tsx
  assets/src/components/stacks/run/job/RunJobPods.tsx
Labels: bug-fix, frontend

#1039 change unstructured component default path
  assets/src/components/cd/services/service/ServiceComponents.tsx
  assets/src/components/component/ComponentDetails.tsx
  assets/src/components/component/ComponentInfo.tsx
  assets/src/routes/cdRoutesConsts.tsx
Labels: enhancement, frontend

#1055 design system audit fixes
  assets/package.json
  assets/src/components/CommandPalette.tsx
  assets/src/components/CommandPaletteLauncher.tsx
  assets/src/components/apps/app/logs/LogsLegend.tsx
  assets/src/components/cd/clusters/create/ProviderTabSelector.tsx
  assets/src/components/cd/utils/RepoKindSelector.tsx
  assets/src/components/layout/ProjectSelect.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#1054 wip: feat(controller): add project controller and project refs to supported resources
  charts/controller/crds/deployments.plural.sh_clusters.yaml
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_infrastructurestacks.yaml
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  charts/controller/crds/deployments.plural.sh_pipelines.yaml
  charts/controller/crds/deployments.plural.sh_projects.yaml
  controller/api/v1alpha1/cluster_types.go
  controller/api/v1alpha1/common_types.go
  controller/api/v1alpha1/globalservice_types.go
  controller/api/v1alpha1/infrastructurestack_types.go
  controller/api/v1alpha1/managednamespace_types.go
  controller/api/v1alpha1/pipeline_types.go
  controller/api/v1alpha1/project_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_clusters.yaml
  controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  controller/config/crd/bases/deployments.plural.sh_infrastructurestacks.yaml
  controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  controller/config/crd/bases/deployments.plural.sh_pipelines.yaml
  controller/config/crd/bases/deployments.plural.sh_projects.yaml
  controller/config/rbac/role.yaml
  controller/docs/api.md
  controller/go.mod
  controller/go.sum
  controller/internal/client/cluster.go
  controller/internal/client/console.go
  controller/internal/client/project.go
  controller/internal/controller/cluster_controller.go
  controller/internal/controller/globalservice_controller.go
  controller/internal/controller/infrastructurestack_controller.go
  controller/internal/controller/managednamespace_controller.go
  controller/internal/controller/pipeline_controller.go
  controller/internal/controller/pipeline_controller_attributes.go
  controller/internal/controller/project_controller.go
  controller/internal/controller/project_controller_test.go
  controller/internal/controller/project_scope.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_clusters.yaml
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  plural/helm/console/crds/deployments.plural.sh_infrastructurestacks.yaml
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
  plural/helm/console/crds/deployments.plural.sh_pipelines.yaml
  plural/helm/console/crds/deployments.plural.sh_projects.yaml
Labels: enhancement

#1058 Fix chart rbac
  charts/console/Chart.yaml
  charts/controller/Chart.yaml
  charts/controller/templates/manager-rbac.yaml
  plural/helm/console/Chart.yaml
Labels: enhancement, hotfix

#1060 add new arrow scroll for subtabs
  assets/package.json
  assets/src/components/cd/ContinuousDeployment.tsx
  assets/src/components/kubernetes/Navigation.tsx
  assets/src/components/kubernetes/workloads/Workloads.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#1063 refactor: Refactor global service controller
  controller/api/v1alpha1/globalservice_types.go
  controller/internal/controller/common.go
  controller/internal/controller/globalservice_controller.go
Labels: enhancement

#1061 Fix cron next run at inference
  assets/src/generated/graphql.ts
  lib/console/cron/job.ex
  lib/console/deployments/settings.ex
  lib/console/graphql/deployments/git.ex
  lib/console/schema/embeds.ex
  lib/console/schema/stack.ex
  schema/schema.graphql
  test/console/deployments/stacks_test.exs
Labels: bug-fix, hotfix

#1064 fix: update stack run view when stack run is deleted
  assets/src/components/stacks/Stacks.tsx
  assets/src/components/stacks/run/Route.tsx
Labels: bug-fix

#1049 Automate compatibility table info
  .gitignore
  static/compatibilities/cert-manager.yaml
  static/compatibilities/external-dns.yaml
  static/compatibilities/ingress-nginx.yaml
  utils/compatibility/.python-version
  utils/compatibility/main.py
  utils/compatibility/requirements.txt
  utils/compatibility/scrapers/__init__.py
  utils/compatibility/scrapers/cert-manager.py
  utils/compatibility/scrapers/external-dns.py
  utils/compatibility/scrapers/ingress-nginx.py
  utils/compatibility/setup_env.sh
  utils/compatibility/utils.py
Labels: enhancement

#1065 Add Github App authorization for scm connections
  assets/src/generated/graphql.ts
  lib/console/deployments/git/agent.ex
  lib/console/deployments/git/cmd.ex
  lib/console/deployments/pr/impl/github.ex
  lib/console/graphql/deployments/git.ex
  lib/console/jwt/github.ex
  lib/console/schema/git_repository.ex
  lib/console/schema/scm_connection.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20240615015556_add_github_app_support.exs
  schema/schema.graphql
  test/console/graphql/queries/deployments/cluster_queries_test.exs
  test/console/jwt/github_test.exs
Labels: enhancement

#1067 Add gh app auth to pr automation flow too
  lib/console/deployments/git/cmd.ex
  lib/console/deployments/pr/git.ex
Labels: bug-fix, hotfix

#1068 Need to move connectionId to GitAttributes not ScmConnectionAttributes
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/git.ex
  schema/schema.graphql
Labels: bug-fix, hotfix

#1070 fix home page math error
  assets/src/components/home/clusteroverview/ClusterOverviewChart.tsx
Labels: bug-fix, frontend

#1069 Add connectionRef to GitRepository type
  .github/workflows/firebase-hosting-pull-request.yml
  charts/controller/crds/deployments.plural.sh_gitrepositories.yaml
  config/config.exs
  controller/api/v1alpha1/gitrepository_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_gitrepositories.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/client/console.go
  controller/internal/client/repository.go
  controller/internal/controller/gitrepository_controller.go
  controller/internal/controller/gitrepository_controller_test.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  lib/console/cron/job.ex
  lib/console/cron/scheduler.ex
  lib/console/deployments/pipelines/discovery.ex
  lib/console/deployments/pr/git.ex
  lib/console/deployments/stacks/discovery.ex
  plural/helm/console/crds/deployments.plural.sh_gitrepositories.yaml
Labels: enhancement

#1071 Add argo rollout types to gql api
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/kubernetes.ex
  lib/console/graphql/kubernetes/rollout.ex
  lib/console/graphql/resolvers/kubernetes.ex
  lib/kube/client.ex
  lib/kube/models.ex
  schema/schema.graphql
  static/crds/rollout.yaml
Labels: enhancement

#1073 feat: Update PR automation CRD and UI
  charts/controller/crds/deployments.plural.sh_customstackruns.yaml
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  controller/api/v1alpha1/prautomation_types.go
  controller/config/crd/bases/deployments.plural.sh_customstackruns.yaml
  controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  controller/config/samples/pr_automation.yaml
  plural/helm/console/crds/deployments.plural.sh_customstackruns.yaml
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
Labels: enhancement

#1072 added logic for nested data to slice polling
  assets/src/components/account/groups/GroupsList.tsx
  assets/src/components/account/users/UsersList.tsx
  assets/src/components/backups/cluster/backups/Backups.tsx
  assets/src/components/backups/cluster/restores/Restores.tsx
  assets/src/components/backups/clusters/Clusters.tsx
  assets/src/components/backups/objectstores/ObjectStores.tsx
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/cd/globalServices/GlobalServiceDetailTable.tsx
  assets/src/components/cd/globalServices/GlobalServiceDetailView.tsx
  assets/src/components/cd/globalServices/GlobalServicesTable.tsx
  assets/src/components/cd/globalSettings/observability/ObservabilityProviders.tsx
  assets/src/components/cd/namespaces/NamespacesDetailTable.tsx
  assets/src/components/cd/namespaces/NamespacesDetailView.tsx
  assets/src/components/cd/namespaces/NamespacesTable.tsx
  assets/src/components/cd/pipelines/Pipelines.tsx
  assets/src/components/cd/services/ServicesTable.tsx
  assets/src/components/cd/utils/useFetchPaginatedData.tsx
  assets/src/components/home/clusteroverview/ClusterOverviewCard.tsx
  assets/src/components/home/deployments/DeploymentsCard.tsx
  assets/src/components/home/managerview/violations/ConstraintViolationsCard.tsx
  assets/src/components/home/pullrequests/PrCard.tsx
  assets/src/components/notifications/routers/NotificationRouters.tsx
  assets/src/components/notifications/sinks/NotificationSinks.tsx
  assets/src/components/policies/Policies.tsx
  assets/src/components/pr/automations/PrAutomations.tsx
  assets/src/components/pr/queue/PrQueue.tsx
  assets/src/components/pr/scm/PrScmConnections.tsx
  assets/src/components/pr/scm/ScmWebhooks.tsx
  assets/src/components/stacks/Stacks.tsx
  assets/src/components/utils/tableFetchHelpers.tsx
  assets/src/utils/graphql.ts
Labels: enhancement, frontend

#1080 add option to configure scm connections with github app auth
  assets/src/components/cd/utils/SshKeyUpload.tsx
  assets/src/components/pr/scm/CreateScmConnection.tsx
  assets/src/components/pr/scm/EditScmConnection.tsx
Labels: enhancement, frontend

#1082 feat: Display minimum kubelet version in clusters table
  assets/src/components/cd/clusters/ClustersColumns.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
Labels: enhancement

#1074 Prep v0.10.4 release
  AGENT_VERSION
  assets/src/generated/graphql.ts
  lib/console.ex
  lib/console/deployments/git/utils.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/jwt/github.ex
  lib/console/schema/scm_connection.ex
  mix.exs
  schema/schema.graphql
  test/console/deployments/git_test.exs
  test/test_helper.exs
Labels: enhancement

#1084 feat: extend Scm connection with the GitHub
  charts/controller/crds/deployments.plural.sh_scmconnections.yaml
  controller/api/v1alpha1/scmconnection_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_scmconnections.yaml
  controller/internal/controller/scmconnection_controller.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  plural/helm/console/crds/deployments.plural.sh_scmconnections.yaml
Labels: enhancement

#1085 Fix sideload of service imports
  lib/console/graphql/resolvers/deployments.ex
Labels: bug-fix

#1086 feat: Show detailed stacks status
  assets/src/components/stacks/StackOverview.tsx
  assets/src/components/stacks/StackRunsEntry.tsx
  assets/src/components/stacks/StacksEntry.tsx
  assets/src/components/stacks/common/StackRunStatusChip.tsx
  assets/src/components/stacks/common/StackStatusChip.tsx
  assets/src/components/stacks/run/Sidecar.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/stacks.graphql
Labels: enhancement

#1077 build: Prod 2278/use a cron GitHub action to automate compatibility gathering
  .github/workflows/compatibility-updater.yaml
  utils/compatibility/.python-version
Labels: enhancement

#1087 Change way kubelet vsn is displayed
  assets/src/components/cd/clusters/ClustersColumns.tsx
Labels: enhancement

#1088 add view for rollout kind
  assets/package.json
  assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
  assets/src/components/cd/services/service/ServicePromote.tsx
  assets/src/components/cluster/pods/PodsList.tsx
  assets/src/components/component/ComponentDetails.tsx
  assets/src/components/component/ComponentInfo.tsx
  assets/src/components/component/info/Daemonset.tsx
  assets/src/components/component/info/Deployment.tsx
  assets/src/components/component/info/Metadata.tsx
  assets/src/components/component/info/common.tsx
  assets/src/components/component/info/rollout/CanarySpecTableColumns.tsx
  assets/src/components/component/info/rollout/Rollout.tsx
  assets/src/components/component/info/rollout/RolloutSections.tsx
  assets/src/components/utils/PieChart.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/kubernetes/argoRollout.graphql
  assets/yarn.lock
  lib/console/graphql/kubernetes/rollout.ex
  schema/schema.graphql
Labels: enhancement, frontend

#1090 add enum type support to pr automation configs
  assets/src/components/pr/automations/CreatePrModal.tsx
  assets/src/components/pr/automations/PrConfigurationInput.tsx
Labels: enhancement, frontend

#1092 Fixes for pr stack runs
  assets/src/generated/graphql.ts
  assets/src/graph/automation.graphql
  lib/console/deployments/pubsub/recurse.ex
  lib/console/deployments/stacks.ex
  lib/console/deployments/stacks/commands.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  lib/console/schema/stack_run.ex
  test/console/deployments/stacks_test.exs
Labels: bug-fix, hotfix

#1083 feat: Add imports to ServiceDeployment CRD
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  controller/api/v1alpha1/common_types.go
  controller/api/v1alpha1/servicedeployment_types.go
  controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  controller/config/samples/service_deployment.yaml
  controller/internal/controller/common.go
  controller/internal/controller/servicedeployment_controller.go
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
Labels: enhancement

#1095 The value for selects in the pr automation config was incorrect
  assets/src/components/pr/automations/PrConfigurationInput.tsx
Labels: bug-fix

#1094 Autogen CRD docs in console repo
  .github/workflows/crd-docs.yaml
  controller/docs/api.md
Labels: enhancement

#1099 fix: allow resource creation when group/user bindings not found
  assets/src/generated/graphql.ts
  controller/api/v1alpha1/cluster_types.go
  controller/api/v1alpha1/common_types.go
  controller/api/v1alpha1/project_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/internal/cache/user_group.go
  controller/internal/controller/common.go
  controller/internal/controller/deploymentsettings_controller.go
  controller/internal/controller/infrastructurestack_controller.go
  controller/internal/controller/servicedeployment_controller.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  lib/console/graphql/deployments/stack.ex
  schema/schema.graphql
Labels: bug-fix

#1101 Fix external ingress
  assets/src/generated/graphql.ts
  charts/console/templates/ingress.yaml
  lib/console/graphql/deployments/cluster.ex
  schema/schema.graphql
Labels: enhancement

#1103 fix caching issue with stack prs/runs
  assets/src/generated/graphql.ts
  assets/src/graph/stacks.graphql
Labels: bug-fix, frontend

#1102 Prune unfound runtime services
  lib/console/deployments/clusters.ex
  test/console/deployments/clusters_test.exs
Labels: enhancement

#1106 Add stacks to `updateRbac`
  assets/src/generated/graphql.ts
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/schema/stack.ex
  schema/schema.graphql
  test/console/graphql/mutations/deployment_mutations_test.exs
Labels: enhancement

#1108 enhancement: use prometheus k8s label
  charts/console/templates/prometheusrule.yaml
  charts/console/values.yaml
Labels: enhancement

#1110 Add stack pr comments on StackUpdated events
  assets/src/generated/graphql.ts
  controller/internal/controller/pipeline_controller.go
  controller/internal/controller/pipeline_controller_attributes.go
  controller/internal/controller/pipeline_controller_test.go
  controller/internal/controller/pipelinecontext_controller.go
  lib/console/deployments/pipelines.ex
  lib/console/deployments/pipelines/stage_worker.ex
  lib/console/deployments/pr/utils.ex
  lib/console/deployments/pubsub/recurse.ex
  lib/console/deployments/stacks.ex
  lib/console/exceptions.ex
  lib/console/graphql/deployments/pipeline.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/exceptions/protocol.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  lib/console/schema/pipeline_stage.ex
  lib/console/schema/service_error.ex
  priv/pr/succeeded.md.eex
  priv/repo/migrations/20240626190945_add_pipeline_errors.exs
  schema/schema.graphql
  test/console/deployments/pipeline_test.exs
  test/console/deployments/stacks_test.exs
Labels: enhancement

#1109 feat: hide state/plan/output tabs if data is not available
  assets/src/components/stacks/run/Header.tsx
Labels: enhancement

#1104 move component metadata to separate tab
  assets/package.json
  assets/src/components/cd/services/service/ServiceComponents.tsx
  assets/src/components/component/ComponentDetails.tsx
  assets/src/components/component/ComponentInfo.tsx
  assets/src/components/component/ComponentMetadata.tsx
  assets/src/components/component/directory.tsx
  assets/src/components/component/info/Canary.tsx
  assets/src/components/component/info/Certificate.tsx
  assets/src/components/component/info/CronJob.tsx
  assets/src/components/component/info/Daemonset.tsx
  assets/src/components/component/info/Deployment.tsx
  assets/src/components/component/info/Job.tsx
  assets/src/components/component/info/PluralServiceDeployment.tsx
  assets/src/components/component/info/Service.tsx
  assets/src/components/component/info/StatefulSet.tsx
  assets/src/components/component/info/common.tsx
  assets/src/components/component/info/rollout/Rollout.tsx
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#1111 add command parser
  assets/src/utils/cmdLineParse.test.ts
  assets/src/utils/cmdLineParse.ts
Labels: enhancement, frontend

#1112 Add mutli-line script parsing
  assets/src/utils/cmdLineParse.test.ts
  assets/src/utils/cmdLineParse.ts
Labels: enhancement

#1105 feat: Stacks improvements
  assets/package.json
  assets/src/components/cd/pipelines/EdgeLine.tsx
  assets/src/components/cd/pipelines/nodes/BaseNode.tsx
  assets/src/components/cd/pipelines/utils/nodeLayouter.tsx
  assets/src/components/cd/utils/PermissionsModal.tsx
  assets/src/components/stacks/StackDelete.tsx
  assets/src/components/stacks/StackDeleteModal.tsx
  assets/src/components/stacks/StackDetach.tsx
  assets/src/components/stacks/StackDetachModal.tsx
  assets/src/components/stacks/StackPermissionsModal.tsx
  assets/src/components/stacks/Stacks.tsx
  assets/src/components/stacks/StacksEntry.tsx
  assets/src/components/stacks/environment/StackEnvironment.tsx
  assets/src/components/stacks/files/StackFiles.tsx
  assets/src/components/stacks/output/StackOutput.tsx
  assets/src/components/stacks/overview/StackConfiguration.tsx
  assets/src/components/stacks/overview/StackMetadata.tsx
  assets/src/components/stacks/overview/StackOverview.tsx
  assets/src/components/stacks/overview/StackRepository.tsx
  assets/src/components/stacks/prs/StackPrs.tsx
  assets/src/components/stacks/state/StackState.tsx
  assets/src/components/stacks/state/StackStateGraph.tsx
  assets/src/components/stacks/state/StackStateGraphEdge.tsx
  assets/src/components/stacks/state/StackStateGraphNode.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdServices.graphql
  assets/src/graph/stacks.graphql
  assets/src/routes/stacksRoutes.tsx
  assets/src/routes/stacksRoutesConsts.tsx
  assets/yarn.lock
Labels: enhancement

#1113 Allow repository to be parameterized in pr automations
  assets/src/components/pr/automations/CreatePrModal.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdPrs.graphql
  lib/console/deployments/git.ex
  lib/console/deployments/pipelines.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/deployments/pipeline.ex
  lib/console/graphql/resolvers/deployments/git.ex
  lib/console/schema/promotion_criteria.ex
  priv/repo/migrations/20240627005403_add_repository_promo_criteria.exs
  schema/schema.graphql
Labels: enhancement

#1119 feat: Add icons to stack menu items
  assets/src/components/stacks/Stacks.tsx
Labels: enhancement

#1117 add custom stack run ui
  assets/package.json
  assets/src/components/account/audits/AuditsList.tsx
  assets/src/components/apps/app/runbooks/runbook/RunbookExecutions.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/pr/automations/PrConfigurationFields.tsx
  assets/src/components/stacks/Stacks.tsx
  assets/src/components/stacks/customrun/StackCustomRun.tsx
  assets/src/components/stacks/customrun/StackCustomRunChooseTemplate.tsx
  assets/src/components/stacks/customrun/StackCustomRunCommands.tsx
  assets/src/components/stacks/customrun/StackCustomRunModal.tsx
  assets/src/components/stacks/customrun/StackCustomRunSettings.tsx
  assets/src/components/stacks/run/progress/Progress.tsx
  assets/src/components/utils/table/StackedText.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/automation.graphql
  assets/src/graph/stacks.graphql
  assets/src/utils/cmdLineParse.test.ts
  assets/src/utils/cmdLineParse.ts
  assets/src/utils/graphql.ts
  assets/yarn.lock
Labels: enhancement, frontend

#1115 feat: Global service details improvements
  assets/src/components/cd/globalServices/GlobalService.tsx
  assets/src/components/cd/globalServices/GlobalServiceDetailTable.tsx
  assets/src/components/cd/globalServices/GlobalServiceDetailView.tsx
  assets/src/components/cd/globalServices/GlobalServiceSidecar.tsx
  assets/src/components/cd/globalServices/details/GlobalService.tsx
  assets/src/components/cd/globalServices/details/GlobalServiceInfo.tsx
  assets/src/components/cd/globalServices/details/GlobalServiceServices.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdGlobalServices.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
Labels: enhancement

#1116 Add `repository` field to promotion criteria
  AGENT_VERSION
  assets/src/components/cd/pipelines/nodes/StageNode.tsx
  assets/src/components/cd/services/ServicesTableErrors.tsx
  assets/src/components/stacks/customrun/StackCustomRun.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdPipelines.graphql
  charts/controller/crds/deployments.plural.sh_pipelines.yaml
  controller/api/v1alpha1/pipeline_types.go
  controller/api/v1alpha1/prautomation_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_pipelines.yaml
  controller/docs/api.md
  controller/go.mod
  controller/go.sum
  controller/internal/controller/pipeline_controller_attributes.go
  controller/internal/controller/prautomation_controller.go
  lib/console/deployments/policies/rbac.ex
  lib/console/schema/global_service.ex
  plural/helm/console/crds/deployments.plural.sh_pipelines.yaml
  static/compatibilities/flux.yaml
  test/console/deployments/global_test.exs
Labels: enhancement, hotfix

#1122 fix flow layout bug
  assets/src/components/cd/pipelines/utils/nodeLayouter.tsx
Labels: bug-fix, frontend

#1121 fix open embed
  assets/index.html
Labels: enhancement, frontend
