Repository pluralsh/console, pull requests merged in 2024-09, with the labels that each got.

#1354 Add value format extraction and git polling to observer resource
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/deployments/git/agent.ex
  lib/console/deployments/git/cache.ex
  lib/console/deployments/git/discovery.ex
  lib/console/deployments/observer/poller.ex
  lib/console/deployments/observer/utils.ex
  lib/console/graphql/deployments/git.ex
  lib/console/schema/observer.ex
  lib/console_web/router.ex
  mix.exs
  mix.lock
  schema/schema.graphql
  test/console/deployments/observer/runner_test.exs
  test/console/graphql/mutations/deployments/git_mutations_test.exs
Labels: enhancement

#1357 Fix unloaded notif bindings on sinks
  lib/console/graphql/deployments/notification.ex
Labels: bug-fix, hotfix

#1358 Complexity check needs to be increased
  lib/console_web/router.ex
Labels: bug-fix, hotfix

#1359 feat(client): add share secret mutation
  go/client/client.go
  go/client/graph/sharedsecret.graphql
Labels: enhancement

#1356 feat(controller): add projectref to prautomation crd
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  go/controller/.golangci.yml
  go/controller/api/v1alpha1/prautomation_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  go/controller/docs/api.md
  go/controller/internal/controller/prautomation_attributes.go
  go/controller/internal/utils/kubernetes.go
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
Labels: enhancement

#1363 use default scope method
  go/controller/internal/client/scmconnection.go
  go/controller/internal/controller/cluster_controller.go
  go/controller/internal/controller/cluster_scope.go
  go/controller/internal/controller/clusterrestore_controller.go
  go/controller/internal/controller/clusterrestore_scope.go
  go/controller/internal/controller/clusterrestoretrigger_controller.go
  go/controller/internal/controller/clusterrestoretrigger_scope.go
  go/controller/internal/controller/customstackrun_controller.go
  go/controller/internal/controller/customstackrun_scope.go
  go/controller/internal/controller/deploymentsettings_controller.go
  go/controller/internal/controller/deploymentsettings_scope.go
  go/controller/internal/controller/gitrepository_controller.go
  go/controller/internal/controller/gitrepository_scope.go
  go/controller/internal/controller/globalservice_controller.go
  go/controller/internal/controller/globalservice_scope.go
  go/controller/internal/controller/infrastructurestack_controller.go
  go/controller/internal/controller/infrastructurestack_scope.go
  go/controller/internal/controller/managednamespace_controller.go
  go/controller/internal/controller/managednamespace_scope.go
  go/controller/internal/controller/namespace_credentials_controller.go
  go/controller/internal/controller/namespace_credentials_scope.go
  go/controller/internal/controller/notificationrouter_controller.go
  go/controller/internal/controller/notificationrouter_scope.go
  go/controller/internal/controller/notificationsink_controller.go
  go/controller/internal/controller/notificationsink_scope.go
  go/controller/internal/controller/pipeline_controller.go
  go/controller/internal/controller/pipeline_scope.go
  go/controller/internal/controller/pipelinecontext_controller.go
  go/controller/internal/controller/pipelinecontext_scope.go
  go/controller/internal/controller/prautomation_controller.go
  go/controller/internal/controller/prautomation_scope.go
  go/controller/internal/controller/prautomationtrigger_controller.go
  go/controller/internal/controller/prautomationtrigger_scope.go
  go/controller/internal/controller/project_controller.go
  go/controller/internal/controller/project_scope.go
  go/controller/internal/controller/provider_controller.go
  go/controller/internal/controller/provider_scope.go
  go/controller/internal/controller/scmconnection_controller.go
  go/controller/internal/controller/scmconnection_scope.go
  go/controller/internal/controller/service_account_controller.go
  go/controller/internal/controller/service_account_scope.go
  go/controller/internal/controller/servicedeployment_controller.go
  go/controller/internal/controller/servicedeployment_scope.go
Labels: enhancement

#1364 feat(client): add distro to mycluster query
  go/client/client.go
  go/client/graph/cluster.graphql
Labels: enhancement

#1365 feat(client): add saveUpgradeInsights mutation
  go/client/client.go
  go/client/graph/upgradeinsights.graphql
Labels: enhancement

#1366 don't force both loki and prometheus settings to be set
  assets/src/components/settings/global/observability/ObservabilitySettings.tsx
Labels: enhancement, frontend

#1355 feat: Add Observer CRD support
  charts/controller/crds/deployments.plural.sh_observers.yaml
  go/client/client.go
  go/client/graph/observer.graphql
  go/controller/PROJECT
  go/controller/api/v1alpha1/observer_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_observers.yaml
  go/controller/config/rbac/observer_editor_role.yaml
  go/controller/config/rbac/observer_viewer_role.yaml
  go/controller/config/rbac/role.yaml
  go/controller/config/samples/deployments_v1alpha1_observer.yaml
  go/controller/internal/client/console.go
  go/controller/internal/client/observer.go
  go/controller/internal/client/prautomation.go
  go/controller/internal/controller/helmrepository_attributes.go
  go/controller/internal/controller/helmrepository_controller.go
  go/controller/internal/controller/helmrepository_test.go
  go/controller/internal/controller/observer_controller.go
  go/controller/internal/controller/observer_test.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  go/controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_observers.yaml
Labels: enhancement

#1367 feat: secure Http connection and add configurationRef to ServiceTemplate
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/managednamespace_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  go/controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  go/controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  go/controller/internal/controller/common.go
  go/controller/internal/controller/deploymentsettings_controller.go
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
Labels: enhancement

#1344 feat: Add in app notifications and fix sink CRD
  assets/src/components/cd/pipelines/nodes/StageNode.tsx
  assets/src/components/commandpalette/commands.ts
  assets/src/components/help/HelpLauncher.tsx
  assets/src/components/help/HelpLauncherBtn.tsx
  assets/src/components/help/HelpMenu.tsx
  assets/src/components/layout/Header.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/notifications/Notification.tsx
  assets/src/components/notifications/NotificationPriorityChip.tsx
  assets/src/components/notifications/Notifications.tsx
  assets/src/components/notifications/NotificationsLauncher.tsx
  assets/src/components/notifications/NotificationsLauncherButton.tsx
  assets/src/components/notifications/NotificationsPanel.tsx
  assets/src/components/settings/Settings.tsx
  assets/src/components/settings/notifications/Notifications.tsx
  assets/src/components/settings/notifications/routers/CreateNotificationRouterModal.tsx
  assets/src/components/settings/notifications/routers/EditNotificationRouterModal.tsx
  assets/src/components/settings/notifications/routers/NotificationRouterConfigurationInput.tsx
  assets/src/components/settings/notifications/routers/NotificationRouterPermissionsModal.tsx
  assets/src/components/settings/notifications/routers/NotificationRouters.tsx
  assets/src/components/settings/notifications/routers/NotificationRoutersColumns.tsx
  assets/src/components/settings/notifications/routers/compareByPrefixes.tsx
  assets/src/components/settings/notifications/routers/insertBetweenLimited.tsx
  assets/src/components/settings/notifications/sinks/NotificationSinks.tsx
  assets/src/components/settings/notifications/sinks/NotificationSinksColumns.tsx
  assets/src/components/settings/notifications/sinks/UpsertNotificationSinkModal.tsx
  assets/src/components/utils/CountBadge.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/notifications.graphql
  assets/src/routes/consoleRoutes.tsx
  assets/src/routes/notificationsRoutes.tsx
  assets/src/routes/notificationsRoutesConsts.tsx
  assets/src/routes/settingsRoutes.tsx
  assets/src/routes/settingsRoutesConst.tsx
  charts/controller/crds/deployments.plural.sh_notificationsinks.yaml
  go/controller/api/v1alpha1/notificationsink_types.go
  go/controller/config/crd/bases/deployments.plural.sh_notificationsinks.yaml
  go/controller/config/samples/deployments_v1alpha1_notificationrouter.yaml
  go/controller/config/samples/deployments_v1alpha1_notificationsink.yaml
  go/controller/config/samples/notifications.yaml
  plural/helm/console/crds/deployments.plural.sh_notificationsinks.yaml
Labels: enhancement

#1372 add smtp form to global settings
  assets/src/components/settings/global/GlobalSettings.tsx
  assets/src/components/settings/global/GlobalSettingsSMTP.tsx
  assets/src/components/settings/usermanagement/email/EmailSettingsForm.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdGlobalSettings.graphql
  assets/src/routes/settingsRoutes.tsx
Labels: enhancement, frontend

#1374 Prepare upcoming 0.10.25 release
  AGENT_VERSION
  Dockerfile
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_customstackruns.yaml
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/prautomation_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_customstackruns.yaml
  go/controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  go/controller/docs/api.md
  lib/console/deployments/git.ex
  lib/console/deployments/pr/impl/bitbucket.ex
  lib/console/deployments/pr/impl/github.ex
  lib/console/deployments/pr/impl/gitlab.ex
  lib/console/deployments/pr/utils.ex
  lib/console/deployments/pr/validation.ex
  lib/console/deployments/pubsub/recurse.ex
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/helpers.ex
  lib/console/schema/embeds.ex
  lib/console/schema/stack.ex
  lib/console/services/base.ex
  mix.exs
  mix.lock
  plural/helm/console/crds/deployments.plural.sh_customstackruns.yaml
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
  schema/schema.graphql
  test/console/deployments/git_test.exs
  test/console/deployments/stacks_test.exs
  test/console/graphql/mutations/deployments/stack_mutations_test.exs
Labels: enhancement

#1379 Drop autospawn behavior
  lib/console/deployments/stacks.ex
  test/console/deployments/stacks_test.exs
Labels: bug-fix, hotfix

#1384 don't stringify bool types in pr automation wizard
  assets/src/components/pr/automations/prConfigurationUtils.tsx
Labels: bug-fix, frontend

#1383 fix: Contextualize observer details modal to target type
  assets/src/components/cd/observers/Observers.tsx
Labels: bug-fix

#1382 Observer api fixes
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_observers.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/observer_types.go
  go/controller/config/crd/bases/deployments.plural.sh_observers.yaml
  go/controller/docs/api.md
  go/controller/internal/controller/observer_controller.go
  go/controller/internal/controller/observer_test.go
  lib/console.ex
  lib/console/application.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/observer/discovery.ex
  lib/console/deployments/observer/poller.ex
  lib/console/deployments/observer/supervisor.ex
  lib/console/deployments/observer/worker.ex
  lib/console/deployments/stacks.ex
  lib/console/deployments/stacks/stability.ex
  lib/console/graphql/deployments/git.ex
  lib/console/schema/observer.ex
  lib/oci/client.ex
  lib/oci/schema.ex
  plural/helm/console/crds/deployments.plural.sh_observers.yaml
  schema/schema.graphql
  test/console/deployments/cron_test.exs
  test/console/deployments/observer/runner_test.exs
  test/console/deployments/stacks_test.exs
Labels: enhancement, hotfix

#1386 reduce unnecessary log outs
  assets/src/components/login/Login.tsx
Labels: bug-fix, frontend

#1393 Handle empty strings in string pr automation context
  lib/console/deployments/pr/validation.ex
  test/console/deployments/git_test.exs
Labels: enhancement

#1396 fix: Fix login flash
  assets/src/components/login/Login.tsx
Labels: bug-fix

#1397 fix various react errors
  assets/package.json
  assets/src/components/cd/cluster/node/Node.tsx
  assets/src/components/cd/utils/PermissionsModal.tsx
  assets/src/components/cluster/nodes/Node.tsx
  assets/src/components/component/ComponentDetails.tsx
  assets/src/components/kubernetes/network/utils.tsx
  assets/src/components/policies/PoliciesFilter.tsx
  assets/src/components/utils/Chloropleth.tsx
  assets/src/components/utils/ModalMountTransition.tsx
  assets/src/components/utils/layout/ResponsiveLayoutContentContainer.tsx
  assets/src/components/utils/layout/ResponsivePageFullWidth.tsx
  assets/yarn.lock
Labels: bug-fix, frontend

#1399 persist last viewed cluster id in k8s dashboard
  assets/src/components/kubernetes/Cluster.tsx
  assets/src/components/kubernetes/Navigation.tsx
Labels: enhancement, frontend

#1398 fix form toggles
  assets/src/components/pr/automations/prConfigurationUtils.tsx
  assets/src/components/settings/global/GlobalSettingsSMTP.tsx
Labels: bug-fix, frontend

#1404 add cloud instance setup modal
  assets/src/components/layout/CloudConsoleWelcomeModal.tsx
  assets/src/components/layout/Console.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/users.graphql
Labels: enhancement, frontend

#1409 fix: prometheus query typo
  lib/console/deployments/observability/metrics.ex
Labels: bug-fix

#1410 Add `stack.run` to event list
  lib/console/schema/notification_router.ex
Labels: enhancement

#1411 requeue when referenced object is not found
  go/controller/internal/controller/prautomation_attributes.go
  go/controller/internal/controller/prautomation_controller.go
  go/controller/internal/controller/prautomation_controller_test.go
Labels: enhancement

#1414 unify handling referenced objects
  go/controller/internal/controller/clusterrestore_controller.go
  go/controller/internal/controller/common.go
  go/controller/internal/controller/customstackrun_controller.go
  go/controller/internal/controller/gitrepository_controller.go
  go/controller/internal/controller/globalservice_controller.go
  go/controller/internal/controller/managednamespace_controller.go
  go/controller/internal/controller/notificationrouter_controller.go
  go/controller/internal/controller/observer_controller.go
  go/controller/internal/controller/pipeline_controller.go
  go/controller/internal/controller/pipeline_controller_attributes.go
  go/controller/internal/controller/prautomation_controller.go
Labels: enhancement

#1412 Implement Urgent Notification delivery
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_notificationsinks.yaml
  config/test.exs
  go/client/models_gen.go
  go/controller/api/v1alpha1/notificationsink_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_notificationsinks.yaml
  go/controller/docs/api.md
  go/controller/internal/controller/notificationsink_controller.go
  lib/console/deployments/events.ex
  lib/console/deployments/notifications.ex
  lib/console/deployments/pubsub/protocols/emailable.ex
  lib/console/email/builder/notification.ex
  lib/console/graphql/deployments/notification.ex
  lib/console/schema/app_notification.ex
  lib/console/schema/notification_sink.ex
  lib/console_web/templates/email/notification.html.eex
  lib/console_web/templates/email/notification.text.eex
  lib/console_web/views/email_view.ex
  mix.exs
  mix.lock
  plural/helm/console/crds/deployments.plural.sh_notificationsinks.yaml
  priv/repo/migrations/20240924230544_add_app_notificaiton_urgent.exs
  schema/schema.graphql
  test/console/deployments/notifications_test.exs
  test/console/deployments/pubsub/email_test.exs
Labels: enhancement

#1417 Log prometheus queries
  lib/console/deployments/observability.ex
  lib/prometheus/client.ex
Labels: enhancement

#1420 fix: Visual bug on add-ons compatibility table
  assets/src/components/cd/cluster/Cluster.tsx
Labels: bug-fix

#1419 feat: Add cloud upgrade insights to upgrade flyout
  assets/package.json
  assets/src/components/cd/clusters/ClusterUpgradeFlyover.tsx
  assets/src/components/cd/clusters/ClusterUpgradePR.tsx
  assets/src/components/cd/clusters/ClustersUpgradeNow.tsx
  assets/src/components/cd/clusters/UpgradeInsights.tsx
  assets/src/components/cd/clusters/clusterUpgradeColumns.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/yarn.lock
Labels: enhancement

#1416 feat(console): use new metrics queries for cluster/node metrics
  assets/src/components/cd/cluster/ClusterNodes.tsx
  assets/src/components/cd/cluster/node/NodeInfo.tsx
  assets/src/components/cluster/nodes/ClusterGauges.tsx
  assets/src/components/cluster/nodes/ClusterMetrics.tsx
  assets/src/components/cluster/nodes/NodeGraphs.tsx
  assets/src/components/cluster/nodes/NodeInfo.tsx
  assets/src/components/cluster/nodes/Nodes.tsx
  assets/src/components/cluster/nodes/SaturationGraphs.tsx
  assets/src/components/component/ComponentMetrics.tsx
  assets/src/components/utils/Graph.tsx
  assets/src/components/utils/GraphHeader.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/graph/cdComponent.graphql
  assets/src/utils/kubernetes.ts
  assets/src/utils/prometheus.ts
Labels: enhancement

#1422 Prep 0.10.30
  AGENT_VERSION
Labels: enhancement, hotfix
