Repository pluralsh/console, pull requests merged in 2024-04, with the labels that each got.

#801 Allow setting secrets on template global services
  assets/src/generated/graphql.ts
  lib/console/deployments/global.ex
  lib/console/graphql/deployments/global.ex
  lib/console/graphql/resolvers/deployments/global.ex
  lib/console/schema/revision.ex
  lib/console/schema/service_template.ex
  priv/repo/migrations/20240330214528_add_service_template_secrets.exs
  schema/schema.graphql
  test/console/deployments/global_test.exs
  test/console/graphql/mutations/deployments/global_mutations_test.exs
  test/console/graphql/queries/deployments/service_queries_test.exs
Labels: enhancement

#800 Add pinned custom resources api
  assets/src/generated/graphql.ts
  lib/console/deployments/clusters.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/schema/pinned_custom_resource.ex
  priv/repo/migrations/20240328143552_add_pinned_custom_resources.exs
  schema/schema.graphql
  test/console/deployments/clusters_test.exs
  test/console/graphql/mutations/deployments/cluster_mutations_test.exs
  test/console/graphql/queries/deployments/cluster_queries_test.exs
  test/support/factory.ex
Labels: enhancement

#803 feat: Added Jaeger compatibility
  static/compatibilities/jaeger.yaml
  static/compatibilities/manifest.yaml
Labels: enhancement

#804 feat: Managed namespace controller
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  charts/controller/templates/manager-rbac.yaml
  controller/PROJECT
  controller/api/v1alpha1/managednamespace_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  controller/config/rbac/managednamespace_editor_role.yaml
  controller/config/rbac/managednamespace_viewer_role.yaml
  controller/config/rbac/role.yaml
  controller/config/samples/deployments_v1alpha1_managednamespace.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/client/console.go
  controller/internal/client/namespace.go
  controller/internal/controller/managednamespace_controller.go
  controller/internal/controller/managednamespace_scope.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
Labels: enhancement

#756 feat: Use Kubernetes Dashboard Helm chart
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.28.tgz
  charts/console/charts/kas-0.0.6.tgz
  charts/console/charts/kubernetes-dashboard-7.1.2.tgz
  charts/console/templates/dashboard/configmap.yaml
  charts/console/templates/dashboard/deployment.yaml
  charts/console/templates/dashboard/rbac.yaml
  charts/console/templates/dashboard/secret.yaml
  charts/console/templates/dashboard/service.yaml
  charts/console/templates/dashboard/serviceaccount.yaml
  charts/console/templates/ingress.yaml
  charts/console/values.yaml
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/kubernetes-dashboard-7.1.2.tgz
  plural/helm/console/templates/dashboard/configmap.yaml
  plural/helm/console/templates/dashboard/deployment.yaml
  plural/helm/console/templates/dashboard/rbac.yaml
  plural/helm/console/templates/dashboard/secret.yaml
  plural/helm/console/templates/dashboard/service.yaml
  plural/helm/console/templates/dashboard/serviceaccount.yaml
  plural/helm/console/templates/ingress.yaml
  plural/helm/console/values.yaml
  plural/helm/console/values.yaml.tpl
  templates/values.yaml.liquid
Labels: enhancement

#805 fix(chart): add missing dashboard repo
  .github/workflows/chart.yaml
Labels: bug-fix

#802 Add Global services view
  assets/.eslintrc.js
  assets/package.json
  assets/src/components/cd/ContinuousDeployment.tsx
  assets/src/components/cd/YamlGeneratorModal.tsx
  assets/src/components/cd/globalServices/GlobalService.tsx
  assets/src/components/cd/globalServices/GlobalServiceDetailTable.tsx
  assets/src/components/cd/globalServices/GlobalServiceDetailView.tsx
  assets/src/components/cd/globalServices/GlobalServicesColumns.tsx
  assets/src/components/cd/globalServices/GlobalServicesTable.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdGlobalServices.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
  assets/yarn.lock
Labels: enhancement

#806 Service details sidecar improvements
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
Labels: enhancement

#809 Pipeline gate force open/close UI
  assets/src/components/cd/ContinuousDeployment.tsx
  assets/src/components/cd/pipelines/job/PipelineJobLogs.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdPipelines.graphql
Labels: enhancement

#808 Basic Terraform Executor CRUD Apis
  AGENT_VERSION
  assets/src/generated/graphql.ts
  config/prod.exs
  lib/console.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/events.ex
  lib/console/deployments/git/agent.ex
  lib/console/deployments/git/cache.ex
  lib/console/deployments/git/discovery.ex
  lib/console/deployments/global.ex
  lib/console/deployments/policies/policies.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/deployments/pubsub/recurse.ex
  lib/console/deployments/stacks.ex
  lib/console/deployments/stacks/commands.ex
  lib/console/external_graphql.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  lib/console/schema/run_log.ex
  lib/console/schema/run_step.ex
  lib/console/schema/service_error.ex
  lib/console/schema/stack.ex
  lib/console/schema/stack_environment.ex
  lib/console/schema/stack_files.ex
  lib/console/schema/stack_output.ex
  lib/console/schema/stack_run.ex
  lib/console/schema/stack_state.ex
  lib/console_web/controllers/git_controller.ex
  lib/console_web/router.ex
  priv/repo/migrations/20240402221806_add_stacks.exs
  rel/config/console.exs
  schema/schema.graphql
  test/console/deployments/pubsub/recurse_test.exs
  test/console/deployments/stacks_test.exs
  test/console/graphql/mutations/deployments/stack_mutations_test.exs
  test/console/graphql/queries/deployments/stack_queries_test.exs
  test/console_web/controllers/git_controller_test.exs
  test/support/factory.ex
Labels: enhancement

#811 feat(chart): bump kubernetes-dashboard chart dep to latest version
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.28.tgz
  charts/console/charts/kas-0.0.6.tgz
  charts/console/charts/kubernetes-dashboard-7.1.2.tgz
  charts/console/charts/kubernetes-dashboard-7.2.0.tgz
  plural/helm/console/Chart.lock
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/controller-0.0.27.tgz
  plural/helm/console/charts/controller-0.0.28.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.1.2.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.2.0.tgz
  templates/values.yaml.tpl
Labels: enhancement

#813 Implement stack destruction
  AGENT_VERSION
  assets/src/generated/graphql.ts
  lib/console/deployments/events.ex
  lib/console/deployments/global.ex
  lib/console/deployments/pubsub/recurse.ex
  lib/console/deployments/services.ex
  lib/console/deployments/stacks.ex
  lib/console/deployments/stacks/commands.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  lib/console/schema/stack.ex
  priv/repo/migrations/20240406003015_add_stack_destroy.exs
  schema/schema.graphql
  test/console/deployments/git/agent_test.exs
  test/console/deployments/pubsub/recurse_test.exs
  test/console/deployments/stacks_test.exs
  test/console/graphql/mutations/deployments/stack_mutations_test.exs
Labels: enhancement, hotfix

#815 Add service template to global services in gql
  assets/src/generated/graphql.ts
  lib/console/deployments/global.ex
  lib/console/graphql/deployments/global.ex
  lib/console/graphql/resolvers/deployments/global.ex
  lib/console/schema/global_service.ex
  schema/schema.graphql
  test/console/deployments/git/agent_test.exs
  test/console/graphql/mutations/deployment_mutations_test.exs
  test/console/graphql/mutations/deployments/global_mutations_test.exs
Labels: enhancement

#816 Table styling inconsistent on backups tables
  assets/src/components/backups/cluster/backups/Backups.tsx
  assets/src/components/backups/cluster/backups/BackupsColumns.tsx
  assets/src/components/backups/cluster/backups/RestoreClusterBackup.tsx
  assets/src/components/backups/clusters/ClusterColumns.tsx
  assets/src/components/backups/clusters/Clusters.tsx
  assets/src/components/backups/objectstores/DeleteObjectStore.tsx
  assets/src/components/backups/objectstores/ObjectStoreColumns.tsx
  assets/src/components/backups/objectstores/ObjectStores.tsx
  assets/src/components/backups/objectstores/UpdateObjectStore.tsx
Labels: enhancement, frontend

#817 add distro icon to global service detail
  assets/src/components/cd/globalServices/GlobalServiceDetailTable.tsx
Labels: enhancement, frontend

#819 Add ability to optionally disable additional volumes for subcharts
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.30.tgz
  charts/console/charts/controller-0.0.31.tgz
  charts/console/charts/kas-0.0.6.tgz
  charts/console/templates/deployment.yaml
  charts/console/values.yaml
  charts/controller/Chart.yaml
  charts/controller/templates/deployment.yaml
  charts/controller/values.yaml
Labels: enhancement, hotfix

#818 limit service list to same cluster
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdServices.graphql
Labels: enhancement, frontend

#820 Bump agent to 0.4.19
  AGENT_VERSION
  charts/controller/values.yaml
Labels: enhancement, hotfix

#821 add resync button to services table action column
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/services/ServicesResyncDeployment.tsx
Labels: enhancement, frontend

#822 Add custom oidc login name
  assets/src/components/login/Login.tsx
  assets/src/generated/graphql.ts
  lib/console/deployments/helm/repository.ex
  lib/console/graphql/configuration.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/user.ex
  lib/console/graphql/users.ex
  lib/console/schema/cluster.ex
  rel/config/console.exs
  schema/schema.graphql
Labels: enhancement

#825 fix: Kubernetes detail views
  assets/package.json
  assets/src/components/kubernetes/Kubernetes.tsx
  assets/yarn.lock
Labels: bug-fix

#826 Add upgrade plan struct
  assets/schema/kubernetes-schema.graphql
  assets/src/components/kubernetes/Kubernetes.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql.ts
  assets/src/routes/kubernetesRoutesConsts.tsx
  assets/src/utils/semver.ts
  lib/console/deployments/git.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/resolvers/deployments/git.ex
  lib/console/schema/cluster.ex
  priv/repo/migrations/20240410220551_add_cluster_upgrade_plan.exs
  schema/schema.graphql
  test/console/graphql/mutations/deployments/git_mutations_test.exs
Labels: enhancement, hotfix

#824 Set up kas host in main secret
  .github/PULL_REQUEST_TEMPLATE.md
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.31.tgz
  charts/console/charts/kas-0.0.6.tgz
  charts/console/charts/kubernetes-dashboard-7.2.0.tgz
  charts/console/charts/kubernetes-dashboard-7.3.1.tgz
  charts/console/templates/secrets.yaml
  plural/helm/console/Chart.lock
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/controller-0.0.30.tgz
  plural/helm/console/charts/controller-0.0.31.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.2.0.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.3.1.tgz
  plural/helm/console/templates/secrets.yaml
Labels: enhancement

#823 feat: service controller supports ServiceTemplate field
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  controller/api/v1alpha1/globalservice_types.go
  controller/api/v1alpha1/servicedeployment_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/controller/common.go
  controller/internal/controller/globalservice_controller.go
  controller/internal/controller/globalservice_test.go
  controller/internal/controller/managednamespace_controller.go
  controller/internal/controller/servicedeployment_controller.go
  controller/internal/controller/servicedeployment_controller_test.go
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
Labels: enhancement

#830 use context id for stage promotion
  lib/console/deployments/pipelines.ex
Labels: bug-fix, hotfix

#828 feat: Improve kubernetes components and prod build chunks
  assets/package.json
  assets/schema/kubernetes-schema.graphql
  assets/src/components/kubernetes/common/Containers.tsx
  assets/src/components/kubernetes/common/Raw.tsx
  assets/src/components/kubernetes/common/ResourceInfoCard.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/graph-kubernetes/cluster/namespace.graphql
  assets/src/graph-kubernetes/storage/persistentvolume.graphql
  assets/src/graph-kubernetes/workloads/pod_fragments.graphql
  assets/src/helpers/kubernetes.client.ts
  assets/src/utils/sha.tsx
  assets/vite.config.mts
  assets/yarn.lock
Labels: enhancement

#833 feat: Add storage capacity info
  assets/src/components/kubernetes/storage/PersistentVolume.tsx
  assets/src/components/kubernetes/storage/PersistentVolumeClaim.tsx
  assets/src/components/kubernetes/storage/PersistentVolumeClaims.tsx
  assets/src/components/kubernetes/storage/PersistentVolumes.tsx
  assets/src/components/kubernetes/storage/StorageClass.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/graph-kubernetes/storage/persistentvolume.graphql
  assets/src/graph-kubernetes/storage/persistentvolumeclaim.graphql
  assets/src/graph-kubernetes/storage/storageclass.graphql
  assets/yarn.lock
Labels: enhancement

#832 feat: add unit tests
  controller/internal/controller/managenamespace_test.go
  controller/internal/controller/notificationrouter_test.go
  controller/internal/controller/notificationsink_test.go
Labels: enhancement

#835 Fix compatibility view for kps
  assets/src/components/cd/clusters/runtime/columns.tsx
  lib/console/deployments/compatibilities/schema.ex
Labels: enhancement

#836 Implement notifications for stack runs
  .github/workflows/helm.yaml
  lib/console/deployments/pubsub/protocols/broadcastable.ex
  lib/console/deployments/pubsub/protocols/notifiable.ex
  lib/console/schema/router_filter.ex
  priv/notifications/slack/stack.run.json.eex
  priv/notifications/teams/cluster.create.json.eex
  priv/notifications/teams/stack.run.json.eex
  priv/repo/migrations/20240413042954_add_stack_notifications.exs
  test/console/deployments/pubsub/broadcast_test.exs
  test/console/deployments/pubsub/notification_test.exs
Labels: enhancement

#838 feat: Custom resource improvements
  assets/src/components/kubernetes/Cluster.tsx
  assets/src/components/kubernetes/Navigation.tsx
  assets/src/components/kubernetes/cluster/HorizontalPodAutoscalers.tsx
  assets/src/components/kubernetes/common/DataSelect.tsx
  assets/src/components/kubernetes/common/NameFilter.tsx
  assets/src/components/kubernetes/common/NamespaceFilter.tsx
  assets/src/components/kubernetes/common/ResourceDetails.tsx
  assets/src/components/kubernetes/common/ResourceList.tsx
  assets/src/components/kubernetes/customresources/CustomResource.tsx
  assets/src/components/kubernetes/customresources/CustomResourceDefinition.tsx
  assets/src/components/kubernetes/customresources/CustomResourceDefinitions.tsx
  assets/src/components/kubernetes/storage/PersistentVolumeClaims.tsx
  assets/src/components/kubernetes/storage/PersistentVolumes.tsx
  assets/src/components/kubernetes/storage/StorageClasses.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/graph-kubernetes/customresourcedefinition.graphql
  assets/src/routes/kubernetesRoute.tsx
  assets/yarn.lock
Labels: enhancement

#841 use multiline input for smc connection private key
  assets/src/components/pr/scm/EditScmConnection.tsx
Labels: enhancement, frontend

#842 fix generated global service yaml
  assets/src/components/cd/YamlGeneratorModal.tsx
Labels: bug-fix, frontend

#840 Bump agent to v0.4.20
  AGENT_VERSION
  lib/console/schema/scm_connection.ex
Labels: enhancement, hotfix

#837 feat: add more info to pod details view
  assets/schema/kubernetes-schema.graphql
  assets/src/components/kubernetes/cluster/Node.tsx
  assets/src/components/kubernetes/common/Conditions.tsx
  assets/src/components/kubernetes/common/Containers.tsx
  assets/src/components/kubernetes/common/ImagePullSecrets.tsx
  assets/src/components/kubernetes/common/ResourceDetails.tsx
  assets/src/components/kubernetes/common/ResourceInfoCard.tsx
  assets/src/components/kubernetes/discovery/Service.tsx
  assets/src/components/kubernetes/workloads/CronJob.tsx
  assets/src/components/kubernetes/workloads/DaemonSet.tsx
  assets/src/components/kubernetes/workloads/Deployment.tsx
  assets/src/components/kubernetes/workloads/Job.tsx
  assets/src/components/kubernetes/workloads/Pod.tsx
  assets/src/components/kubernetes/workloads/Pods.tsx
  assets/src/components/kubernetes/workloads/ReplicaSet.tsx
  assets/src/components/kubernetes/workloads/ReplicaSets.tsx
  assets/src/components/kubernetes/workloads/ReplicationControllers.tsx
  assets/src/components/kubernetes/workloads/StatefulSets.tsx
  assets/src/components/kubernetes/workloads/utils.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/graph-kubernetes/common/fragments.graphql
  assets/src/graph-kubernetes/workloads/pod_fragments.graphql
  assets/src/routes/kubernetesRoute.tsx
  assets/src/routes/kubernetesRoutesConsts.tsx
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.32.tgz
  charts/console/charts/kas-0.0.6.tgz
  charts/console/charts/kubernetes-dashboard-7.3.1.tgz
  charts/console/charts/kubernetes-dashboard-7.3.2.tgz
  plural/helm/console/Chart.lock
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/controller-0.0.32.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.3.1.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.3.2.tgz
Labels: enhancement

#844 Fix reconciliation bug w/ templated global services
  lib/console/deployments/global.ex
  lib/console/schema/global_service.ex
  lib/console/schema/managed_namespace.ex
  lib/console/schema/service.ex
  test/console/deployments/global_test.exs
  test/support/factory.ex
Labels: enhancement

#845 Fix reconciliation logic for managed namespace
  lib/console/deployments/global.ex
  test/console/deployments/global_test.exs
Labels: enhancement, hotfix

#846 feat: add unit tests
  controller/internal/controller/cluster_controller_test.go
  controller/internal/controller/globalservice_test.go
  controller/internal/test/common/kubernetes.go
Labels: enhancement

#849 docs: generate docs from the CRDs
  controller/Makefile
  controller/config.yaml
  controller/docs/api.md
  controller/go.mod
  controller/go.sum
  controller/tools.go
Labels: documentation, enhancement

#850 Fix dashboard rendering cert-manager
  .github/workflows/helm.yaml
  charts/console/values.yaml
  lib/console/deployments/events.ex
  lib/console/deployments/pipelines.ex
  lib/console/deployments/pubsub/recurse.ex
  plural/helm/console/Chart.yaml
  plural/helm/console/values.yaml
  test/console/deployments/pubsub/recurse_test.exs
Labels: bug-fix, hotfix

#851 Tweak pipeline promotion logic a bit more
  lib/console/deployments/clusters.ex
  lib/console/deployments/pipelines.ex
  lib/console/schema/pipeline_promotion.ex
  lib/console/services/base.ex
  priv/repo/migrations/20240416204627_add_promoted_revision.exs
  test/console/deployments/clusters_test.exs
Labels: enhancement

#854 add pipeline name to job breadcrumbs
  assets/src/components/cd/pipelines/job/PipelineJob.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdPipelines.graphql
  lib/console/graphql/deployments/pipeline.ex
  schema/schema.graphql
Labels: enhancement, frontend

#855 Bump agent and cli
  AGENT_VERSION
  Dockerfile
Labels: enhancement, hotfix

#856 Another fix for pipeline logic
  lib/console.ex
  lib/console/deployments/pipelines.ex
  lib/console/graphql/resolvers/deployments/service.ex
  lib/console/schema/revision.ex
  lib/console/services/base.ex
  priv/notifications/slack/cluster.create.json.eex
  priv/notifications/slack/pipeline.update.json.eex
  priv/notifications/slack/pr.close.json.eex
  priv/notifications/slack/service.update.json.eex
  priv/notifications/slack/stack.run.json.eex
Labels: enhancement

#858 fix(controller): existence checks now return error instead of false
  controller/internal/client/cluster.go
  controller/internal/client/console.go
  controller/internal/client/pipeline.go
  controller/internal/client/prautomation.go
  controller/internal/client/provider.go
  controller/internal/client/restore.go
  controller/internal/client/scmconnection.go
  controller/internal/controller/cluster_controller.go
  controller/internal/controller/cluster_controller_test.go
  controller/internal/controller/clusterrestore_controller.go
  controller/internal/controller/clusterrestore_controller_test.go
  controller/internal/controller/pipeline_controller.go
  controller/internal/controller/pipeline_controller_test.go
  controller/internal/controller/prautomation_controller.go
  controller/internal/controller/prautomation_controller_test.go
  controller/internal/controller/provider_controller.go
  controller/internal/controller/provider_controller_test.go
  controller/internal/controller/scmconnection_controller.go
  controller/internal/test/mocks/ConsoleClient_mock.go
Labels: bug-fix

#862 feat: Allow specifying display name for pinned CRDs
  assets/src/components/kubernetes/Cluster.tsx
  assets/src/components/kubernetes/Navigation.tsx
  assets/src/components/kubernetes/customresources/CustomResourceDefinitions.tsx
  assets/src/components/kubernetes/customresources/PinCustomResourceDefinition.tsx
  assets/src/components/kubernetes/customresources/PinCustomResourceDefinitionModal.tsx
  assets/src/components/kubernetes/customresources/PinnedCustomResourceDefinitions.tsx
Labels: enhancement

#864 Use old agent version until plural cd install is fixed
  Dockerfile
Labels: bug-fix, hotfix

#863 show cluster metadata when available
  assets/src/components/cd/cluster/ClusterMetadata.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
Labels: enhancement, frontend

#860 Add ability to backfill cluster upgrade plans hourly
  Dockerfile
  KUBE_VERSION
  assets/src/generated/graphql.ts
  config/prod.exs
  lib/console/commands/command.ex
  lib/console/commands/plural.ex
  lib/console/deployments/clusters.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/global.ex
  lib/console/deployments/init.ex
  lib/console/deployments/pr/dispatcher.ex
  lib/console/deployments/settings.ex
  lib/console/external_graphql.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/middleware/error_handler.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/schema/cluster.ex
  schema/schema.graphql
  static/compatibilities/source-controller.yaml
  test/console/deployments/clusters_test.exs
  test/console/deployments/global_test.exs
  test/console/graphql/queries/deployments/cluster_queries_test.exs
Labels: enhancement

#867 feat: use nginx sidecar to allow exposing grpc agent server on a subpath
  plural/helm/kas/Chart.yaml
  plural/helm/kas/templates/configmap.yaml
  plural/helm/kas/templates/deployment.yaml
  plural/helm/kas/templates/ingress.yaml
  plural/helm/kas/templates/service.yaml
  plural/helm/kas/values.yaml
Labels: enhancement

#868 Support nginx rewrite on plain ingress
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.35.tgz
  charts/console/charts/kas-0.0.6.tgz
  charts/console/charts/kas-0.1.0.tgz
  charts/console/templates/ingress.yaml
  charts/console/values.yaml
Labels: enhancement

#871 Fix error handling for query cast errors
  lib/console/graphql/exceptions/protocol.ex
  lib/console/graphql/middleware/safe_resolution.ex
Labels: bug-fix, hotfix

#873 Fix helm chart bug
  charts/console/Chart.yaml
  charts/console/templates/ingress.yaml
Labels: bug-fix, hotfix

#875 Add observability provider CRUD
  assets/src/generated/graphql.ts
  lib/console/deployments/observability.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/observability.ex
  lib/console/graphql/resolvers/deployments/observability.ex
  lib/console/schema/observability_provider.ex
  priv/repo/migrations/20240423003326_add_observability_providers.exs
  schema/schema.graphql
  test/console/deployments/observability_test.exs
  test/console/graphql/mutations/deployments/observability_mutations_test.exs
  test/console/graphql/queries/deployments/observability_queries_test.exs
  test/support/factory.ex
Labels: enhancement

#876 Fix myriad stack bugs
  assets/src/generated/graphql.ts
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/schema/gates/job_spec.ex
  lib/console/schema/stack_environment.ex
  lib/console/schema/stack_file.ex
  lib/console/schema/stack_state.ex
  schema/schema.graphql
  test/console/graphql/mutations/deployments/stack_mutations_test.exs
Labels: enhancement

#877 Fix stack secret persistence
  lib/console/schema/stack_environment.ex
Labels: enhancement

#878 leave role columns empty when there is no role on PR automation table
  assets/src/components/pr/automations/PrAutomationsColumns.tsx
Labels: enhancement, frontend

#881 use design system tag multi select in cluster filter
  assets/package.json
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/cd/services/ClusterTagsFilter.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#874 Remove rewrite ingress by default
  charts/console/Chart.yaml
  charts/console/templates/deployment.yaml
  charts/console/templates/migration.yaml
  charts/console/values.yaml
  charts/controller/Chart.yaml
  charts/controller/templates/deployment.yaml
  charts/controller/values.yaml
Labels: enhancement

#882 Need to actually run streams in crons
  lib/console/deployments/cron.ex
  lib/console/schema/stack_file.ex
  test/console/deployments/cron_test.exs
Labels: bug-fix

#880 Implement api-level service dependencies
  assets/src/generated/graphql.ts
  lib/console/deployments/services.ex
  lib/console/graphql/deployments/service.ex
  lib/console/schema/service.ex
  lib/console/schema/service_dependency.ex
  lib/console_web/controllers/git_controller.ex
  priv/repo/migrations/20240423154912_add_service_dependencies.exs
  schema/schema.graphql
  test/console/deployments/services_test.exs
  test/console_web/controllers/git_controller_test.exs
  test/support/factory.ex
Labels: enhancement

#869 Add support for git repositories as a helm chart source.
  assets/src/generated/graphql.ts
  lib/console/deployments/services.ex
  lib/console/graphql/deployments/service.ex
  lib/console/schema/service.ex
  schema/schema.graphql
Labels: enhancement

#884 Add cluster to policy constraint
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/policy.ex
  schema/schema.graphql
Labels: enhancement, hotfix

#883 Auto-cancellation of stack runs
  assets/src/generated/graphql.ts
  config/prod.exs
  lib/console/application.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/git/agent.ex
  lib/console/deployments/metrics/provider.ex
  lib/console/deployments/metrics/provider/datadog.ex
  lib/console/deployments/pubsub/recurse.ex
  lib/console/deployments/stacks.ex
  lib/console/deployments/stacks/discovery.ex
  lib/console/deployments/stacks/supervisor.ex
  lib/console/deployments/stacks/worker.ex
  lib/console/graphql/deployments/observability.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/schema/observable_metric.ex
  lib/console/schema/stack.ex
  lib/console/schema/stack_run.ex
  priv/repo/migrations/20240424202548_observable_metrics.exs
  schema/schema.graphql
  test/console/deployments/stacks/worker_test.exs
  test/support/factory.ex
Labels: enhancement

#861 feat: add infrastructure stack
  charts/controller/crds/deployments.plural.sh_infrastructurestacks.yaml
  charts/controller/templates/manager-rbac.yaml
  controller/Makefile
  controller/PROJECT
  controller/api/v1alpha1/infrastructurestack_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_infrastructurestacks.yaml
  controller/config/rbac/infrastructurestack_editor_role.yaml
  controller/config/rbac/infrastructurestack_viewer_role.yaml
  controller/config/rbac/role.yaml
  controller/config/samples/deployments_v1alpha1_infrastructurestack.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/client/console.go
  controller/internal/client/stack.go
  controller/internal/controller/infrastructurestack_controller.go
  controller/internal/controller/infrastructurestack_scope.go
  controller/internal/controller/infrastructurestack_test.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_infrastructurestacks.yaml
Labels: enhancement

#885 Add release name to helm spec
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/service.ex
  lib/console/schema/service.ex
  schema/schema.graphql
Labels: enhancement, hotfix

#887 Sync service dependencies in global services
  assets/src/generated/graphql.ts
  lib/console/deployments/global.ex
  lib/console/deployments/services.ex
  lib/console/graphql/deployments/global.ex
  lib/console/schema/global_service.ex
  lib/console/schema/managed_namespace.ex
  lib/console/schema/service_dependency.ex
  lib/console/schema/service_template.ex
  priv/repo/migrations/20240425230757_dependency_template.exs
  schema/schema.graphql
  test/console/deployments/global_test.exs
Labels: enhancement, hotfix

#890 feat: allow manage dependencies from the API
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  controller/api/v1alpha1/managednamespace_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/controller/common.go
  controller/internal/controller/servicedeployment_controller.go
  controller/internal/controller/servicedeployment_controller_test.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
Labels: enhancement

#886 implement new upgrade plan designs
  assets/src/components/cd/clusters/ClusterUpgrade.tsx
  assets/src/components/cd/clusters/ClusterUpgradeFlyover.tsx
  assets/src/components/cd/clusters/ClustersColumns.tsx
  assets/src/components/cd/clusters/runtime/RuntimeServices.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
Labels: enhancement, frontend

#892 display service dependencies in service details
  assets/src/components/apps/app/App.tsx
  assets/src/components/cd/services/ServiceDependenciesColumns.tsx
  assets/src/components/cd/services/service/ServiceDependencies.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/utils/FractionalChip.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdServices.graphql
  assets/src/routes/cdRoutes.tsx
Labels: enhancement, frontend

#893 Support Helm Release in ServiceDeployment crd
  AGENT_VERSION
  assets/src/components/cd/clusters/ClusterUpgradeFlyover.tsx
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  controller/api/v1alpha1/servicedeployment_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  controller/docs/api.md
  controller/internal/controller/servicedeployment_controller.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
Labels: enhancement, hotfix

#894 Implement newrelic poller
  .tool-versions
  Dockerfile
  config/config.exs
  config/dev.exs
  config/prod.exs
  config/test.exs
  lib/console/deployments/metrics/provider.ex
  lib/console/deployments/metrics/provider/new_relic.ex
  lib/console/schema/observability_provider.ex
  mix.exs
  mix.lock
  test/console/deployments/git_test.exs
  test/console/deployments/stacks/worker_test.exs
Labels: enhancement

#896 Add empty states for cluster flyover accordions
  assets/package.json
  assets/src/components/cd/clusters/ClusterUpgradeFlyover.tsx
  assets/yarn.lock
Labels: enhancement, hotfix

#895 Stack Pull Request workflow
  assets/src/generated/graphql.ts
  lib/console.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/git.ex
  lib/console/deployments/pipelines.ex
  lib/console/deployments/pr/impl/github.ex
  lib/console/deployments/pr/impl/gitlab.ex
  lib/console/deployments/pr/utils.ex
  lib/console/deployments/pubsub/recurse.ex
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  lib/console/schema/pull_request.ex
  lib/console/schema/stack.ex
  lib/console/schema/stack_run.ex
  lib/console_web/controllers/webhook_controller.ex
  priv/repo/migrations/20240427164952_add_pull_request_stack.exs
  schema/schema.graphql
  test/console/deployments/stacks_test.exs
  test/console/graphql/queries/deployments/stack_queries_test.exs
  test/console_web/controllers/webhook_controller_test.exs
Labels: enhancement

#898 Add errored filter for services
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments/git.ex
  lib/console/graphql/resolvers/deployments/service.ex
  lib/console/schema/pull_request.ex
  lib/console/schema/service.ex
  schema/schema.graphql
Labels: enhancement

#899 Kubernetes dashboard tab renaming
  assets/src/components/kubernetes/Navigation.tsx
  assets/src/components/kubernetes/network/Ingress.tsx
  assets/src/components/kubernetes/network/IngressClass.tsx
  assets/src/components/kubernetes/network/IngressClasses.tsx
  assets/src/components/kubernetes/network/Ingresses.tsx
  assets/src/components/kubernetes/network/Network.tsx
  assets/src/components/kubernetes/network/NetworkPolicies.tsx
  assets/src/components/kubernetes/network/NetworkPolicy.tsx
  assets/src/components/kubernetes/network/Service.tsx
  assets/src/components/kubernetes/network/Services.tsx
  assets/src/components/kubernetes/network/utils.tsx
  assets/src/components/kubernetes/rbac/ClusterRole.tsx
  assets/src/components/kubernetes/rbac/ClusterRoleBinding.tsx
  assets/src/components/kubernetes/rbac/ClusterRoleBindings.tsx
  assets/src/components/kubernetes/rbac/ClusterRoles.tsx
  assets/src/components/kubernetes/rbac/Rbac.tsx
  assets/src/components/kubernetes/rbac/Role.tsx
  assets/src/components/kubernetes/rbac/RoleBinding.tsx
  assets/src/components/kubernetes/rbac/RoleBindings.tsx
  assets/src/components/kubernetes/rbac/Roles.tsx
  assets/src/components/kubernetes/rbac/ServiceAccount.tsx
  assets/src/components/kubernetes/rbac/ServiceAccounts.tsx
  assets/src/components/kubernetes/workloads/DaemonSet.tsx
  assets/src/components/kubernetes/workloads/ReplicaSet.tsx
  assets/src/components/kubernetes/workloads/ReplicationController.tsx
  assets/src/routes/kubernetesRoute.tsx
  assets/src/routes/kubernetesRoutesConsts.tsx
Labels: enhancement, frontend

#900 Expose expected agent version so cli + terraform can use it precisely
  AGENT_VERSION
  assets/src/generated/graphql.ts
  lib/console/deployments/settings.ex
  lib/console/graphql/deployments.ex
  lib/console/schema/pull_request.ex
  schema/schema.graphql
Labels: enhancement, hotfix

#902 fix dev mode console warnings
  assets/src/components/cd/pipelines/nodes/ApprovalNode.tsx
  assets/src/components/cd/pipelines/nodes/StageNode.tsx
  assets/src/components/utils/SplitPane.tsx
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/pipelineRoutes.tsx
Labels: bug-fix, frontend

#903 Expose expected agent version so cli + terraform can use it precisely
  AGENT_VERSION
  lib/console/graphql/schema/custom_types.ex
Labels: enhancement, hotfix
