Repository pluralsh/console, pull requests merged in 2024-05, with the labels that each got.

#906 Need to add user dataloader to ext gql api
  assets/src/components/cd/clusters/ClustersColumns.tsx
  lib/console/deployments/stacks.ex
  lib/console/external_graphql.ex
Labels: enhancement, hotfix

#908 Add Pod Logs view to k8s dashboard
  assets/src/components/cd/cluster/ClusterNodes.tsx
  assets/src/components/cluster/nodes/ClusterGauges.tsx
  assets/src/components/cluster/nodes/ClusterMetrics.tsx
  assets/src/components/kubernetes/workloads/Pod.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql.ts
  assets/src/graph-kubernetes/workloads/pod.graphql
  assets/src/graph-kubernetes/workloads/pod_fragments.graphql
  assets/src/routes/kubernetesRoute.tsx
  lib/console/graphql/deployments/policy.ex
  lib/console/graphql/resolvers/deployments/policy.ex
  lib/console/schema/policy_constraint.ex
  schema/schema.graphql
Labels: enhancement

#907 added indicator to service sync button
  assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
  assets/src/components/cd/services/service/ServiceKick.tsx
  assets/src/components/hooks/useSyncCooldown.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdServices.graphql
Labels: enhancement, frontend

#910 Begin working on native helm repository client
  assets/src/generated/graphql.ts
  lib/console/application.ex
  lib/console/deployments/compatibilities/table.ex
  lib/console/deployments/git.ex
  lib/console/deployments/helm/agent.ex
  lib/console/deployments/helm/agent_cache.ex
  lib/console/deployments/helm/cache.ex
  lib/console/deployments/helm/discovery.ex
  lib/console/deployments/helm/supervisor.ex
  lib/console/deployments/helm/utils.ex
  lib/console/deployments/services.ex
  lib/console/deployments/tar.ex
  lib/console/graphql/deployments/policy.ex
  lib/console/graphql/deployments/service.ex
  lib/console/schema/helm_repository.ex
  lib/console/schema/policy_constraint.ex
  lib/console/schema/revision.ex
  lib/console/schema/service.ex
  lib/helm/client.ex
  lib/helm/schema.ex
  priv/repo/migrations/20240502133731_add_helm_repositories.exs
  schema/schema.graphql
  test/console/deployments/helm/agent_test.exs
  test/console/deployments/services_test.exs
Labels: enhancement

#911 Better fk constraint error messages
  lib/console/deployments/clusters.ex
  lib/console/graphql/exceptions/protocol.ex
  lib/console/graphql/middleware/error_handler.ex
  lib/console/schema/cluster.ex
  lib/console/schema/service.ex
  priv/repo/migrations/20240503234630_nilify_owner_id.exs
  test/console/deployments/clusters_test.exs
  test/console/deployments/global_test.exs
Labels: enhancement, hotfix

#912 fix owner id
  assets/src/generated/graphql.ts
  lib/console/deployments/global.ex
  lib/console/graphql/deployments/global.ex
  lib/console/schema/global_service.ex
  priv/repo/migrations/20240503234630_nilify_owner_id.exs
  schema/schema.graphql
Labels: enhancement, hotfix

#913 Add reparent field to global service controller
  Dockerfile
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  controller/api/v1alpha1/globalservice_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/controller/globalservice_controller.go
  lib/console/deployments/git.ex
  lib/console/deployments/git/agent.ex
  lib/console/deployments/git/cache.ex
  lib/console/deployments/global.ex
  lib/console/graphql/deployments/global.ex
  lib/console/graphql/deployments/service.ex
  lib/console/schema/cluster.ex
  lib/console/schema/git_repository.ex
  lib/console/schema/global_service.ex
  lib/console/schema/managed_namespace.ex
  lib/console/schema/service.ex
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  priv/repo/migrations/20240504150952_add_global_service_cascade.exs
  schema/schema.graphql
  test/console/deployments/git/agent_test.exs
  test/console/deployments/global_test.exs
Labels: enhancement, hotfix

#914 Add cascade + service.git.files support in operator
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_infrastructurestacks.yaml
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  controller/api/v1alpha1/common_types.go
  controller/api/v1alpha1/globalservice_types.go
  controller/api/v1alpha1/managednamespace_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  controller/config/crd/bases/deployments.plural.sh_infrastructurestacks.yaml
  controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  controller/docs/api.md
  controller/go.mod
  controller/go.sum
  controller/internal/controller/common.go
  controller/internal/controller/globalservice_controller.go
  controller/internal/controller/managednamespace_controller.go
  controller/internal/controller/servicedeployment_controller.go
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  plural/helm/console/crds/deployments.plural.sh_infrastructurestacks.yaml
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
Labels: enhancement, hotfix

#916 Fix detach in crd typing
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  controller/api/v1alpha1/globalservice_types.go
  controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  controller/docs/api.md
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
Labels: enhancement, hotfix

#918 Implement `helm.repositoryRef` in controller
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  controller/api/v1alpha1/servicedeployment_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  controller/docs/api.md
  controller/internal/controller/servicedeployment_controller.go
  lib/console.ex
  lib/console/deployments/events.ex
  lib/console/deployments/git.ex
  lib/console/deployments/git/agent.ex
  lib/console/deployments/git/cache.ex
  lib/console/deployments/git/cmd.ex
  lib/console/deployments/git/discovery.ex
  lib/console/deployments/pipelines/stage_worker.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/deployments/pubsub/rtc.ex
  lib/console/deployments/stacks.ex
  lib/console/graphql.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments/git.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  lib/console/graphql/topic.ex
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
  schema/schema.graphql
  test/console/deployments/cron_test.exs
  test/console/deployments/pubsub/recurse_test.exs
  test/console/deployments/stacks_test.exs
  test/console/graphql/mutations/deployments/git_mutations_test.exs
  test/console_web/channels/graphql/deployment_subscriptions_test.exs
  test/support/factory.ex
Labels: enhancement

#919 Fix stack state persistence bug
  assets/src/generated/graphql.ts
  lib/console/deployments/cron.ex
  lib/console/deployments/git/cache.ex
  lib/console/deployments/git/cmd.ex
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments/policy.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments/policy.ex
  lib/console/schema/stack.ex
  lib/console/schema/stack_run.ex
  lib/console/schema/stack_state.ex
  priv/repo/migrations/20240506193611_add_run_message.exs
  schema/schema.graphql
  test/console/deployments/cron_test.exs
  test/console/deployments/pubsub/recurse_test.exs
  test/console/deployments/stacks_test.exs
Labels: enhancement

#920 added home screen
  assets/package.json
  assets/src/components/apps/Apps.tsx
  assets/src/components/cd/clusters/ClusterUpgradeFlyover.tsx
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/cd/clusters/ClustersColumns.tsx
  assets/src/components/cd/pipelines/PipelinePullRequests.tsx
  assets/src/components/cd/pipelines/Pipelines.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/services/ServicesTable.tsx
  assets/src/components/cd/utils/useFetchPaginatedData.tsx
  assets/src/components/home/Home.tsx
  assets/src/components/home/HomeCard.tsx
  assets/src/components/home/MonthlyClusterCostsCard.tsx
  assets/src/components/home/clusteroverview/ClusterOverviewCard.tsx
  assets/src/components/home/clusteroverview/ClusterOverviewChart.tsx
  assets/src/components/home/clusteroverview/ClusterOverviewTable.tsx
  assets/src/components/home/clusteroverview/CustomLegend.tsx
  assets/src/components/home/deployments/DeploymentsCard.tsx
  assets/src/components/home/deployments/DeploymentsTable.tsx
  assets/src/components/home/pullrequests/PrCard.tsx
  assets/src/components/home/pullrequests/PrTable.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/pr/queue/PrQueue.tsx
  assets/src/components/pr/queue/PrQueueColumns.tsx
  assets/src/components/utils/RadialBarChart.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdPrs.graphql
  assets/src/graph/home.graphql
  assets/src/routes/consoleRoutes.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#921 added pre-formatted code block for service errors
  assets/src/components/cd/services/service/ServiceErrors.tsx
Labels: enhancement, frontend

#923 Move stack_state_resource.configuration to map type
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/stack.ex
  schema/schema.graphql
Labels: enhancement

#925 Move stack_state_resource.configuration to map type
  assets/src/generated/graphql.ts
  lib/console/deployments/stacks/commands.ex
  lib/console/schema/run_step.ex
  lib/console/schema/stack.ex
  lib/console/schema/stack_state.ex
  schema/schema.graphql
Labels: enhancement

#929 fix: pod shell id missing colon
  assets/src/components/cluster/containers/ContainerShell.tsx
Labels: bug-fix, frontend

#928 Add support for querying cluster scope in policy constraints
  AGENT_VERSION
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  controller/api/v1alpha1/servicedeployment_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  controller/internal/controller/servicedeployment_controller_test.go
  lib/console/graphql/resolvers/deployments/policy.ex
  lib/console/schema/policy_constraint.ex
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
  test/console/deployments/git/agent_test.exs
Labels: enhancement, hotfix

#930 Add group, version, kind to kubernetes unstructured
  assets/src/generated/graphql.ts
  lib/console/graphql/kubernetes.ex
  schema/schema.graphql
Labels: enhancement, hotfix

#931 Add homepage persona settings
  assets/src/components/account/personas/PersonaAttributesEdit.tsx
  assets/src/components/account/personas/PersonaCreate.tsx
  assets/src/generated/graphql.ts
  lib/console/deployments/cron.ex
  lib/console/deployments/global.ex
  lib/console/deployments/services.ex
  lib/console/graphql/kubernetes.ex
  lib/console/graphql/users.ex
  lib/console/schema/persona.ex
  schema/schema.graphql
Labels: enhancement

#932 fix: Fix node limits display
  assets/src/components/cd/services/ServicesTable.tsx
  assets/src/components/home/HomeCard.tsx
  assets/src/components/home/clusteroverview/ClusterOverviewCard.tsx
  assets/src/components/home/deployments/DeploymentsCard.tsx
  assets/src/components/home/pullrequests/PrCard.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/graph-kubernetes/cluster/node.graphql
  assets/src/graph-kubernetes/common/fragments.graphql
Labels: bug-fix

#936 Fix git log
  lib/console/deployments/git/cmd.ex
Labels: enhancement

#934 chore: Update k8s/dashboard chart version, schema and pod list table
  assets/schema/kubernetes-schema.graphql
  assets/src/components/kubernetes/workloads/Pods.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/graph-kubernetes/workloads/pod_fragments.graphql
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.42.tgz
  charts/console/charts/kas-0.1.0.tgz
  charts/console/charts/kubernetes-dashboard-7.3.2.tgz
  charts/console/charts/kubernetes-dashboard-7.4.0.tgz
  plural/helm/console/Chart.lock
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/controller-0.0.42.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.3.2.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.4.0.tgz
Labels: dependencies

#937 Add newrelic credentials input to gql
  assets/src/generated/graphql.ts
  lib/console/deployments/cron.ex
  lib/console/graphql/deployments/observability.ex
  schema/schema.graphql
Labels: enhancement, hotfix

#905 policy management global view
  assets/package.json
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/policies/Policies.tsx
  assets/src/components/policies/PoliciesColumns.tsx
  assets/src/components/policies/PoliciesFilter.tsx
  assets/src/components/policies/PoliciesTable.tsx
  assets/src/components/policies/PoliciesViolationsGauge.tsx
  assets/src/components/policies/policy/Policy.tsx
  assets/src/components/policies/policy/affectedResources/PolicyAffectedResources.tsx
  assets/src/components/policies/policy/affectedResources/ViolationsTableColumns.tsx
  assets/src/components/policies/policy/details/PolicyDetails.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/policies.graphql
  assets/src/routes/consoleRoutes.tsx
  assets/src/routes/policiesRoutes.tsx
  assets/src/routes/policiesRoutesConsts.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#938 added actions to PR table
  assets/src/components/pr/queue/DeletePr.tsx
  assets/src/components/pr/queue/PrQueueColumns.tsx
  assets/src/components/pr/queue/PrSettings.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdPrs.graphql
Labels: enhancement, frontend

#942 fix cluster deletion
  controller/internal/controller/cluster_controller.go
Labels: bug-fix

#939 Better description/recommendation empty state
  assets/src/components/policies/policy/details/PolicyDetails.tsx
  lib/console/deployments/global.ex
Labels: enhancement

#940 add deletion action to global services table
  assets/src/components/cd/YamlGeneratorModal.tsx
  assets/src/components/cd/globalServices/DeleteGlobalService.tsx
  assets/src/components/cd/globalServices/GlobalService.tsx
  assets/src/components/cd/globalServices/GlobalServiceDetailTable.tsx
  assets/src/components/cd/globalServices/GlobalServicesColumns.tsx
  assets/src/components/cd/globalServices/GlobalServicesTable.tsx
  assets/src/components/cd/namespaces/Namespaces.tsx
  assets/src/components/cd/namespaces/NamespacesDetailTable.tsx
  assets/src/components/cd/namespaces/NamespacesTable.tsx
  assets/src/components/cd/pipelines/Pipelines.tsx
  assets/src/routes/cdRoutes.tsx
Labels: enhancement, frontend

#927 Reneboaventura/eng 1993 observability provider UI
  assets/package.json
  assets/src/components/cd/globalSettings/GlobalSettings.tsx
  assets/src/components/cd/globalSettings/observability/EditObservabilityProvider.tsx
  assets/src/components/cd/globalSettings/observability/ObservabilityProviderSelect.tsx
  assets/src/components/cd/globalSettings/observability/ObservabilityProviders.tsx
  assets/src/components/cd/globalSettings/observability/ObservabilityProvidersColumns.tsx
  assets/src/components/cd/globalSettings/observability/ObservabilitySettings.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdGlobalSettings.graphql
  assets/src/routes/cdRoutes.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#945 console bug fixes and cleanup
  assets/src/components/backups/cluster/backups/Backups.tsx
  assets/src/components/backups/cluster/restores/Restores.tsx
  assets/src/components/backups/clusters/Clusters.tsx
  assets/src/components/backups/objectstores/ObjectStores.tsx
  assets/src/components/cd/utils/useFetchPaginatedData.tsx
  assets/src/components/kubernetes/workloads/utils.tsx
  assets/src/components/notifications/routers/NotificationRouters.tsx
  assets/src/components/notifications/sinks/NotificationSinks.tsx
  assets/src/components/policies/Policies.tsx
  assets/src/components/policies/PoliciesTable.tsx
  assets/src/components/pr/automations/PrAutomations.tsx
  assets/src/components/pr/scm/PrScmConnections.tsx
  assets/src/components/pr/scm/ScmWebhooks.tsx
Labels: bug-fix, frontend

#946 show counts next to constraint multi-select options
  assets/src/components/policies/PoliciesFilter.tsx
Labels: enhancement, frontend

#943 Bump agent to 0.4.26
  AGENT_VERSION
  assets/src/generated/graphql.ts
  lib/console/deployments/global.ex
  lib/console/graphql/deployments/policy.ex
  lib/console/graphql/resolvers/deployments/policy.ex
  lib/console/schema/policy_constraint.ex
  lib/console/schema/service_template.ex
  schema/schema.graphql
  test/console/graphql/queries/deployments/policy_queries_test.exs
Labels: enhancement, hotfix

#947 feat: extend stack attributes for files and secret files
  charts/controller/crds/deployments.plural.sh_infrastructurestacks.yaml
  controller/api/v1alpha1/infrastructurestack_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_infrastructurestacks.yaml
  controller/config/samples/deployments_v1alpha1_infrastructurestack.yaml
  controller/internal/controller/infrastructurestack_controller.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  plural/helm/console/crds/deployments.plural.sh_infrastructurestacks.yaml
Labels: enhancement

#948 Stack runs didn't have messages for first run
  lib/console/deployments/git/cache.ex
  test/console/deployments/git/agent_test.exs
Labels: enhancement

#949 Handle byok clusters slightly better
  controller/internal/controller/cluster_controller.go
  controller/internal/controller/cluster_controller_test.go
  controller/internal/test/mocks/ConsoleClient_mock.go
Labels: enhancement

#950 Add support for searching stacks
  assets/src/components/layout/Sidebar.tsx
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  lib/console/schema/stack.ex
  schema/schema.graphql
Labels: enhancement, hotfix

#951 added skeleton loaders to home screen
  assets/src/components/home/clusteroverview/ClusterOverviewCard.tsx
  assets/src/components/home/clusteroverview/ClusterOverviewChart.tsx
  assets/src/components/home/clusteroverview/ClusterOverviewTable.tsx
  assets/src/components/home/deployments/DeploymentsCard.tsx
  assets/src/components/home/deployments/DeploymentsTable.tsx
  assets/src/components/home/pullrequests/PrCard.tsx
  assets/src/components/home/pullrequests/PrTable.tsx
  assets/src/components/utils/SkeletonLoaders.tsx
Labels: enhancement, frontend

#953 Fix bug in pr display on pipelines
  assets/src/components/pr/queue/PrQueueColumns.tsx
Labels: enhancement

#955 fix service deletion
  controller/internal/controller/servicedeployment_controller.go
Labels: bug-fix

#956 added more policy charts
  .vscode/settings.json
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/policies/Policies.tsx
  assets/src/components/policies/PoliciesViolationsGauge.tsx
  assets/src/components/policies/usePolicyChartsData.tsx
  assets/src/components/utils/PieChart.tsx
  assets/src/components/utils/SkeletonLoaders.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/policies.graphql
Labels: enhancement, frontend

#958 Add expanded state to sidebar
  assets/package.json
  assets/src/components/layout/NotificationsPanelOverlay.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#954 Post reviews with terraform plans for pr stack runs
  lib/console/deployments/global.ex
  lib/console/deployments/pr/dispatcher.ex
  lib/console/deployments/pr/impl/github.ex
  lib/console/deployments/pr/impl/gitlab.ex
  lib/console/deployments/pr/impl/pass.ex
  lib/console/deployments/pubsub/recurse.ex
  lib/console/deployments/services.ex
  lib/console/deployments/stacks.ex
  lib/console/schema/pull_request.ex
  priv/pr/failed.md.eex
  priv/pr/stack_summary.md.eex
  priv/repo/migrations/20240512161439_add_review_ids.exs
  test/console/deployments/stacks_test.exs
  test/support/factory.ex
  test/test_helper.exs
Labels: enhancement

#962 update policy page layout
  assets/src/components/policies/Policies.tsx
  assets/src/components/policies/PoliciesFilter.tsx
  assets/src/components/policies/PoliciesViolationsGauge.tsx
  assets/src/components/policies/usePolicyChartsData.tsx
  assets/src/routes/policiesRoutes.tsx
Labels: enhancement, frontend

#961 Reneboaventura/eng 2051 add cascade and reparent settings to global services view
  assets/src/components/cd/globalServices/GlobalServiceDetailTable.tsx
  assets/src/components/cd/globalServices/GlobalServiceDetailView.tsx
  assets/src/components/cd/globalServices/GlobalServiceSidecar.tsx
  assets/src/components/cd/namespaces/NamespaceSidecar.tsx
  assets/src/components/cd/namespaces/NamespacesDetailTable.tsx
  assets/src/components/cd/namespaces/NamespacesDetailView.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdGlobalServices.graphql
  assets/src/graph/cdNamespaces.graphql
Labels: enhancement, frontend

#964 fix installed clusters policy chart bug
  assets/src/components/policies/usePolicyChartsData.tsx
Labels: bug-fix, frontend

#963 Proper draining of attached global services on non-delete actions
  lib/console/deployments/global.ex
  lib/console/deployments/pubsub/recurse.ex
  lib/console/schema/global_service.ex
  lib/console/schema/service.ex
  test/console/deployments/global_test.exs
  test/console/deployments/pubsub/recurse_test.exs
  test/console/graphql/queries/deployments/policy_queries_test.exs
Labels: enhancement

#965 Default disable kas rewrite in OSS chart
  plural/helm/console/templates/ingress.yaml
  plural/helm/console/values.yaml
Labels: enhancement

#941 feat: Add stacks support to console
  assets/package.json
  assets/public/stacks/ansible.svg
  assets/public/stacks/terraform.svg
  assets/src/components/cd/utils/ClusterSelector.tsx
  assets/src/components/cluster/LabelsAnnotations.tsx
  assets/src/components/kubernetes/common/Conditions.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/profile/ObscuredToken.tsx
  assets/src/components/stacks/StackDelete.tsx
  assets/src/components/stacks/StackRun.tsx
  assets/src/components/stacks/StackRunStatusChip.tsx
  assets/src/components/stacks/StackRuns.tsx
  assets/src/components/stacks/StackStatusChip.tsx
  assets/src/components/stacks/StackTypeIcon.tsx
  assets/src/components/stacks/Stacks.tsx
  assets/src/components/stacks/configuration/StackConfiguration.tsx
  assets/src/components/stacks/create/CreateStack.tsx
  assets/src/components/stacks/create/CreateStackModal.tsx
  assets/src/components/stacks/create/CreateStackModalActions.tsx
  assets/src/components/stacks/create/CreateStackModalFormBasic.tsx
  assets/src/components/stacks/create/CreateStackModalFormEnvironment.tsx
  assets/src/components/stacks/create/CreateStackModalFormFiles.tsx
  assets/src/components/stacks/create/CreateStackModalFormJob.tsx
  assets/src/components/stacks/create/CreateStackModalFormRepository.tsx
  assets/src/components/stacks/environment/StackEnvironment.tsx
  assets/src/components/stacks/environment/StackEnvironmentApplyModal.tsx
  assets/src/components/stacks/environment/StackEnvironmentDelete.tsx
  assets/src/components/stacks/environment/StackEnvironmentEdit.tsx
  assets/src/components/stacks/job/StackJob.tsx
  assets/src/components/stacks/repository/StackRepository.tsx
  assets/src/components/stacks/run/Route.tsx
  assets/src/components/stacks/run/Sidecar.tsx
  assets/src/components/stacks/run/Sidenav.tsx
  assets/src/components/stacks/run/output/Output.tsx
  assets/src/components/stacks/run/output/Value.tsx
  assets/src/components/stacks/run/plan/Plan.tsx
  assets/src/components/stacks/run/progress/Progress.tsx
  assets/src/components/stacks/run/progress/Step.tsx
  assets/src/components/stacks/run/repository/Repository.tsx
  assets/src/components/stacks/run/state/State.tsx
  assets/src/components/utils/Confirm.tsx
  assets/src/components/utils/FileDrop.tsx
  assets/src/components/utils/UserInfo.tsx
  assets/src/components/utils/layout/ResponsiveLayoutContentContainer.tsx
  assets/src/components/utils/truncate.ts
  assets/src/generated/graphql.ts
  assets/src/graph/stacks.graphql
  assets/src/helpers/refreshToken.ts
  assets/src/routes/consoleRoutes.tsx
  assets/src/routes/stacksRoutes.tsx
  assets/src/routes/stacksRoutesConsts.tsx
  assets/yarn.lock
Labels: enhancement

#966 fix sidebar spacing
  assets/package.json
  assets/src/components/layout/Sidebar.tsx
  assets/yarn.lock
Labels: bug-fix, frontend

#968 fix cookie settings z-index
  assets/package.json
  assets/src/components/tracking/CookieSettings.tsx
  assets/yarn.lock
Labels: bug-fix, frontend

#969 tweak policy charts styles
  assets/src/components/policies/PoliciesViolationsGauge.tsx
  assets/src/components/utils/PieChart.tsx
Labels: enhancement, frontend

#967 remove info view from kubernetes cluster namespaces
  assets/src/components/kubernetes/cluster/Namespace.tsx
  assets/src/routes/kubernetesRoute.tsx
Labels: enhancement, frontend

#974 Add stack kick api
  assets/src/generated/graphql.ts
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  schema/schema.graphql
Labels: enhancement

#977 Add ability to specify stack hooks
  assets/src/components/stacks/StackRunStatusChip.tsx
  assets/src/generated/graphql.ts
  lib/console/deployments/git/agent.ex
  lib/console/deployments/git/cmd.ex
  lib/console/deployments/stacks.ex
  lib/console/deployments/stacks/commands.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/schema/stack.ex
  lib/console/schema/stack_run.ex
  lib/console/services/users.ex
  schema/schema.graphql
  test/console/deployments/stacks_test.exs
Labels: enhancement

#976 added kick and approve buttons to stack view
  assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
  assets/src/components/home/pullrequests/PrCard.tsx
  assets/src/components/stacks/Stacks.tsx
  assets/src/components/stacks/create/CreateStackModalFormFiles.tsx
  assets/src/components/stacks/run/Route.tsx
  assets/src/components/stacks/run/Sidecar.tsx
  assets/src/components/utils/KickButton.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/stacks.graphql
Labels: enhancement, frontend

#980 Add a restart run button
  assets/src/components/stacks/run/Sidecar.tsx
  assets/src/components/stacks/run/Sidenav.tsx
  assets/src/components/stacks/run/plan/Plan.tsx
  assets/src/components/stacks/run/progress/Progress.tsx
  assets/src/components/stacks/run/progress/Step.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/stacks.graphql
  lib/console/deployments/pubsub/protocols/notifiable.ex
Labels: enhancement, hotfix

#981 Add a restart run button
  assets/src/components/stacks/run/Sidecar.tsx
  assets/src/components/stacks/run/Sidenav.tsx
Labels: enhancement, hotfix

#983 Implement terraform http state remote backend
  assets/src/generated/graphql.ts
  lib/console.ex
  lib/console/deployments/policies/policies.ex
  lib/console/deployments/stacks/state.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/schema/stack.ex
  lib/console/schema/terraform_state.ex
  lib/console_web/controllers/stack_controller.ex
  lib/console_web/router.ex
  priv/repo/migrations/20240526120358_add_terraform_state.exs
  priv/repo/migrations/20240526201015_add_workdir.exs
  schema/schema.graphql
  test/console_web/controllers/stack_controller_test.exs
  test/support/factory.ex
Labels: enhancement, hotfix

#984 Backfill workdir/manage state in a few more places
  assets/src/generated/graphql.ts
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/schema/stack_run.ex
  priv/repo/migrations/20240526202656_add_workdir_to_runs.exs
  schema/schema.graphql
Labels: enhancement, hotfix

#986 fix recreate the stack
  controller/config/samples/deployments_v1alpha1_infrastructurestack.yaml
  controller/internal/controller/infrastructurestack_controller.go
Labels: bug-fix

#987 Use PENDING_APPROVAL state to control approve displays
  assets/src/components/stacks/StackRun.tsx
  assets/src/components/stacks/StackRunStatusChip.tsx
  assets/src/components/stacks/run/Sidecar.tsx
Labels: enhancement

#989 Requeue not found clusters
  controller/internal/controller/cluster_controller.go
Labels: enhancement

#990 Allow detach to be optional
  charts/controller/crds/deployments.plural.sh_infrastructurestacks.yaml
  controller/api/v1alpha1/infrastructurestack_types.go
  controller/config/crd/bases/deployments.plural.sh_infrastructurestacks.yaml
  controller/internal/controller/infrastructurestack_test.go
  plural/helm/console/crds/deployments.plural.sh_infrastructurestacks.yaml
Labels: enhancement

#991 Bump agent to 0.4.30
  AGENT_VERSION
Labels: enhancement, hotfix

#995 Fix prometheus port in OSS chart
  assets/src/components/builds/build/progress/CommandLog.tsx
  plural/helm/console/Chart.yaml
  plural/helm/console/templates/deployment.yaml
Labels: enhancement, hotfix

#993 Expose state urls and plural creds to agent for terraform setup
  assets/src/generated/graphql.ts
  lib/console/deployments/pubsub/recurse.ex
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  lib/console/schema/stack.ex
  lib/console/schema/stack_run.ex
  lib/console_web/plugs/token.ex
  priv/repo/migrations/20240527223318_add_stack_actor.exs
  schema/schema.graphql
  test/console/deployments/pubsub/recurse_test.exs
  test/console/graphql/queries/deployments/stack_queries_test.exs
Labels: enhancement, hotfix

#998 feat: use a batchv1.JobSpec for pipelinegate/stacks spec.jobSpec.raw
  charts/controller/crds/deployments.plural.sh_infrastructurestacks.yaml
  charts/controller/crds/deployments.plural.sh_pipelines.yaml
  controller/api/v1alpha1/pipeline_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_infrastructurestacks.yaml
  controller/config/crd/bases/deployments.plural.sh_pipelines.yaml
  controller/config/samples/deployments_v1alpha1_infrastructurestack.yaml
  controller/internal/controller/common.go
  controller/internal/controller/infrastructurestack_test.go
  plural/helm/console/crds/deployments.plural.sh_infrastructurestacks.yaml
  plural/helm/console/crds/deployments.plural.sh_pipelines.yaml
Labels: enhancement

#997 fix: Fixes and improvements for stacks UI
  assets/package.json
  assets/src/components/builds/build/progress/CommandLog.tsx
  assets/src/components/stacks/StackConfiguration.tsx
  assets/src/components/stacks/StackDelete.tsx
  assets/src/components/stacks/StackDetach.tsx
  assets/src/components/stacks/StackEnvironmentApplyModal.tsx
  assets/src/components/stacks/StackEnvironmentDelete.tsx
  assets/src/components/stacks/StackRepository.tsx
  assets/src/components/stacks/StackRunsEntry.tsx
  assets/src/components/stacks/Stacks.tsx
  assets/src/components/stacks/StacksEntry.tsx
  assets/src/components/stacks/delete/DeleteStack.tsx
  assets/src/components/stacks/run/Header.tsx
  assets/src/components/stacks/run/Route.tsx
  assets/src/components/stacks/run/Sidecar.tsx
  assets/src/components/stacks/run/progress/Step.tsx
  assets/src/components/stacks/run/repository/Repository.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/stacks.graphql
  assets/yarn.lock
Labels: bug-fix

#999 changed create cluster modal command suggestions
  assets/src/components/cd/clusters/create/CreateCluster.tsx
  assets/src/components/cd/clusters/create/NameVersionHandle.tsx
Labels: enhancement, frontend

#996 Implement the ability to trigger custom stack runs
  assets/src/components/stacks/run/Header.tsx
  assets/src/components/stacks/run/Route.tsx
  assets/src/components/stacks/run/job/RunJob.tsx
  assets/src/components/stacks/run/job/RunJobLogs.tsx
  assets/src/components/stacks/run/job/RunJobPods.tsx
  assets/src/components/stacks/run/job/RunJobSpecs.tsx
  assets/src/components/stacks/run/job/RunJobStatus.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/stacks.graphql
  assets/src/routes/stacksRoutes.tsx
  assets/src/routes/stacksRoutesConsts.tsx
  lib/console/deployments/policies/rbac.ex
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  lib/console/schema/custom_stack_run.ex
  lib/console/schema/stack_run.ex
  priv/repo/migrations/20240528200501_add_custom_stack_runs.exs
  schema/schema.graphql
  test/console/deployments/stacks_test.exs
  test/console/graphql/mutations/deployments/stack_mutations_test.exs
  test/support/factory.ex
Labels: enhancement, hotfix

#1000 Fixes for terraform state api
  lib/console/deployments/policies/policies.ex
  lib/console/deployments/stacks/state.ex
  lib/console/schema/terraform_state.ex
  lib/console_web/controllers/stack_controller.ex
  test/console_web/controllers/stack_controller_test.exs
Labels: bug-fix, hotfix

#1001 Add stack hook configuration to operator
  charts/controller/crds/deployments.plural.sh_infrastructurestacks.yaml
  controller/api/v1alpha1/infrastructurestack_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_infrastructurestacks.yaml
  controller/docs/api.md
  controller/internal/controller/infrastructurestack_controller.go
  plural/helm/console/crds/deployments.plural.sh_infrastructurestacks.yaml
Labels: enhancement

#1002 Add stack global configuration and service imports
  AGENT_VERSION
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/service.ex
  lib/console/schema/deployment_settings.ex
  lib/console/schema/service.ex
  lib/console/schema/service_import.ex
  priv/repo/migrations/20240531013353_add_deployment_settings_stacks.exs
  schema/schema.graphql
Labels: enhancement, hotfix
