Repository pluralsh/console, pull requests merged in 2024-10, with the labels that each got.

#1421 enhancement: Policies improvements
  assets/src/components/policies/Policies.tsx
  assets/src/components/policies/PoliciesFilter.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/policies.graphql
Labels: enhancement

#1429 feat: extend JobSpecFragment
  go/client/client.go
  go/client/graph/gates.graphql
Labels: enhancement

#1430 fix: Minor bug fixes on detected by cloud deprecations
  assets/src/components/cd/clusters/ClusterUpgradeFlyover.tsx
  assets/src/components/cd/clusters/UpgradeInsights.tsx
Labels: bug-fix

#1427 Auto-poll a stack pr on new events
  AGENT_VERSION
  charts/console/values.yaml
  lib/console/deployments/clusters.ex
  lib/console/deployments/pubsub/recurse.ex
  lib/console/deployments/stacks.ex
  lib/console/schema/service_template.ex
  test/console/deployments/stacks_test.exs
Labels: enhancement, hotfix

#1436 add upgrade insights client info and runtime services count
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/graphql/deployments/cluster.ex
  lib/console/schema/runtime_service.ex
  lib/console/schema/upgrade_insight_detail.ex
  priv/repo/migrations/20241003160915_insight_detail.exs
  schema/schema.graphql
Labels: enhancement

#1439 enhancement: Reduce spacing between icons in sidebar and add vertical
  assets/.yarnrc.yml
  assets/yarn.lock
Labels: enhancement

#1442 fix: bump design system to the latest version
  assets/package.json
  assets/yarn.lock
Labels: bug-fix

#1443 feat: Add bindings to Pipeline CRD
  charts/controller/crds/deployments.plural.sh_pipelines.yaml
  go/controller/api/v1alpha1/pipeline_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_pipelines.yaml
  go/controller/internal/controller/pipeline_controller.go
  go/controller/internal/controller/pipeline_controller_attributes.go
  go/controller/internal/controller/project_controller_test.go
  go/controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_pipelines.yaml
Labels: enhancement

#1440 Fix router filter logic
  AGENT_VERSION
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_observers.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/observer_types.go
  go/controller/config/crd/bases/deployments.plural.sh_observers.yaml
  go/controller/docs/api.md
  go/controller/internal/controller/globalservice_controller.go
  go/controller/internal/controller/globalservice_test.go
  go/controller/internal/controller/managednamespace_controller.go
  lib/console.ex
  lib/console/deployments/oauth.ex
  lib/console/deployments/pubsub/protocols/notifiable.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/oauth.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/oauth.ex
  lib/console/plural/accounts.ex
  lib/console/plural/models.ex
  lib/console/plural/queries.ex
  lib/console/schema/notification_router.ex
  lib/console/schema/router_filter.ex
  mix.exs
  mix.lock
  plural/helm/console/crds/deployments.plural.sh_observers.yaml
  priv/notifications/slack/pr.close.json.eex
  priv/notifications/slack/service.update.json.eex
  priv/notifications/slack/stack.run.json.eex
  schema/schema.graphql
  test/console/deployments/observer/runner_test.exs
  test/console/deployments/pubsub/notification_test.exs
  test/console/graphql/mutations/deployments/oauth_mutations_test.exs
Labels: enhancement

#1447 Only fail upgrade insights on `:failed` statuses
  lib/console/deployments/clusters.ex
Labels: enhancement

#1448 update DS
  assets/package.json
  assets/yarn.lock
Labels: bug-fix, frontend

#1450 feat(client): Add OIDC provider mutations
  go/client/client.go
  go/client/graph/oauth.graphql
Labels: enhancement

#1452 Add `auth_method` to oidc provider mutations/queries
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/deployments/oauth.ex
  lib/console/graphql/deployments/oauth.ex
  lib/console/plural/models.ex
  lib/console/plural/queries.ex
  schema/schema.graphql
Labels: enhancement, hotfix

#1456 feat(client): Add auth method to OIDC provider fragment
  go/client/client.go
  go/client/graph/oauth.graphql
Labels: enhancement

#1457 Fix console-side oidc queries
  lib/console/deployments/oauth.ex
Labels: enhancement

#1454 add email settings tab to profile
  assets/package.json
  assets/src/components/profile/EmailSettings.tsx
  assets/src/components/profile/MyProfile.tsx
  assets/src/components/profile/Profile.tsx
  assets/src/components/utils/typography/Text.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/users.graphql
  assets/src/routes/consoleRoutes.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#1459 fix secret sharing bugs
  assets/src/components/sharesecret/ConsumeSecret.tsx
  assets/src/components/sharesecret/ShareSecretModal.tsx
Labels: bug-fix, frontend

#1451 feat: Container statuses improvements
  assets/src/components/cd/cluster/pod/Pod.tsx
  assets/src/components/cd/cluster/pod/PodInfo.tsx
  assets/src/components/cd/cluster/pod/PodSidecar.tsx
  assets/src/components/cd/services/service/pod/Pod.tsx
  assets/src/components/cluster/TableElements.tsx
  assets/src/components/cluster/containers/ContainersList.tsx
  assets/src/components/cluster/pods/Pod.tsx
  assets/src/components/cluster/pods/PodInfo.tsx
  assets/src/components/cluster/pods/PodMetadata.tsx
  assets/src/components/cluster/pods/PodSidecar.tsx
  assets/src/utils/status.ts
Labels: enhancement

#1458 Prep 0.10.33 release
  AGENT_VERSION
  assets/.husky/pre-commit
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/deployments/oauth.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/deployments/pubsub/protocols/notifiable.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/kubernetes/daemon_set.ex
  lib/console/graphql/kubernetes/deployment.ex
  lib/console/graphql/kubernetes/service.ex
  lib/console/graphql/kubernetes/stateful_set.ex
  lib/console/schema/catalog.ex
  lib/console/schema/pr_automation.ex
  priv/repo/migrations/20241011004552_add_catalog_create_policy.exs
  priv/repo/migrations/20241011005841_add_icons.exs
  schema/schema.graphql
  test/console/deployments/git_test.exs
  test/console/deployments/pubsub/notification_test.exs
  test/support/factory.ex
Labels: enhancement

#1460 feat: Show client info for upgrade insights
  assets/src/components/cd/clusters/UpgradeInsights.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
Labels: enhancement

#1449 Catalog CRD support
  charts/controller/crds/deployments.plural.sh_catalogs.yaml
  go/client/client.go
  go/client/graph/catalog.graphql
  go/controller/PROJECT
  go/controller/api/v1alpha1/catalog_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_catalogs.yaml
  go/controller/config/rbac/catalog_editor_role.yaml
  go/controller/config/rbac/catalog_viewer_role.yaml
  go/controller/config/rbac/role.yaml
  go/controller/config/samples/deployments_v1alpha1_catalog.yaml
  go/controller/internal/client/catalog.go
  go/controller/internal/client/console.go
  go/controller/internal/controller/catalog_controller.go
  go/controller/internal/controller/catalog_controller_test.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  go/controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_catalogs.yaml
Labels: enhancement

#1463 add conditions tables to statefulset and deployment views
  assets/src/components/component/info/Deployment.tsx
  assets/src/components/component/info/StatefulSet.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/kubernetes/deployment.graphql
  assets/src/graph/kubernetes/statefulSet.graphql
Labels: enhancement, frontend

#1461 Last fixes before v0.10.33
  charts/controller/crds/deployments.plural.sh_catalogs.yaml
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  go/controller/api/v1alpha1/catalog_types.go
  go/controller/api/v1alpha1/prautomation_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_catalogs.yaml
  go/controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  go/controller/docs/api.md
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  lib/console/plural/queries.ex
  plural/helm/console/crds/deployments.plural.sh_catalogs.yaml
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
  priv/notifications/slack/service.update.json.eex
  priv/notifications/slack/stack.run.json.eex
Labels: enhancement

#1468 Implement pr confirmation schema fields
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/prautomation_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  go/controller/docs/api.md
  lib/console/graphql/deployments/git.ex
  lib/console/schema/pr_automation.ex
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
  priv/repo/migrations/20241013132733_pra_checklist.exs
  schema/schema.graphql
Labels: enhancement

#1469 extend service deployment with imports
  go/client/client.go
  go/client/graph/deployment.graphql
Labels: enhancement

#1470 feat: Add stack variables tab
  assets/src/components/stacks/Stacks.tsx
  assets/src/components/stacks/variables/StackVariables.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/stacks.graphql
  assets/src/routes/stacksRoutes.tsx
  assets/src/routes/stacksRoutesConsts.tsx
Labels: enhancement

#1471 add pr automation confirmation checklist UI
  assets/src/components/pr/automations/CreatePrModal.tsx
  assets/src/components/pr/automations/PrAutomationsColumns.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/automation.graphql
Labels: enhancement, frontend

#1472 Add ai provider configuration
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/graphql/deployments/settings.ex
  lib/console/schema/deployment_settings.ex
  lib/console/schema/pull_request.ex
  priv/notifications/plural/pr.close.json.eex
  priv/notifications/slack/pr.close.json.eex
  priv/repo/migrations/20241015165546_add_ai_settings.exs
  schema/schema.graphql
Labels: enhancement

#1475 feat: Add raw view to certificate on ingress page
  assets/src/components/component/ComponentDetails.tsx
  assets/src/components/component/info/Ingress.tsx
  assets/src/components/component/info/IngressCertificates.tsx
Labels: enhancement

#1473 add state filter to service components
  assets/package.json
  assets/src/components/apps/app/components/ComponentList.tsx
  assets/src/components/apps/app/components/Components.tsx
  assets/src/components/apps/app/components/misc.tsx
  assets/src/components/cd/services/service/ServiceComponents.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#1476 Implement AI insight generation machinery
  assets/src/generated/graphql.ts
  config/prod.exs
  go/client/models_gen.go
  lib/console.ex
  lib/console/ai/cron.ex
  lib/console/ai/evidence.ex
  lib/console/ai/evidence/base.ex
  lib/console/ai/evidence/component.ex
  lib/console/ai/evidence/component/cronjob.ex
  lib/console/ai/evidence/component/daemon_set.ex
  lib/console/ai/evidence/component/deployment.ex
  lib/console/ai/evidence/component/ingress.ex
  lib/console/ai/evidence/component/job.ex
  lib/console/ai/evidence/component/pod.ex
  lib/console/ai/evidence/component/resource.ex
  lib/console/ai/evidence/component/stateful_set.ex
  lib/console/ai/evidence/service.ex
  lib/console/ai/memoizer.ex
  lib/console/ai/provider.ex
  lib/console/ai/provider/openai.ex
  lib/console/ai/worker.ex
  lib/console/deployments/events.ex
  lib/console/deployments/notifications.ex
  lib/console/deployments/pubsub/protocols/notifiable.ex
  lib/console/deployments/services.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/deployments/settings.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/schema/ai_insight.ex
  lib/console/schema/deployment_settings.ex
  lib/console/schema/notification_router.ex
  lib/console/schema/service.ex
  lib/console/schema/service_component.ex
  lib/console/schema/stack.ex
  lib/console/schema/stack_run.ex
  priv/notifications/plural/service.insight.json.eex
  priv/notifications/slack/service.insight.json.eex
  priv/notifications/teams/service.insight.json.eex
  priv/repo/migrations/20241016003904_add_ai_service_insights.exs
  schema/schema.graphql
  test/console/ai/cron_test.exs
  test/console/deployments/pubsub/notification_test.exs
  test/support/factory.ex
  test/support/kubernetes_scaffolds.ex
  test/test_helper.exs
Labels: enhancement

#1479 feat: extend service deployment with ignoreHooks
  go/client/client.go
  go/client/graph/deployment.graphql
Labels: enhancement

#1480 feat: use cores/bytes as the base unit for component-level metrics
  assets/src/components/component/ComponentMetrics.tsx
  assets/src/utils/prometheus.ts
Labels: enhancement

#1481 feat: update gql schema: add ai settings to deployment settings
  assets/src/generated/graphql.ts
  go/client/client.go
  go/client/graph/models.graphql
  go/client/models_gen.go
  lib/console/graphql/deployments/settings.ex
  schema/schema.graphql
Labels: enhancement

#1482 deduplicate stack insight notifications
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/ai/memoizer.ex
  lib/console/ai/provider.ex
  lib/console/deployments/pubsub/protocols/notifiable.ex
  lib/console/external_graphql.ex
  lib/console/graphql.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/schema/ai_insight.ex
  lib/console_web/controllers/webhook_controller.ex
  lib/console_web/plugs/token.ex
  lib/console_web/router.ex
  priv/notifications/plural/service.insight.json.eex
  priv/notifications/plural/stack.insight.json.eex
  priv/notifications/slack/service.insight.json.eex
  priv/notifications/slack/stack.insight.json.eex
  priv/notifications/teams/service.insight.json.eex
  priv/notifications/teams/stack.insight.json.eex
  priv/repo/migrations/20241017164615_add_insight_summary.exs
  schema/schema.graphql
  test/console/ai/cron_test.exs
  test/console/graphql/queries/ai_queries_test.exs
  test/console_web/controllers/webhook_controller_test.exs
Labels: enhancement

#1483 feat(deploymentsettings): add ai settings to DeploymentSettings crd
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  go/controller/docs/api.md
  go/controller/internal/controller/deploymentsettings_controller.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  go/controller/internal/utils/safe/README.md
  go/controller/internal/utils/safe/kubernetes.go
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
Labels: enhancement

#1493 add frontend for AI insights
  assets/package.json
  assets/src/components/apps/app/components/ComponentCard.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceInsights.tsx
  assets/src/components/component/ComponentDetails.tsx
  assets/src/components/component/ComponentInsights.tsx
  assets/src/components/component/directory.tsx
  assets/src/components/settings/global/GlobalSettings.tsx
  assets/src/components/settings/global/GlobalSettingsAiProvider.tsx
  assets/src/components/settings/usermanagement/UserManagement.tsx
  assets/src/components/stacks/Stacks.tsx
  assets/src/components/stacks/StacksEntry.tsx
  assets/src/components/stacks/insights/StackInsights.tsx
  assets/src/components/stacks/run/Header.tsx
  assets/src/components/stacks/run/insights/StackRunInsights.tsx
  assets/src/components/stacks/runs/StackRunsEntry.tsx
  assets/src/components/utils/AiInsights.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/aiInsights.graphql
  assets/src/graph/cdGlobalSettings.graphql
  assets/src/graph/cdServices.graphql
  assets/src/graph/stacks.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/settingsRoutes.tsx
  assets/src/routes/stacksRoutes.tsx
  assets/src/routes/stacksRoutesConsts.tsx
  assets/src/utils/date.ts
  assets/yarn.lock
Labels: enhancement, frontend

#1494 enhancement: AI UI improvements
  assets/src/components/apps/app/components/ComponentCard.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceInsights.tsx
  assets/src/components/component/ComponentDetails.tsx
  assets/src/components/component/ComponentInsights.tsx
  assets/src/components/settings/global/GlobalSettingsAiProvider.tsx
  assets/src/components/stacks/Stacks.tsx
  assets/src/components/stacks/StacksEntry.tsx
  assets/src/components/stacks/common/StackObservabilityMetrics.tsx
  assets/src/components/stacks/insights/StackInsights.tsx
  assets/src/components/stacks/run/Header.tsx
  assets/src/components/stacks/run/Route.tsx
  assets/src/components/stacks/run/Sidecar.tsx
  assets/src/components/stacks/run/insights/StackRunInsights.tsx
  assets/src/components/stacks/run/job/RunJob.tsx
  assets/src/components/stacks/run/output/Output.tsx
  assets/src/components/stacks/run/plan/Plan.tsx
  assets/src/components/stacks/run/progress/Progress.tsx
  assets/src/components/stacks/run/repository/Repository.tsx
  assets/src/components/stacks/runs/StackRunsEntry.tsx
  assets/src/components/utils/AiInsights.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/stacks.graphql
Labels: enhancement

#1484 Expand ai evidence gathering some more
  .firebaserc
  .github/workflows/compatibility-updater.yaml
  .gitlab-ci.yml
  AGENT_VERSION
  Makefile
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/component/ComponentInsights.tsx
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  firebase.json
  go/client/models_gen.go
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  lib/console/ai/cron.ex
  lib/console/ai/evidence/base.ex
  lib/console/ai/evidence/component.ex
  lib/console/ai/evidence/component/daemon_set.ex
  lib/console/ai/evidence/component/deployment.ex
  lib/console/ai/evidence/component/job.ex
  lib/console/ai/evidence/component/raw.ex
  lib/console/ai/evidence/component/resource.ex
  lib/console/ai/evidence/component/stateful_set.ex
  lib/console/ai/provider.ex
  lib/console/ai/provider/anthropic.ex
  lib/console/ai/provider/ollama.ex
  lib/console/deployments/clusters.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/pipelines.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/settings.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/schema/deployment_settings.ex
  lib/console/schema/service.ex
  lib/console_web/templates/email/secret.html.eex
  lib/kube/client.ex
  lib/kube/client/base.ex
  lib/kube/models.ex
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
  schema/schema.graphql
  static/crds/metricsaggregate.yaml
  static/versions.yml
  test-runbook.yml
  test/console/deployments/cron_test.exs
Labels: enhancement

#1491 Add observability webhook schemas and core logic
  assets/src/generated/graphql.ts
  charts/console/templates/monitor.yaml
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  config/prod.exs
  config/test.exs
  go/client/models_gen.go
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  lib/console/ai/provider/ollama.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/events.ex
  lib/console/deployments/observability.ex
  lib/console/deployments/observability/webhook.ex
  lib/console/deployments/observability/webhook/base.ex
  lib/console/deployments/observability/webhook/grafana.ex
  lib/console/deployments/observability/webhook/raw.ex
  lib/console/deployments/pubsub/protocols/notifiable.ex
  lib/console/deployments/settings.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/observability.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/deployments/settings.ex
  lib/console/graphql/resolvers/deployments/observability.ex
  lib/console/schema/ai_insight.ex
  lib/console/schema/alert.ex
  lib/console/schema/deployment_settings.ex
  lib/console/schema/notification_router.ex
  lib/console/schema/observability_webhook.ex
  lib/console/schema/tag.ex
  lib/console_web/controllers/webhook_controller.ex
  lib/console_web/router.ex
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
  priv/notifications/plural/alert.fired.json.eex
  priv/notifications/plural/service.insight.json.eex
  priv/notifications/plural/stack.insight.json.eex
  priv/notifications/slack/alert.fired.json.eex
  priv/notifications/slack/service.insight.json.eex
  priv/notifications/slack/stack.insight.json.eex
  priv/notifications/teams/alert.fired.json.eex
  priv/repo/migrations/20241022194617_add_alerts.exs
  schema/schema.graphql
  test/console/deployments/cron_test.exs
  test/console/deployments/observability_test.exs
  test/console/deployments/pubsub/notification_test.exs
  test/console/graphql/mutations/deployments/observability_mutations_test.exs
  test/console/graphql/queries/deployments/service_queries_test.exs
  test/console_web/controllers/webhook_controller_test.exs
  test/support/factory.ex
Labels: enhancement

#1504 enhancement: Use server-defined freshness field to chose how to present insights
  assets/src/components/utils/AiInsights.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/aiInsights.graphql
Labels: enhancement

#1500 Try implementing an ai suggested fix api
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  lib/console/ai/evidence/base.ex
  lib/console/ai/fixer.ex
  lib/console/ai/fixer/base.ex
  lib/console/ai/fixer/service.ex
  lib/console/ai/fixer/stack.ex
  lib/console/ai/provider.ex
  lib/console/ai/provider/azure.ex
  lib/console/deployments/policies/policies.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/settings.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/schema/ai_insight.ex
  lib/console/schema/deployment_settings.ex
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
  schema/schema.graphql
  test/console/graphql/queries/ai_queries_test.exs
Labels: enhancement

#1511 feat: strip down cluster and service sideloads
  go/client/client.go
  go/client/graph/cluster.graphql
  go/client/graph/deployment.graphql
  go/client/graph/models.graphql
  go/controller/internal/client/cluster.go
  go/controller/internal/client/console.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
Labels: enhancement

#1509 Add apis to persist insight components at cluster level
  Makefile
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/ai/fixer/parent.ex
  lib/console/ai/fixer/service.ex
  lib/console/ai/fixer/stack.ex
  lib/console/deployments/clusters.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/schema/ai_insight.ex
  lib/console/schema/cluster.ex
  lib/console/schema/cluster_insight_component.ex
  priv/repo/migrations/20241024163504_cluster_insight_components.exs
  schema/schema.graphql
  test/console/graphql/mutations/deployments/cluster_mutations_test.exs
  test/console/graphql/queries/ai_queries_test.exs
Labels: enhancement

#1512 Stabilize insight id
  lib/console/ai/memoizer.ex
  lib/console/graphql/resolvers/ai.ex
  test/console/ai/cron_test.exs
Labels: enhancement

#1501 feat: Create webhook proxy NGINX Helm chart
  charts/webhook-proxy/.helmignore
  charts/webhook-proxy/Chart.yaml
  charts/webhook-proxy/README.md
  charts/webhook-proxy/templates/_helpers.tpl
  charts/webhook-proxy/templates/configmap.yaml
  charts/webhook-proxy/templates/deployment.yaml
  charts/webhook-proxy/templates/hpa.yaml
  charts/webhook-proxy/templates/ingress.yaml
  charts/webhook-proxy/templates/service.yaml
  charts/webhook-proxy/templates/serviceaccount.yaml
  charts/webhook-proxy/templates/tests/test-connection.yaml
  charts/webhook-proxy/values.yaml
Labels: enhancement

#1505 feat: Explain with AI
  assets/src/components/ai/AIPanel.tsx
  assets/src/components/ai/AIPanelOverlay.tsx
  assets/src/components/ai/AISuggestFix.tsx
  assets/src/components/ai/AISuggestFixButton.tsx
  assets/src/components/ai/ExplainWithAI.tsx
  assets/src/components/ai/ExplainWithAIButton.tsx
  assets/src/components/ai/ExplainWithAIContext.tsx
  assets/src/components/ai/ExplainWithAIPanel.tsx
  assets/src/components/cd/services/component/ServiceComponent.tsx
  assets/src/components/cd/services/service/ServiceInsights.tsx
  assets/src/components/component/ComponentInsights.tsx
  assets/src/components/kubernetes/cluster/Namespace.tsx
  assets/src/components/kubernetes/cluster/Node.tsx
  assets/src/components/kubernetes/configuration/ConfigMap.tsx
  assets/src/components/kubernetes/customresources/CustomResource.tsx
  assets/src/components/kubernetes/customresources/CustomResourceDefinition.tsx
  assets/src/components/kubernetes/network/Ingress.tsx
  assets/src/components/kubernetes/network/IngressClass.tsx
  assets/src/components/kubernetes/network/NetworkPolicy.tsx
  assets/src/components/kubernetes/network/Service.tsx
  assets/src/components/kubernetes/rbac/ClusterRole.tsx
  assets/src/components/kubernetes/rbac/ClusterRoleBinding.tsx
  assets/src/components/kubernetes/rbac/Role.tsx
  assets/src/components/kubernetes/rbac/RoleBinding.tsx
  assets/src/components/kubernetes/rbac/ServiceAccount.tsx
  assets/src/components/kubernetes/storage/PersistentVolume.tsx
  assets/src/components/kubernetes/storage/PersistentVolumeClaim.tsx
  assets/src/components/kubernetes/storage/StorageClass.tsx
  assets/src/components/kubernetes/workloads/CronJob.tsx
  assets/src/components/kubernetes/workloads/DaemonSet.tsx
  assets/src/components/kubernetes/workloads/Deployment.tsx
  assets/src/components/kubernetes/workloads/Job.tsx
  assets/src/components/kubernetes/workloads/Pod.tsx
  assets/src/components/kubernetes/workloads/ReplicaSet.tsx
  assets/src/components/kubernetes/workloads/ReplicationController.tsx
  assets/src/components/kubernetes/workloads/StatefulSet.tsx
  assets/src/components/layout/Console.tsx
  assets/src/components/layout/Subheader.tsx
  assets/src/components/stacks/insights/StackInsights.tsx
  assets/src/components/stacks/run/Route.tsx
  assets/src/components/stacks/run/insights/StackRunInsights.tsx
  assets/src/components/utils/RefreshIconFrame.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/aiInsights.graphql
Labels: enhancement

#1514 Persisted AI chats
  README.md
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  config/prod.exs
  go/client/models_gen.go
  lib/console/ai/chat.ex
  lib/console/ai/cron.ex
  lib/console/ai/fixer.ex
  lib/console/ai/policy.ex
  lib/console/ai/provider.ex
  lib/console/graphql.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/schema/chat.ex
  lib/console/schema/chat_sequence.ex
  lib/console/services/base.ex
  lib/console/services/users.ex
  priv/repo/migrations/20241026141533_ai_chats.exs
  schema/schema.graphql
  test/console/ai/chat_test.exs
  test/console/graphql/mutations/ai_mutations_test.exs
  test/console/graphql/queries/ai_queries_test.exs
  test/support/factory.ex
Labels: enhancement

#1518 feat: Add indicators to dashboard filters
  assets/src/components/kubernetes/Navigation.tsx
  assets/src/components/kubernetes/common/DataSelect.tsx
  assets/src/components/utils/IconExpander.tsx
Labels: enhancement

#1517 Fix pipeline gate logic
  config/prod.exs
  lib/console/deployments/pipelines.ex
  test/console/deployments/pipelines_test.exs
Labels: enhancement

#1522 Cluster Insight Generation
  assets/src/generated/graphql.ts
  config/prod.exs
  go/client/models_gen.go
  lib/console/ai/chat.ex
  lib/console/ai/cron.ex
  lib/console/ai/evidence/base.ex
  lib/console/ai/evidence/cluster.ex
  lib/console/ai/evidence/cluster_insight_component.ex
  lib/console/ai/evidence/service_component.ex
  lib/console/ai/fixer.ex
  lib/console/deployments/clusters.ex
  lib/console/deployments/events.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/deployments/pubsub/protocols/notifiable.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/graphql/resolvers/kubernetes.ex
  lib/console/schema/chat.ex
  lib/console/schema/cluster.ex
  priv/notifications/plural/cluster.insight.json.eex
  priv/notifications/slack/cluster.insight.json.eex
  priv/notifications/teams/cluster.insight.json.eex
  schema/schema.graphql
  test/console/ai/cron_test.exs
  test/console/deployments/pubsub/notification_test.exs
  test/console/graphql/mutations/ai_mutations_test.exs
  test/console/graphql/queries/ai_queries_test.exs
  test/support/factory.ex
Labels: enhancement

#1525 fix service component chip coloring
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/utils/FractionalChip.tsx
Labels: enhancement, frontend

#1523 Add support for AWS bedrock
  README.md
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  config/prod.exs
  go/client/models_gen.go
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  lib/console/ai/provider.ex
  lib/console/ai/provider/bedrock.ex
  lib/console/graphql/deployments/settings.ex
  lib/console/schema/deployment_settings.ex
  mix.exs
  mix.lock
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
  schema/schema.graphql
  test/console/ai/cron_test.exs
  test/test_helper.exs
Labels: enhancement

#1520 feat: UI support for configuring Ollama, Azure AI and Amazon Bedrock
  assets/src/components/settings/global/GlobalSettingsAIProviders.tsx
  assets/src/components/settings/global/GlobalSettingsAiProvider.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/cdGlobalSettings.graphql
Labels: enhancement

#1528 fix: ai-proxy-cd.yaml
  .github/workflows/ai-proxy-cd.yaml
  .github/workflows/ai-proxy-ci.yaml
Labels: bug-fix

#1530 Fix brittle helm repo test
  test/console/graphql/queries/deployments/git_queries_test.exs
Labels: bug-fix

#1531 Add default setup for ollama on cloud clusters
  lib/console/ai/provider/anthropic.ex
  lib/console/ai/provider/openai.ex
  lib/console/deployments/init.ex
  lib/console/schema/deployment_settings.ex
  test/console/ai/chat_test.exs
  test/console/ai/cron_test.exs
  test/console/deployments/init_test.exs
  test/console/graphql/mutations/ai_mutations_test.exs
Labels: enhancement

#1527 fix: suggest a fix panel/button
  assets/src/components/ai/AIPanelOverlay.tsx
  assets/src/components/ai/AISuggestFix.tsx
  assets/src/components/cd/services/service/ServiceInsights.tsx
  assets/src/components/component/ComponentInsights.tsx
  assets/src/components/stacks/insights/StackInsights.tsx
  assets/src/components/stacks/run/insights/StackRunInsights.tsx
Labels: bug-fix

#1524 add compatibility scraper for karpenter and util `validate_semver`
  KUBE_VERSION
  static/compatibilities/external-dns.yaml
  static/compatibilities/ingress-nginx.yaml
  static/compatibilities/karpenter.yaml
  static/compatibilities/manifest.yaml
  test/console/graphql/queries/deployments/cluster_queries_test.exs
  utils/compatibility/main.py
  utils/compatibility/requirements.txt
  utils/compatibility/scrapers/ingress-nginx.py
  utils/compatibility/scrapers/karpenter.py
  utils/compatibility/utils.py
Labels: enhancement

#1533 Implement chat threading
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  config/prod.exs
  go/client/models_gen.go
  lib/console/ai/chat.ex
  lib/console/ai/cron.ex
  lib/console/ai/policy.ex
  lib/console/graphql.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/schema/chat.ex
  lib/console/schema/chat_sequence.ex
  lib/console/schema/chat_thread.ex
  lib/console/schema/user.ex
  priv/repo/migrations/20241029205244_add_chat_threading.exs
  schema/schema.graphql
  test/console/ai/chat_test.exs
  test/console/graphql/mutations/ai_mutations_test.exs
  test/console/graphql/queries/ai_queries_test.exs
  test/support/factory.ex
Labels: enhancement

#1529 feat(deploymentsettings): requeue is secret ref not present
  .github/workflows/controller-ci.yaml
  go/controller/internal/controller/deploymentsettings_controller.go
  go/controller/internal/errors/base.go
Labels: enhancement

#1536 feat: AI verbosity toggle
  assets/src/components/ai/ExplainWithAI.tsx
  assets/src/components/ai/ExplainWithAIContext.tsx
  assets/src/components/ai/ExplainWithAIPanel.tsx
  assets/src/components/settings/global/GlobalSettingsAiProvider.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/aiInsights.graphql
Labels: enhancement

#1490 feat: update k8s dashboard in console chart
  .github/workflows/helm.yaml
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.86.tgz
  charts/console/charts/kas-0.1.0.tgz
  charts/console/charts/kubernetes-dashboard-7.10.0.tgz
  charts/console/charts/kubernetes-dashboard-7.6.1.tgz
  charts/console/templates/secrets.yaml
  charts/console/values.yaml
  plural/helm/console/Chart.lock
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/controller-0.0.86.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.10.0.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.6.1.tgz
  plural/helm/console/templates/secrets.yaml
  plural/helm/console/values.yaml
Labels: enhancement
