Repository pluralsh/console, pull requests merged in 2024-11, with the labels that each got.

#1542 add optimistic updating to ai chat messages
  assets/src/components/ai/AI.tsx
  assets/src/components/ai/AIPinsTable.tsx
  assets/src/components/ai/AIThreadsTable.tsx
  assets/src/components/ai/chatbot/Chatbot.tsx
  assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
  assets/src/components/stacks/Stacks.tsx
  assets/src/components/utils/SkeletonLoaders.tsx
Labels: enhancement, frontend

#1541 Provide basic empty state for ai tab
  assets/src/components/ai/AI.tsx
  assets/src/components/ai/chatbot/Chatbot.tsx
Labels: enhancement, hotfix

#1547 minimize pipline and gates
  go/client/client.go
  go/client/graph/cluster.graphql
  go/client/graph/gates.graphql
  go/client/graph/pipeline.graphql
  go/controller/internal/client/console.go
  go/controller/internal/client/pipeline.go
  go/controller/internal/controller/pipeline_controller.go
  go/controller/internal/controller/pipeline_controller_test.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
Labels: enhancement

#1546 enhancement: pass raw kubernetes object to explain w/ ai prompt
  assets/src/components/kubernetes/cluster/Namespace.tsx
  assets/src/components/kubernetes/cluster/Node.tsx
  assets/src/components/kubernetes/common/ResourceDetails.tsx
  assets/src/components/kubernetes/configuration/ConfigMap.tsx
  assets/src/components/kubernetes/customresources/CustomResource.tsx
  assets/src/components/kubernetes/customresources/CustomResourceDefinition.tsx
  assets/src/components/kubernetes/network/Ingress.tsx
  assets/src/components/kubernetes/network/IngressClass.tsx
  assets/src/components/kubernetes/network/NetworkPolicy.tsx
  assets/src/components/kubernetes/network/Service.tsx
  assets/src/components/kubernetes/rbac/ClusterRole.tsx
  assets/src/components/kubernetes/rbac/ClusterRoleBinding.tsx
  assets/src/components/kubernetes/rbac/Role.tsx
  assets/src/components/kubernetes/rbac/RoleBinding.tsx
  assets/src/components/kubernetes/rbac/ServiceAccount.tsx
  assets/src/components/kubernetes/storage/PersistentVolume.tsx
  assets/src/components/kubernetes/storage/PersistentVolumeClaim.tsx
  assets/src/components/kubernetes/storage/StorageClass.tsx
  assets/src/components/kubernetes/workloads/CronJob.tsx
  assets/src/components/kubernetes/workloads/DaemonSet.tsx
  assets/src/components/kubernetes/workloads/Deployment.tsx
  assets/src/components/kubernetes/workloads/Job.tsx
  assets/src/components/kubernetes/workloads/Pod.tsx
  assets/src/components/kubernetes/workloads/ReplicaSet.tsx
  assets/src/components/kubernetes/workloads/ReplicationController.tsx
  assets/src/components/kubernetes/workloads/StatefulSet.tsx
Labels: enhancement

#1548 feat: add base url to openai settings
  assets/src/components/settings/global/GlobalSettingsAIProviders.tsx
  assets/src/components/settings/global/GlobalSettingsAiProvider.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
Labels: enhancement

#1550 Add ai pin query by insight/thread id
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  lib/console/graphql/ai.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/schema/ai_pin.ex
  priv/repo/migrations/20241104211145_add_pin_uniq.exs
  schema/schema.graphql
  test/console/graphql/queries/ai_queries_test.exs
Labels: enhancement

#1554 feat: stacks improvements
  go/client/client.go
  go/client/graph/stack.graphql
Labels: enhancement

#1555 fix: /cd/clusters page prefetches tags even if tag selector isn't interacted w/
  assets/src/components/cd/services/ClusterTagsFilter.tsx
Labels: bug-fix

#1552 fix: fix ai tab breadcrumbs
  assets/src/components/ai/AI.tsx
Labels: bug-fix

#1549 feat: add pin button and support for pinned insights on ai view list
  assets/src/components/ai/AIContext.tsx
  assets/src/components/ai/AIPinButton.tsx
  assets/src/components/ai/AIThreadsTable.tsx
  assets/src/components/ai/AiThreadsTableActions.tsx
  assets/src/components/ai/chatbot/Chatbot.tsx
  assets/src/components/ai/chatbot/ChatbotButton.tsx
  assets/src/components/ai/chatbot/ChatbotHeader.tsx
  assets/src/components/ai/chatbot/ChatbotPanelInsight.tsx
  assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
  assets/src/components/cd/services/service/ServiceInsights.tsx
  assets/src/components/component/ComponentInsights.tsx
  assets/src/components/stacks/insights/StackInsights.tsx
  assets/src/components/stacks/run/insights/StackRunInsights.tsx
  assets/src/components/utils/SkeletonLoaders.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/ai.graphql
  assets/src/utils/datetime.ts
Labels: enhancement, frontend

#1557 enhancement: cluster sorting by name, version, health and status (upgrades)
  assets/src/components/cd/clusters/ClustersColumns.tsx
Labels: enhancement

#1558 fix: show explain with ai only if ai is enabled
  assets/src/components/ai/AI.tsx
  assets/src/components/ai/explain/ExplainWithAI.tsx
Labels: bug-fix

#1551 Vulnerability Query and Persistence
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/prautomation_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  lib/console/ai/chat.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/deployments/policy.ex
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/deployments/policy.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/policy.ex
  lib/console/schema/namespace_vuln.ex
  lib/console/schema/pr_automation.ex
  lib/console/schema/service.ex
  lib/console/schema/service_vuln.ex
  lib/console/schema/vulnerability.ex
  lib/console/schema/vulnerability_report.ex
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
  priv/repo/migrations/20241104215358_add_vulnerabilities.exs
  schema/schema.graphql
  test/console/deployments/policy_test.exs
  test/console/graphql/mutations/deployments/policy_mutations_test.exs
  test/console/graphql/queries/deployments/policy_queries_test.exs
  test/support/factory.ex
Labels: enhancement

#1559 Implement VertexAI provider
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  lib/console/ai/provider.ex
  lib/console/ai/provider/vertex.ex
  lib/console/graphql/deployments/settings.ex
  lib/console/schema/deployment_settings.ex
  mix.exs
  mix.lock
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
  schema/schema.graphql
Labels: enhancement

#1561 feat: add UpsertVulnerabilities mutation
  go/client/client.go
  go/client/graph/vulnerabilities.graphql
Labels: enhancement

#1560 feat: Vertex AI provider
  assets/src/components/settings/global/GlobalSettingsAIProviders.tsx
  assets/src/components/settings/global/GlobalSettingsAiProvider.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/cdGlobalSettings.graphql
Labels: enhancement

#1562 Sideload cluster on cluster insight components
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/graphql/ai.ex
  schema/schema.graphql
Labels: enhancement

#1566 update add service account file drop to vertex ai settings
  assets/package.json
  assets/src/components/settings/global/GlobalSettingsAIProviders.tsx
  assets/src/components/stacks/common/StackTypeIcon.tsx
  assets/src/components/tracking/CookieSettings.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#1568 Prerelease touchups
  lib/console/ai/chat.ex
  lib/console/ai/fixer.ex
  lib/console/ai/goth_manager.ex
  lib/console/deployments/pubsub/protocols/notifiable.ex
  lib/console/retrier.ex
Labels: enhancement, hotfix

#1574 Fix retrier logic
  lib/console/retrier.ex
Labels: enhancement, hotfix

#1577 Incremental AI improvements
  go/controller/api/v1alpha1/deploymentsettings_types.go
  lib/console/ai/evidence/base.ex
  lib/console/ai/evidence/stack_run.ex
  lib/console/ai/fixer.ex
  lib/console/ai/fixer/base.ex
  lib/console/ai/fixer/parent.ex
  lib/console/ai/fixer/service.ex
  lib/console/ai/fixer/stack.ex
  lib/console/ai/provider.ex
  lib/console/ai/provider/anthropic.ex
Labels: enhancement, hotfix

#1591 enhancement: Homepage improvements
  assets/src/components/ai/AITable.tsx
  assets/src/components/ai/AITableEntry.tsx
  assets/src/components/home/AiThreads.tsx
  assets/src/components/home/CustomLegend.tsx
  assets/src/components/home/Home.tsx
  assets/src/components/home/HomeCard.tsx
  assets/src/components/home/MonthlyClusterCostsCard.tsx
  assets/src/components/home/clusteroverview/ClusterOverviewCard.tsx
  assets/src/components/home/clusteroverview/ClusterOverviewChart.tsx
  assets/src/components/home/deployments/DeploymentsCard.tsx
  assets/src/components/home/deployments/DeploymentsTable.tsx
  assets/src/components/home/pullrequests/PrCard.tsx
  assets/src/components/home/pullrequests/PrTable.tsx
  assets/src/components/home/violations/ConstraintViolationsCard.tsx
  assets/src/components/home/violations/ConstraintViolationsChart.tsx
  assets/src/components/utils/RadialBarChart.tsx
Labels: enhancement

#1590 feat(ai-proxy): add support for vertex ai provider
  charts/ai-proxy/Chart.yaml
  charts/ai-proxy/templates/secrets.yaml
  charts/ai-proxy/values.yaml
  go/ai-proxy/api/provider.go
  go/ai-proxy/api/vertex/vertex.go
  go/ai-proxy/args/args.go
  go/ai-proxy/go.mod
  go/ai-proxy/go.sum
  go/ai-proxy/main.go
  go/ai-proxy/proxy/provider/base.go
  go/ai-proxy/proxy/provider/ollama.go
  go/ai-proxy/proxy/provider/openai.go
  go/ai-proxy/proxy/provider/vertex.go
  go/ai-proxy/proxy/proxy.go
  go/ai-proxy/test/helpers/common.go
  go/ai-proxy/test/vertex/openai_test.go
Labels: enhancement

#1594 ai chat thread improvements
  assets/package.json
  assets/src/components/ai/chatbot/ChatMessage.tsx
  assets/src/components/ai/chatbot/ChatbotHeader.tsx
  assets/src/components/ai/chatbot/ChatbotPanelInsight.tsx
  assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
  assets/src/components/ai/chatbot/ChatbotSendMessageForm.tsx
  assets/src/components/hooks/useCanScroll.ts
  assets/yarn.lock
Labels: enhancement, frontend

#1595 enhancement: Tables improvements
  assets/package.json
  assets/src/components/ai/AITable.tsx
  assets/src/components/home/clusteroverview/ClusterOverviewTable.tsx
  assets/src/components/home/deployments/DeploymentsTable.tsx
  assets/src/components/home/pullrequests/PrTable.tsx
  assets/src/components/home/violations/ConstraintViolationsCard.tsx
  assets/src/components/kubernetes/common/ResourceList.tsx
  assets/src/components/policies/PoliciesTable.tsx
  assets/yarn.lock
Labels: enhancement

#1596 fix streaming api
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/ai/stream.ex
  lib/console/graphql/ai.ex
  schema/schema.graphql
  test/console_web/channels/graphql/ai_subscription_test.exs
Labels: enhancement

#1597 Add sequence number for ai stream objects
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/ai/stream.ex
  lib/console/ai/stream/exec.ex
  lib/console/graphql/ai.ex
  schema/schema.graphql
  test/console_web/channels/graphql/ai_subscription_test.exs
Labels: enhancement, hotfix

#1599 implement streaming into ai chat
  assets/src/components/ai/AIPanel.tsx
  assets/src/components/ai/chatbot/AISuggestFix.tsx
  assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/ai.graphql
  lib/console/ai/stream.ex
  lib/console/ai/stream/exec.ex
  test/console_web/channels/graphql/ai_subscription_test.exs
Labels: enhancement, frontend

#1603 enhancement: Table loading skeletons for home, policies and dashboard pages
  assets/package.json
  assets/src/components/ai/AITable.tsx
  assets/src/components/home/clusteroverview/ClusterOverviewCard.tsx
  assets/src/components/home/clusteroverview/ClusterOverviewChart.tsx
  assets/src/components/home/clusteroverview/ClusterOverviewTable.tsx
  assets/src/components/home/deployments/DeploymentsCard.tsx
  assets/src/components/home/deployments/DeploymentsTable.tsx
  assets/src/components/home/pullrequests/PrCard.tsx
  assets/src/components/home/pullrequests/PrTable.tsx
  assets/src/components/home/violations/ConstraintViolationsCard.tsx
  assets/src/components/home/violations/ConstraintViolationsChart.tsx
  assets/src/components/kubernetes/common/ResourceList.tsx
  assets/src/components/policies/Policies.tsx
  assets/src/components/policies/PoliciesTable.tsx
  assets/src/components/utils/SkeletonLoaders.tsx
  assets/yarn.lock
Labels: enhancement

#1602 Add support for Anthropic/streaming on explain-with-ai
  assets/src/components/ai/chatbot/AISuggestFix.tsx
  assets/src/components/ai/explain/ExplainWithAIPanel.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/ai.graphql
  lib/console/ai/provider/anthropic.ex
  lib/console/ai/stream.ex
  lib/console/ai/stream/exec.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/resolvers/ai.ex
  schema/schema.graphql
Labels: enhancement

#1604 Add insights for terraform plans
  Dockerfile
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/servicedeployment_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  go/controller/internal/controller/servicedeployment_controller.go
  lib/console/ai/evidence/stack_run.ex
  lib/console/ai/evidence/stack_state.ex
  lib/console/ai/pubsub/consumer.ex
  lib/console/ai/pubsub/protocol.ex
  lib/console/deployments/events.ex
  lib/console/deployments/git/cache.ex
  lib/console/deployments/pubsub/recurse.ex
  lib/console/deployments/stacks.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  lib/console/graphql/schema/base.ex
  lib/console/schema/ai_insight.ex
  lib/console/schema/stack_state.ex
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
  priv/pr/insight.md.eex
  priv/repo/migrations/20241121212536_add_insight_id_states.exs
  schema/schema.graphql
  test/console/ai/pubsub/consumer_test.exs
  test/console/deployments/pubsub/recurse_test.exs
Labels: enhancement

#1606 Prep release 0.10.40
  assets/src/components/ai/AITableEntry.tsx
  lib/console/ai/chat.ex
  lib/console/services/users.ex
Labels: enhancement

#1610 Manually reconnect closed sockets
  assets/src/helpers/client.ts
Labels: enhancement, hotfix

#1616 change Ready condition on success
  go/client/client.go
  go/client/graph/stack.graphql
  go/controller/config/samples/deployments_v1alpha1_infrastructurestack.yaml
  go/controller/internal/client/console.go
  go/controller/internal/client/stack.go
  go/controller/internal/controller/infrastructurestack_controller.go
  go/controller/internal/controller/infrastructurestack_test.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
Labels: enhancement

#1615 Fix stack run notification
  Dockerfile
  charts/console-rapid/Chart.yaml
  charts/console/templates/migration.yaml
  charts/console/values.yaml
  lib/console/schema/pr_automation.ex
  lib/console/services/users.ex
  mix.exs
  mix.lock
  priv/notifications/slack/stack.run.json.eex
  rel/overlays/bin/migrate
  rel/runtime.exs
  rel/vm.args.eex
  test/console/services/users_test.exs
Labels: enhancement

#1620 feat(client): Add update user mutation
  go/client/client.go
  go/client/graph/users.graphql
Labels: enhancement

#1622 fix: decrease dashboard api resource requests/limits
  charts/console/Chart.yaml
  charts/console/values.yaml
Labels: bug-fix

#1619 update to reflect new DS bundle
  assets/package.json
  assets/src/App.test.tsx
  assets/src/App.tsx
  assets/src/components/ai/AITable.tsx
  assets/src/components/ai/chatbot/Chatbot.tsx
  assets/src/components/apps/app/App.tsx
  assets/src/components/apps/app/components/misc.tsx
  assets/src/components/cd/clusters/ClusterUpgradeFlyover.tsx
  assets/src/components/cd/clusters/UpgradeInsights.tsx
  assets/src/components/cd/providers/InputRevealer.tsx
  assets/src/components/cd/services/CreateGlobalServiceModal.tsx
  assets/src/components/cd/services/GlobalServiceFields.tsx
  assets/src/components/cd/services/ServicesTableErrors.tsx
  assets/src/components/cd/utils/ProviderSelect.tsx
  assets/src/components/cluster/TableElements.tsx
  assets/src/components/commandpalette/CommandPaletteDialog.tsx
  assets/src/components/commandpalette/commands.ts
  assets/src/components/db-management/DatabaseManagement.tsx
  assets/src/components/help/HelpLauncherBtn.tsx
  assets/src/components/kubernetes/common/ResourceInfoCard.tsx
  assets/src/components/kubernetes/common/utils.tsx
  assets/src/components/layout/Console.tsx
  assets/src/components/layout/SideNavEntries.tsx
  assets/src/components/notifications/NotificationPriorityChip.tsx
  assets/src/components/pr/automations/CreatePrModal.tsx
  assets/src/components/pr/queue/PrQueue.tsx
  assets/src/components/pr/queue/PrQueueColumns.tsx
  assets/src/components/pr/scm/EditScmConnection.tsx
  assets/src/components/profile/Profile.tsx
  assets/src/components/settings/global/GlobalSettingsAiProvider.tsx
  assets/src/components/settings/global/observability/EditObservabilityProvider.tsx
  assets/src/components/settings/notifications/routers/EditNotificationRouterModal.tsx
  assets/src/components/settings/usermanagement/serviceaccounts/ServiceAccountCols.tsx
  assets/src/components/sharesecret/ShareSecretModal.tsx
  assets/src/components/stacks/common/StackApprovalChip.tsx
  assets/src/components/stacks/common/StackRunIcon.tsx
  assets/src/components/stacks/common/StackStatusChip.tsx
  assets/src/components/utils/AiInsights.tsx
  assets/src/components/utils/MarkdocContent.tsx
  assets/src/markdoc/mdSchema.ts
  assets/vite.config.ts
  assets/yarn.lock
Labels: enhancement, frontend

#1624 enhancement: Load only three most recent chat threads on the home page
  assets/src/components/home/AiThreads.tsx
Labels: enhancement

#1625 bump flux to 2.14.0
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/flux2-2.11.1.tgz
  charts/console/charts/flux2-2.14.0.tgz
Labels: dependencies

#1628 feat: extend service deployment with status
  go/client/client.go
  go/client/graph/models.graphql
Labels: enhancement

#1626 improve socket connect retry logic
  assets/package.json
  assets/src/components/pr/scm/CreateScmConnection.tsx
  assets/src/components/pr/scm/EditScmConnection.tsx
  assets/src/helpers/client.ts
  assets/yarn.lock
  lib/console/deployments/git/utils.ex
  lib/console/deployments/git/webhooks.ex
  lib/console/deployments/pr/utils.ex
  lib/console/graphql/resolvers/deployments.ex
  mix.exs
  mix.lock
  test/console/deployments/git_test.exs
  test/console/graphql/queries/kubernetes_queries_test.exs
Labels: bug-fix, frontend

#1633 change scm connection signing private key to use a file upload
  assets/src/components/cd/utils/SshKeyUpload.tsx
  assets/src/components/pr/scm/EditScmConnection.tsx
Labels: enhancement, frontend
