Repository pluralsh/console, pull requests merged in 2024-01, with the labels that each got.

#570 Migration job needs to have a service account assigned
  charts/console/Chart.yaml
  charts/console/templates/deployment.yaml
  charts/console/templates/secrets.yaml
  charts/console/values.yaml
  lib/console/graphql/resolvers/plural.ex
  plural/helm/console/Chart.yaml
  plural/helm/console/templates/migration.yaml
  templates/values.yaml.liquid
  templates/values.yaml.tpl
Labels: enhancement, backend

#572 Add a basic byok override
  lib/console.ex
  rel/config/console.exs
Labels: enhancement

#573 Minor chart tweaks, and finalize deployability of the operator
  .github/workflows/publish.yaml
  charts/controller/Chart.yaml
  charts/controller/templates/deployment.yaml
  charts/controller/values.yaml
Labels: enhancement

#575 Have charts be specified as raw strings
  charts/controller/crds/servicedeployment-crd.yaml
  charts/controller/templates/deployment.yaml
  controller/api/v1alpha1/servicedeployment_types.go.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  controller/internal/controller/servicedeployment_controller.go
  plural/helm/console/crds/servicedeployment-crd.yaml
Labels: enhancement

#579 fix: Fix cluster reconciler error handling
  controller/config/samples/cluster_azure.yaml
  controller/config/samples/cluster_gcp.yaml
  controller/internal/client/cluster.go
  controller/internal/controller/cluster_controller.go
Labels: bug-fix

#577 Auto-update helm dependencies for controller subchart when generating releases
  .github/workflows/publish.yaml
  charts/console/Chart.yaml
  charts/controller/Chart.yaml
  charts/controller/crds/servicedeployment-crd.yaml
  charts/controller/templates/deployment.yaml
  controller/api/v1alpha1/servicedeployment_types.go.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  controller/internal/controller/servicedeployment_controller.go
  lib/console/deployments/git/cmd.ex
Labels: enhancement

#583 Fix duplicate key issue in controller chart
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.5.tgz
  charts/console/charts/controller-0.0.6.tgz
  charts/console/charts/kas-0.0.3.tgz
  charts/controller/Chart.yaml
  charts/controller/templates/deployment.yaml
Labels: enhancement

#587 feat: Create Pipeline and Global Service APIs and update Helm chart
  charts/controller/crds/servicedeployment-crd.yaml
  charts/controller/templates/manager-rbac.yaml
  controller/PROJECT
  controller/api/v1alpha1/globalservice_types.go
  controller/api/v1alpha1/pipeline_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  controller/config/crd/bases/deployments.plural.sh_pipelines.yaml
  controller/config/crd/kustomizeconfig.yaml
  controller/config/rbac/globalservice_editor_role.yaml
  controller/config/rbac/globalservice_viewer_role.yaml
  controller/config/rbac/pipeline_editor_role.yaml
  controller/config/rbac/pipeline_viewer_role.yaml
  controller/config/rbac/role.yaml
  controller/config/samples/deployments_v1alpha1_globalservice.yaml
  controller/config/samples/deployments_v1alpha1_pipeline.yaml
  controller/internal/controller/globalservice_controller.go
  controller/internal/controller/pipeline_controller.go
Labels: enhancement

#578 feat: Add Light Mode support
  assets/index.html
  assets/package.json
  assets/public/aws-icon.png
  assets/public/aws.png
  assets/public/azure.png
  assets/public/chart.png
  assets/public/console-full.png
  assets/public/console-lockup-dark.png
  assets/public/console-logo-white.png
  assets/public/equinix-metal.png
  assets/public/gcp.png
  assets/public/header-logo-dark.png
  assets/public/header-logo-light.png
  assets/public/kind.png
  assets/public/page-load-spinner/page-load-spinner.css
  assets/public/providers/aws-icon-dark.png
  assets/public/providers/aws-icon-light.png
  assets/public/providers/azure-icon.png
  assets/public/providers/chart-icon.png
  assets/public/providers/equinix-icon.png
  assets/public/providers/gcp-icon.png
  assets/public/providers/kind-icon.png
  assets/public/providers/linode-icon.png
  assets/src/App.tsx
  assets/src/components/CommandPalette.tsx
  assets/src/components/account/email/EmailSettingsForm.tsx
  assets/src/components/account/webhooks/Webhook.tsx
  assets/src/components/account/webhooks/WebhooksHeader.tsx
  assets/src/components/apps/AppCard.tsx
  assets/src/components/apps/app/AppSelector.tsx
  assets/src/components/apps/misc.tsx
  assets/src/components/builds/Build.tsx
  assets/src/components/builds/CreateBuild.tsx
  assets/src/components/builds/build/Build.tsx
  assets/src/components/builds/build/changelog/Changelog.tsx
  assets/src/components/cd/clusters/ClusterConditions.tsx
  assets/src/components/cd/clusters/ClustersColumns.tsx
  assets/src/components/cd/clusters/create/ProviderTabSelector.tsx
  assets/src/components/cd/clusters/create/helpers.ts
  assets/src/components/cd/providers/ProvidersColumns.tsx
  assets/src/components/cd/repos/HelmRepositoriesColumns.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/utils/ProviderSelect.tsx
  assets/src/components/cd/utils/RepoKindSelector.tsx
  assets/src/components/cluster/pods/PodsList.tsx
  assets/src/components/db-management/DatabaseManagement.tsx
  assets/src/components/help/HelpLauncherBtn.tsx
  assets/src/components/layout/AppNav.tsx
  assets/src/components/layout/Header.tsx
  assets/src/components/layout/Notification.tsx
  assets/src/components/layout/Subheader.tsx
  assets/src/components/utils/ChartTooltip.tsx
  assets/src/components/utils/Chloropleth.tsx
  assets/src/components/utils/PieChart.tsx
  assets/src/components/utils/Provider.tsx
  assets/src/components/utils/RadialBarChart.tsx
  assets/src/components/utils/charts.tsx
  assets/src/generated/graphql-plural.ts
  assets/yarn.lock
Labels: enhancement, frontend

#590 Add global service fetch, fix job gate cluster assignment
  assets/public/linode.png
  assets/src/components/layout/Sidebar.tsx
  assets/src/generated/graphql.ts
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.6.tgz
  charts/console/charts/kas-0.0.3.tgz
  charts/console/charts/kas-0.0.4.tgz
  lib/console/graphql/deployments/pipeline.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/schema/cluster.ex
  lib/console/schema/pipeline_gate.ex
  plural/helm/kas/Chart.yaml
  plural/helm/kas/templates/configmap.yaml
  plural/helm/kas/templates/deployment.yaml
  plural/helm/kas/templates/ingress.yaml
  schema/schema.graphql
  templates/values.yaml.tpl
  test/console/graphql/mutations/deployment_mutations_test.exs
  test/console/graphql/queries/deployment_queries_test.exs
Labels: enhancement

#591 fix: fix cd pages not loading due to ts error
  assets/src/components/layout/Sidebar.tsx
Labels: bug-fix

#592 Delete pipeline mutation
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/pipeline.ex
  lib/console/graphql/resolvers/deployments.ex
  schema/schema.graphql
  test/console/deployments/pipeline_test.exs
  test/console/graphql/mutations/deployment_mutations_test.exs
Labels: enhancement

#596 add service dependencies support
  controller/api/v1alpha1/servicedeployment_types.go.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  controller/internal/controller/servicedeployment_controller.go
Labels: enhancement

#597 Change labels/annotations on gate jobs
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/pipeline.ex
  schema/schema.graphql
Labels: enhancement

#595 feat: Global service
  controller/api/v1alpha1/globalservice_types.go
  controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/client/console.go
  controller/internal/client/globalservice.go
  controller/internal/client/service.go
  controller/internal/controller/globalservice_controller.go
  controller/internal/controller/globalservice_scope.go
  controller/internal/controller/globalservice_test.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  controller/internal/types/reconciler.go
Labels: enhancement

#594 feat: Show details for Ingress/Deployments in canary view
  assets/src/components/component/info/Canary.tsx
  assets/src/components/component/info/Deployment.tsx
  assets/src/components/component/info/Ingress.tsx
  assets/src/components/component/info/Metadata.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/utils/PieChart.tsx
  assets/src/components/utils/typography/InlineLink.tsx
Labels: enhancement, frontend

#589 feat: Update pipelines controller
  controller/api/v1alpha1/pipeline_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_pipelines.yaml
  controller/config/samples/pipeline.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/client/console.go
  controller/internal/client/pipeline.go
  controller/internal/controller/cluster_controller.go
  controller/internal/controller/gitrepository_controller_test.go
  controller/internal/controller/pipeline_controller.go
  controller/internal/controller/pipeline_controller_attributes.go
  controller/internal/controller/pipeline_controller_test.go
  controller/internal/controller/pipeline_scope.go
  controller/internal/controller/servicedeployment_controller_test.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  controller/internal/types/reconciler.go
  controller/internal/utils/kubernetes.go
Labels: enhancement

#599 feat: Update service condition
  controller/cmd/main.go
  controller/internal/controller/gitrepository_controller_test.go
  controller/internal/controller/globalservice_controller.go
  controller/internal/controller/servicedeployment_controller.go
  controller/internal/controller/servicedeployment_controller_test.go
  controller/internal/errors/base.go
Labels: enhancement

#601 Add first-class objects for plural deployments crds
  assets/src/generated/graphql.ts
  crds/plural-cluster.yaml
  crds/plural-gitrepo.yaml
  crds/plural-service.yaml
  lib/console/graphql/kubernetes.ex
  lib/console/graphql/kubernetes/plural.ex
  lib/console/graphql/resolvers/kubernetes.ex
  lib/console/graphql/resolvers/kubernetes/plural.ex
  lib/kube/client.ex
  lib/kube/models.ex
  schema/schema.graphql
  test/console/graphql/queries/kubernetes_queries_test.exs
  test/support/kubernetes_scaffolds.ex
Labels: enhancement

#600 feat: Conditions improvements
  .github/workflows/controller-cd.yaml
  .github/workflows/controller-ci.yaml
  controller/api/v1alpha1/common_types.go
  controller/go.mod
  controller/go.sum
  controller/internal/controller/cluster_controller.go
  controller/internal/controller/cluster_controller_test.go
  controller/internal/controller/gitrepository_controller.go
  controller/internal/controller/gitrepository_controller_test.go
  controller/internal/controller/globalservice_controller.go
  controller/internal/controller/globalservice_test.go
  controller/internal/controller/pipeline_controller.go
  controller/internal/controller/pipeline_controller_test.go
  controller/internal/controller/provider_controller.go
  controller/internal/controller/provider_controller_test.go
  controller/internal/controller/servicedeployment_controller.go
  controller/internal/controller/servicedeployment_controller_test.go
  controller/internal/utils/kubernetes.go
Labels: enhancement

#604 feat: Show distro names and update icons
  assets/public/providers/aks-icon.png
  assets/public/providers/eks-icon.png
  assets/public/providers/gke-icon.png
  assets/public/providers/k3s-icon.png
  assets/public/providers/rke-icon.png
  assets/src/components/cd/addOns/ClusterSelect.tsx
  assets/src/components/cd/cluster/ClusterMetadata.tsx
  assets/src/components/cd/clusters/ClustersColumns.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/utils/ClusterSelector.tsx
  assets/src/components/utils/Provider.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/graph/cdServices.graphql
Labels: enhancement

#606 Dry Run + On-Demand PR generation data models
  assets/src/generated/graphql.ts
  lib/console/commands/plural.ex
  lib/console/deployments/git.ex
  lib/console/deployments/pr/config.ex
  lib/console/deployments/pr/dispatcher.ex
  lib/console/deployments/pr/git.ex
  lib/console/deployments/pr/impl/github.ex
  lib/console/deployments/pr/impl/gitlab.ex
  lib/console/deployments/pr/impl/pass.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/schema/component_content.ex
  lib/console/schema/pr_automation.ex
  lib/console/schema/scm_connection.ex
  lib/console/schema/scm_webhook.ex
  lib/console/schema/service.ex
  lib/console/schema/service_component.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20240111013712_add_pr_automation.exs
  schema/schema.graphql
  test/console/graphql/queries/deployment_queries_test.exs
Labels: enhancement

#603 feat: Upgrade modal revision
  assets/package.json
  assets/src/components/apps/AppCard.tsx
  assets/src/components/apps/app/App.tsx
  assets/src/components/builds/build/Build.tsx
  assets/src/components/cd/cluster/Cluster.tsx
  assets/src/components/cd/cluster/ClusterAddOns.tsx
  assets/src/components/cd/cluster/ClusterMetadata.tsx
  assets/src/components/cd/cluster/ClusterNodes.tsx
  assets/src/components/cd/cluster/addon/ClusterAddOnCompatibility.tsx
  assets/src/components/cd/cluster/addon/ClusterAddOnDetails.tsx
  assets/src/components/cd/cluster/addon/ClusterAddOnDetailsSidecar.tsx
  assets/src/components/cd/clusters/ClusterUpgrade.tsx
  assets/src/components/cd/clusters/runtime/RuntimeServices.tsx
  assets/src/components/cd/clusters/runtime/columns.tsx
  assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
  assets/src/components/cluster/nodes/ClusterGauges.tsx
  assets/src/components/component/info/common.tsx
  assets/src/components/utils/Metadata.tsx
  assets/src/components/utils/typography/Text.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#608 Expose readmes/release urls for compatibilities
  assets/src/generated/graphql.ts
  lib/console/deployments/clusters.ex
  lib/console/deployments/compatibilities/schema.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/schema/pr_automation.ex
  lib/console/schema/service.ex
  lib/console/schema/service_component.ex
  schema/schema.graphql
  static/compatibilities/argo-rollouts.yaml
  static/compatibilities/cert-manager.yaml
  static/compatibilities/external-dns.yaml
  static/compatibilities/ingress-nginx.yaml
  static/compatibilities/istio.yaml
  static/compatibilities/kube-prometheus-stack.yaml
  test/console/graphql/queries/deployment_queries_test.exs
Labels: enhancement

#605 feat: Add basic search and health filtering on Clusters table
  assets/public/cluster-distros/aks.svg
  assets/public/cluster-distros/eks-dark.svg
  assets/public/cluster-distros/eks-light.svg
  assets/public/cluster-distros/gke-dark.svg
  assets/public/cluster-distros/gke-light.svg
  assets/public/cluster-distros/k3s-dark.svg
  assets/public/cluster-distros/k3s-light.svg
  assets/public/cluster-distros/k8s.svg
  assets/public/cluster-distros/kind.svg
  assets/public/cluster-distros/lke.svg
  assets/public/cluster-distros/rke.svg
  assets/public/providers/aks-icon.png
  assets/public/providers/eks-icon.png
  assets/public/providers/gke-icon.png
  assets/public/providers/k3s-icon.png
  assets/public/providers/rke-icon.png
  assets/src/components/account/groups/GroupMember.tsx
  assets/src/components/account/groups/GroupMembers.tsx
  assets/src/components/account/webhooks/WebhooksHeader.tsx
  assets/src/components/apps/app/runbooks/runbook/RunbookAlerts.tsx
  assets/src/components/cd/addOns/ClusterSelect.tsx
  assets/src/components/cd/cluster/ClusterMetadata.tsx
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/cd/clusters/ClustersColumns.tsx
  assets/src/components/cd/clusters/DynamicClusterIcon.tsx
  assets/src/components/cd/services/ClustersFilters.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/utils/ClusterSelector.tsx
  assets/src/components/utils/BindingInput.tsx
  assets/src/components/utils/ClusterDistro.tsx
  assets/src/components/utils/List.tsx
  assets/src/components/utils/ListInput.tsx
  assets/src/components/utils/Provider.tsx
  assets/src/components/utils/UserInfo.tsx
  assets/src/components/utils/layout/ResponsiveLayoutPage.tsx
  assets/src/components/utils/layout/ResponsivePageFullWidth.tsx
  assets/src/components/utils/table/StackedText.tsx
  assets/src/components/utils/typography/Text.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
Labels: enhancement

#612 Improve Helm chart caching, and dry run persistence
  lib/console/deployments/helm/cache.ex
  lib/console/deployments/helm/server.ex
  lib/console/schema/service_component.ex
  test/console/deployments/services_test.exs
Labels: enhancement

#614 feat: Static dedicated values files for helm services
  assets/src/generated/graphql.ts
  lib/console/deployments/git.ex
  lib/console/deployments/pipelines.ex
  lib/console/deployments/services.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/resolvers/deployments/git.ex
  lib/console/schema/pipeline_promotion.ex
  lib/console/schema/promotion_service.ex
  lib/console/schema/pull_request.ex
  priv/repo/migrations/20240118203028_promotion_service_sha.exs
  priv/repo/migrations/20240119032837_add_more_pr_attrs.exs
  schema/schema.graphql
  test-apps/linode-externaldns/values-linode.yaml.liquid
  test/console/deployments/git_test.exs
  test/console/deployments/pipeline_test.exs
  test/console/deployments/services_test.exs
  test/console/graphql/mutations/deployments/git_mutations_test.exs
Labels: enhancement

#617 Add conjunctive tag queries
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/schema/cluster.ex
  lib/console/schema/tag.ex
  schema/schema.graphql
  test/console/graphql/queries/deployments/cluster_queries_test.exs
Labels: enhancement

#607 feat: Services dry-run
  assets/package.json
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/services/component/ServiceComponent.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
  assets/src/components/cd/services/service/ServiceDryRun.tsx
  assets/src/components/component/ComponentDetails.tsx
  assets/src/components/component/ComponentDryRun.tsx
  assets/src/components/component/ComponentInfo.tsx
  assets/src/components/component/ComponentRaw.tsx
  assets/src/components/component/directory.tsx
  assets/src/components/utils/DiffViewer.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdServices.graphql
  assets/src/routes/cdRoutes.tsx
  assets/yarn.lock
Labels: enhancement

#620 feat: Properly shell to `plural pr template`
  assets/src/generated/graphql.ts
  lib/console/commands/plural.ex
  lib/console/deployments/git.ex
  lib/console/deployments/pr/config.ex
  lib/console/deployments/pr/dispatcher.ex
  lib/console/deployments/pr/git.ex
  lib/console/deployments/pr/impl/github.ex
  lib/console/deployments/pr/impl/gitlab.ex
  lib/console/graphql/deployments/git.ex
  lib/console/schema/pr_automation.ex
  lib/console/schema/scm_connection.ex
  schema/schema.graphql
  test/console/deployments/git_test.exs
  test/console/graphql/mutations/deployments/git_mutations_test.exs
Labels: enhancement

#622 fix: Remove unused userguiding script
  assets/index.html
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/services/component/ServiceComponent.tsx
Labels: bug-fix

#621 small fixups for gate update/pr labels
  assets/src/components/cd/clusters/ClusterUpgrade.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/graph/cdPrs.graphql
  lib/console/deployments/pipelines.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/deployments/pipeline.ex
  lib/console/graphql/resolvers/deployments/pipeline.ex
  lib/console/schema/cluster.ex
  lib/console/schema/pull_request.ex
  priv/repo/migrations/20240123173140_retype_pr_labels.exs
  schema/schema.graphql
Labels: enhancement

#623 feat: Add precise tooltips to all timestamps in Console
  assets/src/components/apps/app/runbooks/runbook/RunbookExecutions.tsx
  assets/src/components/audits/table/AuditTable.tsx
  assets/src/components/builds/Build.tsx
  assets/src/components/builds/build/BuildTimer.tsx
  assets/src/components/cd/cluster/ClusterMetadata.tsx
  assets/src/components/cd/clusters/ClusterConditions.tsx
  assets/src/components/cd/clusters/ClusterHealthChip.tsx
  assets/src/components/cd/clusters/ClusterUpgrade.tsx
  assets/src/components/cd/repos/GitRepositoriesColumns.tsx
  assets/src/components/cd/services/ServiceRevisionColumns.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cluster/pods/PodConditions.tsx
  assets/src/components/db-management/DatabasesList.tsx
  assets/src/components/profile/AccessTokens.tsx
  assets/src/components/utils/EventsTable.tsx
  assets/src/components/utils/TooltipTime.tsx
  assets/src/components/utils/table/DateTimeCol.tsx
Labels: enhancement, frontend

#624 Migrate helm chart cache to write-after
  lib/console/deployments/helm/cache.ex
  lib/console/deployments/helm/server.ex
Labels: enhancement

#625 fix: Flip dry run tab display logic
  assets/src/components/component/ComponentDetails.tsx
Labels: bug-fix

#626 Add git pr configuration types
  assets/src/generated/graphql.ts
  lib/console/deployments/helm/server.ex
  lib/console/graphql/deployments/git.ex
  lib/console/schema/embeds.ex
  lib/console/schema/pr_automation.ex
  priv/repo/migrations/20240124153455_add_pr_configs.exs
  schema/schema.graphql
Labels: enhancement

#616 feat: Add filtering of clusters by tag
  assets/package.json
  assets/src/components/apps/AppStatus.tsx
  assets/src/components/apps/Apps.tsx
  assets/src/components/builds/BuildStatus.tsx
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/cd/services/ClusterTagsFilter.tsx
  assets/src/components/cd/services/ClustersFilters.tsx
  assets/src/components/cd/services/ServiceDeprecations.tsx
  assets/src/components/cd/services/ServiceErrors.tsx
  assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
  assets/src/components/utils/List.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/utils/clusterTags.tsx
  assets/yarn.lock
  lib/console/deployments/helm/cache.ex
  lib/console/schema/tag.ex
  test/console/graphql/queries/deployments/cluster_queries_test.exs
Labels: enhancement

#627 feat: Add Errors subpage
  assets/package.json
  assets/src/components/builds/Build.tsx
  assets/src/components/builds/build/BuildTimer.tsx
  assets/src/components/cd/clusters/ClusterHealthChip.tsx
  assets/src/components/cd/globalSettings/GlobalSettings.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/services/ServicesTableErrors.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceErrors.tsx
  assets/src/components/db-management/DatabasesList.tsx
  assets/src/components/layout/SideNavEntries.tsx
  assets/src/components/profile/AccessTokens.tsx
  assets/src/components/utils/TooltipTime.tsx
  assets/src/routes/cdRoutes.tsx
  assets/src/utils/time.ts
  assets/yarn.lock
Labels: enhancement

#630 fix: Infinite render on some Service Settings pages
  assets/.gitignore
  assets/package.json
  assets/src/components/cd/services/deployModal/DeployServiceSettingsHelm.tsx
  assets/src/components/hooks/useUpdateState.tsx
  assets/src/utils/isNonNullable.ts
  assets/src/utils/isSubsetEqual.test.ts
  assets/src/utils/isSubsetEqual.ts
  assets/yarn.lock
Labels: bug-fix

#631 Support querying scm/pr automation objects by name alongsideid
  assets/src/generated/graphql.ts
  lib/console/deployments/git.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/resolvers/deployments/git.ex
  schema/schema.graphql
Labels: enhancement

#632 Add detach service api
  Dockerfile
  assets/src/generated/graphql.ts
  lib/console/deployments/services.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments/service.ex
  schema/schema.graphql
  test/console/deployments/services_test.exs
  test/console/graphql/mutations/deployments/services_mutations_test.exs
Labels: enhancement

#629 feat: update RBAC for secret/configmap and change crd schema
  .github/workflows/publish.yaml
  charts/controller/crds/deployments.plural.sh_clusters.yaml
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  charts/controller/templates/manager-rbac.yaml
  controller/Makefile
  controller/api/v1alpha1/cluster_types.go
  controller/api/v1alpha1/common_types.go
  controller/api/v1alpha1/globalservice_types.go
  controller/api/v1alpha1/servicedeployment_types.go.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_clusters.yaml
  controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  controller/config/crd/kustomization.yaml
  controller/config/rbac/role.yaml
  controller/internal/client/common.go
  controller/internal/client/console.go
  controller/internal/controller/cluster_controller.go
  controller/internal/controller/common.go
  controller/internal/controller/gitrepository_controller.go
  controller/internal/controller/globalservice_controller.go
  controller/internal/controller/globalservice_test.go
  controller/internal/controller/pipeline_controller_test.go
  controller/internal/controller/provider_controller.go
  controller/internal/controller/servicedeployment_controller.go
  controller/internal/controller/servicedeployment_controller_test.go
  controller/internal/test/mocks/ConsoleClient_mock.go
Labels: enhancement

#635 Fix null pointer crash in console controller
  charts/controller/values.yaml
  controller/internal/controller/servicedeployment_controller.go
Labels: enhancement

#638 fix: service deployment name/namespace override
  controller/api/v1alpha1/servicedeployment_types.go.go
  controller/internal/controller/servicedeployment_controller.go
Labels: bug-fix

#637 Backup/Restore data definitions, Service Context CRUD
  README.md
  assets/src/generated/graphql.ts
  lib/console/deployments/backups.ex
  lib/console/deployments/helm/cache.ex
  lib/console/deployments/policies/policies.ex
  lib/console/deployments/services.ex
  lib/console/external_graphql.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/backup.ex
  lib/console/graphql/deployments/pipeline.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/backup.ex
  lib/console/graphql/resolvers/deployments/pipeline.ex
  lib/console/graphql/resolvers/deployments/service.ex
  lib/console/schema/cluster.ex
  lib/console/schema/cluster_backup.ex
  lib/console/schema/cluster_restore.ex
  lib/console/schema/cluster_restore_history.ex
  lib/console/schema/object_store.ex
  lib/console/schema/service.ex
  lib/console/schema/service_context.ex
  lib/console/schema/service_context_binding.ex
  priv/repo/migrations/20240127024051_backup_restore.exs
  schema/schema.graphql
  test/console/deployments/backups_test.exs
  test/console/deployments/services_test.exs
  test/console/graphql/mutations/deployments/backup_mutations_test.exs
  test/console/graphql/mutations/deployments/services_mutations_test.exs
  test/console/graphql/queries/deployments/backup_queries_test.exs
  test/console/graphql/queries/deployments/pipeline_queries_test.exs
  test/support/factory.ex
Labels: enhancement

#619 feat: Add Velero chart
  charts/velero-s3-proxy/.helmignore
  charts/velero-s3-proxy/Chart.lock
  charts/velero-s3-proxy/Chart.yaml
  charts/velero-s3-proxy/charts/s3-proxy-0.3.1.tgz
  charts/velero-s3-proxy/charts/velero-5.2.2.tgz
  charts/velero-s3-proxy/values.yaml
  charts/velero-s3-proxy/values.yaml.liquid
  charts/velero/.helmignore
  charts/velero/Chart.lock
  charts/velero/Chart.yaml
  charts/velero/charts/velero-5.2.2.tgz
  charts/velero/values.yaml
  charts/velero/values.yaml.liquid
Labels: enhancement

#642 Add restore/object store cluster sideloads
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/git.ex
  schema/schema.graphql
Labels: enhancement

#643 Check if an add-on is blocking for next not current k8s version
  lib/console/deployments/compatibilities/schema.ex
  test/console/graphql/queries/deployments/cluster_queries_test.exs
Labels: enhancement
