Repository pluralsh/console, pull requests merged in 2024-03, with the labels that each got.

#739 Add Pull Request notifications
  assets/src/components/account/personas/PersonaAttributesEdit.tsx
  assets/src/components/account/personas/PersonaCreate.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/personas.graphql
  lib/console/deployments/events.ex
  lib/console/deployments/git.ex
  lib/console/deployments/pr/impl/github.ex
  lib/console/deployments/pubsub/consumers/notifications.ex
  lib/console/deployments/pubsub/protocols/notifiable.ex
  lib/console/graphql/deployments/notification.ex
  lib/console/graphql/users.ex
  lib/console/schema/notification_router.ex
  lib/console/schema/persona.ex
  lib/console/schema/router_filter.ex
  priv/notifications/slack/pr.create.json.eex
  priv/notifications/teams/pr.create.json.eex
  priv/repo/migrations/20240229224117_add_pr_filter_regex.exs
  schema/schema.graphql
  test/console/deployments/git_test.exs
  test/console/deployments/pubsub/notification_test.exs
Labels: enhancement

#738 fix: Link to PR not working when PR list is inside modal
  assets/src/components/pr/queue/PrQueueColumns.tsx
Labels: bug-fix

#742 Add https for console url if not present
  lib/console/deployments/git.ex
  lib/console/deployments/pr/impl/gitlab.ex
  lib/console/graphql/resolvers/kubernetes.ex
  lib/console_web/controllers/webhook_controller.ex
  lib/console_web/router.ex
  rel/config/console.exs
  test/console_web/controllers/webhook_controller_test.exs
Labels: enhancement

#743 feat: Create SCM webhook from SCM connections and list webhooks
  assets/src/components/cd/pipelines/PipelineDetails.tsx
  assets/src/components/pr/Pr.tsx
  assets/src/components/pr/queue/PrQueueColumns.tsx
  assets/src/components/pr/scm/CreateScmWebhook.tsx
  assets/src/components/pr/scm/PrScmConnectionsColumns.tsx
  assets/src/components/pr/scm/ScmWebhooks.tsx
  assets/src/components/pr/scm/ScmWebhooksColumns.tsx
  assets/src/components/utils/StopPropagation.tsx
  assets/src/components/utils/table/TruncateStart.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/automation.graphql
  assets/src/routes/prRoutes.tsx
  assets/src/routes/prRoutesConsts.tsx
  assets/src/utils/graphql.ts
Labels: enhancement, frontend

#744 Deliver notifications for pr close/merge events
  lib/console/deployments/events.ex
  lib/console/deployments/git.ex
  lib/console/deployments/pipelines.ex
  lib/console/deployments/pubsub/protocols/notifiable.ex
  lib/console/schema/notification_router.ex
  priv/notifications/slack/pipeline.update.json.eex
  priv/notifications/slack/pr.close.json.eex
  priv/notifications/teams/pipeline.update.json.eex
  priv/notifications/teams/pr.close.json.eex
  test/console/deployments/pubsub/notification_test.exs
Labels: enhancement

#747 feat: Show badge with open PR count in Pipeline Stage nodes
  assets/src/components/cd/pipelines/nodes/StageNode.tsx
  assets/src/components/help/CountBadge.tsx
Labels: enhancement, frontend

#749 fix: PR status chip colors
  assets/src/components/pr/queue/PrQueueColumns.tsx
Labels: bug-fix, frontend

#751 feat: add notification sink
  charts/controller/crds/deployments.plural.sh_notificationsinks.yaml
  charts/controller/templates/manager-rbac.yaml
  controller/PROJECT
  controller/api/v1alpha1/notificationsink_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_notificationsinks.yaml
  controller/config/rbac/notificationsink_editor_role.yaml
  controller/config/rbac/notificationsink_viewer_role.yaml
  controller/config/rbac/role.yaml
  controller/config/samples/deployments_v1alpha1_notificationsink.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/client/console.go
  controller/internal/client/notification.go
  controller/internal/controller/notificationsink_controller.go
  controller/internal/controller/notificationsink_scope.go
  controller/internal/controller/prautomationtrigger_controller.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_notificationsinks.yaml
Labels: enhancement

#750 feat: PR automation modifications
  assets/src/components/pr/automations/CreatePrModal.tsx
Labels: enhancement, frontend

#752 feat: Implement valuesFrom for helm service crd
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  controller/api/v1alpha1/servicedeployment_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/controller/servicedeployment_controller.go
  controller/internal/controller/servicedeployment_controller_test.go
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
Labels: enhancement

#748 Add flux to base chart
  .github/workflows/add-asana-comment.yml
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.20.tgz
  charts/console/charts/flux2-2.11.1.tgz
  charts/console/charts/kas-0.0.5.tgz
  charts/console/values.yaml
  templates/values.yaml.liquid
Labels: enhancement

#754 Make cluster id immutable for services
  assets/src/components/pr/queue/PrQueueColumns.tsx
  lib/console/deployments/services.ex
  lib/console/schema/service.ex
  test/console/deployments/services_test.exs
Labels: enhancement

#755 Fix schema for notification routers
  assets/src/generated/graphql.ts
  config/config.exs
  lib/console/deployments/notifications.ex
  lib/console/graphql/deployments/notification.ex
  lib/console/schema/scm_webhook.ex
  rel/config/console.exs
  schema/schema.graphql
Labels: bug-fix, hotfix

#758 feat: add notification router
  charts/controller/crds/deployments.plural.sh_notificationrouters.yaml
  charts/controller/crds/deployments.plural.sh_notificationsinks.yaml
  charts/controller/templates/manager-rbac.yaml
  controller/PROJECT
  controller/api/v1alpha1/notificationrouter_types.go
  controller/api/v1alpha1/notificationsink_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_notificationrouters.yaml
  controller/config/crd/bases/deployments.plural.sh_notificationsinks.yaml
  controller/config/rbac/notificationrouter_editor_role.yaml
  controller/config/rbac/notificationrouter_viewer_role.yaml
  controller/config/rbac/role.yaml
  controller/config/samples/deployments_v1alpha1_notificationrouter.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/client/console.go
  controller/internal/client/notification.go
  controller/internal/controller/notificationrouter_controller.go
  controller/internal/controller/notificationrouter_scope.go
  controller/internal/controller/notificationsink_controller.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_notificationrouters.yaml
  plural/helm/console/crds/deployments.plural.sh_notificationsinks.yaml
Labels: enhancement

#760 Implement OPA gatekeeper viz apis
  assets/src/generated/graphql.ts
  lib/console/deployments/policies/rbac.ex
  lib/console/deployments/policy.ex
  lib/console/deployments/pr/impl/github.ex
  lib/console/deployments/pr/impl/gitlab.ex
  lib/console/external_graphql.ex
  lib/console/graphql.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/notification.ex
  lib/console/graphql/deployments/policy.ex
  lib/console/graphql/policies.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/base.ex
  lib/console/graphql/resolvers/deployments/policy.ex
  lib/console/schema/constraint_violation.ex
  lib/console/schema/policy_constraint.ex
  priv/repo/migrations/20240307164829_add_constraints_violations.exs
  schema/schema.graphql
  test/console/deployments/policy_test.exs
  test/console/graphql/mutations/deployments/policy_mutations_test.exs
  test/console/graphql/queries/deployments/cluster_queries_test.exs
  test/console/graphql/queries/deployments/policy_queries_test.exs
  test/support/factory.ex
Labels: enhancement

#762 fix the valuesFrom fetch for service helm values
  controller/api/v1alpha1/servicedeployment_types.go
  controller/internal/controller/servicedeployment_controller.go
  controller/internal/controller/servicedeployment_controller_test.go
Labels: enhancement

#763 More advanced policy constraint queries
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  controller/api/v1alpha1/servicedeployment_types.go
  controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  controller/internal/controller/servicedeployment_controller.go
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/policy.ex
  lib/console/graphql/resolvers/deployments/policy.ex
  lib/console/schema/policy_constraint.ex
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
  schema/schema.graphql
  test/console/graphql/queries/deployments/policy_queries_test.exs
Labels: enhancement

#766 Fix some small issues with notification router reconciliation
  charts/controller/crds/deployments.plural.sh_notificationrouters.yaml
  controller/api/v1alpha1/notificationrouter_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_notificationrouters.yaml
  controller/internal/controller/notificationrouter_controller.go
  controller/internal/utils/kubernetes.go
  plural/helm/console/crds/deployments.plural.sh_notificationrouters.yaml
Labels: enhancement

#765 fix: Sink search not working when editing notification router
  assets/src/components/notifications/routers/CreateNotificationRouterModal.tsx
  assets/src/components/notifications/routers/EditNotificationRouterModal.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/notifications.graphql
Labels: bug-fix

#770 Refactor loki endpoints to json-structure the query format, and auto-…
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/observability.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/observability.ex
  lib/console/graphql/resolvers/user.ex
  lib/console/graphql/schema/base.ex
  lib/console/graphql/users.ex
  lib/console/schema/user.ex
  lib/console/services/observability.ex
  lib/console/services/users.ex
  schema/schema.graphql
  test/console/graphql/mutations/user_mutations_test.exs
  test/console/graphql/queries/deployments/service_queries_test.exs
Labels: enhancement, hotfix

#772 feat: Implement refresh tokens in UI
  assets/package.json
  assets/src/components/contexts.tsx
  assets/src/components/graphql/users.js
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/login/Invite.tsx
  assets/src/components/login/LinkLogin.tsx
  assets/src/components/login/Login.tsx
  assets/src/components/login/OauthCallback.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/users.graphql
  assets/src/helpers/auth.js
  assets/src/helpers/client.js
  assets/src/helpers/refreshToken.ts
  assets/yarn.lock
Labels: enhancement, frontend

#771 Add pod monitor configuration to standalone console chart
  assets/src/generated/graphql.ts
  charts/console/templates/monitor.yaml
  charts/console/templates/prometheusrule.yaml
  config/config.exs
  lib/console.ex
  lib/console/application.ex
  lib/console/deployments/git/agent.ex
  lib/console/deployments/git/statistics.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/service.ex
  lib/console/prom/ecto.ex
  lib/console/prom/metrics.ex
  lib/console/prom/scraper.ex
  lib/console/prom/setup.ex
  mix.exs
  mix.lock
  rel/config/console.exs
  schema/schema.graphql
  test/console/graphql/queries/deployment_queries_test.exs
  test/console/graphql/queries/deployments/service_queries_test.exs
Labels: enhancement

#778 Small query improvements for policies
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/policy.ex
  lib/console/graphql/resolvers/deployments/policy.ex
  lib/console/schema/policy_constraint.ex
  lib/kube/models.ex
  lib/kube/parser.ex
  schema/schema.graphql
Labels: enhancement, hotfix

#773 fix: Refreshing tokens too soon
  .github/workflows/assets.yaml
  assets/package.json
  assets/src/components/contexts.tsx
  assets/src/helpers/auth.js
  assets/src/helpers/client.js
  assets/src/helpers/refreshToken.ts
  assets/yarn.lock
  config/config.exs
  lib/console/services/users.ex
Labels: bug-fix

#776 fix: UI/UX layout issues
  assets/src/components/apps/app/components/ComponentList.tsx
  assets/src/components/apps/app/components/Components.tsx
  assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
  assets/src/components/cd/services/service/ServiceKick.tsx
  assets/src/components/component/info/Service.tsx
Labels: bug-fix, frontend

#777 feat: Add proper support for ServiceDeployment in components tab
  assets/src/components/component/ComponentDetails.tsx
  assets/src/components/component/ComponentInfo.tsx
  assets/src/components/component/info/Conditions.tsx
  assets/src/components/component/info/PluralServiceDeployment.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/kubernetes/pluralServiceDeployment.graphql
Labels: enhancement, frontend

#779 fix: Incorrect cluster id in Component page `View service` link
  assets/src/components/component/ComponentDetails.tsx
Labels: bug-fix

#780 Fix readme sideload for runtime services
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  .gitignore
  assets/src/components/cd/cluster/addon/ClusterAddOnDetails.tsx
  assets/src/components/cd/cluster/addon/ClusterAddOnReadme.tsx
  assets/src/components/cd/cluster/addon/ClusterAddOnReleases.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  config/pubkey.pem
  lib/console/deployments/settings.ex
Labels: enhancement, hotfix

#782 fix: User could get logged out randomly if they temporarily lost connection
  assets/codegen.yml
  assets/package.json
  assets/src/generated/fragments.json
  assets/src/helpers/auth.ts
  assets/src/helpers/client.ts
  assets/src/helpers/refreshToken.ts
  assets/yarn.lock
Labels: bug-fix

#783 Add Log Views to CD pages
  assets/src/components/apps/app/logs/LogContent.tsx
  assets/src/components/apps/app/logs/LogsCard.tsx
  assets/src/components/cd/cluster/Cluster.tsx
  assets/src/components/cd/cluster/ClusterLogs.tsx
  assets/src/components/cd/globalSettings/GlobalSettings.tsx
  assets/src/components/cd/logs/Logs.tsx
  assets/src/components/cd/logs/LogsCard.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceLogs.tsx
  assets/src/components/contexts/DeploymentSettingsContext.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/graph/cdServices.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
  charts/console/templates/ingress.yaml
  charts/console/values.yaml
  controller/internal/controller/servicedeployment_controller.go
  lib/console/deployments/global.ex
  lib/console/schema/policy_constraint.ex
  lib/console/services/observability.ex
  lib/loki/client.ex
  plural/helm/console/templates/ingress.yaml
  plural/helm/console/values.yaml
  priv/repo/migrations/20240318142211_modify_description.exs
Labels: enhancement

#784 Implement Managed Namespaces Api
  assets/src/generated/graphql.ts
  config/config.exs
  config/prod.exs
  config/test.exs
  lib/console/deployments/cron.ex
  lib/console/deployments/events.ex
  lib/console/deployments/global.ex
  lib/console/deployments/policies/policies.ex
  lib/console/deployments/pubsub/recurse.ex
  lib/console/external_graphql.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/global.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/global.ex
  lib/console/schema/cluster.ex
  lib/console/schema/managed_namespace.ex
  lib/console/schema/namespace_cluster.ex
  lib/console/schema/namespace_instance.ex
  lib/console/schema/service.ex
  lib/console/services/users.ex
  priv/repo/migrations/20240318223450_add_managed_namespaces.exs
  rel/config/console.exs
  schema/schema.graphql
  test/console/deployments/global_test.exs
  test/console/deployments/pubsub/recurse_test.exs
  test/console/graphql/mutations/deployments/global_mutations_test.exs
  test/console/graphql/queries/deployments/global_queries_test.exs
  test/console/services/users_test.exs
  test/support/factory.ex
Labels: enhancement

#786 Fix annoying redirect bug
  assets/src/components/PluralApi.jsx
Labels: bug-fix, hotfix

#788 Bump agent version and support airgapped compatibilities + deprecations
  AGENT_VERSION
  assets/src/components/cd/pipelines/PipelineDetails.tsx
  lib/console/deployments/compatibilities/schema.ex
  lib/console/deployments/compatibilities/table.ex
  lib/console/deployments/deprecations/table.ex
  lib/console/deployments/static.ex
  priv/notifications/slack/service.update.json.eex
  rel/config/console.exs
Labels: enhancement

#789 Reduce some repo clutter
  assets/src/components/cd/pipelines/PipelinesColumns.tsx
  assets/src/components/cd/pipelines/nodes/ApprovalNode.tsx
  assets/src/components/cd/pipelines/nodes/BaseNode.tsx
  assets/src/components/cd/pipelines/nodes/JobNode.tsx
  assets/src/components/cd/pipelines/nodes/TestsNode.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdPipelines.graphql
  lib/console/graphql/deployments/pipeline.ex
  lib/console/schema/pipeline.ex
  lib/console/schema/pipeline_gate.ex
  lib/kube/models.ex
  priv/notifications/slack/cluster.create.json.eex
  priv/notifications/slack/pipeline.update.json.eex
  priv/notifications/slack/pr.close.json.eex
  priv/notifications/slack/pr.create.json.eex
  schema/schema.graphql
  static/crds/application.yaml
  static/crds/cert-manager.yaml
  static/crds/clusters.cluster.x-k8s.io.yaml
  static/crds/config-overlay.yaml
  static/crds/dashboard.yaml
  static/crds/flagger-canary.yaml
  static/crds/helmchart.yaml
  static/crds/helmrepository.yaml
  static/crds/license.yaml
  static/crds/logfilter.yaml
  static/crds/plural-cluster.yaml
  static/crds/plural-gitrepo.yaml
  static/crds/plural-service.yaml
  static/crds/postgresql.yaml
  static/crds/runbook.yaml
  static/crds/slashcommand.yaml
  static/crds/ss-resize.yaml
  static/crds/upgrade-plan.yaml
  static/crds/vpa.yaml
  static/crds/wireguardpeer.yaml
  static/crds/wireguardserver.yaml
  test-apps/example/docs/test.md
Labels: enhancement

#791 Disable oidc provider invites when external oidc is used
  assets/src/components/account/users/OIDCInvite.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/users.graphql
  lib/console/graphql/configuration.ex
  priv/notifications/slack/pipeline.update.json.eex
  schema/schema.graphql
Labels: enhancement

#792 Add apis for managing template viewing in-ui
  Dockerfile
  assets/src/generated/graphql.ts
  lib/console/deployments/events.ex
  lib/console/deployments/pubsub/protocols/broadcastable.ex
  lib/console/deployments/services.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments/service.ex
  rel/config/console.exs
  schema/schema.graphql
  test/console/deployments/services_test.exs
  test/console/graphql/mutations/deployments/services_mutations_test.exs
  test/console/graphql/queries/deployments/service_queries_test.exs
Labels: enhancement

#795 Fix cert manager compatibility
  static/compatibilities/cert-manager.yaml
Labels: enhancement

#796 Forgot tls disabling for a few other ingresses, also added rewrite he…
  .github/workflows/publish-cypress.yaml
  AGENT_VERSION
  Dockerfile
  charts/console/templates/deployment.yaml
  charts/console/templates/ingress.yaml
  charts/console/values.yaml
  charts/controller/templates/deployment.yaml
  charts/controller/values.yaml
  config/prod.exs
  lib/console/application.ex
  lib/console/clustering/bootstrapper.ex
  lib/console/commands/configuration.ex
  lib/console/deployments/git/agent.ex
  lib/console/deployments/global.ex
  lib/console/deployments/pubsub/recurse.ex
  lib/console/graphql/deployments/global.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/schema/managed_namespace.ex
  lib/console/schema/service_template.ex
  plural/helm/kas/Chart.yaml
  plural/helm/kas/templates/deployment.yaml
  plural/helm/kas/templates/ingress.yaml
  plural/helm/kas/values.yaml
  priv/notifications/slack/pr.close.json.eex
  priv/notifications/slack/pr.create.json.eex
  priv/repo/migrations/20240327015933_add_service_template.exs
  schema/schema.graphql
  test/console/deployments/pubsub/recurse_test.exs
Labels: enhancement

#798 feat: update cluster tags
  controller/api/v1alpha1/cluster_types.go
  controller/internal/controller/cluster_controller.go
  controller/internal/controller/cluster_controller_test.go
  controller/internal/test/mocks/ConsoleClient_mock.go
Labels: enhancement
