Repository pluralsh/console, pull requests merged in 2024-12, with the labels that each got.

#1632 Fix some compiler warnings
  .tool-versions
  Dockerfile
  README.md
  assets/src/archive/components/ClusterConditions.tsx
  assets/src/components/cd/cluster/ClusterMetadata.tsx
  assets/src/components/cd/clusters/ClustersColumns.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/helpers/client.ts
  config/test.exs
  go/controller/docs/api.md
  lib/console/cached/cluster_nodes.ex
  lib/console/deployments/clusters.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/pr/impl/gitlab.ex
  lib/console/graphql/apq.ex
  lib/console_web/guardian_pipeline.ex
  mix.exs
  mix.lock
  test/console/deployments/cron_test.exs
Labels: enhancement, hotfix

#1638 Fix cd action
  .github/workflows/publish.yaml
Labels: bug-fix, hotfix

#1641 fix: Replace problematic docs fragment
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  go/controller/api/v1alpha1/prautomation_types.go
  go/controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  go/controller/docs/api.md
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
Labels: bug-fix

#1642 Check smtp config
  charts/controller/Chart.yaml
  charts/controller/templates/deployment.yaml
  lib/console/mailer.ex
  mix.exs
  mix.lock
Labels: bug-fix, hotfix

#1645 Begin implementing tool calling
  assets/src/components/ai/AIPanel.tsx
  assets/src/components/ai/chatbot/AISuggestFix.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/ai.graphql
  assets/src/graph/cdGlobalSettings.graphql
  go/client/models_gen.go
  lib/console.ex
  lib/console/ai/fixer.ex
  lib/console/ai/provider.ex
  lib/console/ai/provider/anthropic.ex
  lib/console/ai/provider/azure.ex
  lib/console/ai/provider/bedrock.ex
  lib/console/ai/provider/ollama.ex
  lib/console/ai/provider/openai.ex
  lib/console/ai/provider/vertex.ex
  lib/console/ai/tool.ex
  lib/console/ai/tools/pr.ex
  lib/console/deployments/git.ex
  lib/console/deployments/pr/dispatcher.ex
  lib/console/deployments/pr/git.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/deployments/settings.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/schema/catalog.ex
  lib/console/schema/deployment_settings.ex
  lib/console/schema/scm_connection.ex
  priv/repo/migrations/20241202210945_add_scm_connection_default.exs
  priv/tools/pr.json
  schema/schema.graphql
  test/console/ai/fixer_test.exs
  test/console/graphql/queries/ai_queries_test.exs
  test/console/graphql/queries/deployments/cluster_queries_test.exs
Labels: enhancement

#1649 feat: CRD docs check
  .github/workflows/controller-ci.yaml
Labels: enhancement

#1647 Touchups for pr tool calling
  assets/src/components/ai/chatbot/AISuggestFix.tsx
  assets/src/components/cd/cluster/ClusterInsightComponent.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/ai.graphql
  assets/src/helpers/client.ts
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  go/controller/docs/api.md
  lib/console/ai/evidence/base.ex
  lib/console/ai/fixer.ex
  lib/console/ai/provider/anthropic.ex
  lib/console/ai/provider/azure.ex
  lib/console/ai/provider/bedrock.ex
  lib/console/ai/provider/ollama.ex
  lib/console/ai/provider/openai.ex
  lib/console/ai/provider/vertex.ex
  lib/console/ai/tools/pr.ex
  lib/console/deployments/clusters.ex
  lib/console/deployments/pr/git.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/deployments/policy.ex
  lib/console/graphql/deployments/settings.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/schema/deployment_settings.ex
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
  priv/tools/pr.json
  schema/schema.graphql
  test/console/ai/fixer_test.exs
  test/console/graphql/queries/ai_queries_test.exs
Labels: enhancement

#1655 update DS
  assets/package.json
  assets/src/components/ai/chatbot/AISuggestFix.tsx
  assets/src/components/ai/chatbot/ChatMessage.tsx
  assets/src/components/ai/chatbot/Chatbot.tsx
  assets/src/components/ai/chatbot/ChatbotMarkdown.tsx
  assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#1656 improve tree/table switch
  assets/src/components/cd/cluster/Cluster.tsx
  assets/src/components/utils/ButtonGroup.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
Labels: enhancement, frontend

#1654 prep next release
  assets/src/components/layout/Sidebar.tsx
  assets/src/generated/graphql.ts
  charts/console-rapid/Chart.yaml
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  go/client/client.go
  go/client/graph/users.graphql
  go/client/models_gen.go
  go/controller/api/v1alpha1/catalog_types.go
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/prautomation_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  go/controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  go/controller/docs/api.md
  go/controller/internal/controller/prautomation_attributes.go
  lib/console/ai/provider.ex
  lib/console/ai/provider/anthropic.ex
  lib/console/graphql/deployments/policy.ex
  lib/console/graphql/deployments/settings.ex
  lib/console/graphql/resolvers/deployments/policy.ex
  lib/console/graphql/resolvers/user.ex
  lib/console/graphql/users.ex
  lib/console/schema/deployment_settings.ex
  lib/console/schema/vulnerability_report.ex
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
  schema/schema.graphql
  test/console/graphql/mutations/user_mutations_test.exs
  test/console/graphql/queries/deployments/policy_queries_test.exs
Labels: enhancement

#1652 feat(ui): global services redesign
  assets/src/components/cd/cluster/ClusterAddOns.tsx
  assets/src/components/cd/globalServices/details/GlobalService.tsx
  assets/src/components/cd/globalServices/details/GlobalServiceInfo.tsx
  assets/src/components/cd/globalServices/details/GlobalServiceServices.tsx
  assets/src/components/cd/globalServices/details/GlobalServiceSidecar.tsx
  assets/src/components/cd/globalServices/details/TagsModal.tsx
  assets/src/components/cd/globalServices/details/TemplateModal.tsx
  assets/src/components/cd/globalServices/details/columns.tsx
  assets/src/components/cd/globalServices/details/utils.ts
  assets/src/components/cd/namespaces/details/ManagedNamespaceInfo.tsx
  assets/src/components/utils/PropCard.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdGlobalServices.graphql
  assets/src/routes/cdRoutes.tsx
Labels: enhancement

#1658 Minor changes pre-release
  assets/src/components/cd/clusters/ClusterHealthChip.tsx
  assets/src/components/cd/globalServices/details/columns.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  go/client/models_gen.go
  go/controller/internal/controller/prautomation_attributes.go
  go/controller/internal/controller/prautomation_controller.go
  go/controller/internal/controller/prautomation_controller_test.go
  lib/console/graphql/deployments/cluster.ex
  lib/console/schema/cluster.ex
  lib/console/schema/pr_automation.ex
  schema/schema.graphql
  test/console/graphql/mutations/deployments/git_mutations_test.exs
Labels: enhancement, hotfix

#1651 fix: Chat background and border improvements
  assets/src/components/ai/AITable.tsx
  assets/src/components/ai/chatbot/Chatbot.tsx
  assets/src/components/commandpalette/commands.ts
  assets/src/components/home/ServiceCatalog.tsx
  assets/src/components/layout/Sidebar.tsx
Labels: bug-fix

#1667 fix: Catalog column sizing
  assets/src/components/catalog/CatalogsGrid.tsx
Labels: bug-fix

#1668 Minor pre-relase fixes
  assets/src/components/pr/automations/CreatePrModal.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  go/client/client.go
  go/client/models_gen.go
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/deployments/policy.ex
  schema/schema.graphql
Labels: enhancement

#1670 potentially fix anthropic
  lib/console/ai/provider/anthropic.ex
  lib/console/ai/provider/azure.ex
  lib/console/ai/provider/vertex.ex
Labels: enhancement, hotfix

#1671 Fix compatibility scrapers skipahead
  static/compatibilities/amazon-vpc-cni-k8s.yaml
  static/compatibilities/aws-ebs-csi-driver.yaml
  static/compatibilities/aws-efs-csi-driver.yaml
  static/compatibilities/aws-load-balancer-controller.yaml
  static/compatibilities/contour.yaml
  static/compatibilities/coredns.yaml
  static/compatibilities/external-dns.yaml
  static/compatibilities/ingress-nginx.yaml
  static/compatibilities/jaeger.yaml
  static/compatibilities/traefik.yaml
  utils/compatibility/utils.py
Labels: bug-fix, hotfix

#1674 feat: PR automation icons
  assets/src/components/catalog/Catalog.tsx
  assets/src/components/catalog/CatalogsGrid.tsx
  assets/src/components/pr/automations/PrAutomationsColumns.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/automation.graphql
  assets/src/utils/icon.ts
Labels: enhancement

#1672 Make global service delete cascade by default
  lib/console/deployments/global.ex
  lib/console/deployments/statistics.ex
  lib/console/prom/plugin.ex
  lib/console/schema/stack.ex
  test/console/deployments/global_test.exs
Labels: enhancement

#1677 Auto-parse cvss vectors and present in gql
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  lib/console/utils/vuln.ex
Labels: enhancement

#1675 chore: bump used CLI version to v0.10.3
  Dockerfile
Labels: dependencies

#1679 Add parsed vulnerability schemas
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/graphql/deployments/policy.ex
  lib/console/schema/vulnerability.ex
  schema/schema.graphql
Labels: enhancement

#1680 add k8s dashboard link to ingress certs
  assets/src/components/component/info/IngressCertificates.tsx
Labels: enhancement, frontend

#1663 add vulnerability reports UI
  AGENT_VERSION
  Dockerfile
  assets/src/components/cd/ContinuousDeployment.tsx
  assets/src/components/cd/cluster/pod/PodContainers.tsx
  assets/src/components/cd/services/service/component/Components.tsx
  assets/src/components/commandpalette/commands.ts
  assets/src/components/home/violations/ConstraintViolationsCard.tsx
  assets/src/components/home/violations/ConstraintViolationsChart.tsx
  assets/src/components/kubernetes/Cluster.tsx
  assets/src/components/kubernetes/common/NamespaceMultiSelect.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/policies/policy/Policy.tsx
  assets/src/components/security/Security.tsx
  assets/src/components/security/policies/Policies.tsx
  assets/src/components/security/policies/PoliciesColumns.tsx
  assets/src/components/security/policies/PoliciesFilter.tsx
  assets/src/components/security/policies/PoliciesTable.tsx
  assets/src/components/security/policies/PoliciesViolationsGauge.tsx
  assets/src/components/security/policies/policy/AggregatedPolicyStatsChip.tsx
  assets/src/components/security/policies/policy/Policy.tsx
  assets/src/components/security/policies/policy/affectedResources/PolicyAffectedResources.tsx
  assets/src/components/security/policies/policy/affectedResources/ViolationsTableColumns.tsx
  assets/src/components/security/policies/policy/details/PolicyDetails.tsx
  assets/src/components/security/policies/usePolicyChartsData.tsx
  assets/src/components/security/vulnerabilities/VulnDetailExpanded.tsx
  assets/src/components/security/vulnerabilities/VulnReportDetails.tsx
  assets/src/components/security/vulnerabilities/VulnReportDetailsTableCols.tsx
  assets/src/components/security/vulnerabilities/VulnReports.tsx
  assets/src/components/security/vulnerabilities/VulnReportsTable.tsx
  assets/src/components/security/vulnerabilities/VulnReportsTableCols.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/vulnerabilities.graphql
  assets/src/helpers/client.ts
  assets/src/routes/consoleRoutes.tsx
  assets/src/routes/policiesRoutes.tsx
  assets/src/routes/policiesRoutesConsts.tsx
  assets/src/routes/securityRoutes.tsx
  assets/src/routes/securityRoutesConsts.tsx
  lib/console/cost/extract.ex
  lib/console/cost/loader.ex
  lib/console/cost/utils.ex
  lib/console/local_repo.ex
  lib/console/prom/plugin.ex
  lib/console/schema/vulnerability.ex
  mix.exs
  mix.lock
  schema/schema.graphql
  test/console/cost/loader_test.exs
  test/console/deployments/policy_test.exs
Labels: enhancement, frontend

#1687 add ingestClusterCost mutation
  go/client/client.go
  go/client/graph/kubecost.graphql
  go/client/models_gen.go
Labels: enhancement

#1684 Revert back to alpine base images
  Dockerfile
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/service.ex
  lib/console/graphql/schema/base.ex
  lib/console/schema/service.ex
Labels: enhancement

#1688 update aws efs scraper
  .vscode/settings.json
  static/compatibilities/aws-efs-csi-driver.yaml
  utils/compatibility/scrapers/aws-efs-csi-driver.py
Labels: enhancement

#1695 Add search/filter queries for cost data
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  go/controller/docs/api.md
  go/controller/internal/controller/deploymentsettings_controller.go
  lib/console/deployments/pr/dispatcher.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/settings.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/schema/cluster_namespace_usage.ex
  lib/console/schema/cluster_scaling_recommendation.ex
  lib/console/schema/cluster_usage.ex
  lib/console/schema/deployment_settings.ex
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
  priv/repo/migrations/20241218145152_add_mgmt_repo_setting.exs
  schema/schema.graphql
Labels: enhancement

#1696 Downcase mgmt identifier for mgmt repo substitution
  AGENT_VERSION
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/ai/fixer/parent.ex
  lib/console/cost/ingester.ex
  lib/console/deployments/pr/dispatcher.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/schema/cluster_usage.ex
  priv/repo/migrations/20241218235644_drop_service_id_fkey.exs
  priv/repo/migrations/20241219022052_add_node_cost.exs
  schema/schema.graphql
Labels: enhancement

#1698 enhancement: Simplify resync cooldown logic
  assets/src/components/hooks/useSyncCooldown.tsx
  assets/src/components/utils/KickButton.tsx
Labels: enhancement

#1692 add upcoming releses for cert-manager scraper
  static/compatibilities/cert-manager.yaml
  utils/compatibility/scrapers/cert-manager.py
Labels: enhancement

#1699 feat: add stack ref information to service deployment
  assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
  assets/src/components/stacks/common/StackStatusChip.tsx
  assets/src/components/stacks/common/StackStatusIcon.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/cdServices.graphql
Labels: enhancement

#1693 add cost management UI
  assets/package.json
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/cd/services/ClusterTagsFilter.tsx
  assets/src/components/commandpalette/commands.ts
  assets/src/components/cost-management/ClusterUsagesTableCols.tsx
  assets/src/components/cost-management/CostManagement.tsx
  assets/src/components/cost-management/CostManagementTreeMap.tsx
  assets/src/components/cost-management/details/ClusterScalingRecsTableCols.tsx
  assets/src/components/cost-management/details/CostManagementDetails.tsx
  assets/src/components/cost-management/details/CostManagementDetailsNamespaces.tsx
  assets/src/components/cost-management/details/CostManagementDetailsRecommendations.tsx
  assets/src/components/hooks/useSyncCooldown.tsx
  assets/src/components/layout/NotificationSeverity.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/security/vulnerabilities/VulnReports.tsx
  assets/src/components/security/vulnerabilities/VulnReportsTable.tsx
  assets/src/components/security/vulnerabilities/VulnReportsTableCols.tsx
  assets/src/components/stacks/Stacks.tsx
  assets/src/components/utils/List.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/costManagement.graphql
  assets/src/routes/consoleRoutes.tsx
  assets/src/routes/costManagementRoutes.tsx
  assets/src/routes/costManagementRoutesConsts.tsx
  assets/src/routes/securityRoutes.tsx
  assets/src/types/react-table.d.ts
  assets/src/utils/clusterTags.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#1702 make cost management tables bigger and allow y scroll
  assets/src/components/cost-management/CostManagement.tsx
  assets/src/components/cost-management/details/CostManagementDetails.tsx
  assets/src/components/cost-management/details/CostManagementDetailsNamespaces.tsx
Labels: enhancement, frontend

#1704 fix: UI tweaks
  assets/src/components/kubernetes/rbac/Rbac.tsx
  assets/src/components/pr/automations/CreatePrModal.tsx
  assets/src/components/utils/KickButton.tsx
Labels: bug-fix

#1700 Prep 0.10.44 release
  AGENT_VERSION
  assets/src/components/cost-management/CostManagement.tsx
  assets/src/components/cost-management/CostManagementTreeMap.tsx
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/cost/ingester.ex
  lib/console/deployments/clusters.ex
  lib/console/graphql/deployments/settings.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  schema/schema.graphql
  static/compatibilities/cert-manager.yaml
  static/compatibilities/external-dns.yaml
  static/compatibilities/traefik.yaml
  test/console/graphql/mutations/deployments/cluster_mutations_test.exs
  utils/compatibility/scrapers/cert-manager.py
Labels: enhancement

#1703 feat: add log driver settings to DeploymentSettings
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  go/controller/docs/api.md
  go/controller/internal/controller/deploymentsettings_controller.go
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
Labels: enhancement

#1709 Optimize the caching of some more cluster fields plus other changes
  assets/package.json
  assets/src/components/ai/chatbot/AISuggestFix.tsx
  assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
  assets/src/components/ai/useStreamTopic.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceDocs.tsx
  assets/src/components/hooks/useChannel.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/graph/cdServices.graphql
  assets/src/helpers/client.ts
  assets/src/routes/cdRoutes.tsx
  assets/yarn.lock
  charts/stateless/.helmignore
  charts/stateless/Chart.yaml
  charts/stateless/templates/NOTES.txt
  charts/stateless/templates/_helpers.tpl
  charts/stateless/templates/deployment.yaml
  charts/stateless/templates/hpa.yaml
  charts/stateless/templates/ingress.yaml
  charts/stateless/templates/service.yaml
  charts/stateless/templates/serviceaccount.yaml
  charts/stateless/values.yaml
  go/client/models_gen.go
  lib/console/ai/chat.ex
  lib/console/ai/fixer/base.ex
  lib/console/ai/policy.ex
  lib/console/ai/stream.ex
  lib/console/cached/cluster_nodes.ex
  lib/console/deployments/clusters.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/git.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/graphql/resolvers/dataloader.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/schema/chat.ex
  lib/console_web/channels/ai_channel.ex
  lib/console_web/channels/graphqlws_socket.ex
  lib/console_web/channels/user_socket.ex
  lib/console_web/endpoint.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20241229194925_add_message_pr.exs
  schema/schema.graphql
  test/console/ai/chat_test.exs
  test/console/deployments/cron_test.exs
  test/console/graphql/queries/deployments/service_queries_test.exs
  test/console_web/channels/ai_channel_test.exs
  test/test_helper.exs
Labels: enhancement

#1710 fix: Make not found errors more detailed
  go/controller/internal/controller/catalog_controller.go
  go/controller/internal/controller/clusterrestore_controller.go
  go/controller/internal/controller/common.go
  go/controller/internal/controller/customstackrun_controller.go
  go/controller/internal/controller/gitrepository_controller.go
  go/controller/internal/controller/globalservice_controller.go
  go/controller/internal/controller/managednamespace_controller.go
  go/controller/internal/controller/notificationrouter_controller.go
  go/controller/internal/controller/observer_controller.go
  go/controller/internal/controller/pipeline_controller.go
  go/controller/internal/controller/pipeline_controller_attributes.go
  go/controller/internal/controller/prautomation_attributes.go
  go/controller/internal/controller/prautomation_controller.go
Labels: bug-fix

#1713 chore: Update docs
  .github/workflows/controller-ci.yaml
  .github/workflows/crd-docs.yaml
  .github/workflows/docs.yaml
Labels: enhancement
