Repository pluralsh/console, pull requests merged in 2024-07, with the labels that each got.

#1125 fix: properly cache-and-network on k8s dashboard resource lists
  assets/src/components/kubernetes/common/ResourceList.tsx
  assets/src/components/kubernetes/workloads/Pods.tsx
Labels: bug-fix

#1123 Custom Stack Definitions CRUD
  assets/src/generated/graphql.ts
  lib/console/deployments/pipelines/stage_worker.ex
  lib/console/deployments/policies/policies.ex
  lib/console/deployments/stacks.ex
  lib/console/deployments/stacks/commands.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  lib/console/schema/pull_request.ex
  lib/console/schema/run_step.ex
  lib/console/schema/service.ex
  lib/console/schema/stack.ex
  lib/console/schema/stack_definition.ex
  priv/repo/migrations/20240628202415_add_stack_definitions.exs
  priv/repo/migrations/20240630124210_add_polled_sha.exs
  schema/schema.graphql
  test/console/deployments/stacks_test.exs
  test/console/graphql/mutations/deployments/stack_mutations_test.exs
  test/support/factory.ex
Labels: enhancement

#1127 Add repository id to pr automation changeset
  lib/console/commands/plural.ex
  lib/console/schema/pr_automation.ex
  test/console/deployments/git_test.exs
Labels: bug-fix, hotfix

#1129 remove add ons from cd view
  assets/src/components/CommandPalette.tsx
  assets/src/components/backups/clusters/ConfigureClusterBackupsModal.tsx
  assets/src/components/cd/ContinuousDeployment.tsx
  assets/src/components/cd/addOns/AddOnBasicSettings.tsx
  assets/src/components/cd/addOns/AddOnCard.tsx
  assets/src/components/cd/addOns/AddOns.tsx
  assets/src/components/cd/addOns/ConfigurationInput.tsx
  assets/src/components/cd/addOns/InstallAddOn.tsx
  assets/src/components/cd/addOns/configurationUtils.tsx
  assets/src/components/cd/utils/ClusterSelect.tsx
  assets/src/components/kubernetes/Navigation.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdAddons.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
Labels: enhancement, frontend

#1128 add k8s dashboard link to service component tree view
  assets/src/components/component/tree/ComponentTreeNode.tsx
  assets/src/components/kubernetes/Cluster.tsx
  assets/src/components/kubernetes/Navigation.tsx
Labels: enhancement, frontend

#1130 add fullscreen option to stack state
  assets/src/components/stacks/run/state/State.tsx
  assets/src/components/stacks/state/StackStateGraph.tsx
Labels: enhancement, frontend

#1126 feat: Add `ServiceAccount` CRD
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  charts/controller/crds/deployments.plural.sh_serviceaccounts.yaml
  controller/api/v1alpha1/common_types.go
  controller/api/v1alpha1/serviceaccount_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  controller/config/crd/bases/deployments.plural.sh_serviceaccounts.yaml
  controller/config/rbac/role.yaml
  controller/config/samples/service_account.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/client/console.go
  controller/internal/client/serviceaccount.go
  controller/internal/client/stack.go
  controller/internal/controller/service_account_controller.go
  controller/internal/controller/service_account_scope.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
  plural/helm/console/crds/deployments.plural.sh_serviceaccounts.yaml
Labels: enhancement

#1132 Add caching for change detection w/ stacks
  lib/console/deployments/git/agent.ex
  lib/console/deployments/git/cache.ex
  lib/console/deployments/git/discovery.ex
  lib/console/deployments/pipelines/stage_worker.ex
  lib/console/deployments/stacks.ex
Labels: enhancement

#1134 Need to handle {:more, _, _} clauses in cached body reader
  lib/console_web/plugs/cached_body_reader.ex
Labels: bug-fix, hotfix

#1135 Add iframe headers
  lib/console_web/endpoint.ex
  lib/console_web/plugs/secure_headers.ex
Labels: enhancement, hotfix

#1136 Implement cron triggers for stacks
  assets/src/generated/graphql.ts
  config/prod.exs
  lib/console.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/schema/stack.ex
  lib/console/schema/stack_cron.ex
  priv/repo/migrations/20240704001911_add_stack_crons.exs
  schema/schema.graphql
  test/console/deployments/cron_test.exs
  test/console/deployments/stacks_test.exs
  test/support/factory.ex
Labels: enhancement

#1131 feat: Operator multitenancy support
  charts/controller/crds/deployments.plural.sh_namespacecredentials.yaml
  controller/api/v1alpha1/common_types.go
  controller/api/v1alpha1/namespacecredentials_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/cmd/main.go
  controller/config/crd/bases/deployments.plural.sh_namespacecredentials.yaml
  controller/config/rbac/role.yaml
  controller/config/samples/namespace_credentials.yaml
  controller/internal/client/console.go
  controller/internal/client/credentials.go
  controller/internal/controller/cluster_controller.go
  controller/internal/controller/cluster_controller_test.go
  controller/internal/controller/clusterrestore_controller.go
  controller/internal/controller/clusterrestore_controller_test.go
  controller/internal/controller/clusterrestoretrigger_controller.go
  controller/internal/controller/customstackrun_controller.go
  controller/internal/controller/customstackrun_test.go
  controller/internal/controller/deploymentsettings_controller.go
  controller/internal/controller/deploymentsettings_test.go
  controller/internal/controller/globalservice_controller.go
  controller/internal/controller/globalservice_test.go
  controller/internal/controller/infrastructurestack_controller.go
  controller/internal/controller/infrastructurestack_test.go
  controller/internal/controller/managednamespace_controller.go
  controller/internal/controller/managenamespace_test.go
  controller/internal/controller/namespace_credentials_controller.go
  controller/internal/controller/namespace_credentials_scope.go
  controller/internal/controller/notificationrouter_controller.go
  controller/internal/controller/notificationrouter_test.go
  controller/internal/controller/notificationsink_controller.go
  controller/internal/controller/notificationsink_test.go
  controller/internal/controller/pipeline_controller.go
  controller/internal/controller/pipeline_controller_test.go
  controller/internal/controller/pipelinecontext_controller.go
  controller/internal/controller/pipelinecontext_controller_test.go
  controller/internal/controller/prautomationtrigger_controller.go
  controller/internal/controller/service_account_controller.go
  controller/internal/controller/servicedeployment_controller.go
  controller/internal/controller/servicedeployment_controller_test.go
  controller/internal/credentials/credentials.go
  controller/internal/credentials/fake.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  controller/internal/types/reconciler.go
  controller/internal/utils/kubernetes.go
  plural/helm/console/crds/deployments.plural.sh_namespacecredentials.yaml
Labels: enhancement

#1137 Add cron attributes to operator
  charts/controller/crds/deployments.plural.sh_infrastructurestacks.yaml
  controller/api/v1alpha1/infrastructurestack_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_infrastructurestacks.yaml
  controller/docs/api.md
  controller/go.mod
  controller/go.sum
  controller/internal/controller/infrastructurestack_controller.go
  plural/helm/console/crds/deployments.plural.sh_infrastructurestacks.yaml
Labels: enhancement, hotfix

#1139 Fix controller chart rbac
  charts/controller/templates/manager-rbac.yaml
Labels: bug-fix, hotfix

#1141 Another stab at fixing chart rbac
  charts/controller/templates/manager-rbac.yaml
Labels: bug-fix, hotfix

#1144 light mode fixes
  .vscode/settings.json
  assets/index.html
  assets/package.json
  assets/src/App.tsx
  assets/src/components/help/DocSearchStyles.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/layout/Subheader.tsx
  assets/src/components/stacks/state/StackStateGraph.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#1145 Fix broken webhook verifier
  charts/controller/templates/manager-rbac.yaml
  lib/console_web/controllers/webhook_controller.ex
  lib/console_web/plugs/cached_body_reader.ex
Labels: enhancement

#1147 Scope evaluation is interfering with serviceaccount crd creds
  controller/internal/controller/pipeline_controller.go
  controller/internal/controller/pipelinecontext_controller.go
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments/service.ex
  test/console/graphql/mutations/deployments/services_mutations_test.exs
  test/console/graphql/queries/deployments/service_queries_test.exs
Labels: enhancement

#1150 update pipeline queries fetch policies
  assets/src/components/cd/pipelines/PipelineContexts.tsx
  assets/src/components/cd/pipelines/PipelineDetails.tsx
  assets/src/components/cd/pipelines/context/PipelineContextDetails.tsx
  assets/src/components/cd/pipelines/job/PipelineJob.tsx
  assets/src/components/cd/pipelines/job/PipelineJobLogs.tsx
Labels: bug-fix, frontend

#1149 Project deletion api
  assets/src/generated/graphql.ts
  lib/console/deployments/settings.ex
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/deployments/settings.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments/settings.ex
  lib/console/schema/project.ex
  lib/console/schema/service.ex
  lib/console/schema/stack.ex
  lib/console/schema/stack_run.ex
  priv/repo/migrations/20240706030421_fix_project_fks.exs
  priv/repo/migrations/20240706133612_add_stack_variables.exs
  schema/schema.graphql
  test/console/deployments/settings_test.exs
  test/console/graphql/mutations/deployments/settings_mutations_test.exs
Labels: enhancement, backend, hotfix

#1151 Delete project via operator
  controller/go.mod
  controller/go.sum
  controller/internal/client/console.go
  controller/internal/client/project.go
  controller/internal/controller/namespace_credentials_controller.go
  controller/internal/controller/project_controller.go
  controller/internal/controller/service_account_controller.go
  controller/internal/test/mocks/ConsoleClient_mock.go
Labels: enhancement, backend

#1143 feat: Resync resources in the namespaces on NamespaceCredential changes
  charts/controller/crds/deployments.plural.sh_namespacecredentials.yaml
  controller/api/v1alpha1/clusterrestoretrigger_types.go
  controller/api/v1alpha1/common_types.go
  controller/api/v1alpha1/namespacecredentials_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_namespacecredentials.yaml
  controller/internal/client/console.go
  controller/internal/controller/cluster_controller.go
  controller/internal/controller/cluster_controller_test.go
  controller/internal/controller/clusterrestore_controller.go
  controller/internal/controller/clusterrestore_controller_test.go
  controller/internal/controller/clusterrestoretrigger_controller.go
  controller/internal/controller/customstackrun_controller.go
  controller/internal/controller/customstackrun_test.go
  controller/internal/controller/deploymentsettings_controller.go
  controller/internal/controller/deploymentsettings_test.go
  controller/internal/controller/globalservice_controller.go
  controller/internal/controller/globalservice_test.go
  controller/internal/controller/infrastructurestack_controller.go
  controller/internal/controller/infrastructurestack_test.go
  controller/internal/controller/managednamespace_controller.go
  controller/internal/controller/managenamespace_test.go
  controller/internal/controller/namespace_credentials_controller.go
  controller/internal/controller/notificationrouter_controller.go
  controller/internal/controller/notificationrouter_test.go
  controller/internal/controller/notificationsink_controller.go
  controller/internal/controller/notificationsink_test.go
  controller/internal/controller/pipeline_controller.go
  controller/internal/controller/pipeline_controller_test.go
  controller/internal/controller/pipelinecontext_controller.go
  controller/internal/controller/pipelinecontext_controller_test.go
  controller/internal/controller/prautomationtrigger_controller.go
  controller/internal/controller/service_account_controller.go
  controller/internal/controller/servicedeployment_controller.go
  controller/internal/controller/servicedeployment_controller_test.go
  controller/internal/credentials/cache.go
  controller/internal/credentials/fake.go
  controller/internal/credentials/kubernetes.go
  controller/internal/utils/kubernetes.go
  controller/internal/utils/sha.go
  plural/helm/console/crds/deployments.plural.sh_namespacecredentials.yaml
Labels: enhancement

#1133 enhancement: Prod 2310/backfill chart versions on compatibility tables
  static/compatibilities/argo-rollouts.yaml
  static/compatibilities/cert-manager.yaml
  static/compatibilities/cilium.yaml
  static/compatibilities/contour.yaml
  static/compatibilities/external-dns.yaml
  static/compatibilities/flux.yaml
  static/compatibilities/ingress-nginx.yaml
  static/compatibilities/istio.yaml
  static/compatibilities/jaeger.yaml
  static/compatibilities/keda.yaml
  static/compatibilities/kube-prometheus-stack.yaml
  static/compatibilities/kyverno.yaml
  static/compatibilities/linkerd.yaml
  utils/compatibility/main.py
  utils/compatibility/scrapers/argo-rollouts.py
  utils/compatibility/scrapers/cert-manager.py
  utils/compatibility/scrapers/cilium.py
  utils/compatibility/scrapers/contour.py
  utils/compatibility/scrapers/external-dns.py
  utils/compatibility/scrapers/flux.py
  utils/compatibility/scrapers/ingress-nginx.py
  utils/compatibility/scrapers/istio.py
  utils/compatibility/scrapers/jaeger.py
  utils/compatibility/scrapers/keda.py
  utils/compatibility/scrapers/kube-prometheus-stack.py
  utils/compatibility/scrapers/kyverno.py
  utils/compatibility/scrapers/linkerd.py
  utils/compatibility/scrapers/new-scraper copy.py
  utils/compatibility/scrapers/new-scraper.py
  utils/compatibility/utils.py
Labels: enhancement

#1153 Add chartVersion to graphql schema for compatibilities
  assets/src/components/cd/clusters/runtime/columns.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  lib/console/deployments/compatibilities/schema.ex
  lib/console/graphql/deployments/cluster.ex
  schema/schema.graphql
Labels: enhancement

#1154 update global service services table component
  assets/src/components/cd/globalServices/details/GlobalServiceServices.tsx
Labels: enhancement, frontend

#1158 feat: Add shell view for pods in k8s dashboard
  assets/src/components/kubernetes/workloads/Pod.tsx
  assets/src/routes/kubernetesRoute.tsx
Labels: enhancement

#1159 craft hardwire agent health for our operator types
  controller/internal/controller/cluster_controller.go
  controller/internal/controller/cluster_controller_test.go
  controller/internal/controller/customstackrun_controller.go
  controller/internal/controller/deploymentsettings_controller.go
  controller/internal/controller/gitrepository_controller.go
  controller/internal/controller/globalservice_controller.go
  controller/internal/controller/globalservice_test.go
  controller/internal/controller/infrastructurestack_controller.go
  controller/internal/controller/managednamespace_controller.go
  controller/internal/controller/namespace_credentials_controller.go
  controller/internal/controller/notificationrouter_controller.go
  controller/internal/controller/notificationsink_controller.go
  controller/internal/controller/pipeline_controller.go
  controller/internal/controller/pipeline_controller_test.go
  controller/internal/controller/pipelinecontext_controller.go
  controller/internal/controller/prautomation_controller.go
  controller/internal/controller/prautomationtrigger_controller.go
  controller/internal/controller/project_controller.go
  controller/internal/controller/provider_controller.go
  controller/internal/controller/scmconnection_controller.go
  controller/internal/controller/service_account_controller.go
  controller/internal/controller/servicedeployment_controller.go
  controller/internal/test/mocks/ConsoleClient_mock.go
Labels: enhancement

#1156 Add parentId to reconciled service deployments
  assets/src/generated/graphql.ts
  config/config.exs
  controller/internal/controller/servicedeployment_controller.go
  lib/console/deployments/policies/policies.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/graphql/resolvers/user.ex
  lib/console/graphql/users.ex
  lib/console/schema/managed_namespace.ex
  lib/console/schema/service.ex
  lib/console/services/users.ex
  priv/repo/migrations/20240709123933_drop_parent_id_fkey.exs
  schema/schema.graphql
  test/console/graphql/mutations/user_mutations_test.exs
  test/support/factory.ex
Labels: enhancement

#1160 Add `serviceTree` query
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments/service.ex
  lib/console/schema/pr_automation.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20240709212537_add_pr_automation_deletes.exs
  schema/schema.graphql
  test/console/graphql/queries/deployments/service_queries_test.exs
Labels: enhancement

#1162 fix: Remove managed namespace cluster target refs for now
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  controller/api/v1alpha1/managednamespace_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  controller/internal/controller/managenamespace_test.go
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
Labels: bug-fix

#1163 Add deletes spec to PrAutomation CRD
  Dockerfile
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  controller/api/v1alpha1/prautomation_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/test/mocks/ConsoleClient_mock.go
  lib/console/deployments/global.ex
  lib/console/graphql/deployments/global.ex
  lib/console/schema/managed_namespace.ex
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
  priv/repo/migrations/20240710143225_add_namesapce_unique_constraint.exs
  schema/schema.graphql
Labels: enhancement

#1161 feat: Redesign namespaces view
  assets/src/components/cd/globalServices/details/GlobalServiceInfo.tsx
  assets/src/components/cd/namespaces/NamespacesDetailTable.tsx
  assets/src/components/cd/namespaces/NamespacesDetailView.tsx
  assets/src/components/cd/namespaces/details/ManagedNamespace.tsx
  assets/src/components/cd/namespaces/details/ManagedNamespaceInfo.tsx
  assets/src/components/cd/namespaces/details/ManagedNamespaceServices.tsx
  assets/src/components/utils/ClusterDistro.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdNamespaces.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
  controller/config/samples/deployments_v1alpha1_managednamespace.yaml
Labels: enhancement

#1165 Add get managed namespace by name
  assets/src/generated/graphql.ts
  lib/console/deployments/global.ex
  lib/console/graphql/deployments/global.ex
  lib/console/graphql/resolvers/deployments/global.ex
  schema/schema.graphql
  test/console/graphql/queries/deployments/global_queries_test.exs
Labels: enhancement, hotfix

#1166 Add ability to `updateRbac` projects
  assets/src/generated/graphql.ts
  lib/console/deployments/settings.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/schema/project.ex
  schema/schema.graphql
Labels: enhancement, backend

#1169 add access tokens view to settings
  assets/src/components/profile/AccessTokens.tsx
  assets/src/components/profile/MyProfile.tsx
  assets/src/components/profile/Permissions.tsx
  assets/src/components/profile/Profile.tsx
  assets/src/components/profile/Security.tsx
  assets/src/components/settings/Settings.tsx
  assets/src/routes/settingsRoutes.tsx
Labels: enhancement, frontend

#1168 Implement manifest digest api
  lib/console.ex
  lib/console/deployments/git.ex
  lib/console/deployments/git/agent.ex
  lib/console/deployments/git/discovery.ex
  lib/console/deployments/helm/agent.ex
  lib/console/deployments/helm/agent_cache.ex
  lib/console/deployments/helm/cache.ex
  lib/console/deployments/helm/charts.ex
  lib/console/deployments/helm/discovery.ex
  lib/console/deployments/services.ex
  lib/console_web/controllers/git_controller.ex
  lib/console_web/endpoint.ex
  lib/console_web/router.ex
  test/console/deployments/services_test.exs
  test/console_web/controllers/git_controller_test.exs
Labels: enhancement

#1170 improve manage namespace controller
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  charts/controller/templates/manager-rbac.yaml
  controller/api/v1alpha1/managednamespace_types.go
  controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  controller/config/samples/deployments_v1alpha1_managednamespace.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/client/console.go
  controller/internal/client/namespace.go
  controller/internal/controller/managednamespace_controller.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
Labels: enhancement

#1173 add support for enforceNamespace
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  controller/api/v1alpha1/servicedeployment_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  controller/internal/controller/common.go
  controller/internal/controller/globalservice_test.go
  controller/internal/controller/servicedeployment_controller_test.go
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
Labels: enhancement

#1177 small cd ui bugs
  assets/src/components/cd/globalServices/details/GlobalServiceInfo.tsx
  assets/src/components/utils/layout/ResponsiveLayoutSidecarContainer.tsx
  assets/src/routes/settingsRoutes.tsx
Labels: bug-fix

#1178 fix: Fix styling of namespaces and global services details
  assets/src/components/cd/globalServices/details/GlobalService.tsx
  assets/src/components/cd/globalServices/details/GlobalServiceInfo.tsx
  assets/src/components/cd/namespaces/details/ManagedNamespace.tsx
  assets/src/components/cd/namespaces/details/ManagedNamespaceInfo.tsx
Labels: bug-fix

#1179 fix: tabs scrollbar on kubernetes resource details views
  assets/src/components/kubernetes/common/ResourceDetails.tsx
Labels: bug-fix

#1172 feat(controller): add support for StackDefinition
  assets/src/components/stacks/common/StackTypeIcon.tsx
  charts/controller/crds/deployments.plural.sh_infrastructurestacks.yaml
  charts/controller/crds/deployments.plural.sh_stackdefinitions.yaml
  charts/controller/templates/manager-rbac.yaml
  controller/api/v1alpha1/infrastructurestack_types.go
  controller/api/v1alpha1/stackdefinition_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_infrastructurestacks.yaml
  controller/config/crd/bases/deployments.plural.sh_stackdefinitions.yaml
  controller/config/rbac/role.yaml
  controller/config/samples/stack_definition.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/client/console.go
  controller/internal/client/stackdefinition.go
  controller/internal/controller/cluster_controller.go
  controller/internal/controller/cluster_controller_test.go
  controller/internal/controller/infrastructurestack_controller.go
  controller/internal/controller/infrastructurestack_scope.go
  controller/internal/controller/scope.go
  controller/internal/controller/servicedeployment_controller.go
  controller/internal/controller/stackdefinition_controller.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_infrastructurestacks.yaml
  plural/helm/console/crds/deployments.plural.sh_stackdefinitions.yaml
Labels: enhancement

#1171 Outright digest the git cache tarfile for digest api
  AGENT_VERSION
  KUBE_VERSION
  assets/package.json
  assets/src/components/pr/scm/GitProviderSelect.tsx
  assets/src/components/pr/scm/PrScmConnectionsColumns.tsx
  assets/src/generated/graphql.ts
  assets/yarn.lock
  controller/docs/api.md
  controller/internal/controller/cluster_controller.go
  controller/internal/controller/common.go
  controller/internal/controller/infrastructurestack_controller.go
  controller/internal/controller/infrastructurestack_test.go
  controller/internal/controller/project_controller.go
  controller/internal/controller/servicedeployment_controller.go
  controller/internal/errors/base.go
  lib/console.ex
  lib/console/deployments/clusters.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/discovery.ex
  lib/console/deployments/git/agent.ex
  lib/console/deployments/git/cache.ex
  lib/console/deployments/helm/agent.ex
  lib/console/deployments/helm/agent_cache.ex
  lib/console/deployments/pr/dispatcher.ex
  lib/console/deployments/pr/git.ex
  lib/console/deployments/pr/impl/bitbucket.ex
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments/global.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/middleware/cd_authed.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  lib/console/graphql/resolvers/kubernetes.ex
  lib/console/schema/global_service.ex
  lib/console/schema/managed_namespace.ex
  lib/console/schema/scm_connection.ex
  lib/console/schema/stack.ex
  lib/kube/utils.ex
  plural/helm/kas/templates/deployment.yaml
  plural/helm/kas/values.yaml
  priv/repo/migrations/20240716005259_cascade_cluster_restores.exs
  priv/repo/migrations/20240717162820_add_global_service_parent_id.exs
  schema/schema.graphql
  test/console/deployments/cron_test.exs
  test/console/graphql/queries/deployments/cluster_queries_test.exs
  test/console/graphql/queries/kubernetes_queries_test.exs
Labels: enhancement

#1181 Fix stack queries for tags
  assets/src/generated/graphql.ts
  controller/go.mod
  controller/go.sum
  controller/internal/controller/globalservice_controller.go
  controller/internal/controller/managednamespace_controller.go
  controller/internal/controller/project_controller.go
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  lib/console/schema/stack.ex
  lib/console/schema/tag.ex
  priv/repo/migrations/20240718195049_add_stack_parent_id.exs
  schema/schema.graphql
  test/console/graphql/queries/deployments/stack_queries_test.exs
Labels: enhancement

#1182 Add parent id to stacks
  assets/src/generated/graphql.ts
  controller/go.mod
  controller/go.sum
  controller/internal/controller/infrastructurestack_controller.go
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/schema/tag.ex
  schema/schema.graphql
Labels: enhancement

#1183 fix null entries call
  assets/src/components/kubernetes/network/Service.tsx
Labels: bug-fix, hotfix

#1180 enhancement: React Flow styling changes and refactoring
  assets/src/components/cd/pipelines/EdgeLine.tsx
  assets/src/components/cd/pipelines/PipelineDetails.tsx
  assets/src/components/cd/pipelines/PipelineGraph.tsx
  assets/src/components/cd/pipelines/nodes/ApprovalNode.tsx
  assets/src/components/cd/pipelines/nodes/BaseNode.tsx
  assets/src/components/cd/pipelines/nodes/JobNode.tsx
  assets/src/components/cd/pipelines/nodes/StageNode.tsx
  assets/src/components/cd/pipelines/nodes/TestsNode.tsx
  assets/src/components/cd/pipelines/utils/getNodesAndEdges.tsx
  assets/src/components/component/tree/ComponentTreeGraph.tsx
  assets/src/components/component/tree/ComponentTreeNode.tsx
  assets/src/components/component/tree/getTreeNodesAndEdges.tsx
  assets/src/components/stacks/state/StackStateGraph.tsx
  assets/src/components/stacks/state/StackStateGraphEdge.tsx
  assets/src/components/stacks/state/StackStateGraphNode.tsx
  assets/src/components/utils/reactflow/edges.tsx
  assets/src/components/utils/reactflow/graph.tsx
  assets/src/components/utils/reactflow/markers.tsx
  assets/src/components/utils/reactflow/nodes.tsx
Labels: enhancement

#1186 feat: add tags to infrastructure stacks
  charts/controller/crds/deployments.plural.sh_infrastructurestacks.yaml
  controller/api/v1alpha1/infrastructurestack_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_infrastructurestacks.yaml
  controller/internal/controller/infrastructurestack_controller.go
  plural/helm/console/crds/deployments.plural.sh_infrastructurestacks.yaml
Labels: enhancement

#1184 Add BitBucket to SCM Connection types
  charts/controller/crds/deployments.plural.sh_scmconnections.yaml
  controller/api/v1alpha1/prautomation_types.go
  controller/api/v1alpha1/scmconnection_types.go
  controller/config/crd/bases/deployments.plural.sh_scmconnections.yaml
  controller/docs/api.md
  lib/console/deployments/pr/impl/bitbucket.ex
  plural/helm/console/crds/deployments.plural.sh_scmconnections.yaml
Labels: enhancement

#1189 fix scm connection updates
  assets/src/components/pr/scm/EditScmConnection.tsx
Labels: bug-fix, frontend

#1192 cleanup help widget
  assets/src/components/CommandPalette.tsx
  assets/src/components/help/HelpLauncher.tsx
  assets/src/components/help/HelpLauncherBtn.tsx
  assets/src/components/help/HelpMenu.tsx
Labels: enhancement, frontend

#1191 update project dropdown fetch policy
  assets/src/components/contexts/ProjectsContext.tsx
Labels: enhancement, frontend

#1193 Improved git agent branch handling
  lib/console/deployments/git/cache.ex
  lib/console/deployments/git/cmd.ex
  test-apps/branch-test/.helmignore
  test-apps/branch-test/Chart.yaml
  test-apps/branch-test/templates/NOTES.txt
  test-apps/branch-test/templates/_helpers.tpl
  test-apps/branch-test/templates/deployment.yaml
  test-apps/branch-test/templates/hpa.yaml
  test-apps/branch-test/templates/ingress.yaml
  test-apps/branch-test/templates/service.yaml
  test-apps/branch-test/templates/serviceaccount.yaml
  test-apps/branch-test/templates/tests/test-connection.yaml
  test-apps/branch-test/values.yaml
  test/console/graphql/queries/deployments/stack_queries_test.exs
Labels: enhancement, hotfix

#1194 Fix stupid rbac bug
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  charts/controller/templates/manager-rbac.yaml
  controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
Labels: bug-fix, hotfix

#1196 Need to fix the embed config to support updating namespace metadata
  lib/console/schema/service.ex
Labels: bug-fix, hotfix

#1176 Implement cache for HelmChart crds
  charts/controller/templates/manager-rbac.yaml
  lib/console/cached/base.ex
  lib/console/cached/helm_chart.ex
  lib/console/cached/kubernetes.ex
  lib/console/cached/supervisor.ex
  lib/console/deployments/helm/charts.ex
  lib/console_web/channels/external_socket.ex
  lib/console_web/channels/user_socket.ex
Labels: enhancement

#1198 Pull-less git agent
  controller/internal/controller/globalservice_controller.go
  controller/internal/controller/globalservice_test.go
  lib/console/deployments/git/cmd.ex
Labels: enhancement

#1187 feat: Services tree diagram
  assets/package.json
  assets/src/components/apps/app/components/misc.tsx
  assets/src/components/cd/cluster/Cluster.tsx
  assets/src/components/cd/cluster/ClusterServices.tsx
  assets/src/components/cd/services/Services.tsx
  assets/src/components/cd/services/ServicesFilters.tsx
  assets/src/components/cd/services/ServicesTable.tsx
  assets/src/components/cd/services/ServicesTableErrors.tsx
  assets/src/components/cd/services/ServicesTree.tsx
  assets/src/components/cd/services/ServicesTreeDiagram.tsx
  assets/src/components/cd/services/ServicesTreeDiagramNodes.tsx
  assets/src/components/cd/services/deployModal/DeployService.tsx
  assets/src/components/stacks/state/StackStateGraph.tsx
  assets/src/components/utils/KickButton.tsx
  assets/src/components/utils/reactflow/edges.tsx
  assets/src/components/utils/reactflow/graph.tsx
  assets/src/components/utils/reactflow/nodes.tsx
  assets/src/components/utils/table/ColWithIcon.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdGlobalServices.graphql
  assets/src/graph/cdServices.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
  assets/src/utils/array.ts
  assets/yarn.lock
  go/controller/internal/controller/servicedeployment_controller.go
  lib/console/deployments/pipelines/stage_worker.ex
  lib/console/deployments/pubsub/protocols/pipelineable.ex
  lib/console/deployments/pubsub/recurse.ex
Labels: enhancement

#1202 enhancement: Add group queries to client
  go/client/.gitignore
  go/client/client.go
  go/client/graph/users.graphql
  go/client/graphql.config.yml
  go/client/groups.graphql
Labels: enhancement

#1204 fix: Put file in correct directory
  go/client/Makefile
  go/client/client.go
  go/client/graph/groups.graphql
Labels: bug-fix

#1201 migrate accordions to new API
  assets/package.json
  assets/src/components/cd/clusters/ClusterUpgradeFlyover.tsx
  assets/src/components/cd/clusters/create/provider/NodeGroup.tsx
  assets/src/components/cd/services/ClusterTagsFilter.tsx
  assets/src/components/help/HelpLauncher.tsx
  assets/src/components/help/HelpLauncherBtn.tsx
  assets/src/components/home/pullrequests/PrCard.tsx
  assets/src/components/kubernetes/common/NamespaceFilter.tsx
  assets/src/components/policies/Policies.tsx
  assets/src/components/policies/PoliciesFilter.tsx
  assets/src/components/pr/scm/EditScmConnection.tsx
  assets/src/components/stacks/create/CreateStackModalFormBasic.tsx
  assets/src/components/stacks/prs/PrStackRunsAccordion.tsx
  assets/src/components/stacks/prs/StackPrs.tsx
  assets/src/components/utils/IconExpander.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#1203 tune requeue duration for pending resources
  go/controller/config/samples/deployments_v1alpha1_globalservice.yaml
  go/controller/internal/controller/common.go
  go/controller/internal/controller/globalservice_controller.go
  go/controller/internal/controller/infrastructurestack_controller.go
  go/controller/internal/controller/servicedeployment_controller.go
  go/controller/internal/controller/servicedeployment_controller_test.go
Labels: enhancement

#1205 Add pipeline subscription delivery
  assets/src/generated/graphql.ts
  charts/controller/templates/manager-rbac.yaml
  lib/console/deployments/events.ex
  lib/console/deployments/pipelines.ex
  lib/console/deployments/pubsub/protocols/pipelineable.ex
  lib/console/deployments/pubsub/rtc.ex
  lib/console/deployments/services.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/pipeline.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/topic.ex
  mix.exs
  schema/schema.graphql
  test/console/deployments/services_test.exs
Labels: enhancement

#1207 design QA
  assets/package.json
  assets/src/components/apps/Apps.tsx
  assets/src/components/apps/app/config/Configuration.tsx
  assets/src/components/apps/app/runbooks/runbook/Runbook.tsx
  assets/src/components/backups/Backups.tsx
  assets/src/components/backups/cluster/Cluster.tsx
  assets/src/components/builds/build/changelog/Changelog.tsx
  assets/src/components/cd/ContinuousDeployment.tsx
  assets/src/components/cd/YamlGeneratorModal.tsx
  assets/src/components/cd/cluster/Cluster.tsx
  assets/src/components/cd/cluster/ClusterServices.tsx
  assets/src/components/cd/cluster/node/Node.tsx
  assets/src/components/cd/clusters/ClustersColumns.tsx
  assets/src/components/cd/clusters/DynamicClusterIcon.tsx
  assets/src/components/cd/globalServices/details/GlobalService.tsx
  assets/src/components/cd/namespaces/details/ManagedNamespace.tsx
  assets/src/components/cd/pipelines/PipelineDetails.tsx
  assets/src/components/cd/services/Services.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/services/ServicesFilters.tsx
  assets/src/components/cd/utils/ClusterSelector.tsx
  assets/src/components/cluster/containers/Container.tsx
  assets/src/components/cluster/nodes/Node.tsx
  assets/src/components/component/ComponentDetails.tsx
  assets/src/components/kubernetes/cluster/Cluster.tsx
  assets/src/components/kubernetes/common/ResourceDetails.tsx
  assets/src/components/kubernetes/configuration/Configuration.tsx
  assets/src/components/kubernetes/network/Network.tsx
  assets/src/components/kubernetes/rbac/Rbac.tsx
  assets/src/components/kubernetes/storage/Storage.tsx
  assets/src/components/kubernetes/workloads/Workloads.tsx
  assets/src/components/notifications/Notifications.tsx
  assets/src/components/policies/Policies.tsx
  assets/src/components/policies/PoliciesFilter.tsx
  assets/src/components/policies/PoliciesTable.tsx
  assets/src/components/policies/policy/affectedResources/PolicyAffectedResources.tsx
  assets/src/components/policies/policy/affectedResources/ViolationsTableColumns.tsx
  assets/src/components/pr/Pr.tsx
  assets/src/components/pr/automations/PrAutomations.tsx
  assets/src/components/pr/queue/PrQueue.tsx
  assets/src/components/pr/queue/PrQueueColumns.tsx
  assets/src/components/pr/scm/ScmWebhooksColumns.tsx
  assets/src/components/settings/audits/Audits.tsx
  assets/src/components/settings/global/GlobalSettings.tsx
  assets/src/components/settings/usermanagement/UserManagement.tsx
  assets/src/components/stacks/Stacks.tsx
  assets/src/components/stacks/customrun/StackCustomRun.tsx
  assets/src/components/stacks/customrun/StackCustomRunChooseTemplate.tsx
  assets/src/components/stacks/customrun/StackCustomRunModal.tsx
  assets/src/components/stacks/run/Header.tsx
  assets/src/components/utils/FillLevelDiv.tsx
  assets/src/components/utils/RangePicker.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#1208 Bump cli vsn to 0.9.13
  Dockerfile
Labels: enhancement, hotfix

#1213 fetch service revision ID and sha
  go/client/client.go
  go/client/graph/deployment.graphql
Labels: enhancement

#1214 feat: remove update service components
  go/controller/internal/client/console.go
  go/controller/internal/client/service.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
Labels: enhancement

#1215 fix: ensure bindings
  go/controller/internal/controller/prautomation_controller.go
  go/controller/internal/types/reconciler.go
Labels: bug-fix

#1216 feat: Make sha nullable
  go/client/client.go
  go/client/graph/deployment.graphql
Labels: enhancement

#1212 feat: add observability provider controller
  .github/workflows/controller-ci.yaml
  charts/controller/crds/deployments.plural.sh_infrastructurestacks.yaml
  charts/controller/crds/deployments.plural.sh_observabilityproviders.yaml
  go/client/client.go
  go/client/graph/observabilityprovider.graphql
  go/controller/api/v1alpha1/infrastructurestack_types.go
  go/controller/api/v1alpha1/observabilityprovider_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_infrastructurestacks.yaml
  go/controller/config/crd/bases/deployments.plural.sh_observabilityproviders.yaml
  go/controller/config/rbac/role.yaml
  go/controller/docs/api.md
  go/controller/internal/client/console.go
  go/controller/internal/client/observabilityprovider.go
  go/controller/internal/controller/infrastructurestack_controller.go
  go/controller/internal/controller/observabilityprovider_controller.go
  go/controller/internal/controller/stackdefinition_controller.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  go/controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_infrastructurestacks.yaml
  plural/helm/console/crds/deployments.plural.sh_observabilityproviders.yaml
Labels: enhancement

#1211 add service revision id to pipeline stage nodes
  assets/src/components/cd/pipelines/nodes/BaseNode.tsx
  assets/src/components/cd/pipelines/nodes/StageNode.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdPipelines.graphql
Labels: enhancement, frontend

#1209 Introduce a duplicate rapid chart for console
  .github/workflows/publish.yaml
  AGENT_VERSION
  charts/console-rapid/.gitignore
  charts/console-rapid/.helmignore
  charts/console-rapid/Chart.lock
  charts/console-rapid/Chart.yaml
  charts/console-rapid/charts/controller-0.0.65.tgz
  charts/console-rapid/charts/flux2-2.11.1.tgz
  charts/console-rapid/charts/kas-0.1.0.tgz
  charts/console-rapid/charts/kubernetes-dashboard-7.5.0.tgz
  charts/console-rapid/templates
  charts/console-rapid/values.yaml
  lib/console.ex
  lib/console/deployments/helm/agent_cache.ex
  lib/console/deployments/metrics/provider.ex
  lib/console/deployments/metrics/provider/datadog.ex
  lib/console/deployments/metrics/provider/new_relic.ex
  lib/console/deployments/pipelines/promotion_worker.ex
  lib/console/deployments/pipelines/stage_worker.ex
  lib/console/deployments/pubsub/consumers/pipeline.ex
  lib/console/deployments/pubsub/recurse.ex
  lib/console/deployments/stacks/worker.ex
  test/console/deployments/pubsub/recurse_test.exs
Labels: enhancement, hotfix

#1219 Differentiate branch in rapid pr creation
  .github/workflows/publish.yaml
Labels: bug-fix, hotfix

#1222 Fix rapid charrt action
  .github/workflows/publish.yaml
  Makefile
Labels: enhancement

#1224 fix gh action issue
  .github/workflows/publish.yaml
Labels: bug-fix, hotfix

#1227 Fix pipeline context genserver apply
  config/prod.exs
  lib/console/deployments/pipelines.ex
  lib/console/deployments/pipelines/discovery.ex
  lib/console/deployments/pipelines/promotion_worker.ex
  lib/console/deployments/pipelines/stability.ex
  lib/console/deployments/pipelines/stage_worker.ex
  lib/console/deployments/pubsub/consumers/pipeline.ex
  lib/console/deployments/pubsub/protocols/pipelineable.ex
  lib/console/deployments/pubsub/rtc.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments/service.ex
  lib/console/graphql/topic.ex
  test/console/deployments/pipelines_test.exs
  test/console/deployments/pubsub/pipeline_test.exs
Labels: bug-fix, hotfix

#1229 Getting custom stacks working
  go/controller/internal/types/reconciler.go
  lib/console/deployments/metrics/provider/datadog.ex
  lib/console/deployments/stacks/worker.ex
Labels: enhancement

#1230 Make `configuration` optional in StackAttributes
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments.ex
  schema/schema.graphql
Labels: enhancement

#1233 add identifier to CreatePullRequest mutation
  go/client/client.go
  go/client/graph/git.graphql
Labels: enhancement

#1234 Add cancellation reason to stack run
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/deployments/pubsub/recurse.ex
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments.ex
  schema/schema.graphql
Labels: enhancement

#1232 fix: PR automation bindings
  go/controller/internal/client/prautomation.go
  go/controller/internal/controller/infrastructurestack_controller.go
  go/controller/internal/controller/prautomation_controller.go
Labels: bug-fix

#1217 enhancement: Command palette improvements
  assets/package.json
  assets/src/components/CommandPalette.tsx
  assets/src/components/CommandPaletteLauncher.tsx
  assets/src/components/cd/providers/CreateProvider.tsx
  assets/src/components/cd/repos/GitRepositoriesImportGit.tsx
  assets/src/components/cd/services/deployModal/DeployService.tsx
  assets/src/components/commandpalette/CommandPalette.tsx
  assets/src/components/commandpalette/CommandPaletteDialog.tsx
  assets/src/components/commandpalette/CommandPaletteLauncher.tsx
  assets/src/components/commandpalette/CommandPaletteShortcut.tsx
  assets/src/components/commandpalette/CommandPaletteShortcuts.tsx
  assets/src/components/commandpalette/commands.ts
  assets/src/components/commandpalette/shortcuts.ts
  assets/src/components/layout/Console.tsx
  assets/src/components/layout/Header.tsx
  assets/src/routes/consoleRoutes.tsx
  assets/src/routes/consoleRoutesConsts.tsx
  assets/yarn.lock
Labels: enhancement

#1231 feat: Stack run cancelation and observability metrics
  assets/src/components/stacks/common/StackObservabilityMetrics.tsx
  assets/src/components/stacks/common/StackRunIcon.tsx
  assets/src/components/stacks/run/Header.tsx
  assets/src/components/stacks/run/Sidecar.tsx
  assets/src/components/stacks/runs/StackRunsEntry.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/stacks.graphql
  assets/yarn.lock
  lib/console/deployments/pr/utils.ex
  lib/console/graphql/resolvers/deployments.ex
Labels: enhancement

#1237 fix service table infinite render
  assets/src/components/cd/cluster/ClusterServices.tsx
  assets/src/components/cd/services/Services.tsx
Labels: bug-fix, frontend
