Repository pluralsh/console, pull requests merged in 2024-02, with the labels that each got.

#645 Implement PR Create File flow, more fixups for backup/restore
  assets/src/generated/graphql.ts
  lib/console.ex
  lib/console/commands/plural.ex
  lib/console/deployments/backups.ex
  lib/console/deployments/git/agent.ex
  lib/console/deployments/git/discovery.ex
  lib/console/deployments/pr/dispatcher.ex
  lib/console/graphql/deployments/backup.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/middleware/authenticated.ex
  lib/console/graphql/resolvers/deployments/backup.ex
  lib/console/schema/cluster_backup.ex
  lib/console/schema/pr_automation.ex
  priv/repo/migrations/20240131170141_add_pr_auto_git.exs
  schema/schema.graphql
  test/console/deployments/backups_test.exs
  test/console/deployments/git_test.exs
  test/console/graphql/mutations/deployments/backup_mutations_test.exs
  test/console/graphql/mutations/deployments/git_mutations_test.exs
  test/support/factory.ex
Labels: enhancement

#640 feat: add scm connection crd/controller and improve controller reconcile
  charts/controller/crds/deployments.plural.sh_scmconnections.yaml
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  controller/api/v1alpha1/common_types.go
  controller/api/v1alpha1/scmconnection_types.go
  controller/api/v1alpha1/servicedeployment_types.go.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/cmd/main.go
  controller/config/crd/bases/deployments.plural.sh_scmconnections.yaml
  controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  controller/config/rbac/role.yaml
  controller/config/samples/scm_connection.yaml
  controller/config/samples/service_deployment_helm.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/client/console.go
  controller/internal/client/scmconnection.go
  controller/internal/controller/cluster_controller.go
  controller/internal/controller/gitrepository_controller.go
  controller/internal/controller/globalservice_controller.go
  controller/internal/controller/pipeline_controller.go
  controller/internal/controller/provider_controller.go
  controller/internal/controller/scmconnection_controller.go
  controller/internal/controller/scmconnection_scope.go
  controller/internal/controller/servicedeployment_controller.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  controller/internal/types/reconciler.go
Labels: enhancement

#647 fix: Intercom/chat hotkey interferes w/ service creation modal
  assets/package.json
  assets/src/components/help/DocSearch.tsx
  assets/yarn.lock
Labels: bug-fix

#648 Add ability to bind obect stores to clusters
  .tool-versions
  assets/src/generated/graphql.ts
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.11.tgz
  charts/console/charts/controller-0.0.12.tgz
  charts/console/charts/kas-0.0.4.tgz
  charts/controller/Chart.yaml
  charts/controller/templates/manager-rbac.yaml
  lib/console/deployments/backups.ex
  lib/console/deployments/events.ex
  lib/console/deployments/pubsub/audits.ex
  lib/console/deployments/pubsub/protocols/broadcastable.ex
  lib/console/deployments/services.ex
  lib/console/graphql/deployments/backup.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/resolvers/deployments/backup.ex
  lib/console/schema/audit.ex
  lib/console/schema/object_store.ex
  plural/helm/console/Chart.lock
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/controller-0.0.11.tgz
  plural/helm/console/charts/controller-0.0.12.tgz
  schema/schema.graphql
  test/console/deployments/backups_test.exs
  test/console/deployments/pubsub/broadcast_test.exs
  test/console/graphql/mutations/deployments/backup_mutations_test.exs
  test/console/graphql/queries/deployments/backup_queries_test.exs
Labels: enhancement, backend

#650 Handle nulls in polymorphic cluster backup query
  lib/console/graphql/resolvers/deployments/backup.ex
Labels: bug-fix

#651 fix: pass bindings to service deployment update mutation
  controller/internal/controller/servicedeployment_controller.go
Labels: bug-fix

#655 feat: Add link to app from audits table
  assets/src/components/audits/table/AuditTable.tsx
Labels: enhancement, frontend

#657 feat: Build progress improvements
  assets/src/components/builds/build/progress/Command.tsx
  assets/src/components/builds/build/progress/CommandExitStatus.tsx
  assets/src/components/builds/build/progress/CommandLog.tsx
Labels: enhancement, frontend

#654 Implement agent version pinning
  .tool-versions
  AGENT_VERSION
  lib/console/clustering/bootstrapper.ex
  lib/console/deployments/clusters.ex
  lib/console/deployments/git/cmd.ex
  lib/console/deployments/services.ex
  lib/console/deployments/settings.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/middleware/error_handler.ex
  lib/console/graphql/resolvers/kubernetes.ex
  lib/console/graphql/schema/base.ex
  lib/console/schema/deployment_settings.ex
  lib/console/schema/global_service.ex
  lib/console/schema/pr_automation.ex
  lib/console/schema/service.ex
  priv/repo/migrations/20240204041652_add_agent_version.exs
  test/console/deployments/clusters_test.exs
  test/console/deployments/settings_test.exs
Labels: enhancement

#639 feat: Add restore controller, default schedule and Velero compatibilities
  charts/controller/crds/deployments.plural.sh_clusterrestores.yaml
  charts/velero-s3-proxy/Chart.yaml
  charts/velero-s3-proxy/templates/_helpers.tpl
  charts/velero-s3-proxy/templates/schedule.yaml
  charts/velero-s3-proxy/values.yaml
  charts/velero/Chart.yaml
  charts/velero/templates/_helpers.tpl
  charts/velero/templates/schedule.yaml
  charts/velero/values.yaml
  controller/PROJECT
  controller/api/v1alpha1/clusterrestore_types.go
  controller/api/v1alpha1/common_types.go
  controller/api/v1alpha1/scmconnection_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/cmd/main.go
  controller/config/crd/bases/deployments.plural.sh_clusterrestores.yaml
  controller/config/rbac/clusterrestore_editor_role.yaml
  controller/config/rbac/clusterrestore_viewer_role.yaml
  controller/config/rbac/role.yaml
  controller/config/samples/deployments_v1alpha1_pipeline.yaml
  controller/config/samples/restore.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/client/backup.go
  controller/internal/client/console.go
  controller/internal/client/restore.go
  controller/internal/controller/clusterrestore_controller.go
  controller/internal/controller/clusterrestore_controller_test.go
  controller/internal/controller/clusterrestore_scope.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  controller/internal/types/reconciler.go
  static/compatibilities/velero.yaml
Labels: enhancement

#659 feat: Add addon readmes and release URLs
  assets/src/components/cd/cluster/addon/ClusterAddOnCompatibility.tsx
  assets/src/components/cd/cluster/addon/ClusterAddOnDetails.tsx
  assets/src/components/cd/cluster/addon/ClusterAddOnReadme.tsx
  assets/src/components/cd/cluster/addon/ClusterAddOnReleases.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/routes/cdRoutes.tsx
Labels: enhancement, frontend

#649 feat: automate rbac generation in controller chart and update gh action to use it
  .github/workflows/publish.yaml
  assets/src/generated/graphql.ts
  charts/controller/templates/manager-rbac.yaml
  controller/.gitignore
  controller/Makefile
  schema/schema.graphql
Labels: enhancement

#658 Add pull request search, job sideload on pipeline gate
  assets/package.json
  assets/src/components/cd/globalSettings/GlobalSettings.tsx
  assets/src/components/cd/globalSettings/GlobalSettingsAgents.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdGlobalSettings.graphql
  assets/src/routes/cdRoutes.tsx
  config/prod.exs
  lib/console/deployments/clusters.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/git/agent.ex
  lib/console/deployments/pipelines.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/deployments/services.ex
  lib/console/deployments/settings.ex
  lib/console/external_graphql.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/deployments/pipeline.ex
  lib/console/graphql/kubernetes/job.ex
  lib/console/graphql/resolvers/deployments/git.ex
  lib/console/graphql/resolvers/deployments/pipeline.ex
  lib/console/graphql/resolvers/kubernetes.ex
  lib/console/schema/agent_migration.ex
  lib/console/schema/deployment_settings.ex
  lib/console/schema/pull_request.ex
  priv/repo/migrations/20240206212303_add_agent_helm_values.exs
  schema/schema.graphql
  test/console/deployments/clusters_test.exs
  test/console/deployments/services_test.exs
  test/console/deployments/settings_test.exs
  test/console/graphql/queries/deployments/pipeline_queries_test.exs
Labels: enhancement

#656 feat: add pr automation controller
  charts/controller/crds/deployments.plural.sh_clusterrestores.yaml
  charts/controller/crds/deployments.plural.sh_clusters.yaml
  charts/controller/crds/deployments.plural.sh_gitrepositories.yaml
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_pipelines.yaml
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  charts/controller/crds/deployments.plural.sh_providers.yaml
  charts/controller/crds/deployments.plural.sh_scmconnections.yaml
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  charts/controller/templates/manager-rbac.yaml
  controller/api/v1alpha1/cluster_types.go
  controller/api/v1alpha1/common_types.go
  controller/api/v1alpha1/gitrepository_types.go
  controller/api/v1alpha1/globalservice_types.go
  controller/api/v1alpha1/groupversion_info.go
  controller/api/v1alpha1/pipeline_types.go
  controller/api/v1alpha1/prautomation_types.go
  controller/api/v1alpha1/provider_types.go
  controller/api/v1alpha1/scmconnection_types.go
  controller/api/v1alpha1/servicedeployment_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/cmd/main.go
  controller/config/crd/bases/deployments.plural.sh_clusterrestores.yaml
  controller/config/crd/bases/deployments.plural.sh_clusters.yaml
  controller/config/crd/bases/deployments.plural.sh_gitrepositories.yaml
  controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  controller/config/crd/bases/deployments.plural.sh_pipelines.yaml
  controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  controller/config/crd/bases/deployments.plural.sh_providers.yaml
  controller/config/crd/bases/deployments.plural.sh_scmconnections.yaml
  controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  controller/config/rbac/role.yaml
  controller/config/samples/pr_automation.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/client/console.go
  controller/internal/client/prautomation.go
  controller/internal/controller/cluster_controller.go
  controller/internal/controller/cluster_controller_test.go
  controller/internal/controller/clusterrestore_controller_test.go
  controller/internal/controller/gitrepository_controller_test.go
  controller/internal/controller/globalservice_test.go
  controller/internal/controller/pipeline_controller.go
  controller/internal/controller/pipeline_controller_test.go
  controller/internal/controller/prautomation_attributes.go
  controller/internal/controller/prautomation_controller.go
  controller/internal/controller/prautomation_controller_test.go
  controller/internal/controller/prautomation_scope.go
  controller/internal/controller/provider_controller_test.go
  controller/internal/controller/servicedeployment_controller_test.go
  controller/internal/controller/suite_test.go
  controller/internal/test/common/kubernetes.go
  controller/internal/test/common/random.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  controller/internal/types/reconciler.go
  controller/internal/utils/console.go
  controller/internal/utils/kubernetes.go
Labels: enhancement

#660 Add PrAutomation configuration sideload
  assets/src/generated/graphql.ts
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.12.tgz
  charts/console/charts/controller-0.0.13.tgz
  charts/console/charts/kas-0.0.4.tgz
  charts/console/charts/kas-0.0.5.tgz
  charts/controller/Chart.yaml
  charts/controller/templates/deployment.yaml
  charts/controller/values.yaml
  lib/console/graphql/deployments/git.ex
  plural/helm/kas/Chart.yaml
  plural/helm/kas/templates/deployment.yaml
  plural/helm/kas/values.yaml
  schema/schema.graphql
Labels: enhancement

#661 Nullable scm token updates
  .github/workflows/assets.yaml
  .github/workflows/controller-cd.yaml
  assets/src/generated/graphql.ts
  lib/console/deployments/clusters.ex
  lib/console/graphql/deployments/git.ex
  schema/schema.graphql
Labels: enhancement

#663 Fix binding mappings
  lib/console/schema/pr_automation.ex
Labels: enhancement

#664 Add paginated cluster service/gate fetches
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/pipeline.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments/pipeline.ex
  lib/console/graphql/resolvers/deployments/service.ex
  schema/schema.graphql
  test/console/graphql/queries/deployments/pipeline_queries_test.exs
  test/console/graphql/queries/deployments/service_queries_test.exs
Labels: enhancement

#662 feat: Access token scopes
  assets/src/components/profile/AccessTokens.tsx
  assets/src/components/profile/AccessTokensCreateModal.tsx
  assets/src/components/profile/AccessTokensCreateScope.tsx
  assets/src/components/profile/AccessTokensScopes.tsx
  assets/src/components/utils/TooltipTime.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/tokens.graphql
Labels: enhancement, frontend

#666 Add component tree query
  assets/src/generated/graphql.ts
  lib/console/deployments/clusters.ex
  lib/console/deployments/policies/policies.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/deployments/services.ex
  lib/console/deployments/tree.ex
  lib/console/external_graphql.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/kubernetes.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments/service.ex
  lib/console/schema/cluster.ex
  mix.exs
  mix.lock
  schema/schema.graphql
Labels: enhancement

#667 Consolidated renovate setup api
  assets/src/generated/graphql.ts
  lib/console/deployments/git.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/deployments/pipeline.ex
  lib/console/graphql/resolvers/deployments/git.ex
  lib/console/schema/pipeline.ex
  schema/schema.graphql
  test/console/deployments/git_test.exs
  test/console/graphql/mutations/deployments/services_mutations_test.exs
Labels: enhancement

#668 feat: Add job gates to Pipelines
  assets/src/components/cd/cluster/ClusterPods.tsx
  assets/src/components/cd/cluster/node/Node.tsx
  assets/src/components/cd/cluster/node/NodeInfo.tsx
  assets/src/components/cd/cluster/pod/logs/ContainerLogs.tsx
  assets/src/components/cd/cluster/pod/logs/Logs.tsx
  assets/src/components/cd/pipelines/Pipeline.tsx
  assets/src/components/cd/pipelines/Pipelines.tsx
  assets/src/components/cd/pipelines/job/PipelineJob.tsx
  assets/src/components/cd/pipelines/job/PipelineJobLogs.tsx
  assets/src/components/cd/pipelines/job/PipelineJobPods.tsx
  assets/src/components/cd/pipelines/job/PipelineJobSpecs.tsx
  assets/src/components/cd/pipelines/job/PipelineJobStatus.tsx
  assets/src/components/cd/pipelines/nodes/JobNode.tsx
  assets/src/components/cd/pipelines/utils/_demo_data.ts
  assets/src/components/cd/pipelines/utils/getNodesAndEdges.tsx
  assets/src/components/cluster/nodes/NodeInfo.tsx
  assets/src/components/cluster/pods/Pod.tsx
  assets/src/components/cluster/pods/Pods.tsx
  assets/src/components/cluster/pods/PodsList.tsx
  assets/src/components/component/info/Pods.tsx
  assets/src/components/profile/AccessTokensCreateScope.tsx
  assets/src/components/utils/LabelPairsSection.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdPipelines.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/pipelineJobRoutes.tsx
  assets/src/types/react-table.d.ts
Labels: enhancement, frontend

#669 Auto-create SCM webhooks when registering connections
  assets/src/generated/graphql.ts
  lib/console/deployments/git.ex
  lib/console/deployments/pr/dispatcher.ex
  lib/console/deployments/pr/impl/github.ex
  lib/console/deployments/pr/impl/gitlab.ex
  lib/console/deployments/pr/impl/pass.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/deployments/pipeline.ex
  lib/console/graphql/resolvers/deployments/git.ex
  lib/console/graphql/schema/base.ex
  lib/console/schema/pipeline_gate.ex
  lib/console/schema/scm_webhook.ex
  lib/console_web/controllers/webhook_controller.ex
  lib/console_web/router.ex
  priv/repo/migrations/20240209225431_add_scm_webhook_owner.exs
  schema/schema.graphql
  test/console/deployments/git_test.exs
  test/console/graphql/mutations/deployments/git_mutations_test.exs
  test/console/graphql/queries/deployments/git_queries_test.exs
  test/test_helper.exs
Labels: enhancement

#675 Add error handlers appropriately
  lib/console/graphql/kubernetes/job.ex
  lib/kube/models.ex
Labels: enhancement

#676 Cluster Backup/Restore list queries
  assets/src/generated/graphql.ts
  lib/console/deployments/tree.ex
  lib/console/graphql/deployments/backup.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/kubernetes/deployment.ex
  lib/console/graphql/resolvers/deployments/backup.ex
  lib/console/schema/cluster_restore.ex
  schema/schema.graphql
  test/console/graphql/queries/deployments/backup_queries_test.exs
Labels: enhancement

#671 Add pipeline status sideload
  assets/src/generated/graphql.ts
  lib/console/graphql.ex
  lib/console/graphql/deployments/pipeline.ex
  lib/console/graphql/resolvers/dataloader.ex
  lib/console/schema/pipeline.ex
  schema/schema.graphql
  test/console/graphql/queries/deployments/pipeline_queries_test.exs
Labels: enhancement

#670 Add scm webhook receiver implementation
  assets/src/generated/graphql.ts
  lib/console/deployments/git.ex
  lib/console/deployments/pr/dispatcher.ex
  lib/console/deployments/pr/impl/github.ex
  lib/console/deployments/pr/impl/gitlab.ex
  lib/console/deployments/pr/impl/pass.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/resolvers/deployments/git.ex
  lib/console/schema/pipeline_gate.ex
  lib/console/schema/pull_request.ex
  lib/console_web/controllers/webhook_controller.ex
  priv/repo/migrations/20240211011247_add_pull_request_status.exs
  schema/schema.graphql
  test/console_web/controllers/webhook_controller_test.exs
Labels: enhancement

#674 Optional k8s dashboard in console chart
  charts/console/Chart.yaml
  charts/console/templates/dashboard/configmap.yaml
  charts/console/templates/dashboard/deployment.yaml
  charts/console/templates/dashboard/rbac.yaml
  charts/console/templates/dashboard/secret.yaml
  charts/console/templates/dashboard/service.yaml
  charts/console/templates/dashboard/serviceaccount.yaml
  charts/console/templates/deployment.yaml
  charts/console/templates/ingress.yaml
  charts/console/values.yaml
  plural/helm/console/Chart.yaml
  plural/helm/console/templates/dashboard/configmap.yaml
  plural/helm/console/templates/dashboard/deployment.yaml
  plural/helm/console/templates/dashboard/rbac.yaml
  plural/helm/console/templates/dashboard/secret.yaml
  plural/helm/console/templates/dashboard/service.yaml
  plural/helm/console/templates/dashboard/serviceaccount.yaml
  plural/helm/console/values.yaml
Labels: enhancement

#681 feat: Component tree view
  assets/src/components/apps/app/components/misc.tsx
  assets/src/components/cd/cluster/pod/logs/ContainerLogs.tsx
  assets/src/components/cd/pipelines/EdgeLine.tsx
  assets/src/components/cd/pipelines/Pipelines.tsx
  assets/src/components/cd/pipelines/nodes/BaseNode.tsx
  assets/src/components/cd/pipelines/utils/getNodesAndEdges.tsx
  assets/src/components/cluster/pods/PodsList.tsx
  assets/src/components/component/ComponentRaw.tsx
  assets/src/components/component/ComponentTree.tsx
  assets/src/components/component/directory.tsx
  assets/src/components/component/tree/ComponentTreeGraph.tsx
  assets/src/components/component/tree/ComponentTreeNode.tsx
  assets/src/components/component/tree/getTreeNodesAndEdges.tsx
  assets/src/components/hooks/reactFlowHooks.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/componentTree.graphql
  assets/src/graph/kubernetes/kubernetes.graphql
  assets/src/routes/cdRoutes.tsx
Labels: enhancement, frontend

#683 feat: extend service with contexts
  charts/controller/crds/deployments.plural.sh_scmconnections.yaml
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  controller/api/v1alpha1/scmconnection_types.go
  controller/api/v1alpha1/servicedeployment_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_scmconnections.yaml
  controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/client/console.go
  controller/internal/client/context.go
  controller/internal/client/prautomation.go
  controller/internal/client/provider.go
  controller/internal/client/scmconnection.go
  controller/internal/controller/scmconnection_controller.go
  controller/internal/controller/servicedeployment_controller.go
  controller/internal/errors/base.go
  controller/internal/test/mocks/ConsoleClient_mock.go
Labels: enhancement

#682 Begin working on PR-based pipelines
  assets/src/generated/graphql.ts
  config/prod.exs
  lib/console/deployments/cron.ex
  lib/console/deployments/events.ex
  lib/console/deployments/pipelines.ex
  lib/console/deployments/pipelines/discovery.ex
  lib/console/deployments/pipelines/stage_worker.ex
  lib/console/deployments/pubsub/recurse.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/deployments/pipeline.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/pipeline.ex
  lib/console/schema/pipeline_context.ex
  lib/console/schema/pipeline_promotion.ex
  lib/console/schema/pipeline_pull_request.ex
  lib/console/schema/pipeline_stage.ex
  lib/console/schema/promotion_criteria.ex
  priv/repo/migrations/20240213203030_add_pr_promotions.exs
  schema/schema.graphql
  test/console/deployments/pipeline_test.exs
  test/console/deployments/pubsub/recurse_test.exs
  test/console/graphql/queries/deployments/pipeline_queries_test.exs
  test/support/factory.ex
  test/test_helper.exs
Labels: enhancement

#685 Control promotions for pr pipelines
  assets/src/generated/graphql.ts
  lib/console/deployments/pipelines.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/graphql/deployments/pipeline.ex
  lib/console/graphql/resolvers/deployments/pipeline.ex
  schema/schema.graphql
  test/console/graphql/queries/deployments/pipeline_queries_test.exs
Labels: enhancement

#687 feat: Add table view for Pipelines
  assets/package.json
  assets/src/components/cd/cluster/ClusterSettings.tsx
  assets/src/components/cd/pipelines/DeletePipeline.tsx
  assets/src/components/cd/pipelines/PipelineDetails.tsx
  assets/src/components/cd/pipelines/PipelineGraph.tsx
  assets/src/components/cd/pipelines/Pipelines.tsx
  assets/src/components/cd/pipelines/PipelinesColumns.tsx
  assets/src/components/cd/pipelines/job/PipelineJob.tsx
  assets/src/components/cd/pipelines/job/PipelineJobSpecs.tsx
  assets/src/components/cd/pipelines/nodes/StageNode.tsx
  assets/src/components/cd/pipelines/utils/getNodesAndEdges.tsx
  assets/src/components/component/ComponentRaw.tsx
  assets/src/components/component/tree/ComponentTreeGraph.tsx
  assets/src/components/component/tree/ComponentTreeNode.tsx
  assets/src/components/pr/automations/CreatePrModal.tsx
  assets/src/components/pr/scm/CreateScmConnection.tsx
  assets/src/components/pr/scm/EditScmConnection.tsx
  assets/src/components/utils/Confirm.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdPipelines.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/pipelineRoutes.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#690 Add query to remove backup configuration for a cluster
  assets/src/generated/graphql.ts
  lib/console/deployments/backups.ex
  lib/console/graphql/deployments/backup.ex
  lib/console/graphql/resolvers/deployments/backup.ex
  schema/schema.graphql
  test/console/deployments/backups_test.exs
  test/console/graphql/mutations/deployments/backup_mutations_test.exs
Labels: enhancement

#691 Add support for toggling templating on a service, and azure resource group config
  .tool-versions
  README.md
  assets/src/generated/graphql.ts
  lib/console/deployments/git/agent.ex
  lib/console/deployments/git/discovery.ex
  lib/console/deployments/services.ex
  lib/console/graphql/configuration.ex
  lib/console/graphql/deployments/backup.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/kubernetes.ex
  lib/console/graphql/kubernetes/config.ex
  lib/console/graphql/middleware/cd_authed.ex
  lib/console/graphql/resolvers/deployments/service.ex
  lib/console/schema/object_store.ex
  lib/console/schema/service.ex
  priv/repo/migrations/20240216001533_add_services_templated.exs
  schema/schema.graphql
  test/console/graphql/queries/kubernetes_queries_test.exs
  test/console/graphql/queries/user_queries_test.exs
Labels: enhancement

#689 fix: Switch `bucket` to `containter` for Azure in Velero chart
  charts/velero/values.yaml.liquid
Labels: bug-fix

#693 Fix service delinking for deletion protected svcs, enable backup filtering
  assets/src/generated/graphql.ts
  lib/console/deployments/backups.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/schema/cluster.ex
  schema/schema.graphql
  test/console/deployments/backups_test.exs
Labels: enhancement

#692 feat: push image to docker registry
  .github/workflows/controller-cd.yaml
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
Labels: enhancement

#688 feat: add dependency automation setup
  assets/.gitignore
  assets/package.json
  assets/src/components/pr/queue/PrQueueColumns.tsx
  assets/src/components/pr/scm/PrScmConnections.tsx
  assets/src/components/pr/scm/SetupDependencyAutomation.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/automation.graphql
  assets/src/graph/cdPrs.graphql
  assets/src/types/regex.ts
Labels: enhancement

#695 feat: extend service deployment with the templated flag
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  controller/api/v1alpha1/servicedeployment_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/controller/servicedeployment_controller.go
  controller/internal/controller/servicedeployment_controller_test.go
Labels: enhancement

#694 Add schemas for personas
  assets/src/generated/graphql.ts
  controller/api/v1alpha1/prautomation_types.go
  lib/console/deployments/services.ex
  lib/console/graphql/resolvers/user.ex
  lib/console/graphql/users.ex
  lib/console/schema/persona.ex
  lib/console/services/users.ex
  priv/repo/migrations/20240217015346_add_personas.exs
  priv/repo/seeds/06_personas.exs
  schema/schema.graphql
  test/console/graphql/mutations/user_mutations_test.exs
  test/console/graphql/queries/user_queries_test.exs
  test/support/factory.ex
Labels: enhancement

#677 feat: Cluster backups
  assets/src/components/backups/Backups.tsx
  assets/src/components/backups/backups/Backups.tsx
  assets/src/components/backups/backups/ConfigureClusterBackups.tsx
  assets/src/components/backups/backups/ConfigureClusterBackupsModal.tsx
  assets/src/components/backups/backups/DeleteClusterBackups.tsx
  assets/src/components/backups/clusterbackups/ClusterBackups.tsx
  assets/src/components/backups/clusterbackups/RestoreClusterBackup.tsx
  assets/src/components/backups/objectstores/CreateObjectStore.tsx
  assets/src/components/backups/objectstores/DeleteObjectStore.tsx
  assets/src/components/backups/objectstores/ObjectStoreCloudSettings.tsx
  assets/src/components/backups/objectstores/ObjectStores.tsx
  assets/src/components/backups/objectstores/SaveObjectStoreModal.tsx
  assets/src/components/backups/objectstores/UpdateObjectStore.tsx
  assets/src/components/backups/objectstores/utils.tsx
  assets/src/components/cd/addOns/ClusterSelect.tsx
  assets/src/components/cd/clusters/ClustersColumns.tsx
  assets/src/components/cd/clusters/DynamicClusterIcon.tsx
  assets/src/components/cd/providers/Providers.tsx
  assets/src/components/cd/utils/useBackupsEnabled.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/backups.graphql
  assets/src/graph/cdClusters.graphql
  assets/src/routes/backupRoutes.tsx
  assets/src/routes/backupRoutesConsts.tsx
  assets/src/routes/consoleRoutes.tsx
  charts/velero/templates/schedule.yaml
  charts/velero/values.yaml
  charts/velero/values.yaml.liquid
Labels: enhancement, frontend

#697 Fix kick service, and applied context in query
  lib/console/graphql/resolvers/deployments/service.ex
  lib/console/schema/pipeline_stage.ex
Labels: enhancement

#698 Add pr automation id to promotion criteria
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/pipeline.ex
  schema/schema.graphql
Labels: enhancement

#699 Fix kickService bugs
  lib/console/deployments/services.ex
  test/console/graphql/mutations/deployments/services_mutations_test.exs
Labels: enhancement

#701 feat: extend promotion criteria with PR automation ref
  charts/controller/crds/deployments.plural.sh_pipelines.yaml
  controller/api/v1alpha1/pipeline_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_pipelines.yaml
  controller/go.mod
  controller/go.sum
  controller/internal/controller/pipeline_controller_attributes.go
  controller/internal/utils/kubernetes.go
Labels: enhancement

#703 feat: Add service pod view
  assets/src/components/cd/cluster/pod/PodInfo.tsx
  assets/src/components/cd/cluster/pod/PodShell.tsx
  assets/src/components/cd/services/service/pod/Pod.tsx
  assets/src/components/cluster/containers/ContainerShell.tsx
  assets/src/components/cluster/containers/ContainersList.tsx
  assets/src/components/cluster/pods/PodEvents.tsx
  assets/src/components/cluster/pods/PodRaw.tsx
  assets/src/components/component/info/Pods.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdServices.graphql
  assets/src/graph/kubernetes/pod.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
Labels: enhancement, frontend

#704 Wire console to use agent v0.4.10
  AGENT_VERSION
Labels: enhancement

#706 Fix null constraint for status
  assets/src/generated/graphql.ts
  lib/console/graphql/deployments/git.ex
  schema/schema.graphql
Labels: enhancement

#705 fix: byok consoles don't handle metrics properly
  assets/src/components/cd/cluster/ClusterNodes.tsx
  assets/src/components/cd/services/component/ServiceComponent.tsx
  assets/src/components/cluster/nodes/ClusterGauges.tsx
  assets/src/components/cluster/nodes/ClusterMetrics.tsx
  assets/src/components/cluster/nodes/Nodes.tsx
  assets/src/components/cluster/nodes/SaturationGraphs.tsx
  assets/src/components/contexts/DeploymentSettingsContext.tsx
  assets/src/components/hooks/usePersistedState.tsx
  assets/src/components/layout/Console.tsx
  assets/src/routes/cdRoutes.tsx
Labels: bug-fix

#709 fix cast embed call
  lib/console/schema/pr_automation.ex
  test/console/deployments/git_test.exs
Labels: enhancement

#696 feat: Support GCS in Velero chart
  assets/src/components/backups/objectstores/SaveObjectStoreModal.tsx
  charts/velero/templates/schedule.yaml
  charts/velero/templates/secret.yaml
  charts/velero/values.yaml
  charts/velero/values.yaml.liquid
Labels: enhancement

#710 Default templated to true and other backup/restore fixes
  lib/console/schema/object_store.ex
  lib/console/schema/service.ex
  test/console/deployments/clusters_test.exs
Labels: bug-fix

#711 feat: add pipeline context resource
  charts/controller/crds/deployments.plural.sh_pipelinecontexts.yaml
  charts/controller/templates/manager-rbac.yaml
  controller/PROJECT
  controller/api/v1alpha1/pipelinecontext_types.go
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/config/crd/bases/deployments.plural.sh_pipelinecontexts.yaml
  controller/config/rbac/pipelinecontext_editor_role.yaml
  controller/config/rbac/pipelinecontext_viewer_role.yaml
  controller/config/rbac/role.yaml
  controller/config/samples/deployments_v1alpha1_pipelinecontext.yaml
  controller/internal/client/console.go
  controller/internal/client/pipeline.go
  controller/internal/controller/cluster_controller.go
  controller/internal/controller/pipelinecontext_controller.go
  controller/internal/controller/pipelinecontext_controller_test.go
  controller/internal/controller/pipelinecontext_scope.go
  controller/internal/test/mocks/ConsoleClient_mock.go
  controller/internal/types/reconciler.go
Labels: enhancement

#712 fix: Fix velero secret
  charts/velero/templates/secret.yaml
Labels: bug-fix

#713 use agent v0.4.11
  AGENT_VERSION
Labels: enhancement

#714 fix: do not always redirect to CD page
  assets/src/components/contexts/DeploymentSettingsContext.tsx
  assets/src/components/layout/Sidebar.tsx
Labels: bug-fix

#715 fix: Console logout seems buggy
  assets/package.json
  assets/src/components/contexts/DeploymentSettingsContext.tsx
  assets/src/components/layout/Console.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/utils/Posthog.ts
  assets/src/index.tsx
  assets/src/routes/rootRoutes.tsx
  assets/yarn.lock
Labels: bug-fix

#717 Properly check helm chart config for multisource
  lib/console/deployments/services.ex
Labels: enhancement

#720 fix: Use service ID to fetch pod logs if available
  assets/src/components/cd/cluster/pod/logs/ContainerLogs.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/kubernetes/pod.graphql
Labels: bug-fix

#721 Notification Router APIs
  assets/src/generated/graphql.ts
  config/prod.exs
  lib/console/deployments/backups.ex
  lib/console/deployments/notifications.ex
  lib/console/deployments/pubsub/consumers/notifications.ex
  lib/console/deployments/pubsub/protocols/notifiable.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/notification.ex
  lib/console/graphql/deployments/pipeline.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/notification.ex
  lib/console/schema/notification_router.ex
  lib/console/schema/notification_sink.ex
  lib/console/schema/router_filter.ex
  lib/console/schema/router_sink.ex
  priv/notifications/slack/cluster.create.json.eex
  priv/notifications/slack/pipeline.update.json.eex
  priv/notifications/slack/service.update.json.eex
  priv/notifications/teams/service.update.json.eex
  priv/repo/migrations/20240222232242_add_notification_routing.exs
  schema/schema.graphql
  test/console/deployments/backups_test.exs
  test/console/deployments/notifications_test.exs
  test/console/deployments/pubsub/notification_test.exs
  test/console/graphql/mutations/deployments/notification_mutations_test.exs
  test/console/graphql/queries/deployments/notification_queries_test.exs
  test/support/factory.ex
  test/support/test_helpers.ex
Labels: enhancement

#722 Use agent v0.4.12
  AGENT_VERSION
Labels: enhancement

#725 feat: Fix crash in controller on pr automation pipelines
  assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
  assets/src/components/cd/services/service/ServiceKick.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdServices.graphql
  controller/internal/controller/pipeline_controller_attributes.go
  controller/internal/controller/pipeline_controller_test.go
Labels: bug-fix

#724 feat: Create new pipeline details view
  assets/src/components/cd/pipelines/PipelineContexts.tsx
  assets/src/components/cd/pipelines/PipelineDetails.tsx
  assets/src/components/cd/pipelines/PipelinePullRequests.tsx
  assets/src/components/cd/pipelines/context/PipelineContextDetails.tsx
  assets/src/components/cd/pipelines/nodes/StageNode.tsx
  assets/src/components/component/ComponentRaw.tsx
  assets/src/components/pr/queue/PrQueueColumns.tsx
  assets/src/components/utils/SplitPane.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdPipelines.graphql
  assets/src/graph/kubernetes/pod.graphql
  assets/src/routes/pipelineRoutes.tsx
Labels: enhancement

#728 Allow console tls to be disabled
  charts/console/Chart.yaml
  charts/console/templates/ingress.yaml
  charts/console/values.yaml
Labels: enhancement

#727 Add new fields for pr automation regex replacements
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  controller/Makefile
  controller/api/v1alpha1/prautomation_types.go
  controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  controller/go.mod
  controller/go.sum
  lib/console/graphql/deployments/pipeline.ex
  lib/console/schema/stage_service.ex
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
  schema/schema.graphql
Labels: enhancement

#730 Configure GitHub urls
  config/config.exs
  lib/console.ex
  lib/console/deployments/compatibilities/table.ex
  lib/console/deployments/deprecations/table.ex
  lib/console/graphql/resolvers/deployments.ex
  rel/config/console.exs
Labels: enhancement

#731 feat: eng 1863 show prs for services in pipeline stage nodes
  assets/src/components/cd/clusters/ClusterUpgrade.tsx
  assets/src/components/cd/pipelines/PipelineContexts.tsx
  assets/src/components/cd/pipelines/nodes/StageNode.tsx
  assets/src/components/cd/services/service/ServiceKick.tsx
  assets/src/components/pr/automations/PrAutomationsColumns.tsx
  assets/src/components/pr/queue/PrQueueColumns.tsx
  assets/src/components/utils/ModalMountTransition.tsx
  assets/src/components/utils/StopPropagation.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/automation.graphql
  assets/src/graph/cdPipelines.graphql
Labels: enhancement, frontend

#732 Flesh out more attributes for pr generation
  lib/console/deployments/git.ex
  lib/console/deployments/pipelines.ex
  lib/console/deployments/pr/impl/github.ex
  lib/console/deployments/pr/impl/gitlab.ex
  test/console/deployments/pipeline_test.exs
  test/console/deployments/pubsub/recurse_test.exs
Labels: enhancement

#733 feat: Move PR link column to left
  assets/src/components/pr/queue/PrQueueColumns.tsx
Labels: enhancement, frontend

#735 feat: watch pipeline for changes
  controller/api/v1alpha1/zz_generated.deepcopy.go
  controller/internal/controller/pipelinecontext_controller.go
  controller/internal/controller/pipelinecontext_controller_test.go
Labels: enhancement

#734 Refresh Token implementation
  AGENT_VERSION
  Dockerfile
  assets/src/components/login/Login.tsx
  assets/src/generated/graphql.ts
  config/prod.exs
  lib/console/cron/jobs.ex
  lib/console/graphql/resolvers/user.ex
  lib/console/graphql/users.ex
  lib/console/schema/persona.ex
  lib/console/schema/refresh_token.ex
  lib/console/services/users.ex
  priv/repo/migrations/20240228210958_add_refresh_tokens.exs
  rel/config/config.exs
  schema/schema.graphql
  test/console/cron/jobs_test.exs
  test/console/graphql/mutations/user_mutations_test.exs
  test/console/graphql/queries/user_queries_test.exs
  test/console/services/users_test.exs
  test/support/factory.ex
Labels: enhancement

#736 feat: ENG 1794 – Personas
  assets/src/components/account/Account.tsx
  assets/src/components/account/groups/GroupEdit.tsx
  assets/src/components/account/personas/DeepOmit.tsx
  assets/src/components/account/personas/Persona.tsx
  assets/src/components/account/personas/PersonaAttributesEdit.tsx
  assets/src/components/account/personas/PersonaBindingsEdit.tsx
  assets/src/components/account/personas/PersonaConfiguration.tsx
  assets/src/components/account/personas/PersonaCreate.tsx
  assets/src/components/account/personas/PersonaView.tsx
  assets/src/components/account/personas/Personas.tsx
  assets/src/components/account/personas/PersonasList.tsx
  assets/src/components/account/personas/PersonasSearchHeader.tsx
  assets/src/components/account/roles/RoleFormBindings.tsx
  assets/src/components/apps/app/oidc/UserManagement.tsx
  assets/src/components/cd/ContinuousDeployment.tsx
  assets/src/components/cd/pipelines/nodes/StageNode.tsx
  assets/src/components/contexts.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/login/Login.tsx
  assets/src/components/login/reducePersonaConfigs.tsx
  assets/src/components/pr/automations/PrAutomationsColumns.tsx
  assets/src/components/utils/BindingInput.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/personas.graphql
  assets/src/graph/users.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/consoleRoutes.tsx
  assets/src/utils/deepOmitKey.tsx
Labels: enhancement, frontend
