Repository pluralsh/console, pull requests merged in 2024-08, with the labels that each got.

#1236 feat: Improved add-on compatibility matrices
  Makefile
  assets/package.json
  assets/src/components/cd/cluster/Cluster.tsx
  assets/src/components/cd/cluster/ClusterAddOns.tsx
  assets/src/components/cd/cluster/ClusterAddOnsEntry.tsx
  assets/src/components/cd/cluster/addon/ClusterAddOnCompatibility.tsx
  assets/src/components/cd/cluster/addon/ClusterAddOnDetails.tsx
  assets/src/components/cd/cluster/addon/ClusterAddOnDetailsSidecar.tsx
  assets/src/components/cd/cluster/addon/ClusterAddOnReadme.tsx
  assets/src/components/cd/cluster/addon/ClusterAddOnReleases.tsx
  assets/src/components/cd/clusters/ClusterUpgrade.tsx
  assets/src/components/cd/clusters/ClusterUpgradeFlyover.tsx
  assets/src/components/cd/clusters/runtime/RuntimeServices.tsx
  assets/src/components/cd/clusters/runtime/columns.tsx
  assets/src/components/cd/utils/ClusterSelector.tsx
  assets/src/components/stacks/Stacks.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/types/react-table.d.ts
  assets/yarn.lock
  docker-compose.yml
Labels: enhancement

#1240 fix: Fix command palette shortcuts
  assets/package.json
  assets/src/components/commandpalette/CommandHotkeys.tsx
  assets/src/components/commandpalette/CommandPalette.tsx
  assets/src/components/commandpalette/CommandPaletteLauncher.tsx
  assets/src/components/commandpalette/CommandPaletteShortcut.tsx
  assets/src/components/commandpalette/commands.ts
  assets/src/components/commandpalette/shortcuts.ts
  assets/yarn.lock
Labels: bug-fix

#1239 Begin working on oci client
  assets/src/components/cd/repos/HelmRepositoriesColumns.tsx
  assets/src/components/cd/repos/Repositories.tsx
  assets/src/components/cd/repos/RepositoriesFilters.tsx
  assets/src/components/cd/services/ServiceSettings.tsx
  assets/src/components/cd/services/deployModal/DeployServiceSettingsHelm.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdGitRepos.graphql
  charts/console/templates/clusterrolebinding.yaml
  charts/console/templates/secrets.yaml
  charts/console/templates/serviceaccount.yaml
  charts/console/values.yaml
  charts/controller/templates/secret.yaml
  charts/controller/values.yaml
  config/config.exs
  go/client/models_gen.go
  lib/console.ex
  lib/console/deployments/clusters.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/git.ex
  lib/console/deployments/helm/agent.ex
  lib/console/deployments/helm/agent_cache.ex
  lib/console/deployments/init.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/graphql/configuration.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments/git.ex
  lib/console/schema/cluster.ex
  lib/console/schema/embeds.ex
  lib/console/schema/helm_repository.ex
  lib/console/schema/service.ex
  lib/helm/client.ex
  lib/helm/interface.ex
  lib/helm/interface/http.ex
  lib/helm/interface/oci.ex
  lib/helm/utils.ex
  lib/oci/auth.ex
  lib/oci/client.ex
  lib/oci/schema.ex
  rel/config/console.exs
  schema/schema.graphql
  test/console/deployments/clusters_test.exs
  test/console/deployments/helm/agent_test.exs
  test/console/graphql/mutations/deployments/cluster_mutations_test.exs
  test/console/graphql/mutations/deployments/git_mutations_test.exs
  test/console/graphql/queries/deployments/git_queries_test.exs
  test/oci/client_test.exs
  test/support/factory.ex
Labels: enhancement

#1245 fix: Fix command palette shortcuts
  assets/src/components/commandpalette/CommandHotkeys.tsx
  assets/src/components/commandpalette/CommandPalette.tsx
  assets/src/components/commandpalette/CommandPaletteLauncher.tsx
  assets/src/components/commandpalette/CommandPaletteShortcuts.tsx
  assets/src/components/commandpalette/commands.ts
Labels: bug-fix

#1247 Add error messaging to native helm repositories
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/deployments/helm/agent.ex
  lib/console/graphql/deployments/git.ex
  lib/console/schema/helm_repository.ex
  lib/helm/interface/oci.ex
  priv/repo/migrations/20240805144159_add_helm_repository_error.exs
  schema/schema.graphql
Labels: enhancement

#1248 Add error messaging to native helm repositories
  assets/src/generated/graphql.ts
  charts/console-rapid/Chart.yaml
  charts/console/Chart.yaml
  charts/console/templates/_helpers.tpl
  charts/console/templates/clusterrolebinding.yaml
  charts/console/templates/deployment.yaml
  charts/console/templates/migration.yaml
  charts/console/templates/secrets.yaml
  charts/console/values.yaml
  go/client/models_gen.go
  lib/console/graphql/deployments/git.ex
  lib/console/policies/users.ex
  lib/console/schema/user.ex
  lib/console/services/users.ex
  rel/config/console.exs
  schema/schema.graphql
  test/console/services/users_test.exs
Labels: enhancement

#1255 enhancement: Remove auto-update tab from global settings page
  assets/src/components/settings/global/GlobalSettings.tsx
  assets/src/components/settings/global/SelfManage.tsx
  assets/src/routes/settingsRoutes.tsx
Labels: enhancement

#1254 add auth token encryption
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  Dockerfile
  assets/.env
  assets/package.json
  assets/src/helpers/auth.ts
  assets/yarn.lock
Labels: enhancement, frontend

#1252 Properly communicate ssl_opts in releases
  assets/src/generated/graphql.ts
  lib/console/deployments/clusters.ex
  lib/console/deployments/git.ex
  lib/console/deployments/global.ex
  lib/console/deployments/pipelines.ex
  lib/console/deployments/policies/policies.ex
  lib/console/deployments/settings.ex
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments/observability.ex
  lib/console/graphql/resolvers/deployments/observability.ex
  lib/console/schema/helm_repository.ex
  rel/config/console.exs
  schema/schema.graphql
  test/console/deployments/clusters_test.exs
  test/console/deployments/services_test.exs
  test/console/deployments/settings_test.exs
  test/console/deployments/stacks_test.exs
Labels: enhancement

#1261 fix secret in dockerfile
  Dockerfile
Labels: bug-fix, frontend

#1262 reconfigure command palette shortcuts
  assets/src/components/commandpalette/commands.ts
Labels: enhancement, frontend

#1266 Fix controller chart
  charts/console-rapid/Chart.lock
  charts/console-rapid/Chart.yaml
  charts/console-rapid/charts/controller-0.0.69.tgz
  charts/console-rapid/charts/controller-0.0.70.tgz
  charts/console-rapid/charts/kas-0.1.0.tgz
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.69.tgz
  charts/console/charts/controller-0.0.70.tgz
  charts/console/charts/kas-0.1.0.tgz
  charts/controller/Chart.yaml
  charts/controller/templates/deployment.yaml
  plural/helm/console/Chart.lock
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/controller-0.0.69.tgz
  plural/helm/console/charts/controller-0.0.70.tgz
Labels: bug-fix, hotfix

#1267 Bump chart versions
  charts/console-rapid/Chart.yaml
  charts/console/Chart.yaml
Labels: bug-fix, hotfix

#1268 De-authz git fetch
  lib/console/graphql/resolvers/deployments/git.ex
  test/console/deployments/settings_test.exs
  test/console/graphql/queries/deployments/git_queries_test.exs
Labels: enhancement

#1269 fix: update bindings and requeue time
  go/controller/internal/controller/infrastructurestack_controller.go
  go/controller/internal/controller/project_controller.go
Labels: bug-fix

#1270 enhancement: Improve location of help widget
  assets/src/components/help/HelpLauncher.tsx
  assets/src/components/help/HelpLauncherBtn.tsx
  assets/src/components/help/HelpMaximizeBtn.tsx
  assets/src/components/help/HelpMenu.tsx
  assets/src/components/layout/Console.tsx
  assets/src/components/layout/Header.tsx
  assets/src/components/login/Login.tsx
Labels: enhancement

#1273 Pre-release fixups
  go/controller/internal/controller/project_controller.go
  lib/console/deployments/pipelines.ex
  lib/console/schema/stage_service.ex
  test/console/deployments/clusters_test.exs
  test/console/deployments/pipelines_test.exs
Labels: enhancement, hotfix

#1278 Fix formatting of postgres cert secret
  charts/console/Chart.yaml
  charts/console/templates/secrets.yaml
Labels: bug-fix, hotfix

#1279 Fix secret formatting
  charts/console/Chart.yaml
  charts/console/templates/secrets.yaml
Labels: bug-fix, hotfix

#1281 Fixup loose ends w/ cloud provisioning
  charts/console-rapid/Chart.yaml
  charts/console/templates/ingress.yaml
  charts/console/templates/rolebinding.yaml
  config/config.exs
  lib/console/cached/supervisor.ex
  lib/console/policies/users.ex
  rel/config/console.exs
Labels: enhancement, hotfix

#1283 fix: Bindings for all resources
  go/controller/internal/controller/cluster_controller.go
  go/controller/internal/controller/deploymentsettings_controller.go
  go/controller/internal/controller/infrastructurestack_controller.go
  go/controller/internal/types/reconciler.go
Labels: bug-fix

#1284 Fix helm values injection
  lib/console/deployments/services.ex
Labels: bug-fix, hotfix

#1282 fix(prautomationtrigger): pass identifier to the create pull request mutation
  charts/controller/crds/deployments.plural.sh_prautomationtriggers.yaml
  go/controller/api/v1alpha1/prautomationtrigger_types.go
  go/controller/config/crd/bases/deployments.plural.sh_prautomationtriggers.yaml
  go/controller/docs/api.md
  go/controller/internal/client/console.go
  go/controller/internal/client/prautomation.go
  go/controller/internal/controller/prautomationtrigger_controller.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  plural/helm/console/crds/deployments.plural.sh_prautomationtriggers.yaml
Labels: bug-fix

#1287 feat(client): add TriggerRun mutation support to the console client
  go/client/client.go
  go/client/graph/stack.graphql
Labels: enhancement

#1288 feat(client): add support for tag entry to stack configuration
  go/client/client.go
  go/client/graph/stack.graphql
Labels: enhancement

#1289 Allow `StackConfiguration` version to be nullable
  assets/src/generated/graphql.ts
  go/client/client.go
  go/client/models_gen.go
  lib/console/graphql/deployments/stack.ex
  schema/schema.graphql
Labels: enhancement

#1292 Wrap tf plans in tf blocks to show properly formatted output
  priv/pr/stack_summary.md.eex
Labels: bug-fix, hotfix

#1293 fix cards with missing padding
  assets/src/components/apps/app/runbooks/runbook/RunbookDisplay.tsx
  assets/src/components/apps/app/uninstall/Uninstall.tsx
  assets/src/components/billing/BillingFeatureBlockBanner.tsx
  assets/src/components/builds/build/changelog/Changelog.tsx
  assets/src/components/cd/cluster/node/NodeInfo.tsx
  assets/src/components/cd/clusters/create/provider/NodeGroupContainer.tsx
  assets/src/components/cd/globalServices/details/GlobalServiceInfo.tsx
  assets/src/components/cluster/ScalingRecommender.tsx
  assets/src/components/cluster/nodes/ClusterMetrics.tsx
  assets/src/components/cluster/nodes/NodeInfo.tsx
  assets/src/components/cluster/nodes/Nodes.tsx
  assets/src/components/cluster/pods/PodMetadata.tsx
  assets/src/components/component/ComponentMetrics.tsx
  assets/src/components/stacks/create/CreateStackModalFormFiles.tsx
  assets/src/components/stacks/job/StackJob.tsx
  assets/src/components/stacks/overview/StackConfiguration.tsx
  assets/src/components/stacks/overview/StackMetadata.tsx
  assets/src/components/stacks/overview/StackRepository.tsx
  assets/src/components/utils/List.tsx
Labels: bug-fix, frontend

#1296 tweak service component filtering
  assets/src/components/apps/app/components/AppComponents.tsx
  assets/src/components/apps/app/components/Components.tsx
  assets/src/components/cd/services/service/ServiceComponents.tsx
Labels: enhancement, frontend

#1297 add resync button for stack PRs
  assets/src/components/stacks/prs/PrStackRunsAccordion.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/stacks.graphql
Labels: enhancement, frontend

#1298 feat(client): add optional name arg to observability provider query
  go/client/client.go
  go/client/graph/observabilityprovider.graphql
Labels: enhancement

#1246 feat: `HelmRepository` CRD support
  assets/src/components/cd/repos/GitRepositoriesColumns.tsx
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_helmrepositories.yaml
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  go/client/client.go
  go/client/graph/helm.graphql
  go/controller/api/v1alpha1/helmrepository_types.go
  go/controller/api/v1alpha1/servicedeployment_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  go/controller/config/crd/bases/deployments.plural.sh_helmrepositories.yaml
  go/controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  go/controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  go/controller/config/rbac/role.yaml
  go/controller/config/samples/helm_repository.yaml
  go/controller/internal/client/console.go
  go/controller/internal/client/helmrepository.go
  go/controller/internal/controller/common.go
  go/controller/internal/controller/helmrepository_attributes.go
  go/controller/internal/controller/helmrepository_controller.go
  go/controller/internal/controller/helmrepository_test.go
  go/controller/internal/controller/servicedeployment_controller.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  go/controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  plural/helm/console/crds/deployments.plural.sh_helmrepositories.yaml
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
Labels: enhancement

#1299 service revision improvements
  .vscode/settings.json
  assets/src/components/cd/services/ServiceRevisionColumns.tsx
  assets/src/components/cd/services/service/ServiceRevisions.tsx
  assets/src/components/cluster/TableElements.tsx
Labels: enhancement, frontend

#1300 Support helm relative urls
  lib/helm/interface/http.ex
  test/console/deployments/helm/agent_test.exs
Labels: enhancement, hotfix

#1301 improve discoverability of active search/filters
  assets/src/components/kubernetes/common/DataSelect.tsx
  assets/src/components/utils/IconExpander.tsx
Labels: enhancement, frontend

#1302 add stack deletion empty state
  assets/src/components/stacks/StackDeletedEmptyState.tsx
  assets/src/components/stacks/Stacks.tsx
Labels: enhancement, frontend

#1303 Minor cloud fixes
  lib/console/deployments/git/agent.ex
  lib/console/deployments/git/cmd.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/schema/git_repository.ex
Labels: enhancement, hotfix

#1306 Fix controller compilation
  go/controller/internal/client/observabilityprovider.go
Labels: bug-fix, hotfix

#1309 fix upgrade flyover icon
  assets/src/components/cd/clusters/ClusterUpgradeFlyover.tsx
Labels: bug-fix, frontend

#1272 feat: OCI authentication sidecar
  .github/workflows/oci-auth-cd.yaml
  .github/workflows/oci-auth-ci.yaml
  go/go.work
  go/oci-auth/.gitignore
  go/oci-auth/.golangci.yml
  go/oci-auth/.goreleaser.yml
  go/oci-auth/Dockerfile
  go/oci-auth/Makefile
  go/oci-auth/go.mod
  go/oci-auth/go.sum
  go/oci-auth/internal/args/args.go
  go/oci-auth/internal/environment/version.go
  go/oci-auth/internal/handlers/auth/authentication.go
  go/oci-auth/internal/handlers/auth/aws.go
  go/oci-auth/internal/handlers/auth/azure.go
  go/oci-auth/internal/handlers/auth/azure_token_exchanger.go
  go/oci-auth/internal/handlers/auth/basic.go
  go/oci-auth/internal/handlers/auth/gcp.go
  go/oci-auth/internal/handlers/auth/handler.go
  go/oci-auth/internal/handlers/health/handler.go
  go/oci-auth/internal/router/router.go
  go/oci-auth/main.go
Labels: enhancement

#1311 Virtual Cluster APIs
  Makefile
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/deployments/clusters.ex
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/schema/cluster.ex
  lib/console/services/base.ex
  lib/helm/interface/http.ex
  priv/repo/migrations/20240817162941_add_vclusters.exs
  schema/schema.graphql
  test/console/deployments/clusters_test.exs
  test/console/deployments/helm/agent_test.exs
  test/console/deployments/stacks_test.exs
  test/console/graphql/mutations/deployments/cluster_mutations_test.exs
Labels: enhancement

#1313 cluster controller can update bindings and name
  go/controller/api/v1alpha1/cluster_types.go
  go/controller/go.mod
  go/controller/internal/controller/cluster_controller_test.go
Labels: bug-fix

#1317 enhancement(client): Allow getting stacks by name
  go/client/client.go
  go/client/graph/stack.graphql
Labels: enhancement

#1271 fix(controller): stacks configuration handling and observability provider readonly mode
  charts/controller/crds/deployments.plural.sh_infrastructurestacks.yaml
  charts/controller/crds/deployments.plural.sh_observabilityproviders.yaml
  charts/controller/crds/deployments.plural.sh_stackdefinitions.yaml
  go/controller/api/v1alpha1/infrastructurestack_types.go
  go/controller/api/v1alpha1/observabilityprovider_types.go
  go/controller/api/v1alpha1/stackdefinition_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_infrastructurestacks.yaml
  go/controller/config/crd/bases/deployments.plural.sh_observabilityproviders.yaml
  go/controller/config/crd/bases/deployments.plural.sh_stackdefinitions.yaml
  go/controller/docs/api.md
  go/controller/internal/client/console.go
  go/controller/internal/client/observabilityprovider.go
  go/controller/internal/client/stack.go
  go/controller/internal/controller/customstackrun_test.go
  go/controller/internal/controller/infrastructurestack_controller.go
  go/controller/internal/controller/infrastructurestack_test.go
  go/controller/internal/controller/observabilityprovider_controller.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  plural/helm/console/crds/deployments.plural.sh_infrastructurestacks.yaml
  plural/helm/console/crds/deployments.plural.sh_observabilityproviders.yaml
  plural/helm/console/crds/deployments.plural.sh_stackdefinitions.yaml
Labels: bug-fix

#1316 fix: Make stack env and files tables scrollable
  assets/src/components/stacks/environment/StackEnvironment.tsx
  assets/src/components/stacks/files/StackFiles.tsx
Labels: bug-fix

#1319 feat(client): add stack variables support
  go/client/client.go
  go/client/graph/stack.graphql
Labels: enhancement

#1323 enhancement: Stacks breadcrumbs improvements
  assets/src/components/stacks/Stacks.tsx
  assets/src/components/stacks/environment/StackEnvironment.tsx
  assets/src/components/stacks/files/StackFiles.tsx
  assets/src/components/stacks/job/StackJob.tsx
  assets/src/components/stacks/output/StackOutput.tsx
  assets/src/components/stacks/overview/StackOverview.tsx
  assets/src/components/stacks/prs/PrStackRunsAccordion.tsx
  assets/src/components/stacks/prs/StackPrs.tsx
  assets/src/components/stacks/run/Route.tsx
  assets/src/components/stacks/run/job/RunJob.tsx
  assets/src/components/stacks/runs/StackRuns.tsx
  assets/src/components/stacks/state/StackState.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/stacks.graphql
Labels: enhancement

#1322 add animation to cmdk modal
  assets/package.json
  assets/src/components/commandpalette/CommandPaletteDialog.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#1320 Limit cluster node and node metrics fetches
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/deployments/clusters.ex
  lib/console/graphql/deployments/stack.ex
  lib/kube/client.ex
  lib/kube/client/base.ex
  schema/schema.graphql
Labels: enhancement

#1324 change stackrun variables type to Map and regenerate client
  assets/src/generated/graphql.ts
  go/client/client.go
  go/client/models_gen.go
  lib/console/graphql/deployments/stack.ex
  schema/schema.graphql
Labels: bug-fix

#1318 feat(controller): add support for stack variables to the InfrastructureStack
  charts/controller/crds/deployments.plural.sh_infrastructurestacks.yaml
  go/controller/api/v1alpha1/infrastructurestack_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_infrastructurestacks.yaml
  go/controller/docs/api.md
  go/controller/internal/controller/gitrepository_controller.go
  go/controller/internal/controller/infrastructurestack_controller.go
  go/controller/internal/controller/prautomation_controller.go
  plural/helm/console/crds/deployments.plural.sh_infrastructurestacks.yaml
Labels: enhancement

#1325 add json expander component to canary rollout info
  assets/src/components/component/info/rollout/CanarySpecTableColumns.tsx
Labels: enhancement, frontend

#1327 fix: Fix Kubernetes Dashboard pod logs container switching
  assets/src/components/cd/cluster/pod/logs/ContainerLogs.tsx
  assets/src/components/help/HelpLauncherBtn.tsx
  assets/src/components/kubernetes/workloads/Pod.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/graph-kubernetes/workloads/pod.graphql
Labels: bug-fix

#1326 Begin prepping next release
  AGENT_VERSION
  mix.exs
  rel/config/config.exs
Labels: enhancement

#1331 Add scm webhook delete mutation
  assets/src/generated/graphql.ts
  lib/console/deployments/git.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/resolvers/deployments/git.ex
  schema/schema.graphql
  test/console/graphql/mutations/deployments/git_mutations_test.exs
Labels: enhancement

#1330 add actions menu with delete option to scm webhooks
  assets/package.json
  assets/src/components/pr/scm/ScmWebhooksColumns.tsx
  assets/src/components/utils/Confirm.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/automation.graphql
  assets/yarn.lock
Labels: enhancement, frontend

#1335 feat(client): add upsertVirtualCluster mutation
  go/client/client.go
  go/client/graph/cluster.graphql
Labels: enhancement

#1334 Support In-App Notifications and Shared Secrets
  .gitignore
  Makefile
  assets/src/components/notifications/sinks/NotificationSinksColumns.tsx
  assets/src/generated/graphql.ts
  charts/console-rapid/Chart.yaml
  charts/console/templates/deployment.yaml
  charts/console/values.yaml
  config/config.exs
  go/client/models_gen.go
  lib/console/clustering/bootstrapper.ex
  lib/console/deployments/notifications.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/deployments/pubsub/consumers/notifications.ex
  lib/console/graphql/deployments/notification.ex
  lib/console/graphql/resolvers/deployments/notification.ex
  lib/console/schema/app_notification.ex
  lib/console/schema/group.ex
  lib/console/schema/notification_router.ex
  lib/console/schema/notification_sink.ex
  lib/console/schema/shared_secret.ex
  lib/oci/auth.ex
  lib/oci/client.ex
  priv/notifications/plural/cluster.create.json.eex
  priv/notifications/plural/pipeline.update.json.eex
  priv/notifications/plural/pr.close.json.eex
  priv/notifications/plural/pr.create.json.eex
  priv/notifications/plural/service.update.json.eex
  priv/notifications/plural/stack.run.json.eex
  priv/notifications/secret.txt.eex
  priv/repo/migrations/20240824213536_add_app_notifications.exs
  rel/config/console.exs
  schema/schema.graphql
  test/console/deployments/notifications_test.exs
  test/console/deployments/pubsub/notification_test.exs
  test/console/graphql/mutations/deployments/notification_mutations_test.exs
  test/console/graphql/queries/deployments/notification_queries_test.exs
  test/support/factory.ex
Labels: enhancement

#1336 Fix helm chart deployment
  charts/console-rapid/Chart.yaml
  charts/console/templates/deployment.yaml
Labels: bug-fix, hotfix

#1337 Fix oci-auth image tag
  charts/console-rapid/Chart.yaml
  charts/console/templates/migration.yaml
  charts/console/values.yaml
Labels: bug-fix, hotfix

#1338 wrong format for file arg
  charts/console-rapid/Chart.yaml
  charts/console/templates/deployment.yaml
Labels: bug-fix, hotfix

#1340 feat(client): update upsert virtual cluster mutation
  go/client/client.go
  go/client/graph/cluster.graphql
Labels: enhancement

#1341 feat: Show creation time in all pod lists
  assets/src/components/cd/cluster/ClusterPods.tsx
  assets/src/components/cd/pipelines/job/PipelineJobPods.tsx
  assets/src/components/cluster/pods/Pods.tsx
  assets/src/components/cluster/pods/PodsList.tsx
  assets/src/components/component/info/Pods.tsx
  assets/src/components/stacks/run/job/RunJobPods.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/kubernetes/kubernetes.graphql
Labels: enhancement

#1339 service error text wrap
  assets/src/components/cd/services/ServicesTableErrors.tsx
  assets/src/components/cd/services/service/ServiceErrors.tsx
Labels: enhancement, frontend

#1345 Fix minor virtual cluster bugs
  lib/console/deployments/clusters.ex
  lib/console/schema/cluster.ex
  lib/console/services/base.ex
  lib/console/watchers/upgrade.ex
  test/console/deployments/clusters_test.exs
  test/console/graphql/mutations/deployments/cluster_mutations_test.exs
Labels: enhancement

#1342 Add observer system
  assets/src/generated/graphql.ts
  config/prod.exs
  go/client/models_gen.go
  lib/console/deployments/cron.ex
  lib/console/deployments/git.ex
  lib/console/deployments/observer/action.ex
  lib/console/deployments/observer/poller.ex
  lib/console/deployments/observer/runner.ex
  lib/console/deployments/observer/utils.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/resolvers/deployments/git.ex
  lib/console/schema/observer.ex
  lib/console/schema/pr_automation.ex
  lib/console/schema/service_error.ex
  lib/helm/utils.ex
  lib/oci/auth.ex
  priv/repo/migrations/20240826225106_add_observers.exs
  schema/schema.graphql
  test/console/deployments/git_test.exs
  test/console/deployments/observer/runner_test.exs
  test/console/graphql/mutations/deployments/git_mutations_test.exs
  test/console/graphql/queries/deployments/git_queries_test.exs
  test/support/factory.ex
Labels: enhancement

#1347 feat: support PLURAL notification sink in router
  charts/controller/crds/deployments.plural.sh_notificationsinks.yaml
  go/client/client.go
  go/client/graph/notification.graphql
  go/controller/api/v1alpha1/notificationsink_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_notificationsinks.yaml
  go/controller/internal/controller/notificationsink_controller.go
  go/controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_notificationsinks.yaml
Labels: enhancement

#1346 Upgrade insight CRUD
  Dockerfile
  README.md
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/deployments/clusters.ex
  lib/console/deployments/pr/config.ex
  lib/console/graphql/configuration.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/schema/cluster.ex
  lib/console/schema/upgrade_insight.ex
  lib/console/schema/upgrade_insight_detail.ex
  priv/repo/migrations/20240828200406_add_upgrade_insights.exs
  schema/schema.graphql
  test/console/graphql/mutations/deployments/cluster_mutations_test.exs
  test/console/graphql/queries/deployments/cluster_queries_test.exs
Labels: enhancement

#1351 fix observer cron
  lib/console/deployments/cron.ex
  lib/console/schema/app_notification.ex
  test/console/deployments/cron_test.exs
  test/test_helper.exs
Labels: bug-fix, hotfix
