Repository pluralsh/console, pull requests merged in 2025-04, with the labels that each got.

#2083 Bring back gcr to out container build setups
  .github/workflows/ai-proxy-cd.yaml
  .github/workflows/controller-cd.yaml
  .github/workflows/oci-auth-cd.yaml
  .github/workflows/publish.yaml
  .github/workflows/softserve-cd.yaml
  assets/src/generated/graphql.ts
  go/client/client.go
  go/client/models_gen.go
  lib/console/deployments/git.ex
  lib/console/deployments/observer/discovery.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/resolvers/deployments/git.ex
  lib/console/schema/observer.ex
  schema/schema.graphql
  test/console/graphql/mutations/deployments/git_mutations_test.exs
Labels: enhancement, hotfix

#2063 enhancement: Add condition to global settings if using the wrong name/namespace
  go/controller/internal/controller/deploymentsettings_controller.go
Labels: enhancement

#2099 Improve logs tool (and other flow chat tool changes)
  lib/console/ai/chat/engine.ex
  lib/console/ai/tools/logs.ex
  lib/console/ai/tools/pipelines.ex
  lib/console/schema/cluster.ex
  priv/tools/logs.json
  priv/tools/pipelines.json
Labels: enhancement

#2105 chore: Remove clusters view getting started section
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/cd/clusters/ClustersGettingStarted.tsx
Labels: bug-fix, chore

#2106 fix: Cost management graph curve
  assets/src/components/cost-management/details/CostTimeSeriesGraph.tsx
Labels: bug-fix

#2107 Enable Hydra integration
  assets/src/generated/graphql.ts
  config/config.exs
  go/client/models_gen.go
  lib/console/cost/pr.ex
  lib/console/deployments/oauth.ex
  lib/console/graphql.ex
  lib/console/graphql/deployments/oauth.ex
  lib/console/graphql/oidc.ex
  lib/console/graphql/resolvers/oauth.ex
  lib/console/policies/oidc.ex
  lib/console/schema/oidc_provider.ex
  lib/console/services/oidc.ex
  lib/console/services/oidc/hydra.ex
  priv/repo/migrations/20250408160809_add_oidc_schemas.exs
  rel/runtime.exs
  schema/schema.graphql
  test/console/graphql/mutations/oauth_mutations_test.exs
  test/console/graphql/queries/oauth_queries_test.exs
  test/console/services/oidc_test.exs
  test/support/factory.ex
Labels: enhancement

#2104 cost optimization pr improvements
  assets/src/components/ai/chatbot/AISuggestFix.tsx
  assets/src/components/ai/explain/ExplainWithAIPanel.tsx
  assets/src/components/cd/services/service/ServiceScalingRecs.tsx
  assets/src/components/cost-management/details/recommendations/ClusterScalingRecsTableCols.tsx
  assets/src/components/cost-management/details/recommendations/CostManagementDetailsRecommendations.tsx
  assets/src/components/cost-management/details/recommendations/CreateRecommendationPrModal.tsx
  assets/src/components/cost-management/details/recommendations/CreateRecommendationPrSteps.tsx
  assets/src/components/pr/automations/CreatePrModal.tsx
  assets/src/components/pr/automations/PrAutomations.tsx
  assets/src/components/pr/automations/PrAutomationsColumns.tsx
  assets/src/components/pr/automations/PrConfigurationFields.tsx
  assets/src/components/pr/automations/prConfigurationUtils.tsx
  assets/src/components/pr/automations/wizard/CreatePrActions.tsx
  assets/src/components/pr/automations/wizard/CreatePrSteps.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/ai/chat.graphql
  assets/src/graph/automation.graphql
  assets/src/graph/costManagement.graphql
  assets/src/routes/costManagementRoutes.tsx
Labels: enhancement, frontend

#2108 feat: Update erlang version to 27.3.2
  .tool-versions
  Dockerfile
Labels: enhancement

#2109 fix: Reconcile objects only on generation change
  go/controller/internal/controller/flow_controller.go
  go/controller/internal/controller/mcpserver_controller.go
  go/controller/internal/controller/notificationrouter_controller.go
  go/controller/internal/controller/notificationsink_controller.go
  go/controller/internal/controller/observabilityprovider_controller.go
  go/controller/internal/controller/observer_controller.go
  go/controller/internal/controller/oidcprovider_controller.go
  go/controller/internal/controller/pipelinecontext_controller.go
Labels: bug-fix

#2110 Fix base hydra conf
  config/config.exs
Labels: bug-fix, hotfix

#2111 add pre-flight checklist table
  assets/src/components/cd/clusters/ClusterUpgradeFlyover.tsx
  assets/src/components/cd/clusters/clusterUpgradeColumns.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
Labels: enhancement, frontend

#2116 Add ignoreCrds field to services
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/servicedeployment_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  go/controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  go/controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  go/controller/internal/controller/common.go
  go/controller/internal/controller/servicedeployment_controller.go
  lib/console/graphql/deployments/service.ex
  lib/console/schema/service.ex
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
  schema/schema.graphql
Labels: enhancement

#2117 feat(client): Fetch `ignoreCrds`
  go/client/client.go
  go/client/graph/deployment.graphql
Labels: enhancement

#2062 provider impl
  lib/console/deployments/pr/impl/bitbucket.ex
  lib/console/deployments/pr/impl/gitlab.ex
  test/console/ai/pubsub/vector/consumer_test.exs
Labels: enhancement

#2115 feat: Add OIDC consent pages
  assets/public/plural-logo.png
  assets/public/plural-white.png
  assets/src/components/login/OAuthConsent.tsx
  assets/src/components/login/constants.ts
  assets/src/generated/graphql.ts
  assets/src/graph/oauth.graphql
  assets/src/helpers/localStorage.ts
  assets/src/routes/rootRoutes.tsx
Labels: enhancement

#2118 Add write bindings to oidc providers
  AGENT_VERSION
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/deployments/cron.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/oauth.ex
  lib/console/graphql/resolvers/deployments/oauth.ex
  lib/console/policies/oidc.ex
  lib/console/schema/oidc_provider.ex
  lib/console/services/oidc.ex
  lib/hydra/client.ex
  priv/repo/migrations/20250410231606_add_oidc_write_bindings.exs
  schema/schema.graphql
  test/console/deployments/cron_test.exs
  test/console/graphql/queries/deployments/oauth_queries_test.exs
  test/console/services/oidc_test.exs
  test/support/factory.ex
Labels: enhancement

#2125 Use agent 0.5.20
  AGENT_VERSION
  priv/agent-chart.tgz
Labels: bug-fix, hotfix

#2130 feat: Update OIDC provider fragment
  go/client/client.go
  go/client/graph/oauth.graphql
Labels: enhancement

#2129 Fix oidc
  assets/src/components/login/Login.tsx
  assets/src/components/login/OAuthConsent.tsx
  assets/src/components/login/OauthCallback.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/oauth.graphql
  assets/src/helpers/auth.ts
  config/prod.exs
  lib/console/ai/cron.ex
  lib/console/ai/mcp/agent.ex
  lib/console/deployments/observer/runner.ex
  lib/console/deployments/stacks.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  lib/console/jwt/mcp.ex
  lib/console/schema/mcp_server_audit.ex
  mix.exs
  mix.lock
  rel/runtime.exs
  schema/schema.graphql
  test/console/ai/cron_test.exs
  test/console/deployments/stacks_test.exs
  test/console/graphql/mutations/deployments/stack_mutations_test.exs
  test/console/graphql/queries/ai_queries_test.exs
Labels: enhancement

#2131 fix: don't set owner references on InfrastructureStack
  go/controller/internal/controller/servicedeployment_controller.go
  go/controller/internal/utils/kubernetes.go
Labels: bug-fix

#2128 Support flow id on updates
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  go/controller/internal/controller/servicedeployment_controller.go
  lib/console/graphql/deployments/service.ex
  schema/schema.graphql
Labels: enhancement

#2132 chore: Split builds between ARM and AMD64
  .github/workflows/controller-cd.yaml
Labels: enhancement

#2121 Use non root user for server process
  charts/console/values.yaml
  dockerfiles/Dockerfile.softserve
Labels: bug-fix

#2133 Add some flow crd docs
  charts/controller/crds/deployments.plural.sh_flows.yaml
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/flow_types.go
  go/controller/config/crd/bases/deployments.plural.sh_flows.yaml
  lib/console/deployments/flows.ex
  lib/console/graphql/observability.ex
  plural/helm/console/crds/deployments.plural.sh_flows.yaml
Labels: enhancement

#2135 utilization heatmaps
  assets/package.json
  assets/src/components/cd/cluster/Cluster.tsx
  assets/src/components/cd/cluster/ClusterMetrics.tsx
  assets/src/components/cd/cluster/ClusterNodes.tsx
  assets/src/components/cd/logs/Logs.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceMetrics.tsx
  assets/src/components/cluster/nodes/ClusterGauges.tsx
  assets/src/components/cluster/nodes/ClusterMetrics.tsx
  assets/src/components/cost-management/CostManagementTreeMap.tsx
  assets/src/components/cost-management/details/recommendations/ClusterScalingRecsTableCols.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/security/overview/SecurityOverviewCharts.tsx
  assets/src/components/utils/TreeMap.tsx
  assets/src/components/utils/UtilizationHeatmap.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/graph/cdComponent.graphql
  assets/src/graph/metrics.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
  assets/yarn.lock
  go/client/models_gen.go
  graphql.config.yml
  lib/console/deployments/observability.ex
  lib/console/deployments/observability/metrics.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/observability.ex
  lib/console/graphql/resolvers/deployments/observability.ex
  lib/prometheus/schema.ex
  schema/schema.graphql
  test/console/graphql/queries/deployments/cluster_queries_test.exs
  test/console/graphql/queries/deployments/service_queries_test.exs
Labels: enhancement, frontend

#2138 update with new schema
  assets/src/generated/graphql.ts
Labels: bug-fix

#2140 fix auth handling for pagerduty webhook
  lib/console_web/controllers/webhook_controller.ex
  test/console_web/controllers/webhook_controller_test.exs
Labels: bug-fix

#2134 network graph ui
  assets/package.json
  assets/src/components/cd/cluster/Cluster.tsx
  assets/src/components/cd/cluster/ClusterDetails.tsx
  assets/src/components/cd/cluster/ClusterMetadata.tsx
  assets/src/components/cd/cluster/ClusterMetrics.tsx
  assets/src/components/cd/cluster/ClusterNetwork.tsx
  assets/src/components/cd/cluster/ClusterPRs.tsx
  assets/src/components/cd/logs/Logs.tsx
  assets/src/components/cd/pipelines/utils/nodeLayouter.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceNetwork.tsx
  assets/src/components/cd/services/service/component/ComponentList.tsx
  assets/src/components/component/tree/ComponentTreeNode.tsx
  assets/src/components/home/CustomLegend.tsx
  assets/src/components/kubernetes/common/NamespaceFilter.tsx
  assets/src/components/notifications/NotificationsPanel.tsx
  assets/src/components/utils/CountBadge.tsx
  assets/src/components/utils/TimestampSlider.tsx
  assets/src/components/utils/network-graph/NetworkGraph.tsx
  assets/src/components/utils/network-graph/NetworkGraphNodes.tsx
  assets/src/components/utils/reactflow/edges.tsx
  assets/src/components/utils/reactflow/graph.tsx
  assets/src/components/utils/reactflow/markers.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
  assets/yarn.lock
  go/client/models_gen.go
  lib/console/graphql/deployments/cluster.ex
  lib/console/mesh/prometheus.ex
  lib/console/mesh/provider/ebpf.ex
  lib/console/mesh/provider/istio.ex
  lib/console/mesh/provider/utils.ex
  lib/console/mesh/schema.ex
  schema/schema.graphql
  test/console/graphql/queries/deployments/cluster_queries_test.exs
  test/console/mesh/provider/istio_test.exs
Labels: enhancement, frontend

#2006 refactor GetProject method
  go/controller/internal/controller/bootstraptoken_controller.go
  go/controller/internal/controller/catalog_controller.go
  go/controller/internal/controller/cluster_controller.go
  go/controller/internal/controller/common.go
  go/controller/internal/controller/common_test.go
  go/controller/internal/controller/flow_controller.go
  go/controller/internal/controller/globalservice_controller.go
  go/controller/internal/controller/infrastructurestack_controller.go
  go/controller/internal/controller/managednamespace_controller.go
  go/controller/internal/controller/observer_controller.go
  go/controller/internal/controller/pipeline_controller.go
Labels: enhancement

#2141 feat: Add kubelet version to node list
  assets/schema/kubernetes-schema.graphql
  assets/src/components/kubernetes/cluster/Nodes.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/graph-kubernetes/cluster/node.graphql
  charts/console-rapid/Chart.lock
  charts/console-rapid/Chart.yaml
  charts/console-rapid/charts/controller-0.0.115.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
  charts/console-rapid/charts/kubernetes-dashboard-7.11.1.tgz
  charts/console-rapid/charts/kubernetes-dashboard-7.12.0.tgz
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.115.tgz
  charts/console/charts/kas-0.3.0.tgz
  charts/console/charts/kubernetes-dashboard-7.11.1.tgz
  charts/console/charts/kubernetes-dashboard-7.12.0.tgz
  charts/console/values.yaml
  plural/helm/console/Chart.lock
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/controller-0.0.115.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.11.1.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.12.0.tgz
Labels: enhancement

#2142 fix: Fix view layout
  assets/src/components/ai/AIThreads.tsx
Labels: bug-fix

#2143 Prepare 0.11.11 release
  AGENT_VERSION
  lib/console/deployments/git/discovery.ex
  lib/console/schema/service_template.ex
  priv/agent-chart.tgz
  test/console/deployments/global_test.exs
  test/console/mesh/provider/istio_test.exs
Labels: enhancement, hotfix

#2151 service details consolidation
  assets/src/components/cd/cluster/ClusterMetrics.tsx
  assets/src/components/cd/services/deployModal/DeployServiceSettingsHelmValues.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceHelm.tsx
  assets/src/components/cd/services/service/ServiceMetrics.tsx
  assets/src/components/cd/services/service/ServiceRevisions.tsx
  assets/src/components/cd/services/service/ServiceSettings.tsx
  assets/src/components/cd/services/service/settings/ServiceRepoSettings.tsx
  assets/src/components/cd/services/service/settings/ServiceSecrets.tsx
  assets/src/components/cd/services/service/settings/ServiceSettings.tsx
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
Labels: enhancement, frontend

#2139 Datadog observability webhook
  config/test.exs
  lib/console/deployments/observability/webhook.ex
  lib/console/deployments/observability/webhook/datadog.ex
  lib/console_web/controllers/webhook_controller.ex
  test/console_web/controllers/webhook_controller_test.exs
Labels: enhancement

#2155 extend RegisterRuntimeServices with deprecated arg
  go/client/client.go
  go/client/graph/cluster.graphql
Labels: enhancement

#2154 Intelligently fetch log context when adding log context to ai insights
  assets/src/components/ai/insights/LogsEvidencePanel.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/ai/insights.graphql
  config/config.exs
  go/client/models_gen.go
  lib/console/ai/chat.ex
  lib/console/ai/evidence/logs.ex
  lib/console/cached/kubernetes.ex
  lib/console/deployments/policy.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/configuration.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/logs/time.ex
  lib/console/mesh/provider.ex
  lib/console/schema/ai_insight_evidence.ex
  lib/console_web/controllers/git_controller.ex
  schema/schema.graphql
  test/console/ai/cron_test.exs
Labels: enhancement

#2157 Fix socket context bug
  .github/workflows/controller-cd.yaml
  .github/workflows/test.yaml
  assets/src/generated/graphql.ts
  lib/console/deployments/pr/impl/github.ex
  lib/console/graphql/deployments/service.ex
  lib/console/schema/pull_request.ex
  lib/console_web/channels/user_socket.ex
  priv/repo/migrations/20250422203453_pr_commit_sha.exs
  schema/schema.graphql
Labels: enhancement

#2160 feat: add input-based confirmation to CRD delete dialog
  assets/src/components/kubernetes/common/DeleteResource.tsx
  assets/src/components/kubernetes/common/ResourceList.tsx
  assets/src/components/kubernetes/common/utils.tsx
  assets/src/components/utils/Confirm.tsx
Labels: enhancement

#2159 fix: Preserve namespace param on initial load
  assets/src/components/kubernetes/Navigation.tsx
  assets/src/components/kubernetes/common/DataSelect.tsx
Labels: bug-fix

#2156 feat: Compliance reports
  assets/package.json
  assets/public/mitm.html
  assets/public/sw.js
  assets/src/components/security/Security.tsx
  assets/src/components/security/policies/CreatePolicyReportModal.tsx
  assets/src/components/security/policies/PastReportsModal.tsx
  assets/src/components/security/policies/Policies.tsx
  assets/src/components/security/policies/PoliciesFilter.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/policies.graphql
  assets/yarn.lock
Labels: enhancement

#2163 feat(console): add "Create secret" button and modal
  assets/src/components/cd/ContinuousDeployment.tsx
  assets/src/components/kubernetes/Navigation.tsx
  assets/src/components/kubernetes/common/ResourceList.tsx
  assets/src/components/kubernetes/common/create/secret/SecretButton.tsx
  assets/src/components/kubernetes/common/create/secret/SecretModal.tsx
  assets/src/components/kubernetes/common/create/secret/common.ts
  assets/src/components/kubernetes/common/create/secret/type/BasicAuth.tsx
  assets/src/components/kubernetes/common/create/secret/type/Opaque.tsx
  assets/src/components/kubernetes/common/create/secret/type/SSH.tsx
  assets/src/components/kubernetes/common/create/secret/type/ServiceAccount.tsx
  assets/src/components/kubernetes/configuration/Secrets.tsx
  assets/src/components/utils/EditableDiv.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/graph-kubernetes/common/resource.graphql
Labels: enhancement

#2158 migrate react flow graphs to elk
  assets/package.json
  assets/src/components/cd/cluster/ClusterNetwork.tsx
  assets/src/components/cd/logs/DateTimeFormInput.tsx
  assets/src/components/cd/pipelines/PipelineGraph.tsx
  assets/src/components/cd/pipelines/nodes/PipelineBaseNode.tsx
  assets/src/components/cd/pipelines/utils/nodeLayouter.tsx
  assets/src/components/cd/services/ServicesTreeDiagram.tsx
  assets/src/components/cd/services/component/ServiceComponent.tsx
  assets/src/components/cd/services/service/ServiceAlerts.tsx
  assets/src/components/cd/services/service/ServiceComponents.tsx
  assets/src/components/cd/services/service/ServiceDependencies.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceErrors.tsx
  assets/src/components/cd/services/service/ServiceInsights.tsx
  assets/src/components/cd/services/service/ServiceLogs.tsx
  assets/src/components/cd/services/service/ServiceNetwork.tsx
  assets/src/components/cd/services/service/ServicePRs.tsx
  assets/src/components/cd/services/service/ServiceScalingRecs.tsx
  assets/src/components/cd/services/service/settings/ServiceSecrets.tsx
  assets/src/components/component/tree/ComponentTreeGraph.tsx
  assets/src/components/stacks/state/StackStateGraph.tsx
  assets/src/components/utils/TimestampSlider.tsx
  assets/src/components/utils/network-graph/NetworkGraph.tsx
  assets/src/components/utils/network-graph/NetworkGraphNodes.tsx
  assets/src/components/utils/network-graph/NetworkGraphStatistics.tsx
  assets/src/components/utils/reactflow/ReactFlowGraph.tsx
  assets/src/components/utils/reactflow/edges.tsx
  assets/src/components/utils/reactflow/graph.tsx
  assets/src/components/utils/reactflow/layouting.tsx
  assets/src/components/utils/reactflow/markers.tsx
  assets/src/components/utils/reactflow/nodes.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/graph/cdServices.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/utils/runAfterBrowserLayout.ts
  assets/yarn.lock
Labels: enhancement, frontend

#2166 fix(chart): disable csrf protection for dashboard API
  charts/console/values.yaml
  plural/helm/console/values.yaml
Labels: bug-fix

#2168 feat: improve helm chart loading state and upgrade design system
  assets/package.json
  assets/src/components/cd/services/ServiceSettings.tsx
  assets/src/components/cd/services/deployModal/DeployServiceSettingsHelm.tsx
  assets/src/components/cd/services/service/settings/ServiceGitSettings.tsx
  assets/src/components/cd/services/service/settings/ServiceHelmSettings.tsx
  assets/src/components/cd/services/service/settings/ServiceSettings.tsx
  assets/src/components/utils/SubTabs.tsx
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
  assets/yarn.lock
Labels: enhancement

#2175 PR Preview Environment CRUD apis
  assets/src/components/flows/Flows.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql.ts
  config/prod.exs
  go/client/models_gen.go
  lib/console/ai/stream/exec.ex
  lib/console/deployments/events.ex
  lib/console/deployments/flows.ex
  lib/console/deployments/flows/preview.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/deployments/pr/dispatcher.ex
  lib/console/deployments/pr/impl/bitbucket.ex
  lib/console/deployments/pr/impl/github.ex
  lib/console/deployments/pr/impl/gitlab.ex
  lib/console/deployments/pr/impl/pass.ex
  lib/console/deployments/pr/utils.ex
  lib/console/deployments/pubsub/consumers/preview.ex
  lib/console/deployments/pubsub/protocols/previewable.ex
  lib/console/graphql/deployments/flow.ex
  lib/console/graphql/resolvers/deployments/flow.ex
  lib/console/schema/preview_environment_instance.ex
  lib/console/schema/preview_environment_template.ex
  lib/console/schema/pull_request.ex
  lib/console/schema/service.ex
  priv/pr/preview_env.md.eex
  priv/repo/migrations/20250428134709_add_preview_environments.exs
  schema/schema.graphql
  test/console/deployments/flows_test.exs
  test/console/deployments/pubsub/preview_test.exs
  test/console/graphql/mutations/deployments/flow_mutations_test.exs
  test/console/graphql/queries/deployments/flow_queries_test.exs
  test/support/factory.ex
  test/test_helper.exs
Labels: enhancement

#2181 feat: Add deprecated custom resources to upgrade panel
  assets/src/components/cd/clusters/ClusterUpgradeFlyover.tsx
  assets/src/components/cd/clusters/clusterDeprecatedCustomResourcesColumns.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
Labels: enhancement

#2176 add alert and knowledge ai evidence types
  assets/src/components/ai/chatbot/Chatbot.tsx
  assets/src/components/ai/chatbot/ChatbotPanelEvidence.tsx
  assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
  assets/src/components/ai/chatbot/ChatbotSendMessageForm.tsx
  assets/src/components/ai/insights/AlertEvidencePanel.tsx
  assets/src/components/ai/insights/InsightEvidence.tsx
  assets/src/components/ai/insights/KnowledgeEvidencePanel.tsx
  assets/src/components/ai/insights/LogsEvidencePanel.tsx
  assets/src/components/flows/FlowCard.tsx
  assets/src/components/utils/alerts/AlertsTable.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/ai/insights.graphql
Labels: enhancement, frontend

#2169 Openai to ollama ai proxy
  go/ai-proxy/Dockerfile
  go/ai-proxy/api/ollama/ollama.go
  go/ai-proxy/args/args.go
  go/ai-proxy/go.mod
  go/ai-proxy/go.sum
  go/ai-proxy/proxy/ollama/embeddings.go
  go/ai-proxy/proxy/ollama/ollama.go
  go/ai-proxy/proxy/proxy.go
  go/ai-proxy/test/ollama/ollama_test.go
  go/ai-proxy/test/py_scripts/ollama_proxy.py
  go/go.work
Labels: enhancement

#2179 newrelic impl
  config/test.exs
  lib/console/deployments/observability/webhook.ex
  lib/console/deployments/observability/webhook/newrelic.ex
  lib/console_web/controllers/webhook_controller.ex
  test/console_web/controllers/webhook_controller_test.exs
Labels: enhancement

#2180 feat: add PreviewEnvironmentTemplate CRD
  .github/workflows/controller-ci.yaml
  charts/controller/crds/deployments.plural.sh_previewenvironmenttemplates.yaml
  go/client/client.go
  go/client/graph/models.graphql
  go/client/graph/previewenvironmenttemplate.graphql
  go/controller/PROJECT
  go/controller/api/v1alpha1/flow_types.go
  go/controller/api/v1alpha1/previewenvironmenttemplate_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_previewenvironmenttemplates.yaml
  go/controller/config/rbac/previewenvironmenttemplate_editor_role.yaml
  go/controller/config/rbac/previewenvironmenttemplate_viewer_role.yaml
  go/controller/config/rbac/role.yaml
  go/controller/config/samples/deployments_v1alpha1_previewenvironmenttemplate.yaml
  go/controller/internal/client/console.go
  go/controller/internal/client/previewenvironmenttemplate.go
  go/controller/internal/controller/clusterrestore_controller.go
  go/controller/internal/controller/prautomation_attributes.go
  go/controller/internal/controller/previewenvironmenttemplate_controller.go
  go/controller/internal/controller/previewenvironmenttemplate_controller_test.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  go/controller/internal/types/reconciler.go
  go/controller/internal/utils/console.go
  plural/helm/console/crds/deployments.plural.sh_previewenvironmenttemplates.yaml
Labels: enhancement

#2187 Add enable helm attribute to service kustomize
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  charts/controller/crds/deployments.plural.sh_previewenvironmenttemplates.yaml
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/servicedeployment_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  go/controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  go/controller/config/crd/bases/deployments.plural.sh_previewenvironmenttemplates.yaml
  go/controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  lib/console/graphql/deployments/service.ex
  lib/console/schema/service.ex
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
  plural/helm/console/crds/deployments.plural.sh_previewenvironmenttemplates.yaml
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
  schema/schema.graphql
Labels: enhancement

#2190 Bump console rapid chart
  charts/console-rapid/Chart.yaml
  charts/console-rapid/charts/controller-0.0.117.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
Labels: enhancement
