Repository pluralsh/console, pull requests merged in 2025-05, with the labels that each got.

#2193 fix cluster details graphql bug
  assets/src/components/cd/cluster/ClusterInsights.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
Labels: bug-fix

#2191 Fixes for preview environments
  lib/console.ex
  lib/console/ai/chat.ex
  lib/console/deployments/flows/preview.ex
  lib/console/deployments/observer/poller.ex
  lib/console/deployments/pr/utils.ex
  lib/console/deployments/pubsub/protocols/previewable.ex
  lib/console/deployments/services.ex
  lib/console/schema/pull_request.ex
  lib/oci/client.ex
  lib/oci/schema.ex
  mix.exs
  mix.lock
  priv/pr/preview_env.md.eex
  priv/repo/migrations/20250430133529_add_onboarding_status.exs
  test/console/ai/chat_test.exs
  test/console/deployments/pubsub/preview_test.exs
  test/console_web/controllers/webhook_controller_test.exs
Labels: enhancement

#2194 ai thread improvements
  assets/package.json
  assets/src/components/ai/AIContext.tsx
  assets/src/components/ai/AIPinButton.tsx
  assets/src/components/ai/AITableActions.tsx
  assets/src/components/ai/AITableEntry.tsx
  assets/src/components/ai/chatbot/ChatMessage.tsx
  assets/src/components/ai/chatbot/ChatMessageContent.tsx
  assets/src/components/ai/chatbot/Chatbot.tsx
  assets/src/components/ai/chatbot/ChatbotButton.tsx
  assets/src/components/ai/chatbot/ChatbotHeader.tsx
  assets/src/components/ai/chatbot/ChatbotPanelEvidence.tsx
  assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
  assets/src/components/ai/chatbot/ChatbotThreadMoreMenu.tsx
  assets/src/components/cd/cluster/ClusterInsightComponent.tsx
  assets/src/components/cd/cluster/ClusterInsights.tsx
  assets/src/components/cd/clusters/ClustersColumns.tsx
  assets/src/components/cd/repos/HelmHealthChip.tsx
  assets/src/components/cd/services/service/ServiceInsights.tsx
  assets/src/components/component/ComponentInsights.tsx
  assets/src/components/security/policies/PoliciesColumns.tsx
  assets/src/components/security/policies/PoliciesTable.tsx
  assets/src/components/stacks/insights/StackInsights.tsx
  assets/src/components/stacks/run/insights/StackRunInsights.tsx
  assets/src/components/utils/MoreMenu.tsx
  assets/src/components/utils/UtilizationHeatmap.tsx
  assets/src/components/utils/alerts/AlertInsight.tsx
  assets/src/components/utils/network-graph/NetworkGraph.tsx
  assets/src/components/utils/network-graph/NetworkGraphNodes.tsx
  assets/src/components/utils/reactflow/edges.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/ai/chat.graphql
  assets/src/graph/policies.graphql
  assets/src/utils/prometheus.ts
  assets/yarn.lock
Labels: enhancement, frontend

#2184 feat: New getting started section
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/contexts/DeploymentSettingsContext.tsx
  assets/src/components/home/GettingStarted.tsx
  assets/src/components/home/Home.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdGlobalSettings.graphql
Labels: enhancement

#2189 feat: extend kustomize with enableHelm field for agent
  go/client/client.go
  go/client/graph/deployment.graphql
Labels: enhancement

#2196 Begin prepping 0.11.13
  assets/src/components/ai/chatbot/prompts.json
  assets/src/components/cd/cluster/Cluster.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/graph/cdServices.graphql
  go/client/models_gen.go
  lib/console/ai/chat.ex
  lib/console/deployments/settings.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/git.ex
  lib/console/mesh/provider.ex
  mix.exs
  mix.lock
  schema/schema.graphql
  test/console/graphql/queries/deployments/git_queries_test.exs
Labels: enhancement

#2202 feat(client): Add automation queries
  go/client/client.go
  go/client/graph/automation.graphql
Labels: enhancement

#2205 Misc gql schema fixes
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  schema/schema.graphql
Labels: enhancement

#2208 Fix preview environment schemas
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/graphql/deployments/flow.ex
  schema/schema.graphql
Labels: bug-fix

#2207 linkerd impl + ebpf unit test
  lib/console/mesh/provider.ex
  lib/console/mesh/provider/linkerd.ex
  test/console/mesh/provider/ebpf_test.exs
  test/console/mesh/provider/linkerd_test.exs
Labels: enhancement

#2209 ui for preview environment in flows
  assets/src/components/cd/services/ServiceSelector.tsx
  assets/src/components/cd/services/ServiceStatusChip.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/services/ServicesTableErrors.tsx
  assets/src/components/cd/services/service/settings/ServiceSettings.tsx
  assets/src/components/contexts/DeploymentSettingsContext.tsx
  assets/src/components/flows/flow/Flow.tsx
  assets/src/components/flows/flow/previews/FlowPreviews.tsx
  assets/src/components/flows/flow/previews/PreviewInstancesTableCols.tsx
  assets/src/components/flows/flow/previews/PreviewTemplatesTable.tsx
  assets/src/components/flows/flow/previews/PreviewTemplatesTableCols.tsx
  assets/src/components/utils/SubTabs.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdServices.graphql
  assets/src/graph/flow.graphql
  assets/src/routes/flowRoutes.tsx
  assets/src/utils/graphql.ts
Labels: enhancement, frontend

#2214 feat: add confirmation prompt with cluster name for DeleteCluster and DetachCluster modals
  assets/src/components/cd/providers/DeleteCluster.tsx
  assets/src/components/cd/providers/DetachCluster.tsx
Labels: enhancement

#2216 preview environment qa
  assets/src/components/ai/McpServers.tsx
  assets/src/components/ai/insights/InsightEvidence.tsx
  assets/src/components/flows/flow/Flow.tsx
  assets/src/components/flows/flow/previews/FlowPreviews.tsx
  assets/src/components/flows/flow/previews/PreviewInstancesTableCols.tsx
  assets/src/components/flows/flow/previews/PreviewTemplatesTable.tsx
  assets/src/components/flows/flow/previews/PreviewTemplatesTableCols.tsx
  assets/src/components/flows/flow/previews/SpawnPreviewModal.tsx
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/ai/mcp.graphql
Labels: enhancement, frontend

#2210 Finalizing v0.11.13
  AGENT_VERSION
  assets/src/generated/graphql.ts
  lib/console/ai/provider.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/user.ex
  lib/console/graphql/users.ex
  lib/console/services/users.ex
  priv/agent-chart.tgz
  schema/schema.graphql
  test/console/deployments/observer/runner_test.exs
  test/console/mesh/provider/cilium_test.exs
  test/console/services/users_test.exs
Labels: enhancement

#2219 Implement dynamic templating in global services
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/globalservice_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  lib/console/deployments/flows/preview.ex
  lib/console/deployments/global.ex
  lib/console/graphql/deployments/global.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/schema/cluster.ex
  lib/console/schema/global_service.ex
  lib/console/schema/template_context.ex
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  priv/repo/migrations/20250507223311_add_template_contexts.exs
  schema/schema.graphql
  test/console/deployments/global_test.exs
  test/support/factory.ex
Labels: enhancement

#2221 bump console rapid chart for testing
  charts/console-rapid/Chart.yaml
  charts/console-rapid/charts/controller-0.0.118.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
Labels: enhancement, hotfix

#2222 fix getting started bugs
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/contexts/DeploymentSettingsContext.tsx
  assets/src/components/home/GettingStarted.tsx
Labels: bug-fix, frontend

#2213 feat: Remove copy button on access tokens list
  assets/src/components/profile/AccessTokens.tsx
  assets/src/components/profile/AccessTokensCreateModal.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/tokens.graphql
Labels: enhancement

#2228 OIDC provider crud
  assets/src/components/settings/global/GlobalSettings.tsx
  assets/src/components/settings/global/GlobalSettingsAgents.tsx
  assets/src/components/settings/global/GlobalSettingsPermissions.tsx
  assets/src/components/settings/global/GlobalSettingsRepositories.tsx
  assets/src/components/settings/global/observability/Observability.tsx
  assets/src/components/settings/global/oidc/OidcCreateProviderModal.tsx
  assets/src/components/settings/global/oidc/OidcProvider.tsx
  assets/src/components/settings/global/oidc/OidcProviderWritePermissions.tsx
  assets/src/components/settings/global/oidc/OidcProviders.tsx
  assets/src/components/settings/global/oidc/OidcSettings.tsx
  assets/src/components/utils/CopyButton.tsx
  assets/src/components/utils/table/StackedText.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cd/globalServices.graphql
  assets/src/graph/oidc.graphql
  assets/src/routes/settingsRoutes.tsx
  assets/src/routes/settingsRoutesConst.tsx
Labels: enhancement, frontend

#2201 feat: add ClusterSync resource
  charts/controller/crds/deployments.plural.sh_clustersyncs.yaml
  go/client/client.go
  go/client/graph/cluster.graphql
  go/controller/PROJECT
  go/controller/api/v1alpha1/clustersync_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_clustersyncs.yaml
  go/controller/config/rbac/clustersync_editor_role.yaml
  go/controller/config/rbac/clustersync_viewer_role.yaml
  go/controller/config/rbac/role.yaml
  go/controller/config/samples/deployments_v1alpha1_clustersync.yaml
  go/controller/internal/client/cluster.go
  go/controller/internal/client/console.go
  go/controller/internal/controller/clustersync_controler_test.go
  go/controller/internal/controller/clustersync_controller.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  go/controller/internal/types/reconciler.go
  go/controller/internal/utils/funcs.go
  go/controller/internal/utils/template.go
  plural/helm/console/crds/deployments.plural.sh_clustersyncs.yaml
Labels: enhancement

#2224 Add compliance report generator schemas and CRUD
  assets/src/generated/graphql.ts
  config/test.exs
  go/client/models_gen.go
  lib/console/ai/mcp/agent.ex
  lib/console/compliance/datasource/services.ex
  lib/console/compliance/report.ex
  lib/console/deployments/flows/preview.ex
  lib/console/deployments/git.ex
  lib/console/deployments/git/agent.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/deployments/policy.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/deployments/policy.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments/git.ex
  lib/console/graphql/resolvers/deployments/policy.ex
  lib/console/graphql/resolvers/deployments/stack.ex
  lib/console/schema/compliance_report.ex
  lib/console/schema/compliance_report_generator.ex
  lib/console_web/controllers/compliance_controller.ex
  lib/console_web/plugs/remote_ip.ex
  lib/console_web/router.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20250508194959_add_compliance_report_generators.exs
  priv/repo/migrations/20250509015538_add_report_generator_id.exs
  rel/runtime.exs
  schema/schema.graphql
  test/console/deployments/git_test.exs
  test/console/graphql/mutations/deployments/policy_mutations_test.exs
  test/console/graphql/queries/deployments/policy_queries_test.exs
  test/console/graphql/queries/deployments/stack_queries_test.exs
  test/console_web/controllers/compliance_controller_test.exs
  test/support/factory.ex
Labels: enhancement

#2235 feat: Example prompts improvements
  assets/src/components/ai/chatbot/ChatbotPanelExamplePrompts.tsx
Labels: enhancement

#2232 add flow breadcrumbs when drilling down into a service
  assets/src/components/cd/cluster/ClusterDetails.tsx
  assets/src/components/cd/cluster/ClusterPods.tsx
  assets/src/components/cd/cluster/node/NodeInfo.tsx
  assets/src/components/cd/cluster/pod/Pod.tsx
  assets/src/components/cd/cluster/pod/PodContainers.tsx
  assets/src/components/cd/cluster/pod/PodInfo.tsx
  assets/src/components/cd/cluster/pod/PodShell.tsx
  assets/src/components/cd/services/ServiceSelector.tsx
  assets/src/components/cd/services/component/ServiceComponent.tsx
  assets/src/components/cd/services/service/ServiceComponents.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceDryRun.tsx
  assets/src/components/cd/services/service/pod/Pod.tsx
  assets/src/components/cd/services/service/settings/ServiceGitSettings.tsx
  assets/src/components/cd/services/service/settings/ServiceSettings.tsx
  assets/src/components/commandpalette/commands.ts
  assets/src/components/component/ComponentDetails.tsx
  assets/src/components/component/info/Pods.tsx
  assets/src/components/component/tree/ComponentTreeNode.tsx
  assets/src/components/flows/flow/Flow.tsx
  assets/src/components/flows/flow/FlowServices.tsx
  assets/src/components/flows/flow/previews/FlowPreviews.tsx
  assets/src/components/flows/flow/previews/PreviewTemplatesTableCols.tsx
  assets/src/components/layout/HeaderProjectSelect.tsx
  assets/src/components/utils/alerts/AlertInsight.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cd/globalServices.graphql
  assets/src/graph/flow.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
  assets/src/routes/flowRoutes.tsx
  assets/src/routes/flowRoutesConsts.tsx
Labels: enhancement, frontend

#2237 typo fix
  assets/src/components/security/compliance/ComplianceReports.tsx
  assets/src/components/security/compliance/CreateComplianceReportModal.tsx
Labels: bug-fix, frontend

#2239 include elk in bundle
  assets/src/components/utils/network-graph/NetworkGraphStatistics.tsx
  assets/src/components/utils/reactflow/layouting.tsx
Labels: bug-fix, frontend

#2238 Adds smarter caching for git and helm
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  AGENT_VERSION
  Dockerfile
  bin/setup/alpine.sh
  bin/setup/ubuntu.sh
  charts/console/templates/deployment.yaml
  charts/console/values.yaml
  lib/console/deployments/flows.ex
  lib/console/deployments/git/agent.ex
  lib/console/deployments/git/cache.ex
  lib/console/deployments/git/supervisor.ex
  lib/console/deployments/helm/agent.ex
  lib/console/deployments/helm/agent_cache.ex
  lib/console/deployments/helm/supervisor.ex
  lib/console/deployments/policy.ex
  priv/agent-chart.tgz
Labels: enhancement

#2241 fix: handle null chart versions in compatibility scrapers
  static/compatibilities/argo-rollouts.yaml
  static/compatibilities/contour.yaml
  static/compatibilities/external-dns.yaml
  utils/compatibility/scrapers/argo-rollouts.py
  utils/compatibility/scrapers/aws-ebs-csi-driver.py
  utils/compatibility/scrapers/aws-efs-csi-driver.py
  utils/compatibility/scrapers/aws-load-balancer-controller.py
  utils/compatibility/scrapers/calico.py
  utils/compatibility/scrapers/cert-manager.py
  utils/compatibility/scrapers/contour.py
  utils/compatibility/scrapers/coredns.py
  utils/compatibility/scrapers/external-dns.py
  utils/compatibility/scrapers/ingress-nginx.py
  utils/compatibility/scrapers/istio.py
  utils/compatibility/scrapers/jaeger.py
  utils/compatibility/scrapers/karpenter.py
  utils/compatibility/scrapers/kube-prometheus-stack.py
  utils/compatibility/scrapers/new-scraper.py
  utils/compatibility/scrapers/traefik.py
  utils/compatibility/utils.py
Labels: bug-fix

#2246 feat: Show last value in observers table
  assets/src/components/cd/observers/Observers.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cd/observers.graphql
Labels: enhancement

#2247 add serviceid to pod query
  assets/src/components/cd/cluster/pod/Pod.tsx
Labels: bug-fix, frontend

#2236 feat: `ComplianceReportGenerator` CRD
  charts/controller/crds/deployments.plural.sh_compliancereportgenerators.yaml
  go/client/client.go
  go/client/graph/policies.graphql
  go/controller/api/v1alpha1/compliancereportgenerator_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_compliancereportgenerators.yaml
  go/controller/config/rbac/role.yaml
  go/controller/config/samples/compliancereportgenerator.yaml
  go/controller/docs/api.md
  go/controller/internal/client/compliancereportgenerator.go
  go/controller/internal/client/console.go
  go/controller/internal/controller/compliancereportgenerator_controller.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  go/controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_compliancereportgenerators.yaml
Labels: enhancement

#2245 Fix preview environment template upserts
  .github/workflows/test.yaml
  lib/console/deployments/flows.ex
  lib/console/deployments/git/agent.ex
  lib/console/deployments/git/cmd.ex
  lib/console/deployments/helm/agent.ex
  lib/console/deployments/oauth.ex
  lib/console/graphql/deployments/oauth.ex
  lib/console/schema/git_repository.ex
  lib/console/schema/preview_environment_template.ex
  lib/console/schema/revision.ex
  lib/console/schema/service_dependency.ex
  test/console/deployments/flows_test.exs
  test/console/deployments/git/agent_test.exs
  test/console/graphql/queries/deployments/oauth_queries_test.exs
Labels: bug-fix

#2248 Fix oidc backwards compat
  lib/console/graphql/deployments/oauth.ex
  test/console/graphql/mutations/deployments/oauth_mutations_test.exs
Labels: bug-fix

#2251 Fix helm values extraction
  assets/src/components/ai/chatbot/Chatbot.tsx
  assets/src/components/flows/flow/previews/FlowPreviews.tsx
  lib/console/deployments/flows.ex
  lib/console/deployments/flows/preview.ex
  lib/console/deployments/pubsub/recurse.ex
  lib/console/graphql/resolvers/deployments/service.ex
  lib/console/schema/preview_environment_instance.ex
  test/console/deployments/flows_test.exs
  test/console/deployments/pubsub/recurse_test.exs
Labels: bug-fix

#2259 Compile compatibility matrices to a single file
  static/compatibilities.yaml
  utils/compatibility/main.py
Labels: enhancement, hotfix

#2260 fix: Add kubelet skew to clusters upgrade query
  assets/src/generated/graphql.ts
  assets/src/graph/cd/clustersUpgrades.graphql
Labels: bug-fix

#2262 Minor change to latest-version
  Makefile
  utils/versions/main.py
Labels: enhancement, hotfix

#2265 Don't need to fetch vpn resources anymore
  AGENT_VERSION
  lib/console/cached/kubernetes.ex
  lib/console/cached/supervisor.ex
  lib/console/services/vpn.ex
  priv/agent-chart.tgz
Labels: enhancement, hotfix

#2261 AI Chat Tool for Alerts
  lib/console/ai/chat/engine.ex
  lib/console/ai/tools/alerts.ex
  lib/console/schema/alert.ex
  priv/tools/alerts.json
  test/console/ai/chat_test.exs
Labels: enhancement

#2271 add service component uid
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/graphql/deployments/service.ex
  lib/console/schema/service_component.ex
  priv/repo/migrations/20250520134234_add_component_uid.exs
  schema/schema.graphql
Labels: enhancement

#2272 truncate vulnerability reports before migration
  priv/repo/migrations/20250520004950_add_vuln_report_uniq.exs
Labels: bug-fix

#2273 feat(graphql): add `uid` field to ServiceDeployment components
  go/client/client.go
  go/client/graph/models.graphql
Labels: enhancement

#2275 upload compatibility matricies to s3 bucket
  .github/workflows/compatability-matrices.yaml
Labels: enhancement

#2276 feat: Graphql: Add terraform configuration fields to stack schema
  go/client/client.go
  go/client/graph/stack.graphql
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
Labels: enhancement

#2278 feat(console): add components tree view to the service deployment
  assets/src/components/cd/services/ServicesTreeDiagramNodes.tsx
  assets/src/components/cd/services/service/ServiceComponents.tsx
  assets/src/components/cd/services/service/ServiceComponentsTree.tsx
  assets/src/components/utils/ButtonGroup.tsx
  assets/src/components/utils/FillLevelDiv.tsx
  assets/src/components/utils/reactflow/nodes.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cd/services.graphql
  assets/src/routes/kubernetesRoutesConsts.tsx
Labels: enhancement

#2279 feat: add raw yaml to the components tree view info modal
  AGENT_VERSION
  assets/src/components/cd/services/service/ServiceComponentsTree.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cd/services.graphql
  assets/src/routes/kubernetesRoutesConsts.tsx
  go/client/models_gen.go
  lib/console/ai/tools/alerts.ex
  lib/console/deployments/services.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments/service.ex
  lib/console/schema/alert.ex
  lib/console/schema/stack.ex
  priv/agent-chart.tgz
  rel/runtime.exs
  schema/schema.graphql
  test/console/deployments/services_test.exs
  test/console/graphql/queries/deployments/service_queries_test.exs
  test/support/factory.ex
Labels: enhancement

#2282 feat: Add search to stacks state graph
  assets/src/components/stacks/state/StackStateGraph.tsx
Labels: enhancement

#2280 Opensearch Schema/GoLang Changes
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  go/controller/api/v1alpha1/deploymentsettings_types.go
  lib/console/schema/deployment_settings.ex
  schema/schema.graphql
Labels: enhancement

#2283 Add support for rds cert chain
  Dockerfile
  assets/src/components/ai/chatbot/prompts.json
  assets/src/components/cd/services/service/ServiceComponentsTree.tsx
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/ai/chat/engine.ex
  lib/console/ai/mcp/agent.ex
  lib/console/ai/tools/alerts.ex
  lib/console/ai/tools/logs.ex
  lib/console/deployments/init.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/repo.ex
  lib/console/schema/cluster.ex
  lib/console/schema/cluster_insight_component.ex
  lib/console/services/users.ex
  lib/mix/tasks/db.certs.ex
  mix.lock
  priv/certs/aws.pem
  priv/certs/azure.pem
  priv/repo/migrations/20250522133259_add_cluster_scores.exs
  priv/repo/seeds/07_sre_group.exs
  rel/runtime.exs
  schema/schema.graphql
  test/console/deployments/init_test.exs
Labels: enhancement

#2288 add filtering to service component tree
  assets/src/components/cd/cluster/ClusterServices.tsx
  assets/src/components/cd/services/Services.tsx
  assets/src/components/cd/services/service/ServiceComponents.tsx
  assets/src/components/cd/services/service/ServiceComponentsTree.tsx
  assets/src/components/cd/services/service/component/ComponentList.tsx
  assets/src/components/cd/services/service/component/Components.tsx
  assets/src/components/utils/ButtonGroup.tsx
Labels: enhancement, frontend

#2287 Prepare v0.11.18
  .github/workflows/compatability-matrices.yaml
  config/config.exs
  lib/console.ex
  lib/console/deployments/compatibilities/cloud_addons.ex
  lib/console/deployments/compatibilities/table.ex
  lib/console/deployments/deprecations/table.ex
  lib/console/deployments/global.ex
  lib/console/deployments/init.ex
  rel/runtime.exs
  static/versions.yml
  test/console/deployments/init_test.exs
Labels: enhancement, hotfix

#2285 Alerts resolution tool implementation.
  lib/console/ai/chat/engine.ex
  lib/console/ai/tools/alerts_resolutions.ex
  priv/tools/alerts_resolutions.json
  test/console/ai/chat_test.exs
Labels: enhancement

#2286 feat: add ServiceContext CRD
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  charts/controller/crds/deployments.plural.sh_servicecontexts.yaml
  go/controller/PROJECT
  go/controller/api/v1alpha1/servicecontext_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  go/controller/config/crd/bases/deployments.plural.sh_servicecontexts.yaml
  go/controller/config/rbac/role.yaml
  go/controller/config/rbac/servicecontext_editor_role.yaml
  go/controller/config/rbac/servicecontext_viewer_role.yaml
  go/controller/config/samples/deployments_v1alpha1_servicecontext.yaml
  go/controller/go.mod
  go/controller/internal/client/console.go
  go/controller/internal/client/context.go
  go/controller/internal/controller/servicecontext_controller.go
  go/controller/internal/controller/servicecontext_controller_test.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  go/controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
  plural/helm/console/crds/deployments.plural.sh_servicecontexts.yaml
Labels: enhancement

#2295 chore: scaffold datastore controller manager
  .github/workflows/datastore-cd.yaml
  charts/datastore/.helmignore
  charts/datastore/Chart.yaml
  charts/datastore/crds/dbs.plural.sh_elasticsearchcredentials.yaml
  charts/datastore/templates/_helpers.tpl
  charts/datastore/templates/deployment.yaml
  charts/datastore/templates/leader-election-rbac.yaml
  charts/datastore/templates/manager-rbac.yaml
  charts/datastore/templates/secret.yaml
  charts/datastore/templates/serviceaccount.yaml
  charts/datastore/values.yaml
  go/datastore/.gitignore
  go/datastore/.golangci.yml
  go/datastore/.goreleaser.yml
  go/datastore/.mockery.yaml
  go/datastore/Dockerfile
  go/datastore/Makefile
  go/datastore/PROJECT
  go/datastore/README.md
  go/datastore/api/v1alpha1/common_types.go
  go/datastore/api/v1alpha1/elasticsearchcredentials_types.go
  go/datastore/api/v1alpha1/groupversion_info.go
  go/datastore/api/v1alpha1/zz_generated.deepcopy.go
  go/datastore/cmd/main.go
  go/datastore/config.yaml
  go/datastore/config/crd/bases/dbs.plural.sh_elasticsearchcredentials.yaml
  go/datastore/config/crd/kustomization.yaml
  go/datastore/config/crd/kustomizeconfig.yaml
  go/datastore/config/rbac/elasticsearchcredentials_editor_role.yaml
  go/datastore/config/rbac/elasticsearchcredentials_viewer_role.yaml
  go/datastore/config/rbac/role.yaml
  go/datastore/config/samples/dbs_v1alpha1_elasticsearchcredentials.yaml
  go/datastore/config/samples/kustomization.yaml
  go/datastore/go.mod
  go/datastore/go.sum
  go/datastore/internal/client/console.go
  go/datastore/internal/controller/elasticsearchcredentials_controller.go
  go/datastore/internal/controller/suite_test.go
  go/datastore/internal/test/mocks/ConsoleClient_mock.go
  go/datastore/internal/types/controller.go
  go/datastore/internal/types/reconciler.go
  go/go.work
  go/paths.mk
  plural/helm/console/Chart.lock
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/controller-0.0.123.tgz
  plural/helm/console/charts/datastore-0.0.1.tgz
  plural/helm/console/crds/dbs.plural.sh_elasticsearchcredentials.yaml
Labels: enhancement

#2298 fix logs polling bug
  assets/package.json
  assets/src/components/cd/logs/Logs.tsx
  assets/src/components/kubernetes/common/Raw.tsx
  assets/src/components/kubernetes/common/create/secret/SecretModal.tsx
  assets/src/components/kubernetes/customresources/PinnedCustomResourceDefinitions.tsx
  assets/src/components/kubernetes/workloads/CronJob.tsx
  assets/src/components/utils/Confirm.tsx
  assets/yarn.lock
Labels: bug-fix, frontend

#2304 feat: Show AI insights on nested component children
  assets/src/components/cd/services/service/ServiceComponentsTree.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cd/services.graphql
Labels: enhancement

#2302 Add graphql schema for service context proj
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_servicecontexts.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/servicecontext_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_servicecontexts.yaml
  go/controller/internal/controller/servicecontext_controller.go
  lib/console.ex
  lib/console/deployments/init.ex
  lib/console/deployments/observability.ex
  lib/console/deployments/observability/metrics.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/observability.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments/observability.ex
  plural/helm/console/crds/deployments.plural.sh_servicecontexts.yaml
  rel/runtime.exs
  schema/schema.graphql
  test/console/deployments/init_test.exs
Labels: enhancement

#2306 add git connection to cloud setup flow
  assets/src/components/cd/utils/SshKeyUpload.tsx
  assets/src/components/cloud-setup/CloudConsoleWelcomeModal.tsx
  assets/src/components/cloud-setup/GitHubSetup.tsx
  assets/src/components/cloud-setup/steps/AuthenticateStep.tsx
  assets/src/components/cloud-setup/steps/LearnStep.tsx
  assets/src/components/cloud-setup/steps/scm-setup/GitHubAppSetup.tsx
  assets/src/components/cloud-setup/steps/scm-setup/GitHubSetupStep.tsx
  assets/src/components/cloud-setup/steps/scm-setup/ManualGitSetup.tsx
  assets/src/components/contexts.tsx
  assets/src/components/home/Home.tsx
  assets/src/components/layout/CloudConsoleWelcomeModal.tsx
  assets/src/components/layout/Console.tsx
  assets/src/components/pr/scm/CreateScmConnection.tsx
  assets/src/components/pr/scm/EditScmConnection.tsx
  assets/src/components/pr/scm/GitProviderSelect.tsx
  assets/src/components/utils/GenerateAccessToken.tsx
  assets/src/components/utils/typography/BasicTextButton.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/automation.graphql
  assets/src/routes/consoleRoutes.tsx
Labels: enhancement, frontend
