Repository pluralsh/console, pull requests merged in 2025-09, with the labels that each got.

#2638 assorted fixes/updates
  assets/src/components/ai/chatbot/ChatMessageContent.tsx
  assets/src/components/cd/cluster/Cluster.tsx
  assets/src/components/cd/cluster/ClusterServices.tsx
  assets/src/components/cd/services/Services.tsx
  assets/src/components/cd/services/ServicesFilters.tsx
  assets/src/components/cd/services/ServicesTable.tsx
  assets/src/components/cd/services/ServicesTree.tsx
  assets/src/components/profile/EmailSettings.tsx
  assets/src/components/profile/Groups.tsx
  assets/src/components/profile/MyProfile.tsx
  assets/src/components/profile/Permissions.tsx
  assets/src/components/profile/Profile.tsx
  assets/src/components/profile/SecurityAccess.tsx
  assets/src/components/profile/SecurityPassword.tsx
  assets/src/components/self-service/pr/automations/PrAutomations.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/automation.graphql
  assets/src/graph/users.graphql
  assets/src/routes/consoleRoutes.tsx
Labels: enhancement, frontend

#2646 add azure devops to scm configuration form
  Dockerfile
  assets/package.json
  assets/src/components/ai/AIAgent.tsx
  assets/src/components/cloud-setup/steps/scm-setup/ManualGitSetup.tsx
  assets/src/components/hooks/useUpdateState.tsx
  assets/src/components/self-service/pr/scm/CreateScmConnection.tsx
  assets/src/components/self-service/pr/scm/EditScmConnection.tsx
  assets/src/components/self-service/pr/scm/GitProviderSelect.tsx
  assets/src/components/self-service/pr/scm/PrScmConnectionsColumns.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/ai/chat.graphql
  assets/src/graph/automation.graphql
  assets/yarn.lock
Labels: enhancement, frontend

#2655 add sentry error reporting to UI
  .github/workflows/publish.yaml
  Dockerfile
  assets/.gitignore
  assets/package.json
  assets/src/App.tsx
  assets/src/components/SentryInitializer.tsx
  assets/src/components/cd/PluralErrorBoundary.tsx
  assets/src/components/layout/Console.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/users.graphql
  assets/src/index.tsx
  assets/src/instrument.ts
  assets/src/routes/rootRoutes.tsx
  assets/vite.config.ts
  assets/yarn.lock
Labels: enhancement, frontend

#2647 Add email inference if opted in via env var
  assets/src/generated/graphql.ts
  charts/console-rapid/charts/controller-0.0.146.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
  charts/console/charts/controller-0.0.146.tgz
  charts/console/charts/kas-0.3.0.tgz
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  charts/controller/crds/deployments.plural.sh_previewenvironmenttemplates.yaml
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  config/prod.exs
  config/test.exs
  go/client/models_gen.go
  go/controller/api/v1alpha1/servicedeployment_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  go/controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  go/controller/config/crd/bases/deployments.plural.sh_previewenvironmenttemplates.yaml
  go/controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  go/controller/docs/api.md
  lib/console/ai/provider.ex
  lib/console/application.ex
  lib/console/bootstrapper.ex
  lib/console/deployments/clusters.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/git.ex
  lib/console/deployments/git/discovery.ex
  lib/console/deployments/observer/discovery.ex
  lib/console/deployments/observer/supervisor.ex
  lib/console/deployments/observer/worker.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments/git.ex
  lib/console/pipelines/observer/pipeline.ex
  lib/console/pipelines/observer/producer.ex
  lib/console/schema/observer.ex
  lib/console/schema/service.ex
  lib/console/services/users.ex
  plural/helm/console/Chart.lock
  plural/helm/console/charts/controller-0.0.145.tgz
  plural/helm/console/charts/controller-0.0.146.tgz
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
  plural/helm/console/crds/deployments.plural.sh_previewenvironmenttemplates.yaml
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
  rel/runtime.exs
  schema/schema.graphql
  test/console/deployments/git_test.exs
  test/console/graphql/mutations/deployments/git_mutations_test.exs
  test/console/services/users_test.exs
  utils/extended/main.py
Labels: enhancement

#2660 Allow ai analysis rates to be tuned
  assets/src/generated/graphql.ts
  charts/console-rapid/charts/controller-0.0.146.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
  charts/console/charts/controller-0.0.146.tgz
  charts/console/charts/kas-0.3.0.tgz
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  go/controller/docs/api.md
  lib/console/graphql/deployments/settings.ex
  lib/console/schema/ai_insight.ex
  lib/console/schema/deployment_settings.ex
  plural/helm/console/charts/controller-0.0.146.tgz
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
  schema/schema.graphql
Labels: enhancement

#2681 Add openai proxy endpoints
  assets/src/components/settings/global/GlobalSettingsAIProviders.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cd/globalSettings.graphql
  charts/console-rapid/charts/controller-0.0.147.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
  charts/console/charts/controller-0.0.147.tgz
  charts/console/charts/kas-0.3.0.tgz
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  go/client/go.mod
  go/client/models_gen.go
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  go/controller/docs/api.md
  go/tools/go.mod
  lib/console/ai/provider.ex
  lib/console/ai/provider/anthropic.ex
  lib/console/ai/provider/azure.ex
  lib/console/ai/provider/bedrock.ex
  lib/console/ai/provider/ollama.ex
  lib/console/ai/provider/openai.ex
  lib/console/ai/provider/vertex.ex
  lib/console/ai/proxy.ex
  lib/console/deployments/agents.ex
  lib/console/graphql/deployments/agent.ex
  lib/console/graphql/deployments/settings.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/schema/agent_prompt_history.ex
  lib/console/schema/agent_run.ex
  lib/console/schema/agent_runtime.ex
  lib/console/schema/deployment_settings.ex
  lib/console_web/controllers/ai_controler.ex
  lib/console_web/controllers/ingest_controller.ex
  lib/console_web/router.ex
  plural/helm/console/Chart.lock
  plural/helm/console/charts/controller-0.0.146.tgz
  plural/helm/console/charts/controller-0.0.147.tgz
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
  priv/repo/migrations/20250914172047_add_agent_runtime_proxy_settings.exs
  schema/schema.graphql
  test/console/ai/cron_test.exs
  test/console/deployments/agents_test.exs
Labels: enhancement

#2682 Add more agent runtime types
  assets/src/generated/graphql.ts
  config/prod.exs
  go/client/models_gen.go
  lib/console/ai/cron.ex
  lib/console/deployments/agents.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/deployments/agent.ex
  lib/console/graphql/resolvers/deployments/agent.ex
  lib/console/schema/agent_run.ex
  lib/console/schema/agent_runtime.ex
  priv/repo/migrations/20250915194425_add_agent_session_run_assoc.exs
  schema/schema.graphql
  test/console/deployments/agents_test.exs
Labels: enhancement

#2691 add return-to path support on login
  assets/src/components/login/Login.tsx
  assets/src/components/login/OauthCallback.tsx
  assets/src/helpers/refreshToken.ts
Labels: enhancement, frontend

#2695 feat: Change health score and cluster upgrades color when agent is unhealthy
  assets/src/components/cd/clusters/ClusterHealthChip.tsx
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/cd/clusters/ClustersColumns.tsx
Labels: enhancement

#2704 remove ai pin logic from the ui
  assets/src/components/ai/AI.tsx
  assets/src/components/ai/AIAgent.tsx
  assets/src/components/ai/AIPinButton.tsx
  assets/src/components/ai/AITable.tsx
  assets/src/components/ai/AITableActions.tsx
  assets/src/components/ai/AITableEntry.tsx
  assets/src/components/ai/AIThreads.tsx
  assets/src/components/ai/McpServers.tsx
  assets/src/components/ai/chatbot/ChatbotThreadMoreMenu.tsx
  assets/src/components/cd/cluster/ClusterInsightComponent.tsx
  assets/src/components/cd/cluster/ClusterInsights.tsx
  assets/src/components/cd/globalServices/GlobalServicesTable.tsx
  assets/src/components/cd/pipelines/Pipelines.tsx
  assets/src/components/cd/services/service/ServiceInsights.tsx
  assets/src/components/commandpalette/CommandPalette.tsx
  assets/src/components/component/ComponentInsights.tsx
  assets/src/components/kubernetes/cluster/Node.tsx
  assets/src/components/stacks/insights/StackInsights.tsx
  assets/src/components/stacks/run/insights/StackRunInsights.tsx
  assets/src/components/utils/Alert.tsx
  assets/src/components/utils/alerts/AlertInsight.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/ai/chat.graphql
Labels: enhancement, frontend

#2712 make expanded sidebar persist
  assets/package.json
  assets/src/components/ai/AIContext.tsx
  assets/src/components/help/HelpLauncherBtn.tsx
  assets/src/components/layout/Console.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/utils/sidebar/SidebarItem.tsx
  assets/src/components/utils/sidebar/SidebarSection.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#2710 More flexible groups inference
  AGENT_VERSION
  lib/console/services/users.ex
  priv/agent-chart.tgz
Labels: bug-fix, hotfix
