Repository pluralsh/console, pull requests merged in 2025-10, with the labels that each got.

#2719 create sentinel CRD
  charts/console-rapid/charts/controller-0.0.149.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
  charts/console/charts/controller-0.0.149.tgz
  charts/console/charts/kas-0.3.0.tgz
  charts/controller/crds/deployments.plural.sh_sentinels.yaml
  go/client/client.go
  go/client/graph/sentinel.graphql
  go/controller/PROJECT
  go/controller/api/v1alpha1/sentinel_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/cmd/register.go
  go/controller/config/crd/bases/deployments.plural.sh_sentinels.yaml
  go/controller/config/rbac/role.yaml
  go/controller/config/rbac/sentinel_editor_role.yaml
  go/controller/config/rbac/sentinel_viewer_role.yaml
  go/controller/config/samples/deployments_v1alpha1_sentinel.yaml
  go/controller/docs/api.md
  go/controller/internal/client/console.go
  go/controller/internal/client/sentinel.go
  go/controller/internal/controller/sentinel_controller.go
  go/controller/internal/controller/sentinel_controller_test.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  go/controller/internal/types/reconciler.go
  go/controller/internal/utils/kubernetes.go
  plural/helm/console/Chart.lock
  plural/helm/console/charts/controller-0.0.148.tgz
  plural/helm/console/charts/controller-0.0.149.tgz
  plural/helm/console/crds/deployments.plural.sh_sentinels.yaml
Labels: enhancement

#2707 feat: Jitter waiting for resources in console operator
  go/controller/internal/controller/bootstraptoken_controller.go
  go/controller/internal/controller/catalog_controller.go
  go/controller/internal/controller/cloudconnection_controller.go
  go/controller/internal/controller/cluster_controller.go
  go/controller/internal/controller/clusterrestore_controller.go
  go/controller/internal/controller/clustersync_controller.go
  go/controller/internal/controller/common.go
  go/controller/internal/controller/customstackrun_controller.go
  go/controller/internal/controller/federatedcredential_controller.go
  go/controller/internal/controller/flow_controller.go
  go/controller/internal/controller/gitrepository_controller.go
  go/controller/internal/controller/globalservice_controller.go
  go/controller/internal/controller/infrastructurestack_controller.go
  go/controller/internal/controller/managednamespace_controller.go
  go/controller/internal/controller/namespace_credentials_controller.go
  go/controller/internal/controller/notificationrouter_controller.go
  go/controller/internal/controller/notificationsink_controller.go
  go/controller/internal/controller/observabilityprovider_controller.go
  go/controller/internal/controller/observer_controller.go
  go/controller/internal/controller/persona_controller.go
  go/controller/internal/controller/pipeline_controller.go
  go/controller/internal/controller/pipeline_controller_attributes.go
  go/controller/internal/controller/pipelinecontext_controller.go
  go/controller/internal/controller/prautomation_attributes.go
  go/controller/internal/controller/prautomation_controller.go
  go/controller/internal/controller/prautomationtrigger_controller.go
  go/controller/internal/controller/previewenvironmenttemplate_controller.go
  go/controller/internal/controller/prgovernance_controller.go
  go/controller/internal/controller/project_controller.go
  go/controller/internal/controller/provider_controller.go
  go/controller/internal/controller/scmconnection_controller.go
  go/controller/internal/controller/sentinel_controller.go
  go/controller/internal/controller/service_account_controller.go
  go/controller/internal/controller/servicecontext_controller.go
  go/controller/internal/controller/servicedeployment_controller.go
  go/controller/internal/controller/stackdefinition_controller.go
  go/datastore/internal/controller/common.go
  go/datastore/internal/controller/elasticsearchilmpolicy_controller.go
  go/datastore/internal/controller/elasticsearchindextemplate_controller.go
  go/datastore/internal/controller/elasticsearchuser_controller.go
  go/datastore/internal/controller/mysqlcredentials_controller.go
  go/datastore/internal/controller/mysqldatabase_controller.go
  go/datastore/internal/controller/mysqluser_controller.go
  go/datastore/internal/controller/postgrescredentials_controller.go
  go/datastore/internal/controller/postgresdatabase_controller.go
  go/datastore/internal/controller/postgresuser_controller.go
Labels: enhancement

#2731 fix: set Content-Length in the new PersistedQueryInterceptor
  go/client/utils.go
Labels: bug-fix

#2723 Pull Request merge cron logic
  lib/console/ai/provider.ex
  lib/console/ai/provider/openai.ex
  lib/console/ai/stream/exec.ex
  lib/console/cost/pr.ex
  lib/console/deployments/git.ex
  lib/console/deployments/pr/dispatcher.ex
  lib/console/deployments/pr/impl/azure.ex
  lib/console/deployments/pr/impl/bitbucket.ex
  lib/console/deployments/pr/impl/github.ex
  lib/console/deployments/pr/impl/gitlab.ex
  lib/console/deployments/pr/impl/pass.ex
  lib/console/deployments/pr/utils.ex
  lib/console/graphql/resolvers/deployments/service.ex
  lib/console/pipelines/pull_request/pipeline.ex
  lib/console/pipelines/pull_request/producer.ex
  lib/console/pipelines/supervisor.ex
  lib/console/schema/pull_request.ex
  lib/console/services/users/access_tokens.ex
  lib/console_web/controllers/ai_controler.ex
  lib/console_web/controllers/ingest_controller.ex
  priv/prompts/agent.md
  priv/prompts/agent_chat.md
  priv/prompts/agent_manifests.md
  priv/prompts/agent_pre.md
  priv/prompts/agent_search.md
  priv/prompts/chat.md
  priv/prompts/kubernetes_agent.md
  priv/prompts/kubernetes_pr.md
  priv/prompts/provisioning.md
  priv/prompts/terraform_agent.md
  priv/prompts/terraform_commit.md
  priv/prompts/terraform_pr.md
  priv/repo/migrations/20251001190849_add_pr_merge_cron.exs
  test/console/deployments/git_test.exs
  test/console/graphql/mutations/deployments/services_mutations_test.exs
  test/console_web/controllers/webhook_controller_test.exs
  utils/ai/go.mod
  utils/ai/go.sum
  utils/ai/tester.go
Labels: enhancement

#2732 Work around insight component goofiness
  go/client/utils.go
  lib/console/ai/memoizer.ex
  lib/console/deployments/clusters.ex
  lib/console/graphql/persisted_query.ex
  lib/console/prom/plugin.ex
Labels: bug-fix, hotfix

#2733 add apollo persisted queries to client
  assets/package.json
  assets/src/generated/persisted-queries/goclient.json
  assets/src/helpers/client.ts
  assets/yarn.lock
Labels: enhancement, frontend

#2730 fix: Fix OCI Auth sidecar CVE
  charts/console/templates/deployment.yaml
  charts/console/values.yaml
  go/oci-auth/go.mod
  go/oci-auth/go.sum
Labels: dependencies

#2745 feat(client): add CreateAgentPullRequest mutation and client method
  go/client/client.go
  go/client/generated/persisted-queries/queries.json
  go/client/graph/agentruntime.graphql
Labels: enhancement

#2746 chore: trim down lockfile
  .github/workflows/assets.yaml
  assets/e2e/.dockerignore
  assets/e2e/.eslintrc.yaml
  assets/e2e/.gitignore
  assets/e2e/.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  assets/e2e/.yarn/releases/yarn-3.6.0.cjs
  assets/e2e/.yarnrc.yml
  assets/e2e/Makefile
  assets/e2e/cypress.Dockerfile
  assets/e2e/cypress.config.ts
  assets/e2e/cypress/config/config.ts
  assets/e2e/cypress/e2e/stories/login.cy.ts
  assets/e2e/cypress/intercept/factory.ts
  assets/e2e/cypress/intercept/graphql.ts
  assets/e2e/cypress/pages/base.ts
  assets/e2e/cypress/pages/login.ts
  assets/e2e/cypress/pages/root.ts
  assets/e2e/cypress/support/index.ts
  assets/e2e/cypress/types/condition.ts
  assets/e2e/cypress/types/dispatch.ts
  assets/e2e/cypress/types/graphql.ts
  assets/e2e/cypress/types/mutations.ts
  assets/e2e/cypress/types/queries.ts
  assets/e2e/cypress/types/time.ts
  assets/e2e/package.json
  assets/e2e/tsconfig.json
  assets/e2e/webpack.config.ts
  assets/e2e/yarn.lock
  assets/package.json
  assets/src/components/layout/ApplicationUpdateToast.tsx
  assets/src/index.tsx
  assets/src/service-worker.ts
  assets/src/serviceWorkerRegistration.ts
  assets/src/setupTests.ts
  assets/vite.config.ts
  assets/vitest.config.ts
  assets/yarn.lock
Labels: enhancement, frontend

#2744 fix k8s dashboard filter logic
  assets/README.md
  assets/src/components/kubernetes/Cluster.tsx
  assets/src/components/kubernetes/Navigation.tsx
  assets/src/components/kubernetes/audit/Audit.tsx
  assets/src/components/kubernetes/common/DataSelect.tsx
  assets/src/components/kubernetes/customresources/CustomResourceDefinition.tsx
  assets/src/components/kubernetes/customresources/PinnedCustomResourceDefinitions.tsx
  assets/waitOnConfig.json
Labels: enhancement, frontend
