Repository pluralsh/console, pull requests merged in 2025-07, with the labels that each got.

#2424 Fix chart templating
  charts/console-rapid/Chart.yaml
  charts/console/templates/cloud-query/deployment.yaml
  charts/console/templates/cloud-query/service.yaml
Labels: enhancement, hotfix

#2426 First stab at pr automation tools for agent provisioning
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_infrastructurestacks.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/infrastructurestack_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_infrastructurestacks.yaml
  go/controller/docs/api.md
  go/controller/internal/controller/infrastructurestack_controller.go
  lib/console/ai/chat/engine.ex
  lib/console/ai/tools/agent/base.ex
  lib/console/ai/tools/agent/call_pr.ex
  lib/console/ai/tools/agent/catalogs.ex
  lib/console/ai/tools/agent/pr_automations.ex
  lib/console/deployments/git/agent.ex
  lib/console/deployments/stacks.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/schema/chat.ex
  lib/console/schema/stack.ex
  lib/console/schema/stack_cron.ex
  plural/helm/console/crds/deployments.plural.sh_infrastructurestacks.yaml
  priv/repo/migrations/20250703212353_add_chat_pr_automation.exs
  priv/repo/migrations/20250704153126_add_stack_cron_overrides.exs
  priv/tools/agent/call_pr.json
  priv/tools/agent/catalogs.json
  priv/tools/agent/pr_automations.json
  schema/schema.graphql
  test/console/ai/tools/agent/call_pr_test.exs
  test/console/ai/tools/agent/catalogs_test.exs
  test/console/ai/tools/agent/pr_automations_test.exs
  test/console/deployments/stacks_test.exs
Labels: enhancement

#2436 fix: name override in controllers
  go/controller/api/v1alpha1/oidcprovider_types.go
  go/controller/api/v1alpha1/previewenvironmenttemplate_types.go
  go/controller/api/v1alpha1/servicecontext_types.go
  go/controller/internal/controller/previewenvironmenttemplate_controller.go
  go/controller/internal/controller/servicecontext_controller.go
Labels: bug-fix

#2442 Bump agent + pkce unauthenticated
  AGENT_VERSION
  priv/agent-chart.tgz
  rel/runtime.exs
Labels: enhancement

#2420 new cost management view
  assets/package.json
  assets/src/components/ai/insights/InsightEvidence.tsx
  assets/src/components/ai/insights/KnowledgeEvidencePanel.tsx
  assets/src/components/cd/services/ClusterTagsFilter.tsx
  assets/src/components/cost-management/ClusterUsagesTableCols.tsx
  assets/src/components/cost-management/CostManagement.tsx
  assets/src/components/cost-management/CostManagementChartView.tsx
  assets/src/components/cost-management/CostManagementTableView.tsx
  assets/src/components/cost-management/ProjectCostUsageSeries.tsx
  assets/src/components/cost-management/details/CostManagementDetailsNamespaces.tsx
  assets/src/components/cost-management/details/CostManagementDetailsOverview.tsx
  assets/src/components/cost-management/details/CostTimeSeriesGraph.tsx
  assets/src/components/cost-management/details/recommendations/CreateRecommendationPrSteps.tsx
  assets/src/components/flows/flow/previews/PreviewTemplatesTable.tsx
  assets/src/components/stacks/Stacks.tsx
  assets/src/components/utils/Graph.tsx
  assets/src/components/utils/ProjectSelector.tsx
  assets/src/components/utils/TreeMap.tsx
  assets/src/components/utils/UtilizationHeatmap.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/costManagement.graphql
  assets/src/routes/costManagementRoutes.tsx
  assets/src/routes/costManagementRoutesConsts.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#2423 feat: enable gRPC extract streaming for aws provider
  go/cloud-query/Makefile
  go/cloud-query/cmd/main.go
  go/cloud-query/go.mod
  go/cloud-query/go.sum
  go/cloud-query/internal/common/database.go
  go/cloud-query/internal/connection/connection.go
  go/cloud-query/internal/connection/query.go
  go/cloud-query/internal/connection/schema.go
  go/cloud-query/internal/extractor/aws/extractor.go
  go/cloud-query/internal/extractor/aws/resource_ec2_instance.go
  go/cloud-query/internal/extractor/aws/resource_eks_addon.go
  go/cloud-query/internal/extractor/aws/resource_eks_cluster.go
  go/cloud-query/internal/extractor/aws/resource_eks_node_group.go
  go/cloud-query/internal/extractor/aws/resource_s3_bucket.go
  go/cloud-query/internal/extractor/aws/resource_vpc.go
  go/cloud-query/internal/extractor/aws/resource_vpc_peering_connection.go
  go/cloud-query/internal/extractor/aws/resource_vpc_subnet.go
  go/cloud-query/internal/extractor/extractor.go
  go/cloud-query/internal/extractor/extractor_default.go
  go/cloud-query/internal/extractor/resource_mocks.go
  go/cloud-query/internal/extractor/sink_dump.go
  go/cloud-query/internal/server/cloudquery.go
  go/cloud-query/internal/server/route.go
  go/cloud-query/internal/server/server.go
  go/cloud-query/internal/service/cloudquery.go
  go/cloud-query/internal/service/cloudquery_extract.go
  go/cloud-query/internal/service/cloudquery_query.go
  go/cloud-query/internal/service/cloudquery_schema.go
  go/cloud-query/internal/service/service.go
Labels: enhancement

#2449 migrate ai chats to new apis
  assets/package.json
  assets/src/components/ai/chatbot/Chatbot.tsx
  assets/src/components/ai/chatbot/ChatbotHeader.tsx
  assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
  assets/src/components/ai/chatbot/ChatbotSendMessageForm.tsx
  assets/src/components/ai/explain/ExplainWithAIButton.tsx
  assets/src/components/commandpalette/commands.ts
  assets/src/components/flows/FeatureFlagContext.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/ai/chat.graphql
  assets/yarn.lock
Labels: enhancement, frontend

#2458 chore: add diff normalizer spec to ServiceDeployment
  charts/console-rapid/charts/controller-0.0.133.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
  charts/console/charts/controller-0.0.133.tgz
  charts/console/charts/kas-0.3.0.tgz
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  charts/controller/crds/deployments.plural.sh_previewenvironmenttemplates.yaml
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  go/client/client.go
  go/client/graph/deployment.graphql
  go/controller/api/v1alpha1/servicedeployment_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  go/controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  go/controller/config/crd/bases/deployments.plural.sh_previewenvironmenttemplates.yaml
  go/controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  go/controller/docs/api.md
  go/controller/internal/controller/servicedeployment_controller_test.go
  plural/helm/console/charts/controller-0.0.133.tgz
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
  plural/helm/console/crds/deployments.plural.sh_previewenvironmenttemplates.yaml
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
Labels: enhancement

#2459 Azure schema fixes
  assets/src/components/settings/global/GlobalSettingsAIProviders.tsx
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/ai/agents/terraform.ex
  lib/console/ai/chat/system.ex
  lib/console/ai/chat/tools.ex
  lib/console/ai/provider/azure.ex
  lib/console/ai/provider/openai.ex
  lib/console/ai/tools/agent/coding/stack_files.ex
  lib/console/graphql/deployments/settings.ex
  lib/console/schema/deployment_settings.ex
  priv/prompts/terraform_commit.md
  priv/prompts/terraform_pr.md
  schema/schema.graphql
  test/console/ai/tools/agent/coding/stack_files_test.exs
Labels: bug-fix

#2466 add forecasting to cost management
  assets/src/components/cost-management/CostManagementChartView.tsx
  assets/src/components/cost-management/ProjectCostUsageSeries.tsx
  assets/src/components/cost-management/details/CostTimeSeriesGraph.tsx
  assets/src/components/utils/NivoLineForecastingLayer.tsx
  assets/src/utils/datetime.ts
Labels: enhancement, frontend

#2471 chore: add SyncConfig
  go/client/client.go
  go/client/graph/models.graphql
Labels: enhancement

#2468 feat(personas): add AI persona fields and integrate with PR creation logic
  assets/src/components/ai/chatbot/AISuggestFix.tsx
  assets/src/components/utils/persona.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/personas.graphql
Labels: enhancement

#2481 extend DiffNormalizerFragment with backfill flag
  go/client/client.go
  go/client/graph/deployment.graphql
Labels: enhancement

#2482 remove tabs on homepage charts
  assets/src/components/ai/chatbot/ChatMessageContent.tsx
  assets/src/components/ai/chatbot/ChatbotHeader.tsx
  assets/src/components/home/Home.tsx
  assets/src/components/home/HomeFilterOptionCard.tsx
  assets/src/components/home/clusteroverview/ClusterHealthScoresHeatmap.tsx
  assets/src/components/home/clusteroverview/ClusterHealthScoresHeatmapEmpty.tsx
  assets/src/components/home/clusteroverview/ClusterUpgradesChart.tsx
  assets/src/components/stacks/Stacks.tsx
  assets/src/components/utils/AiInsights.tsx
  assets/src/components/utils/TreeMap.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/home.graphql
  lib/console/ai/provider.ex
Labels: enhancement, frontend

#2477 Bring back cloudquery behavior again
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  assets/public/cluster-distros/openshift-dark.svg
  assets/public/cluster-distros/openshift-light.svg
  assets/src/components/utils/ClusterDistro.tsx
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/ai/chat/tools.ex
  lib/console/ai/pubsub/agent/consumer.ex
  lib/console/ai/pubsub/consumer.ex
  lib/console/ai/tools/agent/query.ex
  lib/console/ai/tools/agent/schema.ex
  lib/console/ai/tools/agent/search.ex
  lib/console/application.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/pubsub/consumers/broadcast.ex
  lib/console/deployments/pubsub/consumers/email.ex
  lib/console/deployments/pubsub/consumers/governance.ex
  lib/console/deployments/pubsub/consumers/notifications.ex
  lib/console/deployments/pubsub/consumers/pipeline.ex
  lib/console/deployments/pubsub/consumers/preview.ex
  lib/console/deployments/stacks.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/deployments/settings.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/plural/config.ex
  lib/console/pubsub/consumers/audit.ex
  lib/console/pubsub/consumers/recurse.ex
  lib/console/pubsub/consumers/rtc.ex
  lib/console/schema/chat_thread.ex
  lib/console/schema/cluster.ex
  priv/prompts/agent_search.md
  priv/tools/agent/schema.json
  schema/schema.graphql
Labels: enhancement

#2486 add type-to-confirm for dashboard namespace deletion
  assets/src/components/kubernetes/common/DeleteResource.tsx
Labels: enhancement, frontend

#2493 Fix dataloader fetch for agent session connection
  lib/console/graphql/resolvers/deployments.ex
  test/console/graphql/queries/ai_queries_test.exs
Labels: enhancement

#2494 Fix bytes ingest collection
  .github/workflows/chart.yaml
  lib/console_web/controllers/ingest_controller.ex
  test/console/graphql/queries/ai_queries_test.exs
Labels: bug-fix, hotfix

#2495 Fix chart gh action
  .github/workflows/chart.yaml
Labels: bug-fix, hotfix

#2499 Remove usage of metrics aggregate and replace with db-local cluster data
  AGENT_VERSION
  assets/src/components/cd/clusters/ClustersColumns.tsx
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/cd/clusters.graphql
  charts/console-rapid/charts/controller-0.0.136.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
  charts/console/charts/controller-0.0.136.tgz
  charts/console/charts/kas-0.3.0.tgz
  go/controller/internal/controller/notificationrouter_controller.go
  lib/console/compliance/datasource/clusters.ex
  lib/console/deployments/cron.ex
  plural/helm/console/Chart.lock
  plural/helm/console/charts/controller-0.0.135.tgz
  plural/helm/console/charts/controller-0.0.136.tgz
  priv/agent-chart.tgz
  priv/repo/migrations/20250728030004_fix_cascades_notification_routers.exs
  test/console/deployments/cron_test.exs
Labels: enhancement

#2501 Add reverse sort support for ai chat threads
  assets/src/components/cd/clusters/ClustersColumns.tsx
  assets/src/generated/graphql.ts
  charts/console-rapid/charts/controller-0.0.136.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
  charts/console/charts/controller-0.0.136.tgz
  charts/console/charts/kas-0.3.0.tgz
  charts/controller/crds/deployments.plural.sh_cloudconnections.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/cloudconnection_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_cloudconnections.yaml
  go/controller/docs/api.md
  go/controller/internal/controller/cloudconnection_controller_attributes.go
  go/controller/internal/controller/cloudconnection_controller_test.go
  lib/console/deployments/pr/dispatcher.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/deployments/flow.ex
  lib/console/graphql/deployments/settings.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/graphql/resolvers/deployments/flow.ex
  lib/console/schema/cloud_connection.ex
  lib/console/schema/vulnerability_report.ex
  plural/helm/console/charts/controller-0.0.136.tgz
  plural/helm/console/crds/deployments.plural.sh_cloudconnections.yaml
  schema/schema.graphql
  test/console/graphql/queries/deployments/flow_queries_test.exs
  test/support/factory.ex
Labels: enhancement

#2511 Add agent fetch of lua folder
  go/client/client.go
  go/client/graph/deployment.graphql
  lib/console/deployments/pubsub/recurse.ex
Labels: enhancement, hotfix

#2512 Add availability zones to cluster list
  AGENT_VERSION
  assets/package.json
  assets/src/components/cd/clusters/ClustersColumns.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cd/clusters.graphql
  assets/yarn.lock
  lib/console/compliance/datasource/clusters.ex
  lib/console/deployments/clusters.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/global.ex
  lib/console/deployments/services.ex
  lib/console/schema/agent_migration.ex
  lib/console/schema/service_dependency.ex
  lib/console/schema/service_template.ex
  lib/console_web/controllers/git_controller.ex
  priv/agent-chart.tgz
  rel/runtime.exs
  test/console/deployments/global_test.exs
  test/console/deployments/services_test.exs
Labels: enhancement
