Repository pluralsh/console, pull requests merged in 2025-03, with the labels that each got.

#1945 fix: update tooling pipeline and vendor most critical tool binaries
  .github/workflows/ai-proxy-cd.yaml
  .github/workflows/ai-proxy-ci.yaml
  .github/workflows/controller-cd.yaml
  .github/workflows/controller-ci.yaml
  .github/workflows/docs.yaml
  .github/workflows/oci-auth-cd.yaml
  .github/workflows/oci-auth-ci.yaml
  .gitignore
  go/ai-proxy/Dockerfile
  go/ai-proxy/Makefile
  go/ai-proxy/go.mod
  go/ai-proxy/go.sum
  go/client/Makefile
  go/controller/Dockerfile
  go/controller/Makefile
  go/controller/go.mod
  go/oci-auth/.golangci.yml
  go/oci-auth/Dockerfile
  go/oci-auth/Makefile
  go/oci-auth/go.mod
  go/paths.mk
  go/tools/Makefile
  go/tools/binaries.mk
  go/tools/go.mod
  go/tools/go.sum
  go/tools/tools.go
Labels: bug-fix

#1951 feat(client): add dryRun flag to stackrun
  go/client/Makefile
  go/client/client.go
  go/client/graph/stack.graphql
Labels: enhancement

#1952 feat: Add EKS icon next to EKS addon names
  assets/src/components/cd/clusters/runtime/columns.tsx
Labels: enhancement

#1953 Fix compatibility updater
  .github/workflows/cron.yaml
  utils/addons/requirements.txt
Labels: bug-fix, hotfix

#1954 Allow ability to manually run cron gh actions
  .github/workflows/cron.yaml
Labels: enhancement, hotfix

#1957 Tune flaky service error logs
  go/demo/flaky-service/api/behavior_modifiers.go
Labels: enhancement

#1963 feat: update cluster bindings in read-only mode
  go/controller/api/v1alpha1/cluster_types.go
  go/controller/internal/controller/cluster_controller.go
  go/controller/internal/controller/cluster_controller_test.go
Labels: enhancement

#1964 improve react flow graphs
  assets/package.json
  assets/src/components/cd/logs/DateTimeFormInput.tsx
  assets/src/components/cd/pipelines/PipelineDetails.tsx
  assets/src/components/cd/pipelines/PipelineGraph.tsx
  assets/src/components/cd/pipelines/nodes/ApprovalNode.tsx
  assets/src/components/cd/pipelines/nodes/JobNode.tsx
  assets/src/components/cd/pipelines/nodes/PipelineBaseNode.tsx
  assets/src/components/cd/pipelines/nodes/StageNode.tsx
  assets/src/components/cd/pipelines/nodes/TestsNode.tsx
  assets/src/components/cd/pipelines/utils/getNodesAndEdges.tsx
  assets/src/components/cd/pipelines/utils/nodeLayouter.tsx
  assets/src/components/cd/services/ServicesTree.tsx
  assets/src/components/cd/services/ServicesTreeDiagram.tsx
  assets/src/components/cd/services/ServicesTreeDiagramNodes.tsx
  assets/src/components/component/ComponentTree.tsx
  assets/src/components/component/tree/ComponentTreeGraph.tsx
  assets/src/components/component/tree/ComponentTreeNode.tsx
  assets/src/components/hooks/reactFlowHooks.tsx
  assets/src/components/stacks/run/state/State.tsx
  assets/src/components/stacks/state/StackState.tsx
  assets/src/components/stacks/state/StackStateGraph.tsx
  assets/src/components/stacks/state/StackStateGraphNode.tsx
  assets/src/components/utils/reactflow/edges.tsx
  assets/src/components/utils/reactflow/graph.tsx
  assets/src/components/utils/reactflow/nodes.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#1958 Troubleshoot vector indexing
  .github/workflows/ai-proxy-cd.yaml
  .github/workflows/ai-proxy-ci.yaml
  .github/workflows/assets.yaml
  .github/workflows/codeql.yml
  .github/workflows/controller-cd.yaml
  .github/workflows/controller-ci.yaml
  .github/workflows/demo-cd.yaml
  .github/workflows/oci-auth-cd.yaml
  .github/workflows/oci-auth-ci.yaml
  .github/workflows/pr-labels.yaml
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  go/demo/flaky-service/api/behavior_modifiers.go
  lib/console/ai/evidence/context.ex
  lib/console/ai/evidence/vector.ex
  lib/console/ai/provider.ex
  lib/console/ai/pubsub/vector/consumer.ex
  lib/console/ai/pubsub/vector/protocol.ex
  lib/console/ai/vector/content.ex
  lib/console/ai/vector/elastic.ex
  lib/console/ai/vector_store.ex
  lib/console/deployments/pr/impl/github.ex
  test-apps/flaky-service/flaky-service.yaml.liquid
  test/console/ai/cron_test.exs
  test/console/ai/pubsub/vector/consumer_test.exs
Labels: enhancement

#1965 More pr indexing fixes
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  go/demo/flaky-service/api/behavior_modifiers.go
  lib/console/ai/cron.ex
  lib/console/ai/evidence/vector.ex
  lib/console/ai/vector/utils.ex
  lib/console/ai/vector_store.ex
  lib/console/deployments/settings.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/schema/deployment_settings.ex
  lib/console/schema/operational_layout.ex
  priv/repo/migrations/20250305170252_add_service_mesh.exs
  priv/tools/vector.json
  schema/schema.graphql
  test/console/ai/pubsub/vector/consumer_test.exs
Labels: enhancement

#1966 add pr evidence UI
  assets/package.json
  assets/src/components/ai/chatbot/ChatMessage.tsx
  assets/src/components/ai/chatbot/ChatbotPanelEvidence.tsx
  assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
  assets/src/components/ai/insights/InsightDisplay.tsx
  assets/src/components/ai/insights/InsightEvidence.tsx
  assets/src/components/ai/insights/LogsEvidencePanel.tsx
  assets/src/components/ai/insights/PrEvidenceDetails.tsx
  assets/src/components/ai/insights/PrEvidencePanel.tsx
  assets/src/components/utils/DiffViewer.tsx
  assets/src/components/utils/table/StackedText.tsx
  assets/src/components/utils/typography/Text.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/ai.graphql
  assets/src/utils/url.test.ts
  assets/src/utils/url.ts
  assets/yarn.lock
Labels: enhancement, frontend

#1962 feat: Support PodDisruptionBudget resource
  assets/schema/kubernetes-schema.graphql
  assets/src/components/kubernetes/cluster/Cluster.tsx
  assets/src/components/kubernetes/cluster/PodDisruptionBudget.tsx
  assets/src/components/kubernetes/cluster/PodDisruptionBudgets.tsx
  assets/src/components/kubernetes/common/types.ts
  assets/src/generated/graphql-kubernetes.ts
  assets/src/graph-kubernetes/cluster/poddisruptionbudget.graphql
  assets/src/routes/kubernetesRoute.tsx
  assets/src/routes/kubernetesRoutesConsts.tsx
  charts/console-rapid/Chart.lock
  charts/console-rapid/Chart.yaml
  charts/console-rapid/charts/controller-0.0.107.tgz
  charts/console-rapid/charts/kas-0.2.0.tgz
  charts/console-rapid/charts/kubernetes-dashboard-7.10.3.tgz
  charts/console-rapid/charts/kubernetes-dashboard-7.11.0.tgz
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.107.tgz
  charts/console/charts/kas-0.2.0.tgz
  charts/console/charts/kubernetes-dashboard-7.10.3.tgz
  charts/console/charts/kubernetes-dashboard-7.11.0.tgz
  plural/helm/console/Chart.lock
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/controller-0.0.107.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.10.3.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.11.0.tgz
Labels: enhancement

#1970 fix: Ensure existing compatibilities updates
  static/compatibilities/amazon-vpc-cni-k8s.yaml
  static/compatibilities/aws-ebs-csi-driver.yaml
  static/compatibilities/aws-load-balancer-controller.yaml
  static/compatibilities/calico.yaml
  static/compatibilities/cert-manager.yaml
  static/compatibilities/contour.yaml
  static/compatibilities/coredns.yaml
  static/compatibilities/external-dns.yaml
  static/compatibilities/ingress-nginx.yaml
  static/compatibilities/jaeger.yaml
  static/compatibilities/karpenter.yaml
  static/compatibilities/traefik.yaml
  static/compatibilities/vitess.yaml
  utils/compatibility/utils.py
Labels: bug-fix

#1969 Begin prepping the release
  go/demo/flaky-service/api/behavior_modifiers.go
  lib/console/ai/evidence/vector.ex
  lib/console/ai/fixer.ex
  lib/console/ai/fixer/alert.ex
  lib/console/ai/fixer/base.ex
  lib/console/ai/fixer/service.ex
  lib/console/ai/tools/pr.ex
  lib/console/ai/vector/elastic.ex
  lib/console/ai/vector/storable.ex
  lib/console/ai/vector_store.ex
  lib/console/deployments/pr/file.ex
  lib/console/deployments/pr/impl/github.ex
  lib/console/schema/ai_insight_evidence.ex
Labels: enhancement

#1976 Flow CRUD endpoints
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/deployments/events.ex
  lib/console/deployments/flows.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/deployments/pr/utils.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/flow.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/deployments/pipeline.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/flow.ex
  lib/console/schema/flow.ex
  lib/console/schema/pipeline.ex
  lib/console/schema/pull_request.ex
  lib/console/schema/service.ex
  priv/repo/migrations/20250306201348_add_flows.exs
  schema/schema.graphql
  test/console/deployments/flows_test.exs
  test/console/graphql/mutations/deployments/flow_mutations_test.exs
  test/console/graphql/queries/deployments/flow_queries_test.exs
  test/support/factory.ex
Labels: enhancement

#1978 Improve console controller tests
  go/controller/internal/controller/catalog_controller_test.go
  go/controller/internal/controller/clusterrestore_controller_test.go
  go/controller/internal/controller/customstackrun_test.go
  go/controller/internal/controller/gitrepository_controller_test.go
  go/controller/internal/controller/managenamespace_test.go
Labels: enhancement

#1973 Softserve setup
  .github/workflows/publish.yaml
  .github/workflows/softserve-cd.yaml
  charts/console/templates/softserve.yaml
  charts/console/values.yaml
  softserve/Dockerfile.softserve
  softserve/softserve_setup.sh
Labels: enhancement

#1979 Rearrange softserve dockerfile and fix gh action
  .github/workflows/publish.yaml
  .github/workflows/softserve-cd.yaml
  charts/console/templates/git-server.yaml
  charts/console/values.yaml
  dockerfiles/Dockerfile.softserve
  dockerfiles/bin/softserve_setup.sh
Labels: enhancement

#1982 Fix git server enabled logic
  charts/console-rapid/Chart.yaml
  charts/console/templates/git-server.yaml
Labels: bug-fix, hotfix

#1983 Accidentally dropped rapid chart app version
  charts/console-rapid/Chart.yaml
Labels: bug-fix, hotfix

#1961 chore: update kas chart to use vendored ghcr nginx image instead of dockerhub
  charts/console-rapid/Chart.lock
  charts/console-rapid/Chart.yaml
  charts/console-rapid/charts/controller-0.0.108.tgz
  charts/console-rapid/charts/kas-0.2.0.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
  charts/console-rapid/charts/kubernetes-dashboard-7.11.0.tgz
  charts/console-rapid/charts/kubernetes-dashboard-7.11.1.tgz
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.108.tgz
  charts/console/charts/kas-0.2.0.tgz
  charts/console/charts/kas-0.3.0.tgz
  charts/console/charts/kubernetes-dashboard-7.11.0.tgz
  charts/console/charts/kubernetes-dashboard-7.11.1.tgz
  plural/helm/console/Chart.lock
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/controller-0.0.108.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.11.0.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.11.1.tgz
  plural/helm/kas/Chart.yaml
  plural/helm/kas/values.yaml
Labels: enhancement

#1986 chore: disable ollama gh action
  .github/workflows/publish-ollama.yaml
Labels: dependencies

#1988 Softserve Fix
  dockerfiles/Dockerfile.softserve
Labels: bug-fix

#1991 return empty string if no region bedrock
  go/ai-proxy/args/args.go
Labels: bug-fix

#1992 bump app version (bedrock aws region bugfix)
  charts/ai-proxy/Chart.yaml
Labels: enhancement

#1985 Fix auth method inference for git repositories
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_observers.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/observer_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_observers.yaml
  lib/console/ai/vector/storable.ex
  lib/console/deployments/pr/impl/github.ex
  lib/console/graphql/deployments/git.ex
  lib/console/schema/git_repository.ex
  lib/console/schema/observer.ex
  plural/helm/console/crds/deployments.plural.sh_observers.yaml
  schema/schema.graphql
  test/console/ai/pubsub/vector/consumer_test.exs
  test/console/deployments/git_test.exs
Labels: enhancement

#1987 Flow controller
  charts/controller/crds/deployments.plural.sh_flows.yaml
  go/client/client.go
  go/client/graph/flow.graphql
  go/controller/PROJECT
  go/controller/api/v1alpha1/flow_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_flows.yaml
  go/controller/config/rbac/flow_editor_role.yaml
  go/controller/config/rbac/flow_viewer_role.yaml
  go/controller/config/rbac/role.yaml
  go/controller/config/samples/deployments_v1alpha1_flow.yaml
  go/controller/internal/client/console.go
  go/controller/internal/client/flow.go
  go/controller/internal/controller/flow_controller.go
  go/controller/internal/controller/flow_controller_test.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  go/controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_flows.yaml
Labels: enhancement

#1993 Add flow id filtering for pr vector search
  lib/console/ai/evidence/alert.ex
  lib/console/ai/evidence/vector.ex
  lib/console/ai/pubsub/vector/consumer.ex
  lib/console/ai/pubsub/vector/protocol.ex
  lib/console/ai/pubsub/vector/types.ex
  lib/console/ai/vector/elastic.ex
  lib/console/ai/vector_store.ex
  lib/console/deployments/pr/dispatcher.ex
  lib/console/deployments/pr/file.ex
  lib/console/deployments/pr/impl/github.ex
  test/console/ai/cron_test.exs
  test/console/ai/pubsub/vector/consumer_test.exs
Labels: enhancement

#1996 Add flowRef to ServiceDeployment and Pipeline CRDs
  charts/controller/crds/deployments.plural.sh_pipelines.yaml
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  go/controller/api/v1alpha1/pipeline_types.go
  go/controller/api/v1alpha1/servicedeployment_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_pipelines.yaml
  go/controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  go/controller/internal/controller/pipeline_controller_attributes.go
  go/controller/internal/controller/servicedeployment_controller.go
  plural/helm/console/crds/deployments.plural.sh_pipelines.yaml
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
Labels: enhancement, hotfix

#1997 Bump rapid chart
  charts/console-rapid/Chart.yaml
  charts/console-rapid/charts/controller-0.0.109.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
Labels: bug-fix, hotfix

#1998 Improve flow reconciliation
  go/controller/internal/controller/pipeline_controller_attributes.go
  go/controller/internal/controller/servicedeployment_controller.go
  lib/console/deployments/git.ex
  lib/console/deployments/observability/webhook/base.ex
  lib/console/deployments/observability/webhook/raw.ex
  test/console_web/controllers/webhook_controller_test.exs
Labels: enhancement

#2000 fix: recreate global service
  go/controller/internal/controller/globalservice_controller.go
Labels: bug-fix

#2001 fix: Fix service errors table scaling issues
  assets/src/components/cd/services/ServicesTableErrors.tsx
  assets/src/components/cd/services/service/ServiceErrors.tsx
Labels: bug-fix

#2002 Index PRs for flows
  lib/console/ai/pubsub/vector/protocol.ex
  lib/console/ai/vector/elastic.ex
  lib/console/schema/alert.ex
  test/console_web/controllers/webhook_controller_test.exs
Labels: enhancement

#2004 remove honorable from console
  assets/package.json
  assets/src/App.tsx
  assets/src/components/contexts.tsx
  assets/src/components/login/Login.tsx
  assets/src/components/utils/Metadata.tsx
  assets/src/helpers/refreshToken.ts
  assets/vite.config.ts
  assets/yarn.lock
Labels: enhancement, frontend

#2007 feat(helm-test): add helm tests for console chart
  .github/workflows/helm-test-ci.yaml
  go/go.work
  go/helm-test/Makefile
  go/helm-test/go.mod
  go/helm-test/go.sum
  go/helm-test/internal/common/consts.go
  go/helm-test/internal/common/env.go
  go/helm-test/internal/common/helm.go
  go/helm-test/internal/common/log.go
  go/helm-test/internal/common/resource.go
  go/helm-test/test/console/common.go
  go/helm-test/test/console/container_image_test.go
  go/helm-test/test/console/core_test.go
  go/helm-test/test/console/security_context_test.go
  go/helm-test/test/console/suite_test.go
  go/helm-test/test/console/volumes_test.go
  go/paths.mk
  go/tools/Makefile
  go/tools/go.mod
  go/tools/tools.go
Labels: enhancement

#2014 fix chat evidence bugs
  assets/eslint.config.mjs
  assets/package.json
  assets/src/components/ai/chatbot/ChatbotPanelEvidence.tsx
  assets/src/components/ai/chatbot/ChatbotPanelInsight.tsx
  assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
  assets/src/components/ai/insights/LogsEvidencePanel.tsx
  assets/yarn.lock
Labels: bug-fix, frontend

#2023 don't linkify vuln report image urls
  assets/src/components/security/vulnerabilities/VulnReportDetails.tsx
  assets/src/components/security/vulnerabilities/VulnReportsTable.tsx
  assets/src/components/security/vulnerabilities/VulnReportsTableCols.tsx
Labels: enhancement, frontend

#2020 feat: `MCPServer` resource and add server associations to `Flow` resource
  .github/CODEOWNERS
  charts/controller/crds/deployments.plural.sh_flows.yaml
  charts/controller/crds/deployments.plural.sh_mcpservers.yaml
  go/client/client.go
  go/client/graph/flow.graphql
  go/client/graph/mcp.graphql
  go/controller/api/v1alpha1/flow_types.go
  go/controller/api/v1alpha1/mcpserver_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_flows.yaml
  go/controller/config/crd/bases/deployments.plural.sh_mcpservers.yaml
  go/controller/config/rbac/role.yaml
  go/controller/config/samples/mcp_server.yaml
  go/controller/docs/api.md
  go/controller/internal/client/console.go
  go/controller/internal/client/mcp.go
  go/controller/internal/controller/flow_controller.go
  go/controller/internal/controller/mcpserver_controller.go
  go/controller/internal/controller/mcpserver_controller_test.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  go/controller/internal/types/reconciler.go
  go/tools/go.mod
  go/tools/go.sum
  plural/helm/console/crds/deployments.plural.sh_flows.yaml
  plural/helm/console/crds/deployments.plural.sh_mcpservers.yaml
Labels: enhancement

#2028 fix: Fix default SCM connection update
  go/controller/internal/controller/scmconnection_controller.go
Labels: bug-fix

#2027 add alert resolutions UI
  assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
  assets/src/components/ai/chatbot/ChatbotSendMessageForm.tsx
  assets/src/components/cd/services/Services.tsx
  assets/src/components/cd/services/ServicesFilters.tsx
  assets/src/components/cd/services/ServicesTable.tsx
  assets/src/components/cd/services/ServicesTree.tsx
  assets/src/components/utils/EditableDiv.tsx
  assets/src/components/utils/alerts/AlertResolutionModal.tsx
  assets/src/components/utils/alerts/AlertsTable.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/alerts.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/utils/applyNodeToRefs.ts
Labels: enhancement, frontend

#2012 Fully fleshed out values.yaml for console helm chart
  charts/console/values.yaml
  go/demo/flaky-service/go.mod
  go/go.work
  go/helmchartutils/args/args.go
  go/helmchartutils/fileutils/fileutils.go
  go/helmchartutils/go.mod
  go/helmchartutils/main.go
  go/helmchartutils/yaml/yaml_parser.go
Labels: enhancement

#2024 Service Mesh Graph Querying
  AGENT_VERSION
  assets/src/generated/graphql.ts
  charts/console-rapid/Chart.yaml
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/managednamespace_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  go/controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  go/controller/internal/controller/common.go
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/mesh/builder.ex
  lib/console/mesh/prometheus.ex
  lib/console/mesh/provider.ex
  lib/console/mesh/provider/istio.ex
  lib/console/mesh/schema.ex
  lib/prometheus/client.ex
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
  priv/tools/pr.json
  schema/schema.graphql
  test/console/deployments/observer/runner_test.exs
  test/console/graphql/queries/deployments/cluster_queries_test.exs
  test/console/mesh/provider/istio_test.exs
  test/test_helper.exs
Labels: enhancement

#2030 Fix docker-compose for mcp server
  docker-compose.yml
  lib/console/deployments/pipelines/stage_worker.ex
  lib/console/deployments/pr/validation.ex
  lib/console/schema/embeds.ex
  priv/agent-chart.tgz
Labels: enhancement

#2044 fix: Bump design system version
  assets/package.json
  assets/yarn.lock
Labels: bug-fix

#2043 More intelligent tool call file editing
  assets/src/components/pr/automations/PrAutomationsColumns.tsx
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  go/controller/api/v1alpha1/prautomation_types.go
  lib/console/ai/chat.ex
  lib/console/ai/file/distance_replacer.ex
  lib/console/ai/file/editor.ex
  lib/console/ai/tools/pr.ex
  lib/console/deployments/flows.ex
  lib/console/deployments/pr/git.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/flow.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/flow.ex
  lib/console/graphql/resolvers/deployments/git.ex
  lib/console/logs/provider/elastic.ex
  lib/console/schema/alert.ex
  lib/console/schema/flow.ex
  lib/console/schema/pr_automation.ex
  priv/tools/pr.json
  schema/schema.graphql
  test/console/ai/chat_test.exs
  test/console/ai/file/editor_test.exs
  test/console/ai/fixer_test.exs
  test/console/cost/pr_test.exs
  test/console/graphql/queries/ai_queries_test.exs
Labels: enhancement

#2055 Implement chat confirmation flow
  assets/src/components/cost-management/details/ClusterScalingRecsTableCols.tsx
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/ai/chat.ex
  lib/console/ai/chat/engine.ex
  lib/console/ai/fixer.ex
  lib/console/ai/mcp/agent.ex
  lib/console/ai/policy.ex
  lib/console/ai/provider/anthropic.ex
  lib/console/ai/provider/base.ex
  lib/console/ai/provider/openai.ex
  lib/console/ai/stream.ex
  lib/console/cost/dimensions.ex
  lib/console/cost/pr.ex
  lib/console/deployments/flows.ex
  lib/console/deployments/observability.ex
  lib/console/deployments/observability/metrics.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/deployments.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/flow.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/observability.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments/observability.ex
  lib/console/schema/chat.ex
  lib/console/schema/mcp_server.ex
  lib/prometheus/client.ex
  priv/repo/migrations/20250324170838_add_chat_confirmed_at.exs
  schema/schema.graphql
  test/console/ai/chat_test.exs
  test/console/cost/pr_test.exs
  test/console/graphql/queries/deployments/cluster_queries_test.exs
  test/console/graphql/queries/deployments/service_queries_test.exs
Labels: enhancement

#2064 Directly specify agent values in self-install process
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_flows.yaml
  charts/controller/crds/deployments.plural.sh_mcpservers.yaml
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/flow_types.go
  go/controller/api/v1alpha1/mcpserver_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_flows.yaml
  go/controller/config/crd/bases/deployments.plural.sh_mcpservers.yaml
  go/controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  go/controller/internal/controller/mcpserver_controller.go
  lib/console/commands/plural.ex
  lib/console/deployments/clusters.ex
  lib/console/deployments/pubsub/protocols/notifiable.ex
  lib/console/graphql/deployments/flow.ex
  lib/console/schema/notification_router.ex
  plural/helm/console/crds/deployments.plural.sh_flows.yaml
  plural/helm/console/crds/deployments.plural.sh_mcpservers.yaml
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
  priv/notifications/plural/stack.pending.json.eex
  priv/notifications/slack/stack.pending.json.eex
  priv/notifications/teams/stack.pending.json.eex
  schema/schema.graphql
  test/console/deployments/clusters_test.exs
  test/console/deployments/pubsub/notification_test.exs
Labels: enhancement

#2057 ui for flows and MCP
  assets/package.json
  assets/src/components/ai/AI.tsx
  assets/src/components/ai/AIThreads.tsx
  assets/src/components/ai/McpAuditTable.tsx
  assets/src/components/ai/McpServerDetails.tsx
  assets/src/components/ai/McpServerTableCols.tsx
  assets/src/components/ai/McpServers.tsx
  assets/src/components/ai/insights/InsightMainContent.tsx
  assets/src/components/ai/useStreamTopic.tsx
  assets/src/components/catalog/CatalogsGrid.tsx
  assets/src/components/cd/ContinuousDeployment.tsx
  assets/src/components/cd/utils/PermissionsModal.tsx
  assets/src/components/commandpalette/CommandPalette.tsx
  assets/src/components/commandpalette/CommandPaletteLauncher.tsx
  assets/src/components/commandpalette/commands.ts
  assets/src/components/flows/FeatureFlagContext.tsx
  assets/src/components/flows/FlowCard.tsx
  assets/src/components/flows/Flows.tsx
  assets/src/components/flows/flow/ChangeMcpConnectionsModal.tsx
  assets/src/components/flows/flow/Flow.tsx
  assets/src/components/flows/flow/FlowAlerts.tsx
  assets/src/components/flows/flow/FlowMcpConnections.tsx
  assets/src/components/flows/flow/FlowPipelines.tsx
  assets/src/components/flows/flow/FlowPrs.tsx
  assets/src/components/flows/flow/FlowServices.tsx
  assets/src/components/flows/flow/McpServerSelector.tsx
  assets/src/components/home/AiThreads.tsx
  assets/src/components/layout/Console.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/security/Security.tsx
  assets/src/components/settings/audits/AuditsList.tsx
  assets/src/components/utils/Alert.tsx
  assets/src/components/utils/JsonExpanderCard.tsx
  assets/src/components/utils/SubTabs.tsx
  assets/src/components/utils/alerts/AlertInsight.tsx
  assets/src/components/utils/alerts/AlertsTable.tsx
  assets/src/components/utils/devHooks.ts
  assets/src/components/utils/hooks.ts
  assets/src/components/utils/table/StackedText.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/ai/chat.graphql
  assets/src/graph/ai/insights.graphql
  assets/src/graph/ai/mcp.graphql
  assets/src/graph/alerts.graphql
  assets/src/graph/cdPipelines.graphql
  assets/src/graph/cdPrs.graphql
  assets/src/graph/cdServices.graphql
  assets/src/graph/flow.graphql
  assets/src/graph/rbac.graphql
  assets/src/routes/aiRoutes.tsx
  assets/src/routes/aiRoutesConsts.tsx
  assets/src/routes/consoleRoutes.tsx
  assets/src/routes/flowRoutes.tsx
  assets/src/routes/flowRoutesConsts.tsx
  assets/yarn.lock
  priv/notifications/slack/stack.pending.json.eex
  test/console/graphql/queries/deployments/cluster_queries_test.exs
Labels: enhancement, frontend

#2074 Lockfile fix
  .github/workflows/test.yaml
  AGENT_VERSION
  assets/src/components/component/ComponentInsights.tsx
  lib/console/jwt/mcp.ex
  mix.lock
  priv/agent-chart.tgz
Labels: enhancement, hotfix

#2078 Drop gcr for now
  .github/workflows/ai-proxy-cd.yaml
  .github/workflows/controller-cd.yaml
  .github/workflows/oci-auth-cd.yaml
  .github/workflows/publish.yaml
  .github/workflows/softserve-cd.yaml
Labels: bug-fix, hotfix
