Repository pluralsh/console, pull requests merged in 2025-06, with the labels that each got.

#2309 Begin prepping 0.11.19
  AGENT_VERSION
  assets/src/components/cd/cluster/ClusterInsights.tsx
  assets/src/components/stacks/Stacks.tsx
  priv/agent-chart.tgz
Labels: enhancement, hotfix

#2316 fix: Allow resetting version
  assets/src/components/stacks/overview/StackConfiguration.tsx
Labels: bug-fix

#2315 Add clusters to resource accounting
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  charts/controller/crds/deployments.plural.sh_previewenvironmenttemplates.yaml
  charts/controller/crds/deployments.plural.sh_scmconnections.yaml
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/managednamespace_types.go
  go/controller/api/v1alpha1/scmconnection_types.go
  go/controller/api/v1alpha1/servicedeployment_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  go/controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  go/controller/config/crd/bases/deployments.plural.sh_previewenvironmenttemplates.yaml
  go/controller/config/crd/bases/deployments.plural.sh_scmconnections.yaml
  go/controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  go/controller/internal/controller/common.go
  go/controller/internal/controller/servicedeployment_controller.go
  lib/console/ai/tools/pr.ex
  lib/console/cached/node.ex
  lib/console/clustering/info.ex
  lib/console/cost/ingester.ex
  lib/console/deployments/global.ex
  lib/console/deployments/services.ex
  lib/console/deployments/statistics.ex
  lib/console/graphql/deployments/global.ex
  lib/console/graphql/deployments/service.ex
  lib/console/schema/service.ex
  lib/console/schema/service_context.ex
  lib/console/schema/service_template.ex
  lib/console/watchers/upgrade.ex
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
  plural/helm/console/crds/deployments.plural.sh_previewenvironmenttemplates.yaml
  plural/helm/console/crds/deployments.plural.sh_scmconnections.yaml
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
  schema/schema.graphql
  test/console/clustering/info_test.exs
  test/console/deployments/global_test.exs
  test/console/deployments/services_test.exs
  test/console/deployments/statistics_test.exs
  test/console_web/controllers/git_controller_test.exs
Labels: enhancement

#2319 update helm chart forms and small fixes
  assets/src/components/cd/services/ServiceSelector.tsx
  assets/src/components/cd/services/ServiceSettings.tsx
  assets/src/components/cd/services/deployModal/DeployService.tsx
  assets/src/components/cd/services/deployModal/DeployServiceSettingsHelm.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/settings/ServiceHelmSettings.tsx
  assets/src/components/security/Security.tsx
Labels: enhancement, frontend

#2323 fix: datastore resource deletion
  go/datastore/Makefile
  go/datastore/api/v1alpha1/elasticsearchindextemplate_types.go
  go/datastore/config/samples/all.yaml
  go/datastore/config/samples/dbs_v1alpha1_elasticsearchilmpolicy.yaml
  go/datastore/internal/controller/common.go
  go/datastore/internal/controller/elasticsearchcredentials_controller.go
  go/datastore/internal/controller/elasticsearchilmpolicy_controller.go
  go/datastore/internal/controller/elasticsearchindextemplate_controller.go
  go/datastore/internal/controller/elasticsearchuser_controller.go
Labels: bug-fix

#2328 Org email suffix as env var
  config/config.exs
  lib/console/services/users.ex
  rel/runtime.exs
  test/console/services/users_test.exs
Labels: enhancement

#2331 extend service with helm values
  go/client/client.go
  go/client/graph/deployment.graphql
Labels: enhancement

#2321 Add o11y setup for cloud
  .github/workflows/controller-ci.yaml
  AGENT_VERSION
  assets/src/generated/graphql.ts
  charts/console-rapid/Chart.yaml
  charts/console-rapid/charts/controller-0.0.124.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
  charts/console/charts/controller-0.0.124.tgz
  charts/console/charts/kas-0.3.0.tgz
  charts/console/templates/cloud.yaml
  charts/console/values.yaml
  go/client/models_gen.go
  lib/console/deployments/git/agent.ex
  lib/console/deployments/init.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/deployments/pr/impl/github.ex
  lib/console/deployments/pubsub/recurse.ex
  lib/console/deployments/settings.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/deployments/settings.ex
  lib/console/graphql/resolvers/deployments/settings.ex
  lib/console/schema/cloud_connection.ex
  lib/console/services/users/access_tokens.ex
  lib/console_web/plugs/token.ex
  plural/helm/kas/templates/deployment.yaml
  plural/helm/kas/values.yaml
  priv/agent-chart.tgz
  priv/repo/migrations/20250605231531_add_cloud_connections.exs
  priv/repo/seeds/07_sre_group.exs
  schema/schema.graphql
  test/console/deployments/init_test.exs
  test/console/deployments/settings_test.exs
  test/console/graphql/mutations/deployments/services_mutations_test.exs
  test/console/graphql/mutations/deployments/settings_mutations_test.exs
  test/console/graphql/queries/deployments/settings_queries_test.exs
  test/support/factory.ex
Labels: enhancement, hotfix

#2338 Fix datastore chart and other release fixes
  .github/workflows/publish.yaml
  Makefile
  charts/console/charts/controller-0.0.124.tgz
  charts/console/charts/kas-0.3.0.tgz
  plural/helm/console/Chart.lock
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/controller-0.0.124.tgz
  plural/helm/console/charts/datastore-0.0.1.tgz
Labels: bug-fix, hotfix

#2342 chore: add CloudConnection client
  go/client/client.go
  go/client/graph/cloud.graphql
  go/controller/internal/client/cloud.go
  go/controller/internal/client/console.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
Labels: enhancement

#2341 fix: Make stack outputs section scrollable
  assets/src/components/stacks/output/StackOutput.tsx
Labels: bug-fix

#2345 o11y fixes
  charts/console-rapid/Chart.yaml
  charts/console/templates/cloud.yaml
  lib/console/deployments/global.ex
Labels: enhancement

#2352 bump DS
  assets/package.json
  assets/src/components/ai/chatbot/AISuggestFix.tsx
  assets/src/components/ai/chatbot/AISuggestFixButton.tsx
  assets/src/components/ai/chatbot/ChatbotButton.tsx
  assets/src/components/catalog/Catalogs.tsx
  assets/src/components/cd/cluster/pod/PodInfo.tsx
  assets/src/components/cd/clusters/ClusterUpgradePR.tsx
  assets/src/components/cd/logs/LogContextPanel.tsx
  assets/src/components/cd/logs/LogsFilters.tsx
  assets/src/components/cd/pipelines/nodes/StageNode.tsx
  assets/src/components/cd/services/deployModal/DeployServiceSettingsHelmValues.tsx
  assets/src/components/cd/services/deployModal/DeployServiceSettingsSecrets.tsx
  assets/src/components/cd/services/service/ServicePromote.tsx
  assets/src/components/cluster/containers/ShellCommandEditor.tsx
  assets/src/components/flows/flow/previews/PreviewInstancesTableCols.tsx
  assets/src/components/login/Login.tsx
  assets/src/components/notifications/NotificationsPanel.tsx
  assets/src/components/profile/SecurityAccess.tsx
  assets/src/components/security/compliance/CreateComplianceReportModal.tsx
  assets/src/components/stacks/RestoreStackButton.tsx
  assets/src/components/stacks/create/CreateStackModalFormEnvironment.tsx
  assets/src/components/stacks/create/CreateStackModalFormFiles.tsx
  assets/src/components/stacks/customrun/StackCustomRunCommands.tsx
  assets/src/components/stacks/run/Header.tsx
  assets/src/components/utils/ReturnToBeginning.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#2354 remove deprecated node details view
  assets/src/components/cd/cluster/ClusterNodes.tsx
  assets/src/components/cd/cluster/node/Node.tsx
  assets/src/components/cd/cluster/node/NodeEvents.tsx
  assets/src/components/cd/cluster/node/NodeInfo.tsx
  assets/src/components/cd/cluster/node/NodeMetadata.tsx
  assets/src/components/cd/cluster/node/NodeRaw.tsx
  assets/src/components/kubernetes/common/DrainNodeModal.tsx
  assets/src/components/utils/Confirm.tsx
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
Labels: enhancement, frontend

#2347 Add logging for failed global service templates
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  config/config.exs
  config/prod.exs
  go/client/models_gen.go
  lib/console/application.ex
  lib/console/deployments/global.ex
  lib/console/deployments/init.ex
  lib/console/deployments/statistics.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/prom/meter.ex
  lib/console/schema/cluster.ex
  lib/console_web/controllers/ingest_controller.ex
  lib/console_web/endpoint.ex
  lib/console_web/plugs/ingest.ex
  lib/console_web/plugs/noop.ex
  lib/console_web/plugs/prom_proxy.ex
  lib/console_web/proxy_router.ex
  lib/console_web/router.ex
  mix.exs
  mix.lock
  rel/runtime.exs
  schema/schema.graphql
  test/console/deployments/global_test.exs
  test/console/deployments/init_test.exs
  test/console/prom/meter_test.exs
Labels: enhancement

#2358 Add splitbrain detection header
  lib/console/deployments/local/server.ex
  lib/console_web/controllers/git_controller.ex
Labels: enhancement

#2353 Clusters Users Dump
  lib/console/compliance/datasource/clusters.ex
  test/console/compliance/clusters_test.exs
Labels: enhancement

#2365 Add arbitrary multi-source support and custom render pipelines for se…
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/ai/evidence/component/raw.ex
  lib/console/deployments/git.ex
  lib/console/deployments/services.ex
  lib/console/graphql/deployments/service.ex
  lib/console/schema/service.ex
  priv/repo/migrations/20250615175950_add_service_sources.exs
  schema/schema.graphql
  test/console/compliance/clusters_test.exs
  test/console/deployments/services_test.exs
Labels: enhancement

#2370 feat: add postgres datastore
  charts/datastore/crds/dbs.plural.sh_postgrescredentials.yaml
  charts/datastore/crds/dbs.plural.sh_postgresdatabases.yaml
  charts/datastore/crds/dbs.plural.sh_postgresusers.yaml
  go/datastore/PROJECT
  go/datastore/api/v1alpha1/postgrescredentials_types.go
  go/datastore/api/v1alpha1/postgresdatabase_types.go
  go/datastore/api/v1alpha1/postgresuser_types.go
  go/datastore/api/v1alpha1/zz_generated.deepcopy.go
  go/datastore/config/crd/bases/dbs.plural.sh_postgrescredentials.yaml
  go/datastore/config/crd/bases/dbs.plural.sh_postgresdatabases.yaml
  go/datastore/config/crd/bases/dbs.plural.sh_postgresusers.yaml
  go/datastore/config/crd/kustomization.yaml
  go/datastore/config/rbac/postgrescredentials_editor_role.yaml
  go/datastore/config/rbac/postgrescredentials_viewer_role.yaml
  go/datastore/config/rbac/postgresdatabase_editor_role.yaml
  go/datastore/config/rbac/postgresdatabase_viewer_role.yaml
  go/datastore/config/rbac/postgresuser_editor_role.yaml
  go/datastore/config/rbac/postgresuser_viewer_role.yaml
  go/datastore/config/rbac/role.yaml
  go/datastore/config/samples/dbs_v1alpha1_postgrescredentials.yaml
  go/datastore/config/samples/dbs_v1alpha1_postgresdatabase.yaml
  go/datastore/config/samples/dbs_v1alpha1_postgresuser.yaml
  go/datastore/config/samples/kustomization.yaml
  go/datastore/go.mod
  go/datastore/go.sum
  go/datastore/internal/client/postgres/client.go
  go/datastore/internal/controller/common.go
  go/datastore/internal/controller/elasticsearchcredentials_controller.go
  go/datastore/internal/controller/elasticsearchuser_controller.go
  go/datastore/internal/controller/postgrescredentials_controller.go
  go/datastore/internal/controller/postgresdatabase_controller.go
  go/datastore/internal/controller/postgresuser_controller.go
  go/datastore/internal/types/reconciler.go
  plural/helm/console/crds/dbs.plural.sh_postgrescredentials.yaml
  plural/helm/console/crds/dbs.plural.sh_postgresdatabases.yaml
  plural/helm/console/crds/dbs.plural.sh_postgresusers.yaml
Labels: enhancement

#2375 Begin prepping release
  AGENT_VERSION
  lib/console/deployments/git/agent.ex
  lib/console/deployments/git/cmd.ex
  lib/console/deployments/git/discovery.ex
  lib/console/deployments/pubsub/protocols/broadcastable.ex
  lib/console/deployments/services.ex
  lib/console/schema/service.ex
  priv/agent-chart.tgz
Labels: enhancement

#2381 investigate console mem issues
  AGENT_VERSION
  assets/src/components/cd/cluster/ClusterMetrics.tsx
  assets/src/components/cd/clusters/info-flyover/overview/OverviewTab.tsx
  assets/src/components/pr/automations/PrConfigurationFields.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/automation.graphql
  assets/src/graph/home.graphql
  charts/controller/crds/deployments.plural.sh_customstackruns.yaml
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/prautomation_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_customstackruns.yaml
  go/controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  go/controller/docs/api.md
  lib/console/ai/evidence/component/raw.ex
  lib/console/ai/evidence/component/resource.ex
  lib/console/ai/evidence/service_component.ex
  lib/console/ai/evidence/service_component_child.ex
  lib/console/deployments/git/agent.ex
  lib/console/graphql/deployments/git.ex
  lib/console/schema/embeds.ex
  lib/console/schema/service_component_child.ex
  plural/helm/console/crds/deployments.plural.sh_customstackruns.yaml
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
  priv/agent-chart.tgz
  schema/schema.graphql
  test/console/ai/cron_test.exs
  test/support/kubernetes_scaffolds.ex
Labels: bug-fix

#2389 fix: Project deletion improvements
  go/controller/config/samples/project.yaml
  go/controller/internal/client/console.go
  go/controller/internal/client/project.go
  go/controller/internal/controller/project_controller.go
  go/controller/internal/controller/project_controller_test.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
Labels: bug-fix

#2390 revert useless cluster user dump; stream service creation date
  lib/console/compliance/datasource/clusters.ex
  lib/console/compliance/datasource/services.ex
  test/console/compliance/clusters_test.exs
  test/console/compliance/datasource/services_test.exs
Labels: enhancement

#2394 add new subtabs to service settings
  assets/src/components/cd/services/ServiceDependenciesColumns.tsx
  assets/src/components/cd/services/service/ServiceContexts.tsx
  assets/src/components/cd/services/service/ServiceDependencies.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceRevisions.tsx
  assets/src/components/cd/services/service/ServiceStackImports.tsx
  assets/src/components/cd/services/service/settings/ServiceSecrets.tsx
  assets/src/components/cd/services/service/settings/ServiceSettings.tsx
  assets/src/components/utils/SubTabs.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cd/services.graphql
  assets/src/graph/stacks.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
Labels: enhancement, frontend

#2391 Fix context attachment race condition
  AGENT_VERSION
  assets/src/components/settings/usermanagement/personas/PersonaAttributesEdit.tsx
  assets/src/components/settings/usermanagement/personas/PersonaCreate.tsx
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/compliance/datasource/flows.ex
  lib/console/compliance/datasource/users.ex
  lib/console/compliance/report.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/global.ex
  lib/console/graphql/users.ex
  lib/console/schema/flow.ex
  lib/console/schema/persona.ex
  lib/console/schema/service_template.ex
  lib/console/schema/user.ex
  priv/agent-chart.tgz
  priv/repo/migrations/20250624201927_add_persona_role.exs
  schema/schema.graphql
  test/console/deployments/global_test.exs
Labels: enhancement

#2382 new self service tab
  assets/src/components/catalog/Catalogs.tsx
  assets/src/components/cd/cluster/ClusterPRs.tsx
  assets/src/components/cd/pipelines/PipelinePullRequests.tsx
  assets/src/components/cd/services/service/ServicePRs.tsx
  assets/src/components/cloud-setup/steps/scm-setup/ManualGitSetup.tsx
  assets/src/components/commandpalette/commands.ts
  assets/src/components/cost-management/details/recommendations/CreateRecommendationPrModal.tsx
  assets/src/components/cost-management/details/recommendations/CreateRecommendationPrSteps.tsx
  assets/src/components/flows/Flows.tsx
  assets/src/components/flows/flow/FlowPrs.tsx
  assets/src/components/home/Home.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/pr/Pr.tsx
  assets/src/components/pr/scm/PrScmConnections.tsx
  assets/src/components/pr/scm/ScmWebhooks.tsx
  assets/src/components/self-service/SelfService.tsx
  assets/src/components/self-service/catalog/Catalog.tsx
  assets/src/components/self-service/catalog/CatalogPRAutomations.tsx
  assets/src/components/self-service/catalog/CatalogPermissions.tsx
  assets/src/components/self-service/catalog/Catalogs.tsx
  assets/src/components/self-service/catalog/CatalogsFilters.tsx
  assets/src/components/self-service/catalog/CatalogsFiltersGroup.tsx
  assets/src/components/self-service/catalog/CatalogsGrid.tsx
  assets/src/components/self-service/pr/automations/CreatePrModal.tsx
  assets/src/components/self-service/pr/automations/PrAutomationPermissionsModal.tsx
  assets/src/components/self-service/pr/automations/PrAutomations.tsx
  assets/src/components/self-service/pr/automations/PrAutomationsColumns.tsx
  assets/src/components/self-service/pr/automations/PrConfigurationFields.tsx
  assets/src/components/self-service/pr/automations/PrConfigurationInput.tsx
  assets/src/components/self-service/pr/automations/prConfigurationUtils.tsx
  assets/src/components/self-service/pr/automations/wizard/CreatePrActions.tsx
  assets/src/components/self-service/pr/automations/wizard/CreatePrSteps.tsx
  assets/src/components/self-service/pr/queue/DeletePr.tsx
  assets/src/components/self-service/pr/queue/OutstandingPrs.tsx
  assets/src/components/self-service/pr/queue/PrQueueColumns.tsx
  assets/src/components/self-service/pr/queue/PrSettings.tsx
  assets/src/components/self-service/pr/scm/CreateScmConnection.tsx
  assets/src/components/self-service/pr/scm/CreateScmConnectionWebhook.tsx
  assets/src/components/self-service/pr/scm/CreateScmWebhook.tsx
  assets/src/components/self-service/pr/scm/EditScmConnection.tsx
  assets/src/components/self-service/pr/scm/GitProviderSelect.tsx
  assets/src/components/self-service/pr/scm/PrScmConnectionsColumns.tsx
  assets/src/components/self-service/pr/scm/PrScmManagement.tsx.tsx
  assets/src/components/self-service/pr/scm/ScmWebhooksColumns.tsx
  assets/src/components/self-service/pr/scm/SetupDependencyAutomation.tsx
  assets/src/components/stacks/customrun/StackCustomRunSettings.tsx
  assets/src/components/stacks/prs/PrStackRunsAccordion.tsx
  assets/src/components/stacks/run/Sidecar.tsx
  assets/src/components/utils/StretchedFlex.tsx
  assets/src/components/utils/SubTabs.tsx
  assets/src/index.css
  assets/src/routes/catalogRoutes.tsx
  assets/src/routes/catalogRoutesConsts.tsx
  assets/src/routes/consoleRoutes.tsx
  assets/src/routes/prRoutes.tsx
  assets/src/routes/prRoutesConsts.tsx
  assets/src/routes/selfServiceRoutes.tsx
  assets/src/routes/selfServiceRoutesConsts.tsx
Labels: enhancement, frontend

#2405 Minor chart fixes for postgres creds setup
  charts/console-rapid/Chart.yaml
  charts/console/templates/database.yaml
  charts/console/values.yaml
  lib/console/deployments/pubsub/protocols/previewable.ex
Labels: bug-fix, hotfix

#2403 home screen QA
  assets/src/components/cd/cluster/ClusterMetrics.tsx
  assets/src/components/cd/clusters/ClusterHealthChip.tsx
  assets/src/components/cd/clusters/ClusterUpgradeButton.tsx
  assets/src/components/cd/clusters/ClustersColumns.tsx
  assets/src/components/cd/clusters/info-flyover/overview/OverviewHeatmaps.tsx
  assets/src/components/cd/clusters/info-flyover/overview/OverviewTab.tsx
  assets/src/components/home/GettingStarted.tsx
  assets/src/components/home/Home.tsx
  assets/src/components/home/HomeFilterOptionCard.tsx
  assets/src/components/home/clusteroverview/ClusterHealthScoresHeatmap.tsx
  assets/src/components/home/clusteroverview/ClusterHealthScoresHeatmapEmpty.tsx
  assets/src/components/home/clusteroverview/ClusterUpgradesChart.tsx
  assets/src/components/home/clusteroverview/ClusterUpgradesChartEmpty.tsx
  assets/src/components/utils/RadialBarChart.tsx
  assets/src/components/utils/UtilizationHeatmap.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/metrics.graphql
Labels: enhancement, frontend

#2407 add new persona configuration for service details
  assets/src/components/cd/clusters/ClustersColumns.tsx
  assets/src/components/cd/clusters/info-flyover/overview/OverviewHeatmaps.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/settings/ServiceSecrets.tsx
  assets/src/components/cd/services/service/settings/ServiceSettings.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/personas.graphql
Labels: enhancement, frontend

#2408 prep 0.11.25
  AGENT_VERSION
  priv/agent-chart.tgz
Labels: enhancement, hotfix

#2414 fix: update SetDatabaseOwner for postgres
  go/datastore/internal/client/postgres/client.go
Labels: bug-fix
