Repository pluralsh/console, pull requests merged in 2025-08, with the labels that each got.

#2356 PersistentVolume Evidence Module for AI
  lib/console/ai/evidence/base.ex
  lib/console/ai/evidence/component/persistent_volume_claim.ex
  lib/console/ai/evidence/component/resource.ex
  lib/console/ai/evidence/component/stateful_set.ex
  lib/console/ai/evidence/context.ex
  lib/console/ai/evidence/logs.ex
  test/console/ai/cron_test.exs
  test/console/graphql/queries/kubernetes_queries_test.exs
  test/support/kubernetes_scaffolds.ex
  test/test_helper.exs
Labels: enhancement

#2522 extend syncConfig with deleteNamespace flag
  go/client/client.go
  go/client/graph/deployment.graphql
Labels: enhancement

#2528 Implement genstage based insight generation
  assets/src/components/ai/insights/InsightRefresh.tsx
  assets/src/components/cd/cluster/ClusterInsights.tsx
  assets/src/components/cd/services/service/ServiceInsights.tsx
  assets/src/components/stacks/insights/StackInsights.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/ai/insights.graphql
  config/prod.exs
  lib/console/ai/fixer.ex
  lib/console/ai/memoizer.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/pipelines/ai/alert/pipeline.ex
  lib/console/pipelines/ai/alert/producer.ex
  lib/console/pipelines/ai/base.ex
  lib/console/pipelines/ai/cluster/pipeline.ex
  lib/console/pipelines/ai/cluster/producer.ex
  lib/console/pipelines/ai/service/pipeline.ex
  lib/console/pipelines/ai/service/producer.ex
  lib/console/pipelines/ai/stack/pipeline.ex
  lib/console/pipelines/ai/stack/producer.ex
  lib/console/pipelines/supervisor.ex
  lib/console/schema/ai_insight.ex
  lib/console/schema/alert.ex
  lib/console/schema/cluster.ex
  lib/console/schema/global_service.ex
  lib/console/schema/pull_request.ex
  lib/console/schema/service.ex
  lib/console/schema/stack.ex
  priv/repo/migrations/20250805013721_add_insight_poll_at.exs
  priv/repo/migrations/20250805134039_ai_insight_force.exs
  schema/schema.graphql
  test/console/ai/cron_test.exs
  test/console/graphql/mutations/ai_mutations_test.exs
Labels: enhancement

#2533 fix: Remove namespace links from kubernetes lists
  assets/src/components/kubernetes/common/utils.tsx
Labels: enhancement

#2532 fix(federatedcredential): include required userID in attributes for all credential operations
  charts/console-rapid/charts/controller-0.0.137.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
  charts/console/charts/controller-0.0.137.tgz
  charts/console/charts/kas-0.3.0.tgz
  charts/controller/crds/deployments.plural.sh_federatedcredentials.yaml
  go/controller/api/v1alpha1/federatedcredential_types.go
  go/controller/config/crd/bases/deployments.plural.sh_federatedcredentials.yaml
  go/controller/internal/controller/federatedcredential_controller.go
  plural/helm/console/Chart.lock
  plural/helm/console/charts/controller-0.0.136.tgz
  plural/helm/console/charts/controller-0.0.137.tgz
  plural/helm/console/crds/deployments.plural.sh_federatedcredentials.yaml
Labels: bug-fix

#2531 fix(db-init): enhance PostgreSQL initialization and readiness checks
  charts/console/templates/cloud-query/deployment.yaml
  go/cloud-query/db.Dockerfile
  go/cloud-query/hack/init.sh
  go/cloud-query/hack/init.sql
Labels: bug-fix

#2506 refactor(scmconnection): use custom annotation to reconcile on secret ref changes
  charts/console-rapid/charts/controller-0.0.137.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
  charts/console/charts/controller-0.0.137.tgz
  charts/console/charts/kas-0.3.0.tgz
  go/controller/Dockerfile
  go/controller/api/v1alpha1/scmconnection_types.go
  go/controller/config/rbac/role.yaml
  go/controller/go.mod
  go/controller/go.sum
  go/controller/internal/controller/common.go
  go/controller/internal/controller/scmconnection_controller.go
  go/controller/internal/utils/kubernetes.go
  plural/helm/console/charts/controller-0.0.137.tgz
Labels: bug-fix

#2542 fix: ensure helm.values yaml encoding is stable
  go/controller/internal/controller/servicedeployment_controller.go
  go/controller/internal/controller/servicedeployment_controller_test.go
Labels: bug-fix

#2537 Basic HTTPROXY support
  assets/src/generated/graphql.ts
  charts/console-rapid/charts/controller-0.0.137.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
  charts/console/charts/controller-0.0.137.tgz
  charts/console/charts/kas-0.3.0.tgz
  charts/controller/crds/deployments.plural.sh_scmconnections.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/scmconnection_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_scmconnections.yaml
  go/controller/docs/api.md
  lib/console/deployments/git/cmd.ex
  lib/console/graphql/deployments/git.ex
  lib/console/schema/scm_connection.ex
  plural/helm/console/charts/controller-0.0.137.tgz
  plural/helm/console/crds/deployments.plural.sh_scmconnections.yaml
  priv/repo/migrations/20250807202721_add_proxy_columns.exs
  rel/runtime.exs
  schema/schema.graphql
Labels: enhancement

#2551 Revert values file sort logic
  charts/console-rapid/charts/controller-0.0.139.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
  charts/console/charts/controller-0.0.139.tgz
  charts/console/charts/kas-0.3.0.tgz
  go/controller/internal/controller/servicedeployment_controller.go
  plural/helm/console/Chart.lock
  plural/helm/console/charts/controller-0.0.137.tgz
  plural/helm/console/charts/controller-0.0.139.tgz
Labels: bug-fix, hotfix

#2559 chore: Remove component level tree view
  assets/src/components/component/ComponentTree.tsx
  assets/src/components/component/directory.tsx
  assets/src/routes/cdRoutes.tsx
Labels: bug-fix, chore

#2561 Fix ai proxy
  go/ai-proxy/proxy/openai/embeddings.go
Labels: enhancement

#2562 Bump ai proxy helm chart to 1.3.2
  charts/ai-proxy/Chart.yaml
Labels: enhancement

#2560 feat: Add mgmt column to global services table
  assets/src/components/cd/globalServices/GlobalServices.tsx
  assets/src/components/cd/globalServices/GlobalServicesColumns.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cd/globalServices.graphql
Labels: enhancement

#2556 Allow for file deletions in file updates block of generic pr toolcall
  assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
  charts/console-rapid/charts/controller-0.0.140.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
  charts/console/charts/controller-0.0.140.tgz
  charts/console/charts/kas-0.3.0.tgz
  charts/console/templates/secrets.yaml
  config/config.exs
  config/prod.exs
  go/controller/internal/controller/pipeline_controller.go
  lib/console/ai/chat/tools.ex
  lib/console/ai/file/editor.ex
  lib/console/ai/tools/agent/coding/generic_pr.ex
  lib/console/ai/tools/agent/coding/pr.ex
  lib/console/ai/tools/agent/service_component.ex
  lib/console/ai/tools/agent/stack.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/git.ex
  lib/console/deployments/git/cmd.ex
  lib/console/deployments/pipelines.ex
  lib/console/deployments/pr/git.ex
  lib/console/deployments/pr/impl/github.ex
  lib/console/jwt/github.ex
  lib/console/schema/cluster_usage.ex
  lib/console/schema/cluster_usage_history.ex
  lib/console/schema/git_repository.ex
  lib/console/schema/service_template.ex
  mix.exs
  mix.lock
  plural/helm/console/charts/controller-0.0.140.tgz
  priv/prompts/terraform_commit.md
  rel/runtime.exs
  test/console/ai/pubsub/vector/consumer_test.exs
  test/console/ai/tools/agent/service_component_test.exs
  test/console/ai/tools/agent/stack_test.exs
  test/console/deployments/cron_test.exs
  test/console/graphql/queries/deployments/cluster_queries_test.exs
  test/console/jwt/github_test.exs
Labels: enhancement

#2555 feat(chart): add check for existing chart version before OCI push
  .github/workflows/chart.yaml
Labels: bug-fix

#2574 Switch helm publishes to gcr (#2573)
  .github/workflows/chart.yaml
Labels: enhancement

#2569 use registry cache
  .github/workflows/test.yaml
  README.md
Labels: enhancement

#2575 Pre-release touchups
  AGENT_VERSION
  assets/src/components/ai/chatbot/ChatMessageContent.tsx
  assets/src/components/ai/chatbot/ChatbotHeader.tsx
  assets/src/components/self-service/pr/automations/CreatePrModal.tsx
  assets/src/components/self-service/pr/automations/prConfigurationUtils.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/ai/chat.graphql
  go/client/models_gen.go
  lib/console/ai/tools/agent/call_pr.ex
  lib/console/ai/tools/agent/coding/generic_pr.ex
  lib/console/graphql/ai.ex
  lib/console/schema/chat.ex
  priv/agent-chart.tgz
  priv/repo/migrations/20250815135206_add_policy_indexes.exs
  priv/tools/agent/call_pr.json
  schema/schema.graphql
Labels: enhancement

#2579 Fix notification sink configuration optional
  charts/console-rapid/charts/controller-0.0.141.tgz
  charts/console-rapid/charts/kas-0.3.0.tgz
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.140.tgz
  charts/console/charts/controller-0.0.141.tgz
  charts/console/charts/kas-0.3.0.tgz
  charts/controller/crds/deployments.plural.sh_notificationsinks.yaml
  go/controller/api/v1alpha1/notificationsink_types.go
  go/controller/config/crd/bases/deployments.plural.sh_notificationsinks.yaml
  go/controller/docs/api.md
  plural/helm/console/Chart.lock
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/controller-0.0.140.tgz
  plural/helm/console/charts/controller-0.0.141.tgz
  plural/helm/console/crds/deployments.plural.sh_notificationsinks.yaml
Labels: bug-fix, hotfix

#2588 feat(client): add distro field to ClusterFragment
  go/client/client.go
  go/client/graph/cluster.graphql
Labels: enhancement

#2593 chat ui bug fixes
  assets/src/components/ai/chatbot/ChatMessage.tsx
  assets/src/components/ai/chatbot/ChatMessageContent.tsx
  assets/src/components/ai/chatbot/Chatbot.tsx
  assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
  assets/src/components/ai/chatbot/input/ChatInput.tsx
  assets/src/components/utils/VirtualList.tsx
Labels: bug-fix, frontend

#2603 Drop a few gh actions
  .github/workflows/publish.yaml
  .github/workflows/test-pr.yaml
  lib/console/deployments/services.ex
  priv/repo/migrations/20250821180844_add_template_id_index.exs
Labels: enhancement

#2591 remove standard scroller from cmd k
  assets/package.json
  assets/src/components/ai/AIContext.tsx
  assets/src/components/ai/chatbot/ChatbotHeader.tsx
  assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
  assets/src/components/ai/chatbot/ChatbotThreadMoreMenu.tsx
  assets/src/components/ai/chatbot/input/ChatInput.tsx
  assets/src/components/commandpalette/CommandPalette.tsx
  assets/src/components/commandpalette/CommandPaletteContext.tsx
  assets/src/components/commandpalette/CommandPaletteDialog.tsx
  assets/src/components/commandpalette/CommandPaletteLauncher.tsx
  assets/src/components/commandpalette/commands.ts
  assets/src/components/stacks/state/StackStateGraph.tsx
  assets/src/components/utils/EditableDiv.tsx
  assets/src/components/utils/SkeletonLoaders.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#2617 fix chat message width bug
  assets/src/components/ai/chatbot/ChatMessage.tsx
  assets/src/components/ai/chatbot/ChatMessageContent.tsx
Labels: bug-fix, frontend

#2621 Work on fixing dupe tool use
  lib/console/ai/chat/engine.ex
  lib/console/ai/chat/system.ex
  lib/console/ai/provider.ex
  lib/console/ai/provider/anthropic.ex
  lib/console/ai/provider/openai.ex
  lib/console/ai/stream/exec.ex
  lib/console/deployments/compatibilities/schema.ex
  lib/console/schema/chat.ex
  priv/prompts/kubernetes_pr.md
  priv/prompts/provisioning.md
  priv/prompts/terraform_pr.md
  static/compatibilities/cilium.yaml
  test/console/deployments/clusters_test.exs
Labels: enhancement

#2618 feat: Build extended support matrices for aks/gke/eks
  .github/workflows/compatability-matrices.yaml
  .github/workflows/cron.yaml
  static/extended/aks.yaml
  static/extended/eks.yaml
  static/extended/gke.yaml
  utils/extended/main.py
  utils/extended/requirements.txt
Labels: enhancement

#2624 Prep v0.11.41
  Dockerfile
  lib/console/deployments/cron.ex
  lib/console/deployments/services.ex
Labels: enhancement
