Repository pluralsh/console, pull requests merged in 2025-01, with the labels that each got.

#1717 Prep 0.10.45 release
  AGENT_VERSION
  Makefile
  assets/src/generated/graphql.ts
  assets/src/helpers/client.ts
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  config/prod.exs
  go/client/models_gen.go
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  go/controller/docs/api.md
  go/controller/internal/controller/deploymentsettings_controller.go
  lib/console/ai/evidence.ex
  lib/console/ai/evidence/cluster.ex
  lib/console/ai/evidence/cluster_insight_component.ex
  lib/console/ai/evidence/service.ex
  lib/console/ai/evidence/service_component.ex
  lib/console/ai/evidence/stack.ex
  lib/console/ai/evidence/stack_run.ex
  lib/console/ai/evidence/stack_state.ex
  lib/console/ai/memoizer.ex
  lib/console/application.ex
  lib/console/buffers/cluster_audit.ex
  lib/console/deployments/cron.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/schema/cluster_audit_log.ex
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
  priv/repo/migrations/20250102012446_add_cluster_audits.exs
  schema/schema.graphql
  test/console/buffers/cluster_audit_test.exs
  test/console/deployments/cron_test.exs
  test/console/graphql/mutations/deployments/cluster_mutations_test.exs
  test/console/graphql/queries/deployments/cluster_queries_test.exs
  test/support/factory.ex
  utils/versions/main.py
  utils/versions/requirements.txt
Labels: enhancement

#1727 enhancement: AI empty states
  assets/public/ai.png
  assets/src/components/ai/AI.tsx
  assets/src/components/ai/InsightDisplay.tsx
  assets/src/components/cd/cluster/ClusterInsightComponent.tsx
  assets/src/components/cd/cluster/ClusterInsights.tsx
  assets/src/components/cd/services/service/ServiceInsights.tsx
  assets/src/components/component/ComponentInsights.tsx
  assets/src/components/contexts/DeploymentSettingsContext.tsx
  assets/src/components/home/AiThreads.tsx
  assets/src/components/stacks/insights/StackInsights.tsx
  assets/src/components/stacks/run/insights/StackRunInsights.tsx
Labels: enhancement

#1724 Fix cpu recommendation inference
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/ai/provider/ollama.ex
  lib/console/cost/ingester.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/schema/cluster_scaling_recommendation.ex
  priv/repo/migrations/20250106200605_add_recommendation_utils.exs
  schema/schema.graphql
  test/console/cost/ingester_test.exs
Labels: enhancement

#1728 Add memory util fields to schema
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/graphql/deployments/cluster.ex
  schema/schema.graphql
Labels: hotfix

#1730 Add memory util fields to schema
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/graphql/ai.ex
  schema/schema.graphql
Labels: enhancement

#1729 Scaling recommendations based off utilization
  lib/console/cost/ingester.ex
  test/console/cost/ingester_test.exs
  test/console/graphql/mutations/deployments/cluster_mutations_test.exs
Labels: enhancement, hotfix

#1733 enhancement: AI empty state improvements
  assets/src/components/ai/AI.tsx
  assets/src/components/ai/InsightDisplay.tsx
  assets/src/components/contexts/DeploymentSettingsContext.tsx
  assets/src/components/home/AiThreads.tsx
Labels: enhancement

#1731 add new actions to ai chat
  assets/package.json
  assets/src/components/ai/chatbot/ChatMessage.tsx
  assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
  assets/src/components/ai/chatbot/ChatbotSendMessageForm.tsx
  assets/src/components/ai/chatbot/useCurrentPageChatContext.tsx
  assets/src/components/contexts/NavigationContext.tsx
  assets/src/components/pr/scm/EditScmConnection.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/ai.graphql
  assets/yarn.lock
Labels: enhancement, frontend

#1734 Adds automated PRs to apply scaling recommendations
  AGENT_VERSION
  Dockerfile
  assets/src/components/cost-management/details/ClusterScalingRecsTableCols.tsx
  assets/src/components/cost-management/details/CostManagementDetailsRecommendations.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/costManagement.graphql
  lib/console/ai/fixer.ex
  lib/console/ai/tools/pr.ex
  lib/console/cost/dimensions.ex
  lib/console/cost/pr.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/logs/provider/victoria.ex
  lib/console/logs/query.ex
  lib/console/schema/deployment_settings.ex
  priv/tools/pr.json
  schema/schema.graphql
  test/console/cost/pr_test.exs
Labels: enhancement

#1737 show service errors on stack run detail
  assets/src/components/settings/usermanagement/groups/GroupCreate.tsx
  assets/src/components/settings/usermanagement/groups/GroupEdit.tsx
  assets/src/components/stacks/run/Header.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/groups.graphql
Labels: enhancement, frontend

#1738 Fix victoria logs provider
  charts/console-rapid/Chart.yaml
  charts/controller/Chart.yaml
  charts/controller/templates/manager-rbac.yaml
  lib/console/logs/provider/victoria.ex
  lib/console/logs/stream/exec.ex
Labels: enhancement, hotfix

#1741 bump controller chart
  charts/console-rapid/Chart.lock
  charts/console-rapid/charts/controller-0.0.100.tgz
  charts/console-rapid/charts/controller-0.0.99.tgz
  charts/console-rapid/charts/kas-0.1.0.tgz
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.100.tgz
  charts/console/charts/controller-0.0.99.tgz
  charts/console/charts/kas-0.1.0.tgz
Labels: enhancement, hotfix

#1743 fix: GeneratedSecret reconciler
  go/controller/config/samples/deployments_v1alpha1_generatedsecret.yaml
  go/controller/internal/controller/generatedsecret_controller.go
Labels: bug-fix

#1742 enhancement: Lazy load cluster nodes
  assets/src/components/cd/cluster/ClusterNodes.tsx
  assets/src/components/cluster/nodes/ClusterMetrics.tsx
  assets/src/components/home/AiThreads.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/utils/prometheus.ts
Labels: enhancement

#1739 various QA
  assets/src/components/ai/AITableEntry.tsx
  assets/src/components/ai/chatbot/ChatbotPanelThread.tsx
  assets/src/components/cost-management/CostManagement.tsx
  assets/src/components/cost-management/details/CostManagementDetailsNamespaces.tsx
  assets/src/components/utils/AiInsights.tsx
Labels: enhancement, frontend

#1744 Implement elasticsearch log driver
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  charts/console-rapid/Chart.lock
  charts/console-rapid/Chart.yaml
  charts/console-rapid/charts/controller-0.0.100.tgz
  charts/console-rapid/charts/controller-0.0.101.tgz
  charts/console-rapid/charts/kas-0.1.0.tgz
  charts/controller/Chart.yaml
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  go/controller/docs/api.md
  lib/console/graphql/deployments/settings.ex
  lib/console/logs/provider.ex
  lib/console/logs/provider/elastic.ex
  lib/console/logs/provider/elastic/client.ex
  lib/console/schema/deployment_settings.ex
  mix.exs
  mix.lock
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
  schema/schema.graphql
Labels: enhancement

#1745 bump console rapid chart
  charts/console-rapid/Chart.yaml
Labels: enhancement, hotfix

#1748 extend AISettings with ScmConnection
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
Labels: enhancement

#1747 fix: controller manager RBAC
  charts/controller/templates/manager-rbac.yaml
Labels: bug-fix

#1751 updated logs view
  assets/package.json
  assets/src/components/apps/app/logs/LogContent.tsx
  assets/src/components/apps/app/logs/LogInfo.tsx
  assets/src/components/apps/app/logs/LogLine.tsx
  assets/src/components/apps/app/logs/Logs.tsx
  assets/src/components/apps/app/logs/LogsCard.tsx
  assets/src/components/apps/app/logs/LogsDownloader.tsx
  assets/src/components/apps/app/logs/LogsFilters.tsx
  assets/src/components/apps/app/logs/LogsFullScreen.tsx
  assets/src/components/apps/app/logs/LogsLabels.tsx
  assets/src/components/apps/app/logs/LogsScrollIndicator.tsx
  assets/src/components/apps/app/logs/misc.ts
  assets/src/components/cd/cluster/pod/Pod.tsx
  assets/src/components/cd/cluster/pod/logs/ContainerLogs.tsx
  assets/src/components/cd/logs/LogContextPanel.tsx
  assets/src/components/cd/logs/LogLine.tsx
  assets/src/components/cd/logs/Logs.tsx
  assets/src/components/cd/logs/LogsCard.tsx
  assets/src/components/cd/logs/LogsInfoPanel.tsx
  assets/src/components/cd/logs/LogsLabels.tsx
  assets/src/components/cd/logs/LogsLegend.tsx
  assets/src/components/cd/logs/LogsScrollIndicator.tsx
  assets/src/components/cd/logs/LogsTable.tsx
  assets/src/components/cd/services/service/ServiceDetailsSidecar.tsx
  assets/src/components/cd/services/service/ServiceLogs.tsx
  assets/src/components/cd/services/service/ServiceSecrets.tsx
  assets/src/components/cd/services/service/pod/Pod.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/stacks/common/StackStatusIcon.tsx
  assets/src/components/utils/table/StackedText.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/logs.graphql
  assets/src/utils/datetime.ts
  assets/yarn.lock
  go/client/models_gen.go
  lib/console/deployments/cron.ex
  lib/console/graphql/observability.ex
  lib/console/logs/provider/elastic.ex
  lib/console/logs/query.ex
  schema/schema.graphql
Labels: enhancement, frontend

#1752 Add functionality to AI Proxy for full Open AI protocol
  go/ai-proxy/Dockerfile
  go/ai-proxy/api/openai/openai.go
  go/ai-proxy/api/provider.go
  go/ai-proxy/api/proxy.go
  go/ai-proxy/go.mod
  go/ai-proxy/go.sum
  go/ai-proxy/main.go
  go/ai-proxy/proxy/openai/openai.go
  go/ai-proxy/proxy/provider/openai.go
  go/ai-proxy/proxy/proxy.go
  go/ai-proxy/router/router.go
  go/ai-proxy/test/helpers/common.go
  go/ai-proxy/test/openai_standard/openai_standard_test.go
Labels: enhancement, backend

#1754 Device registration APIs
  assets/src/components/cd/pipelines/PipelineGraph.tsx
  assets/src/components/cd/pipelines/nodes/StageNode.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdPipelines.graphql
  go/ai-proxy/api/openai/openai.go
  go/client/models_gen.go
  lib/console/deployments/clusters.ex
  lib/console/deployments/init.ex
  lib/console/deployments/pipelines.ex
  lib/console/deployments/policies/bootstrap_policies.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/pipeline.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/logs/provider/elastic.ex
  lib/console/schema/cluster_registration.ex
  lib/console/schema/pipeline_pull_request.ex
  priv/repo/migrations/20250115182839_add_device_registrations.exs
  priv/repo/migrations/20250115214225_add_pipeline_pr_stage.exs
  schema/schema.graphql
  test/console/deployments/clusters_test.exs
  test/console/deployments/init_test.exs
  test/console/deployments/pipelines_test.exs
  test/console/graphql/mutations/deployments/cluster_mutations_test.exs
  test/console/graphql/queries/deployments/cluster_queries_test.exs
  test/support/factory.ex
Labels: enhancement

#1749 chore: bump console kas/dashboard helm chart versions
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.100.tgz
  charts/console/charts/controller-0.0.101.tgz
  charts/console/charts/kas-0.1.0.tgz
  charts/console/charts/kas-0.1.1.tgz
  charts/console/charts/kubernetes-dashboard-7.10.0.tgz
  charts/console/charts/kubernetes-dashboard-7.10.1.tgz
  plural/helm/console/Chart.lock
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/controller-0.0.101.tgz
  plural/helm/console/charts/controller-0.0.99.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.10.0.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.10.1.tgz
  plural/helm/kas/Chart.yaml
Labels: enhancement

#1757 feat(client): add cluster registration queries
  go/client/client.go
  go/client/graph/edge.graphql
Labels: enhancement

#1755 Release ai-proxy v1.2.0
  assets/src/generated/graphql.ts
  charts/ai-proxy/Chart.yaml
  lib/console/deployments/clusters.ex
  lib/console/deployments/init.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  schema/schema.graphql
  test/console/deployments/init_test.exs
  test/console/graphql/queries/deployments/cluster_queries_test.exs
Labels: release

#1758 feat: add bootstraptoken controller
  charts/controller/crds/deployments.plural.sh_bootstraptokens.yaml
  go/client/client.go
  go/client/graph/bootstraptoken.graphql
  go/controller/api/v1alpha1/bootstraptoken_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_bootstraptokens.yaml
  go/controller/config/rbac/role.yaml
  go/controller/config/samples/bootstraptoken.yaml
  go/controller/docs/api.md
  go/controller/internal/client/bootstraptoken.go
  go/controller/internal/client/console.go
  go/controller/internal/controller/bootstraptoken_controller.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  go/controller/internal/types/reconciler.go
  plural/helm/console/crds/deployments.plural.sh_bootstraptokens.yaml
Labels: enhancement

#1759 bump console rapid chart
  charts/console-rapid/Chart.lock
  charts/console-rapid/Chart.yaml
  charts/console-rapid/charts/controller-0.0.101.tgz
  charts/console-rapid/charts/flux2-2.11.1.tgz
  charts/console-rapid/charts/flux2-2.14.1.tgz
  charts/console-rapid/charts/kas-0.1.0.tgz
  charts/console-rapid/charts/kas-0.1.1.tgz
  charts/console-rapid/charts/kubernetes-dashboard-7.10.0.tgz
  charts/console-rapid/charts/kubernetes-dashboard-7.10.1.tgz
Labels: release

#1761 add overview tab to cost management
  assets/package.json
  assets/src/components/cd/cluster/ClusterInsightsComponents.tsx
  assets/src/components/cd/logs/LogsCard.tsx
  assets/src/components/cd/logs/LogsTable.tsx
  assets/src/components/cost-management/ClusterUsagesTableCols.tsx
  assets/src/components/cost-management/details/ClusterScalingRecsTableCols.tsx
  assets/src/components/cost-management/details/CostManagementDetails.tsx
  assets/src/components/cost-management/details/CostManagementDetailsNamespaces.tsx
  assets/src/components/cost-management/details/CostManagementDetailsOverview.tsx
  assets/src/components/cost-management/details/CostTimeSeriesGraph.tsx
  assets/src/components/hooks/useNavBlocker.tsx
  assets/src/components/utils/AiInsights.tsx
  assets/src/components/utils/Graph.tsx
  assets/src/components/utils/layout/FullHeightTableWrap.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/costManagement.graphql
  assets/src/routes/costManagementRoutes.tsx
  assets/src/routes/costManagementRoutesConsts.tsx
  assets/src/theme.ts
  assets/yarn.lock
Labels: enhancement, frontend

#1762 feat: add machine id to cluster registration queries
  go/client/client.go
  go/client/graph/edge.graphql
Labels: enhancement

#1763 Add cluster/project pr automation config types
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_customstackruns.yaml
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/prautomation_types.go
  go/controller/config/crd/bases/deployments.plural.sh_customstackruns.yaml
  go/controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  go/controller/docs/api.md
  lib/console/schema/embeds.ex
  plural/helm/console/crds/deployments.plural.sh_customstackruns.yaml
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
  schema/schema.graphql
Labels: enhancement

#1764 fix: project controller trying to delete readonly project
  go/controller/internal/controller/project_controller.go
Labels: bug-fix

#1765 add ui for cluster/project pr automation config types
  AGENT_VERSION
  assets/src/components/cd/utils/ClusterHandleSelector.tsx
  assets/src/components/layout/Header.tsx
  assets/src/components/layout/HeaderProjectSelect.tsx
  assets/src/components/pr/automations/CreatePrModal.tsx
  assets/src/components/pr/automations/PrConfigurationInput.tsx
  assets/src/components/settings/notifications/routers/NotificationRouterConfigurationInput.tsx
  assets/src/components/utils/ProjectSelector.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  lib/console/schema/cluster.ex
Labels: enhancement, frontend

#1766 Log Enabling Fix
  assets/src/components/contexts/DeploymentSettingsContext.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdGlobalSettings.graphql
  config/prod.exs
  lib/console.ex
  lib/console/ai/cron.ex
  lib/console/deployments/clusters.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/global.ex
  lib/console/deployments/services.ex
  lib/console/deployments/stacks.ex
  lib/console/schema/cluster.ex
  test/console/console_test.exs
  test/console/deployments/global_test.exs
Labels: enhancement, hotfix

#1769 Add validations for project/cluster pr config types
  lib/console/deployments/pr/validation.ex
  test/console/deployments/git_test.exs
Labels: enhancement, hotfix

#1772 extend GetServiceDeploymentForAgent with the cluster distro
  go/client/client.go
  go/client/graph/deployment.graphql
Labels: enhancement

#1771 Tie stack jwts to the lifecycle of a stack run
  assets/src/generated/graphql.ts
  go/client/client.go
  go/client/models_gen.go
  lib/console/deployments/stacks.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/guardian.ex
  lib/console/schema/cluster_registration.ex
  lib/console/schema/stack.ex
  priv/repo/migrations/20250120165507_add_machine_id_uniq_constraint.exs
  schema/schema.graphql
  test/console/deployments/clusters_test.exs
  test/console/deployments/stacks_test.exs
Labels: enhancement

#1773 Bootstrap tokens should be able to query deploy tokens
  lib/console/deployments/policies/bootstrap_policies.ex
  lib/console/deployments/policies/policies.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  test/console/deployments/policies/bootstrap_policies_test.exs
  test/console_web/controllers/gql_test.exs
Labels: enhancement

#1776 feat: Edge view
  assets/src/components/cd/services/TagSelection.tsx
  assets/src/components/commandpalette/commands.ts
  assets/src/components/edge/CompleteClusterRegistrationModal.tsx
  assets/src/components/edge/Edge.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/edge.graphql
  assets/src/graph/users.graphql
  assets/src/routes/consoleRoutes.tsx
  assets/src/routes/edgeRoutes.tsx
Labels: enhancement

#1775 Minor bugfixes
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_globalservices.yaml
  charts/controller/crds/deployments.plural.sh_managednamespaces.yaml
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  go/client/models_gen.go
  go/controller/api/v1alpha1/prautomation_types.go
  go/controller/api/v1alpha1/servicedeployment_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_globalservices.yaml
  go/controller/config/crd/bases/deployments.plural.sh_managednamespaces.yaml
  go/controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  go/controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  go/controller/docs/api.md
  go/controller/internal/controller/common.go
  go/controller/internal/controller/servicedeployment_controller.go
  lib/console/deployments/cron.ex
  lib/console/graphql/deployments/git.ex
  lib/console/schema/pr_automation.ex
  plural/helm/console/crds/deployments.plural.sh_globalservices.yaml
  plural/helm/console/crds/deployments.plural.sh_managednamespaces.yaml
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
  schema/schema.graphql
Labels: enhancement

#1785 Don't validate optional fields
  lib/console/deployments/pr/validation.ex
Labels: bug-fix

#1788 add k8s dashboard link to cronjob service components
  assets/src/components/component/ComponentDetails.tsx
  assets/src/components/component/info/CronJob.tsx
  assets/src/components/kubernetes/workloads/Job.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/graph/cdServices.graphql
  assets/src/graph/kubernetes/cronJob.graphql
Labels: enhancement, frontend

#1779 fix: prautomation type
  go/controller/api/v1alpha1/prautomation_types.go
Labels: bug-fix

#1778 Implement cloud addon scraping gql CRUD
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/deployments/clusters.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/schema/cloud_addon.ex
  lib/console/schema/cluster.ex
  priv/repo/migrations/20250123223446_add_cloud_addons.exs
  schema/schema.graphql
  test/console/graphql/mutations/deployments/cluster_mutations_test.exs
Labels: enhancement

#1774 use secretKeyRefs for helm repository
  charts/controller/crds/deployments.plural.sh_helmrepositories.yaml
  charts/controller/crds/deployments.plural.sh_observers.yaml
  go/controller/api/v1alpha1/helmrepository_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_helmrepositories.yaml
  go/controller/config/crd/bases/deployments.plural.sh_observers.yaml
  go/controller/config/samples/helm_repository.yaml
  go/controller/internal/controller/helmrepository_attributes.go
  go/controller/internal/controller/helmrepository_controller.go
  go/controller/internal/controller/helmrepository_test.go
  go/controller/internal/controller/observer_controller.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  plural/helm/console/crds/deployments.plural.sh_helmrepositories.yaml
  plural/helm/console/crds/deployments.plural.sh_observers.yaml
Labels: enhancement

#1777 new alert views
  assets/src/components/ai/AITableEntry.tsx
  assets/src/components/cd/cluster/Cluster.tsx
  assets/src/components/cd/cluster/ClusterAlerts.tsx
  assets/src/components/cd/cluster/pod/PodContainers.tsx
  assets/src/components/cd/logs/LogContextPanel.tsx
  assets/src/components/cd/services/service/ServiceAlerts.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/security/vulnerabilities/VulnDetailExpanded.tsx
  assets/src/components/security/vulnerabilities/VulnReportDetails.tsx
  assets/src/components/utils/AlertsTable.tsx
  assets/src/components/utils/AlertsTableExpander.tsx
  assets/src/components/utils/table/StackedText.tsx
  assets/src/components/utils/table/useFetchPaginatedData.tsx
  assets/src/components/utils/typography/Text.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/alerts.graphql
  assets/src/graph/cdClusters.graphql
  assets/src/graph/cdServices.graphql
  assets/src/routes/cdRoutes.tsx
  assets/src/routes/cdRoutesConsts.tsx
Labels: enhancement, frontend

#1793 fix: bootstrap token status not handled properly
  go/controller/internal/controller/bootstraptoken_controller.go
Labels: bug-fix

#1794 feat: add default plural=edge tag when registering edge devices
  assets/src/components/edge/CompleteClusterRegistrationModal.tsx
Labels: enhancement

#1796 feat: update saveUpdateInsights mutation
  go/client/client.go
  go/client/graph/upgradeinsights.graphql
Labels: enhancement

#1801 Fix gate resources schema
  AGENT_VERSION
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/deployments/compatibilities/cloud_addons.ex
  lib/console/graphql/deployments/pipeline.ex
  schema/schema.graphql
Labels: bug-fix

#1802 add frontend filtering to service components
  assets/src/components/cd/services/service/ServiceComponents.tsx
  assets/src/components/cd/services/service/component/ComponentList.tsx
  assets/src/components/cd/services/service/component/Components.tsx
  assets/src/components/kubernetes/common/DataSelect.tsx
  assets/src/components/kubernetes/customresources/CustomResourceDefinition.tsx
  assets/src/components/utils/IconExpander.tsx
  assets/src/components/utils/layout/ResponsiveLayoutContentContainer.tsx
  assets/src/routes/kubernetesRoute.tsx
Labels: enhancement, frontend

#1813 Add Cluster ISO Image CRUD gql
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/deployments/clusters.ex
  lib/console/deployments/policies/bootstrap_policies.ex
  lib/console/deployments/policies/rbac.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/schema/cluster_iso_image.ex
  priv/repo/migrations/20250128165205_add_cluster_isos.exs
  schema/schema.graphql
  test/console/deployments/clusters_test.exs
  test/console/graphql/mutations/deployments/cluster_mutations_test.exs
  test/console/graphql/queries/deployments/cluster_queries_test.exs
  test/support/factory.ex
Labels: enhancement

#1805 enhancement: Sync K8s versions
  .dockerignore
  .github/workflows/k8s-versions-updater.yaml
  .gitignore
  Makefile
Labels: enhancement

#1815 small tweaks/fixes
  assets/src/components/cd/logs/LogsCard.tsx
  assets/src/components/cd/logs/LogsTable.tsx
  assets/src/components/cost-management/CostManagement.tsx
  assets/src/components/cost-management/details/CostManagementDetails.tsx
  assets/src/components/cost-management/details/CostManagementDetailsNamespaces.tsx
  assets/src/components/cost-management/details/CostManagementDetailsOverview.tsx
  assets/src/components/cost-management/details/CostManagementDetailsRecommendations.tsx
  assets/src/components/cost-management/details/CostTimeSeriesGraph.tsx
Labels: bug-fix, frontend

#1818 Add query to aggregate vuln reports by cluster
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/graphql.ex
  lib/console/graphql/deployments/git.ex
  lib/console/graphql/deployments/policy.ex
  lib/console/graphql/deployments/service.ex
  lib/console/graphql/resolvers/dataloader.ex
  lib/console/graphql/resolvers/deployments/policy.ex
  lib/console/schema/cluster_scaling_recommendation.ex
  lib/console/schema/pr_automation.ex
  lib/console/schema/service.ex
  lib/console/schema/vulnerability_report.ex
  schema/schema.graphql
  test/console/graphql/queries/deployments/policy_queries_test.exs
Labels: enhancement

#1819 Make clusterRefs mutable
  charts/controller/crds/deployments.plural.sh_servicedeployments.yaml
  go/controller/api/v1alpha1/servicedeployment_types.go
  go/controller/config/crd/bases/deployments.plural.sh_servicedeployments.yaml
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  plural/helm/console/crds/deployments.plural.sh_servicedeployments.yaml
Labels: enhancement

#1820 add ui for observability webhooks settings
  assets/package.json
  assets/src/components/settings/global/observability/EditObservabilityWebhook.tsx
  assets/src/components/settings/global/observability/Observability.tsx
  assets/src/components/settings/global/observability/ObservabilityProviders.tsx
  assets/src/components/settings/global/observability/ObservabilityProvidersColumns.tsx
  assets/src/components/settings/global/observability/ObservabilityWebhooks.tsx
  assets/src/components/settings/global/observability/ObservabilityWebhooksColumns.tsx
  assets/src/components/utils/CopyButton.tsx
  assets/src/components/utils/SubTabs.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdGlobalSettings.graphql
  assets/src/routes/settingsRoutes.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#1821 feat: add tabs to edge view
  assets/src/components/edge/Edge.tsx
  assets/src/components/edge/clusters/Clusters.tsx
  assets/src/components/edge/clusters/CompleteClusterRegistrationModal.tsx
  assets/src/components/edge/context.tsx
  assets/src/components/edge/hooks.ts
  assets/src/components/edge/images/Images.tsx
  assets/src/components/edge/images/hooks.ts
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/routes/edgeRoutes.tsx
Labels: enhancement

#1825 feat: extend prautomation crd to support condition field
  charts/console-rapid/charts/controller-0.0.104.tgz
  charts/console-rapid/charts/kas-0.1.1.tgz
  charts/console/charts/controller-0.0.104.tgz
  charts/console/charts/kas-0.1.1.tgz
  charts/controller/crds/deployments.plural.sh_prautomations.yaml
  go/controller/api/v1alpha1/prautomation_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_prautomations.yaml
  go/controller/docs/api.md
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  plural/helm/console/charts/controller-0.0.104.tgz
  plural/helm/console/crds/deployments.plural.sh_prautomations.yaml
Labels: enhancement

#1814 add security overview tab
  assets/src/components/cd/services/service/component/Components.tsx
  assets/src/components/cost-management/CostManagement.tsx
  assets/src/components/cost-management/CostManagementTreeMap.tsx
  assets/src/components/cost-management/details/CostManagementDetailsNamespaces.tsx
  assets/src/components/cost-management/details/CostTimeSeriesGraph.tsx
  assets/src/components/home/CustomLegend.tsx
  assets/src/components/home/clusteroverview/ClusterOverviewCard.tsx
  assets/src/components/home/clusteroverview/ClusterOverviewChart.tsx
  assets/src/components/home/violations/ConstraintViolationsChart.tsx
  assets/src/components/kubernetes/common/NamespaceMultiSelect.tsx
  assets/src/components/security/Security.tsx
  assets/src/components/security/overview/SecurityOverview.tsx
  assets/src/components/security/overview/SecurityOverviewCharts.tsx
  assets/src/components/security/overview/useSecurityOverviewChartsData.tsx
  assets/src/components/security/policies/Policies.tsx
  assets/src/components/security/policies/PoliciesViolationsGauge.tsx
  assets/src/components/security/policies/usePolicyChartsData.tsx
  assets/src/components/security/vulnerabilities/VulnReports.tsx
  assets/src/components/utils/Graph.tsx
  assets/src/components/utils/PieChart.tsx
  assets/src/components/utils/RadialBarChart.tsx
  assets/src/components/utils/TreeMap.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/vulnerabilities.graphql
  assets/src/routes/securityRoutes.tsx
  assets/src/routes/securityRoutesConsts.tsx
Labels: enhancement, frontend

#1829 add deploymentRepositoryRef and scaffoldsRepositoryRef
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  go/controller/internal/controller/common.go
  go/controller/internal/controller/deploymentsettings_controller.go
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
Labels: enhancement

#1832 add new query PagedClusterServicesForAgent
  go/client/client.go
  go/client/graph/deployment.graphql
  go/client/graph/models.graphql
Labels: enhancement

#1830 fix: Set widths for upgrade insights columns
  assets/src/components/cd/clusters/UpgradeInsights.tsx
Labels: bug-fix

#1833 scaling recommendation tweaks
  assets/src/components/cd/services/service/ServiceAlerts.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/ServiceScalingRecs.tsx
  assets/src/components/cost-management/details/ClusterScalingRecsTableCols.tsx
  assets/src/components/cost-management/details/CostManagementDetailsRecommendations.tsx
  assets/src/components/security/Security.tsx
  assets/src/components/security/policies/Policies.tsx
  assets/src/components/security/policies/PoliciesFilter.tsx
  assets/src/components/security/policies/PoliciesTable.tsx
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/cdServices.graphql
  assets/src/graph/costManagement.graphql
  assets/src/routes/cdRoutes.tsx
Labels: enhancement, frontend

#1831 fix: Deselect namespace on cluster change
  assets/src/components/kubernetes/Cluster.tsx
  assets/src/components/kubernetes/common/DataSelect.tsx
Labels: bug-fix

#1826 Prep release v0.11.0
  AGENT_VERSION
  Dockerfile
  lib/console/deployments/pr/validation.ex
  lib/console/deployments/settings.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/schema/service.ex
  test/console/graphql/queries/deployments/cluster_queries_test.exs
Labels: enhancement

#1822 enhancement: Minor changes to the edge tab
  assets/package.json
  assets/src/components/commandpalette/commands.ts
  assets/src/components/edge/Edge.tsx
  assets/src/components/edge/clusters/Clusters.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/yarn.lock
Labels: enhancement

#1824 feat: bump console chart dependencies
  charts/console-rapid/Chart.lock
  charts/console-rapid/Chart.yaml
  charts/console-rapid/charts/controller-0.0.104.tgz
  charts/console-rapid/charts/kas-0.1.1.tgz
  charts/console-rapid/charts/kubernetes-dashboard-7.10.1.tgz
  charts/console-rapid/charts/kubernetes-dashboard-7.10.3.tgz
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.104.tgz
  charts/console/charts/kas-0.1.1.tgz
  charts/console/charts/kubernetes-dashboard-7.10.1.tgz
  charts/console/charts/kubernetes-dashboard-7.10.3.tgz
  plural/helm/console/Chart.lock
  plural/helm/console/Chart.yaml
  plural/helm/console/charts/controller-0.0.104.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.10.1.tgz
  plural/helm/console/charts/kubernetes-dashboard-7.10.3.tgz
Labels: enhancement
