Repository pluralsh/console, pull requests merged in 2025-02, with the labels that each got.

#1827 Elasticsearch docker test
  config/test.exs
  docker-compose.yml
  lib/console/logs/provider/elastic.ex
  lib/mix/tasks/elasticsearch_setup.ex
  lib/mix/tasks/elasticsearch_teardown.ex
  mix.exs
  mix.lock
  test/console/graphql/queries/observability_queries_test.exs
  test/support/elasticsearch_utils.ex
Labels: enhancement

#1840 Add schema to support syncing namespaces for important controllers
  assets/src/components/layout/Sidebar.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  go/client/models_gen.go
  lib/console/deployments/clusters.ex
  lib/console/deployments/providers/versions.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/logs/provider/elastic.ex
  lib/console/logs/query.ex
  lib/console/schema/cluster.ex
  lib/console/schema/operational_layout.ex
  lib/mix/tasks/elasticsearch_setup.ex
  priv/repo/migrations/20250203141931_add_operational_layout.exs
  schema/schema.graphql
  static/k8s-versions/eks.json
  test/console/deployments/clusters_test.exs
Labels: enhancement

#1847 chore: add ListClusterMinimalStacks query
  go/client/client.go
  go/client/graph/stack.graphql
Labels: enhancement

#1849 fix: broken readonly feature in project and catalog controllers
  go/controller/internal/controller/bootstraptoken_controller.go
  go/controller/internal/controller/catalog_controller.go
  go/controller/internal/controller/project_controller.go
Labels: bug-fix

#1845 Begin working on log evidence for Plural AI
  .github/workflows/k8s-versions-updater.yaml
  assets/src/generated/graphql.ts
  charts/console/templates/_helpers.tpl
  config/config.exs
  config/test.exs
  go/client/models_gen.go
  lib/console.ex
  lib/console/ai/evidence.ex
  lib/console/ai/evidence/base.ex
  lib/console/ai/evidence/cluster.ex
  lib/console/ai/evidence/cluster_insight_component.ex
  lib/console/ai/evidence/context.ex
  lib/console/ai/evidence/logs.ex
  lib/console/ai/evidence/service.ex
  lib/console/ai/evidence/service_component.ex
  lib/console/ai/evidence/stack.ex
  lib/console/ai/evidence/stack_run.ex
  lib/console/ai/evidence/stack_state.ex
  lib/console/ai/memoizer.ex
  lib/console/ai/tool.ex
  lib/console/ai/tools/logging.ex
  lib/console/deployments/clusters.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/configuration.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/schema/ai_insight.ex
  lib/console/schema/ai_insight_evidence.ex
  lib/mix/tasks/elasticsearch/down.ex
  lib/mix/tasks/elasticsearch/up.ex
  lib/mix/tasks/elasticsearch_setup.ex
  lib/mix/tasks/elasticsearch_teardown.ex
  mix.exs
  priv/repo/migrations/20250203220837_add_insight_evidence.exs
  priv/tools/logging.json
  rel/runtime.exs
  schema/schema.graphql
  test/console/ai/cron_test.exs
  test/console/graphql/queries/observability_queries_test.exs
  test/support/elasticsearch_utils.ex
Labels: enhancement

#1848 chore: bump CLI version in console dockerfile
  Dockerfile
Labels: dependencies

#1855 extend RegisterRuntimeServices mutation
  go/client/client.go
  go/client/graph/cluster.graphql
  go/client/graph/edge.graphql
Labels: enhancement

#1853 add typing to service components
  assets/eslint.config.mjs
  assets/src/components/cd/cluster/Cluster.tsx
  assets/src/components/cd/cluster/pod/PodsList.tsx
  assets/src/components/cd/services/component/ServiceComponent.tsx
  assets/src/components/cd/services/service/ServiceComponents.tsx
  assets/src/components/cd/services/service/ServiceDetails.tsx
  assets/src/components/cd/services/service/component/ComponentCard.tsx
  assets/src/components/cd/services/service/component/ComponentList.tsx
  assets/src/components/cd/services/service/component/misc.tsx
  assets/src/components/component/ComponentDetails.tsx
  assets/src/components/component/ComponentDryRun.tsx
  assets/src/components/component/ComponentEvents.tsx
  assets/src/components/component/ComponentInfo.tsx
  assets/src/components/component/ComponentMetadata.tsx
  assets/src/components/component/ComponentRaw.tsx
  assets/src/components/component/ViewLogsButton.tsx
  assets/src/components/component/info/Canary.tsx
  assets/src/components/component/info/Certificate.tsx
  assets/src/components/component/info/CronJob.tsx
  assets/src/components/component/info/Daemonset.tsx
  assets/src/components/component/info/Deployment.tsx
  assets/src/components/component/info/Ingress.tsx
  assets/src/components/component/info/Job.tsx
  assets/src/components/component/info/PluralServiceDeployment.tsx
  assets/src/components/component/info/Pods.tsx
  assets/src/components/component/info/Service.tsx
  assets/src/components/component/info/StatefulSet.tsx
  assets/src/components/component/useFetchComponentDetails.tsx
  assets/src/components/contexts.tsx
  assets/src/components/layout/Sidebar.tsx
  assets/src/components/utils/EventsTable.tsx
  assets/src/generated/graphql-kubernetes.ts
  assets/src/generated/graphql-plural.ts
  assets/src/generated/graphql.ts
  assets/src/graph/kubernetes/argoRollout.graphql
  assets/src/graph/kubernetes/canary.graphql
  assets/src/graph/kubernetes/certificate.graphql
  assets/src/graph/kubernetes/cronJob.graphql
  assets/src/graph/kubernetes/daemonset.graphql
  assets/src/graph/kubernetes/deployment.graphql
  assets/src/graph/kubernetes/ingress.graphql
  assets/src/graph/kubernetes/job.graphql
  assets/src/graph/kubernetes/service.graphql
  assets/src/graph/kubernetes/statefulSet.graphql
  assets/src/graph/users.graphql
Labels: enhancement, frontend

#1854 Fix pipeline gate rerunning
  .github/workflows/k8s-versions-updater.yaml
  lib/console/deployments/pipelines.ex
  test/console/deployments/pipelines_test.exs
  utils/compatibility/utils.py
Labels: bug-fix

#1851 Minor chart changes
  charts/console-rapid/Chart.yaml
  charts/console/Chart.yaml
  charts/console/templates/migration.yaml
  charts/console/templates/secrets.yaml
  plural/helm/kas/Chart.yaml
  plural/helm/kas/templates/deployment.yaml
  plural/helm/kas/templates/secrets.yaml
  plural/helm/kas/values.yaml
Labels: enhancement

#1859 add query GetClusterIsoImage
  go/client/client.go
  go/client/graph/edge.graphql
Labels: enhancement

#1860 feat(client): add cluster audit log mutation
  go/client/client.go
  go/client/graph/audit.graphql
Labels: enhancement

#1846 John/prod 3109 add bedrock backend for ai proxy
  go/ai-proxy/api/bedrock/bedrock.go
  go/ai-proxy/api/provider.go
  go/ai-proxy/args/args.go
  go/ai-proxy/go.mod
  go/ai-proxy/go.sum
  go/ai-proxy/main.go
  go/ai-proxy/proxy/bedrock/bedrock.go
  go/ai-proxy/proxy/proxy.go
  go/ai-proxy/test/bedrock/bedrock_test.go
  go/ai-proxy/test/helpers/common.go
Labels: enhancement

#1856 Debug ai cost management prs, fix cluster audit logs
  assets/src/generated/graphql.ts
  charts/ai-proxy/Chart.yaml
  charts/ai-proxy/templates/deployment.yaml
  charts/ai-proxy/templates/serviceaccount.yaml
  charts/ai-proxy/values.yaml
  go/client/models_gen.go
  lib/console/graphql/deployments/cluster.ex
  lib/console/schema/cluster_audit_log.ex
  priv/repo/migrations/20250206161947_add_log_response_code.exs
  schema/schema.graphql
  test/console/graphql/queries/deployments/cluster_queries_test.exs
Labels: enhancement

#1863 make notifications panel scrollable
  assets/src/components/cd/logs/LogContextPanel.tsx
  assets/src/components/cd/logs/LogsCard.tsx
  assets/src/components/notifications/NotificationsLauncher.tsx
  assets/src/components/notifications/NotificationsPanel.tsx
Labels: bug-fix, frontend

#1862 Failing service demo
  .github/workflows/demo-cd.yaml
  go/demo/flaky-service/Dockerfile
  go/demo/flaky-service/Dockerfile.sidecar
  go/demo/flaky-service/README.md
  go/demo/flaky-service/api/api_server.go
  go/demo/flaky-service/api/behavior_modifiers.go
  go/demo/flaky-service/api_caller.sh
  go/demo/flaky-service/args/args.go
  go/demo/flaky-service/docker-compose.yml
  go/demo/flaky-service/go.mod
  go/demo/flaky-service/go.sum
  go/demo/flaky-service/internal/log/log.go
  go/demo/flaky-service/main.go
  go/demo/flaky-service/metrics/prometheus_metric_server.go
  go/go.work
  test-apps/flaky-service/flaky-service-monitoring.yaml
  test-apps/flaky-service/flaky-service.yaml
Labels: enhancement

#1858 improve DAG views
  assets/package.json
  assets/src/components/cd/pipelines/PipelineContexts.tsx
  assets/src/components/cd/pipelines/PipelineDetails.tsx
  assets/src/components/cd/pipelines/PipelineGraph.tsx
  assets/src/components/cd/pipelines/nodes/BaseNode.tsx
  assets/src/components/cd/pipelines/nodes/StageNode.tsx
  assets/src/components/cd/pipelines/utils/nodeLayouter.tsx
  assets/src/components/cd/services/ServicesTreeDiagram.tsx
  assets/src/components/component/ComponentTree.tsx
  assets/src/components/component/tree/ComponentTreeGraph.tsx
  assets/src/components/component/tree/getTreeNodesAndEdges.tsx
  assets/src/components/stacks/state/StackStateGraph.tsx
  assets/src/components/utils/reactflow/graph.tsx
  assets/src/components/utils/reactflow/nodes.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#1887 fix(console): vertical scroll on cluster nodes list
  assets/src/components/cd/cluster/ClusterNodes.tsx
Labels: bug-fix

#1817 enhancement: Console controller error handling improvements
  charts/controller/crds/deployments.plural.sh_bootstraptokens.yaml
  go/controller/api/v1alpha1/bootstraptoken_types.go
  go/controller/config/crd/bases/deployments.plural.sh_bootstraptokens.yaml
  go/controller/config/samples/catalog.yaml
  go/controller/config/samples/deployments_v1alpha1_catalog.yaml
  go/controller/config/samples/managed_namespace.yaml
  go/controller/docs/api.md
  go/controller/internal/controller/bootstraptoken_controller.go
  go/controller/internal/controller/catalog_controller.go
  go/controller/internal/controller/cluster_controller.go
  go/controller/internal/controller/clusterrestore_controller.go
  go/controller/internal/controller/common.go
  go/controller/internal/controller/customstackrun_controller.go
  go/controller/internal/controller/deploymentsettings_controller.go
  go/controller/internal/controller/generatedsecret_controller.go
  go/controller/internal/controller/gitrepository_controller.go
  go/controller/internal/controller/globalservice_controller.go
  go/controller/internal/controller/helmrepository_controller.go
  go/controller/internal/controller/infrastructurestack_controller.go
  go/controller/internal/controller/managednamespace_controller.go
  go/controller/internal/controller/notificationrouter_controller.go
  go/controller/internal/controller/notificationsink_controller.go
  go/controller/internal/controller/observabilityprovider_controller.go
  go/controller/internal/controller/observer_controller.go
  go/controller/internal/controller/oidcprovider_controller.go
  go/controller/internal/controller/pipeline_controller.go
  go/controller/internal/controller/prautomation_controller.go
  go/controller/internal/controller/project_controller.go
  go/controller/internal/controller/provider_controller.go
  go/controller/internal/controller/scmconnection_controller.go
  go/controller/internal/controller/scope.go
  go/controller/internal/controller/service_account_controller.go
  go/controller/internal/controller/servicedeployment_controller.go
  go/controller/internal/controller/stackdefinition_controller.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  plural/helm/console/crds/deployments.plural.sh_bootstraptokens.yaml
Labels: enhancement

#1878 Add Alert insights
  assets/src/generated/graphql.ts
  config/prod.exs
  go/client/models_gen.go
  lib/console/ai/cron.ex
  lib/console/ai/evidence/alert.ex
  lib/console/ai/evidence/component/certificate.ex
  lib/console/ai/evidence/component/resource.ex
  lib/console/ai/evidence/logs.ex
  lib/console/ai/pubsub/consumer.ex
  lib/console/ai/pubsub/protocol.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/events.ex
  lib/console/deployments/observability.ex
  lib/console/deployments/pubsub/protocols/notifiable.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/deployments/observability.ex
  lib/console/schema/ai_insight.ex
  lib/console/schema/alert.ex
  lib/kube/client.ex
  lib/kube/models.ex
  priv/notifications/plural/alert.insight.json.eex
  priv/notifications/slack/alert.insight.json.eex
  priv/notifications/teams/alert.insight.json.eex
  priv/repo/migrations/20250209172814_add_alert_insights.exs
  schema/schema.graphql
  static/crds/certificate-request.yaml
  test/console/ai/cron_test.exs
  test/console/ai/pubsub/consumer_test.exs
  test/console/services/plural_test.exs
  test/console/utils/path_test.exs
  test/support/test_helpers.ex
Labels: enhancement

#1894 bump deps
  assets/package.json
  assets/src/components/component/tree/ComponentTreeNode.tsx
  assets/src/components/kubernetes/workloads/Pods.tsx
  assets/src/components/profile/AccessTokens.tsx
  assets/src/components/profile/AccessTokensCreateScope.tsx
  assets/src/components/settings/notifications/sinks/NotificationSinksColumns.tsx
  assets/src/components/stacks/state/StackStateGraphNode.tsx
  assets/src/components/utils/AiInsights.tsx
  assets/vitest.config.ts
  assets/yarn.lock
Labels: dependencies, frontend

#1891 Fix alert schema and logs ts bugs
  AGENT_VERSION
  config/prod.exs
  lib/console/ai/evidence/alert.ex
  lib/console/ai/evidence/base.ex
  lib/console/ai/evidence/cluster.ex
  lib/console/ai/evidence/cluster_insight_component.ex
  lib/console/ai/evidence/component/certificate.ex
  lib/console/ai/evidence/component/resource.ex
  lib/console/ai/evidence/context.ex
  lib/console/ai/evidence/logs.ex
  lib/console/ai/evidence/service_component.ex
  lib/console/ai/evidence/stack.ex
  lib/console/ai/evidence/stack_run.ex
  lib/console/ai/evidence/stack_state.ex
  lib/console/ai/fixer/base.ex
  lib/console/ai/fixer/service.ex
  lib/console/cached/cluster_nodes.ex
  lib/console/deployments/clusters.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/helm/agent.ex
  lib/console/deployments/helm/agent_cache.ex
  lib/console/graphql/kubernetes/ingress.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/graphql/resolvers/kubernetes.ex
  lib/console/schema/alert.ex
  test/console/deployments/helm/agent_test.exs
Labels: enhancement

#1886 feat: edge images view
  assets/src/components/cd/services/service/ServiceSecrets.tsx
  assets/src/components/edge/hooks.ts
  assets/src/components/edge/images/Images.tsx
  assets/src/components/edge/images/hooks.ts
  assets/src/generated/graphql.ts
  assets/src/graph/edge.graphql
Labels: enhancement

#1861 feat: add cluster audit logs view to kubernetes dashboard
  assets/src/components/kubernetes/Navigation.tsx
  assets/src/components/kubernetes/audit/Audit.tsx
  assets/src/components/kubernetes/common/DataSelect.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/kubernetes.graphql
  assets/src/routes/kubernetesRoute.tsx
  assets/src/routes/kubernetesRoutesConsts.tsx
Labels: enhancement

#1898 ai updates
  assets/package.json
  assets/src/components/ai/AIPanelOverlay.tsx
  assets/src/components/ai/chatbot/AISuggestFix.tsx
  assets/src/components/ai/chatbot/AISuggestFixButton.tsx
  assets/src/components/ai/chatbot/ChatbotButton.tsx
  assets/src/components/ai/chatbot/ChatbotHeader.tsx
  assets/src/components/home/clusteroverview/ClusterOverviewTable.tsx
  assets/src/components/security/policies/PoliciesColumns.tsx
  assets/src/components/security/policies/PoliciesTable.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#1895 Prelease Fixes
  AGENT_VERSION
  Makefile
  charts/console-rapid/Chart.lock
  charts/console-rapid/Chart.yaml
  charts/console-rapid/charts/controller-0.0.105.tgz
  charts/console-rapid/charts/kas-0.1.1.tgz
  charts/console-rapid/charts/kas-0.1.3.tgz
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.105.tgz
  charts/console/charts/kas-0.1.1.tgz
  charts/console/charts/kas-0.1.3.tgz
  lib/console/ai/evidence/cluster_insight_component.ex
  lib/console/ai/evidence/context.ex
  lib/console/ai/evidence/logs.ex
  lib/console/ai/memoizer.ex
  lib/console/cached/cluster_nodes.ex
  lib/console/logs/query.ex
  plural/helm/console/charts/controller-0.0.105.tgz
  plural/helm/kas/Chart.yaml
  test/console/ai/cron_test.exs
  test/support/elasticsearch_utils.ex
  test/support/factory.ex
Labels: enhancement

#1905 fix make dependencies
  Makefile
Labels: enhancement, hotfix

#1908 replace moment with dayjs
  assets/package.json
  assets/src/components/ai/AITableEntry.tsx
  assets/src/components/billing/BillingLegacyUserMessage.tsx
  assets/src/components/billing/BillingSubscriptionProvider.tsx
  assets/src/components/cd/cluster/ClusterMetadata.tsx
  assets/src/components/cd/cluster/pod/PodContainers.tsx
  assets/src/components/cd/clusters/ClusterHealthChip.tsx
  assets/src/components/cd/clusters/UpgradeInsights.tsx
  assets/src/components/cd/globalServices/GlobalServicesColumns.tsx
  assets/src/components/cd/namespaces/NamespaceSidecar.tsx
  assets/src/components/cd/namespaces/NamespacesColumns.tsx
  assets/src/components/cd/services/ServiceRevisionColumns.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
  assets/src/components/cd/services/ServicesTreeDiagramNodes.tsx
  assets/src/components/cd/services/service/ServiceInsights.tsx
  assets/src/components/cd/services/service/ServiceRevisions.tsx
  assets/src/components/component/ComponentInsights.tsx
  assets/src/components/component/ComponentMetrics.tsx
  assets/src/components/kubernetes/common/ResourceOwner.tsx
  assets/src/components/kubernetes/common/utils.tsx
  assets/src/components/kubernetes/workloads/CronJob.tsx
  assets/src/components/kubernetes/workloads/Deployment.tsx
  assets/src/components/layout/Notification.tsx
  assets/src/components/notifications/Notification.tsx
  assets/src/components/profile/AccessTokens.tsx
  assets/src/components/security/policies/policy/details/PolicyDetails.tsx
  assets/src/components/settings/global/observability/ObservabilityProvidersColumns.tsx
  assets/src/components/settings/global/observability/ObservabilityWebhooksColumns.tsx
  assets/src/components/settings/usermanagement/webhooks/Webhook.tsx
  assets/src/components/stacks/insights/StackInsights.tsx
  assets/src/components/stacks/overview/StackMetadata.tsx
  assets/src/components/stacks/run/Sidecar.tsx
  assets/src/components/stacks/run/insights/StackRunInsights.tsx
  assets/src/components/stacks/runs/StackRunsEntry.tsx
  assets/src/components/utils/AiInsights.tsx
  assets/src/components/utils/RangePicker.tsx
  assets/src/utils/date.ts
  assets/src/utils/datetime.test.ts
  assets/src/utils/datetime.ts
  assets/src/utils/test-globals.ts
  assets/src/utils/time.ts
  assets/vite.config.ts
  assets/vitest.config.ts
  assets/yarn.lock
Labels: enhancement, frontend

#1915 fix k8s dashboard detail views width
  assets/src/components/kubernetes/common/ResourceDetails.tsx
Labels: enhancement, frontend

#1916 feat: Add network-observability-operator chart
  charts/network-observability-operator/.helmignore
  charts/network-observability-operator/Chart.yaml
  charts/network-observability-operator/crds/flows.netobserv.io_flowcollectors.yaml
  charts/network-observability-operator/crds/flows.netobserv.io_flowmetrics.yaml
  charts/network-observability-operator/templates/_helpers.tpl
  charts/network-observability-operator/templates/certificate.yaml
  charts/network-observability-operator/templates/configmap.yaml
  charts/network-observability-operator/templates/deployment.yaml
  charts/network-observability-operator/templates/roles.yaml
  charts/network-observability-operator/templates/serviceaccount.yaml
  charts/network-observability-operator/templates/services.yaml
  charts/network-observability-operator/values.yaml
Labels: enhancement

#1919 feat: extend infrastructure stack with violation/policy field
  go/client/client.go
  go/client/graph/stack.graphql
Labels: enhancement

#1920 fix: Move NOO CRDs to template directory
  charts/network-observability-operator/Chart.yaml
  charts/network-observability-operator/templates/flows.netobserv.io_flowcollectors.yaml
  charts/network-observability-operator/templates/flows.netobserv.io_flowmetrics.yaml
Labels: bug-fix

#1923 fix: Fix network-observability-operator chart
  charts/network-observability-operator/Chart.yaml
  charts/network-observability-operator/templates/flows.netobserv.io_flowcollectors.yaml
  charts/network-observability-operator/templates/flows.netobserv.io_flowmetrics.yaml
Labels: bug-fix

#1921 Don't set replicas env var in helper template
  .github/workflows/cron.yaml
  assets/src/generated/graphql.ts
  charts/console/templates/_helpers.tpl
  charts/console/templates/deployment.yaml
  charts/console/templates/migration.yaml
  config/config.exs
  config/test.exs
  lib/console/ai/policy.ex
  lib/console/ai/service.ex
  lib/console/cache.ex
  lib/console/deployments/clusters.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/global.ex
  lib/console/graphql/ai.ex
  lib/console/graphql/resolvers/ai.ex
  lib/console/schema/cluster.ex
  plural/helm/kas/templates/deployment.yaml
  plural/helm/kas/values.yaml
  priv/repo/migrations/20250218061443_optimization_indices.exs
  schema/schema.graphql
  static/addons/eks.yaml
  test/console/deployments/cron_test.exs
  test/console/graphql/queries/ai_queries_test.exs
Labels: bug-fix

#1926 enhancement(client): add upsert user mutation
  go/client/client.go
  go/client/graph/users.graphql
Labels: enhancement

#1924 Add alert sideloading, Scaling Improvements
  assets/src/generated/graphql.ts
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  config/config.exs
  config/prod.exs
  go/client/models_gen.go
  go/controller/api/v1alpha1/deploymentsettings_types.go
  go/controller/api/v1alpha1/zz_generated.deepcopy.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  lib/console/ai/provider.ex
  lib/console/application.ex
  lib/console/cached/cluster_nodes.ex
  lib/console/deployments/clusters.ex
  lib/console/deployments/cron.ex
  lib/console/deployments/git.ex
  lib/console/deployments/helm/agent_cache.ex
  lib/console/deployments/helm/cache.ex
  lib/console/deployments/local/cache.ex
  lib/console/deployments/local/server.ex
  lib/console/deployments/observer/runner.ex
  lib/console/deployments/stacks.ex
  lib/console/deployments/tar.ex
  lib/console/graphql/deployments/cluster.ex
  lib/console/graphql/deployments/settings.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/deployments.ex
  lib/console/graphql/resolvers/deployments/cluster.ex
  lib/console/schema/cluster.ex
  lib/console/schema/deployment_settings.ex
  lib/console/schema/stack.ex
  lib/console/schema/stack_violation_cause.ex
  lib/console_web/controllers/git_controller.ex
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
  priv/repo/migrations/20250219171335_add_filename_to_causes.exs
  schema/schema.graphql
  static/addons/eks.yaml
  utils/addons/main.py
Labels: enhancement

#1927 enhancement: Global service view enhancements
  .github/CODEOWNERS
  assets/src/components/cd/globalServices/GlobalService.tsx
  assets/src/components/cd/globalServices/details/GlobalService.tsx
  assets/src/components/cd/globalServices/details/GlobalServiceSidecar.tsx
  assets/src/components/cd/services/ServicesColumns.tsx
Labels: enhancement

#1930 remove honorable Flex components
  assets/package.json
  assets/src/components/cd/cluster/node/NodeEvents.tsx
  assets/src/components/cd/cluster/node/NodeMetadata.tsx
  assets/src/components/cd/cluster/node/NodeRaw.tsx
  assets/src/components/cd/cluster/pod/Pod.tsx
  assets/src/components/cd/cluster/pod/PodContainers.tsx
  assets/src/components/cd/cluster/pod/PodInfo.tsx
  assets/src/components/cd/cluster/pod/PodMetadata.tsx
  assets/src/components/cd/logs/LogsInfoPanel.tsx
  assets/src/components/cd/services/service/pod/Pod.tsx
  assets/src/components/cluster/ContainerStatuses.tsx
  assets/src/components/cluster/Gauges.tsx
  assets/src/components/cluster/LabelsAnnotations.tsx
  assets/src/components/cluster/TableElements.tsx
  assets/src/components/cluster/containers/ContainerShell.tsx
  assets/src/components/cluster/containers/ShellCommandEditor.tsx
  assets/src/components/cluster/nodes/ClusterMetrics.tsx
  assets/src/components/edge/clusters/Clusters.tsx
  assets/src/components/layout/Console.tsx
  assets/src/components/layout/Header.tsx
  assets/src/components/layout/Notification.tsx
  assets/src/components/layout/NotificationsPanel.tsx
  assets/src/components/layout/NotificationsPanelOverlay.tsx
  assets/src/components/login/Invite.tsx
  assets/src/components/login/Login.tsx
  assets/src/components/pr/scm/CreateScmWebhook.tsx
  assets/src/components/profile/Permissions.tsx
  assets/src/components/profile/Security.tsx
  assets/src/components/settings/audits/AuditsList.tsx
  assets/src/components/settings/usermanagement/groups/GroupEdit.tsx
  assets/src/components/settings/usermanagement/personas/PersonaActions.tsx
  assets/src/components/settings/usermanagement/personas/PersonaAttributesEdit.tsx
  assets/src/components/settings/usermanagement/roles/Roles.tsx
  assets/src/components/settings/usermanagement/webhooks/Webhook.tsx
  assets/src/components/settings/usermanagement/webhooks/Webhooks.tsx
  assets/src/components/stacks/run/Route.tsx
  assets/src/components/stacks/run/plan/Plan.tsx
  assets/src/components/stacks/run/progress/Progress.tsx
  assets/src/components/stacks/run/progress/Step.tsx
  assets/src/components/terminal/Terminal.tsx
  assets/src/components/terminal/TerminalThemeSelector.tsx
  assets/src/components/utils/CommandLog.tsx
  assets/src/components/utils/FractionalChip.tsx
  assets/src/components/utils/Metadata.tsx
  assets/src/components/utils/layout/ConsolePageTitle.tsx
  assets/src/components/utils/layout/ResponsiveLayoutContentContainer.tsx
  assets/src/components/utils/layout/ScrollablePage.tsx
  assets/yarn.lock
Labels: enhancement, frontend

#1933 Minor additional scaling tweaks
  lib/console/deployments/cron.ex
  lib/console/services/users.ex
Labels: enhancement

#1936 Fix console templates
  templates/values.yaml.liquid
  templates/values.yaml.tpl
Labels: bug-fix, hotfix

#1934 Support openai embeddings endpoints in ai proxy
  go/ai-proxy/api/bedrock/bedrock.go
  go/ai-proxy/api/openai/openai.go
  go/ai-proxy/api/provider.go
  go/ai-proxy/args/args.go
  go/ai-proxy/go.mod
  go/ai-proxy/go.sum
  go/ai-proxy/main.go
  go/ai-proxy/proxy/bedrock/embeddings.go
  go/ai-proxy/proxy/openai/embeddings.go
  go/ai-proxy/proxy/proxy.go
  go/ai-proxy/test/bedrock/bedrock_test.go
  go/ai-proxy/test/helpers/common.go
  go/ai-proxy/test/openai_standard/openai_standard_test.go
Labels: enhancement

#1938 feat: add security violations UI in the stack run view
  assets/src/components/security/vulnerabilities/VulnReportDetailsTableCols.tsx
  assets/src/components/stacks/overview/StackMetadata.tsx
  assets/src/components/stacks/run/Header.tsx
  assets/src/components/stacks/run/Sidecar.tsx
  assets/src/components/stacks/run/violations/ViolationExpansionPanel.tsx
  assets/src/components/stacks/run/violations/Violations.tsx
  assets/src/components/stacks/run/violations/columns.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/stacks.graphql
  assets/src/routes/stacksRoutes.tsx
  assets/src/routes/stacksRoutesConsts.tsx
Labels: enhancement

#1937 Add url to vendor the current agent chart
  .github/workflows/test.yaml
  AGENT_VERSION
  Dockerfile
  assets/src/components/login/OauthCallback.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/users.graphql
  config/config.exs
  config/test.exs
  go/client/client.go
  go/client/models_gen.go
  lib/console/application.ex
  lib/console/commands/plural.ex
  lib/console/deployments/init.ex
  lib/console/deployments/settings.ex
  lib/console/graphql/deployments/stack.ex
  lib/console/graphql/resolvers/user.ex
  lib/console/graphql/users.ex
  lib/console/services/base.ex
  lib/console/services/oauth.ex
  lib/console_web/controllers/git_controller.ex
  lib/console_web/router.ex
  lib/mix/tasks/agent.chart.ex
  mix.exs
  mix.lock
  priv/agent-chart.tgz
  rel/runtime.exs
  schema/schema.graphql
  test/console/deployments/clusters_test.exs
  test/console_web/controllers/git_controller_test.exs
Labels: enhancement

#1941 new log filter ui
  assets/package.json
  assets/src/components/cd/cluster/addon/ClusterCloudAddOnCompatibility.tsx
  assets/src/components/cd/logs/DateTimeFormInput.tsx
  assets/src/components/cd/logs/Logs.tsx
  assets/src/components/cd/logs/LogsCard.tsx
  assets/src/components/cd/logs/LogsFilters.tsx
  assets/src/components/cd/logs/LogsScrollIndicator.tsx
  assets/src/components/cd/logs/LogsTable.tsx
  assets/src/components/utils/IconExpander.tsx
  assets/src/utils/datetime.ts
  assets/yarn.lock
Labels: enhancement, frontend

#1942 fix: race condition in multiple reconcilers
  charts/controller/crds/deployments.plural.sh_deploymentsettings.yaml
  go/client/client.go
  go/client/models_gen.go
  go/controller/config/crd/bases/deployments.plural.sh_deploymentsettings.yaml
  go/controller/go.mod
  go/controller/go.sum
  go/controller/internal/client/catalog.go
  go/controller/internal/controller/bootstraptoken_controller.go
  go/controller/internal/controller/catalog_controller.go
  go/controller/internal/controller/catalog_controller_test.go
  go/controller/internal/controller/clusterrestore_controller.go
  go/controller/internal/controller/clusterrestoretrigger_controller.go
  go/controller/internal/controller/customstackrun_controller.go
  go/controller/internal/controller/deploymentsettings_controller.go
  go/controller/internal/controller/generatedsecret_controller.go
  go/controller/internal/controller/gitrepository_controller.go
  go/controller/internal/controller/infrastructurestack_controller.go
  go/controller/internal/controller/managednamespace_controller.go
  go/controller/internal/controller/namespace_credentials_controller.go
  go/controller/internal/controller/notificationrouter_controller.go
  go/controller/internal/controller/notificationsink_controller.go
  go/controller/internal/controller/observabilityprovider_controller.go
  go/controller/internal/controller/observer_controller.go
  go/controller/internal/controller/oidcprovider_controller.go
  go/controller/internal/controller/pipelinecontext_controller.go
  go/controller/internal/controller/prautomation_controller.go
  go/controller/internal/controller/prautomationtrigger_controller.go
  go/controller/internal/controller/project_controller.go
  go/controller/internal/controller/provider_controller.go
  go/controller/internal/controller/scmconnection_controller.go
  go/controller/internal/controller/service_account_controller.go
  go/controller/internal/controller/stackdefinition_controller.go
  go/controller/internal/test/mocks/ConsoleClient_mock.go
  go/tools/Makefile
  plural/helm/console/crds/deployments.plural.sh_deploymentsettings.yaml
Labels: bug-fix

#1944 Jake/prod 3253 add filter for cluster upgradeability
  assets/src/components/cd/clusters/Clusters.tsx
  assets/src/components/cd/logs/DateTimeFormInput.tsx
  assets/src/components/cd/logs/LogsFilters.tsx
  assets/src/components/cd/services/ClustersFilters.tsx
  assets/src/generated/graphql.ts
  assets/src/graph/cdClusters.graphql
  assets/src/utils/datetime.ts
Labels: enhancement, frontend

#1947 Fix console chart deps
  charts/console/Chart.lock
  charts/console/Chart.yaml
  charts/console/charts/controller-0.0.106.tgz
  charts/console/charts/kas-0.1.3.tgz
  charts/console/charts/kas-0.2.0.tgz
Labels: bug-fix, hotfix
